### ISSUE TITLE
Fine-tuning Tacotron/WaveGlow models

### ISSUE THREAD

**Issue by khusainovaidar** [NVIDIA/DeepLearningExamples#100]
I'm wondering whether it is possible to use pre-trained models using this repo? as it can be done in https://github.com/NVIDIA/tacotron2 [-c param of train.py script].
I want to start from -c tacotron2_statedict.pt model to obtain better synthesis quality.
Thank you.

**Comment by GrzegorzKarchNV** [comment]
Hi,
at this moment loading pre-trained models for training is not supported, but this feature is on our roadmap.

**Comment by pragyachaturvedi99** [comment]
Inferencing using Fastpitch/Waveglow is possible using checkpoints provided by nvidea
