### ISSUE TITLE
TypeError: Expected maxsize to be an integer or None

### ISSUE THREAD

**Issue by majidAdibian77** [NVIDIA/DeepLearningExamples#1016]
I tried to train FastPitch in google colab and I followed the [Quick Start Guide](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/SpeechSynthesis/FastPitch#quick-start-guide) and after downloading the LJSpeech-1.1 dataset when executing the following command:
`bash scripts/prepare_dataset.sh`

I get the this error:
```
Processing filelists/ljs_audio_text.txt...
Traceback (most recent call last):
  File "prepare_dataset.py", line 174, in <module>
    main()
  File "prepare_dataset.py", line 129, in main
    pitch_online_method=args.f0_method)
  File "/content/DeepLearningExamples/PyTorch/SpeechSynthesis/FastPitch/fastpitch/data_function.py", line 190, in __init__
    self.betabinomial_interpolator = BetaBinomialInterpolator()
  File "/content/DeepLearningExamples/PyTorch/SpeechSynthesis/FastPitch/fastpitch/data_function.py", line 54, in __init__
    self.bank = functools.lru_cache(beta_binomial_prior_distribution)
  File "/usr/lib/python3.7/functools.py", line 490, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None
```

**Comment by alancucki** [comment]
Hi @majidAdibian77 ,

thanks for reporting this bug!
You're using Python <= 3.7, in Python 3.8+ `lru_cache` has gotten [user_function](https://docs.python.org/3/library/functools.html#functools.lru_cache) argument, which is used in FastPitch code.

In the Quick Start Guide, we recommend the setup that we support using [NGC containers](https://ngc.nvidia.com/catalog/containers/nvidia:pytorch), which come with up-to-date Python.

**Comment by DarkIndoraptor** [comment]
One question, does this also work with lutris?
