### ISSUE TITLE
[Transformer] Question about inconsistent BLEU score specifications between your setup and scaling18

### ISSUE THREAD

**Issue by Peter-1213** [NVIDIA/DeepLearningExamples#1019]
Dear Authors:
I've been working on reproducing different varients of Transformer and using your repo as the base backbone. However, When I go through your docs, I found that you are calculating sacreBLEU score in case insensitive mode:

> To test model checkpoint accuracy on wmt14 test set run following command:
> `sacrebleu -t wmt14/full -l en-de --echo src | python inference.py --buffer-size 5000 --path /path/to/your/checkpoint.pt --max-tokens 10240 --fuse-dropout-add --remove-bpe --bpe-codes /data/code --fp16 | sacrebleu -t wmt14/full -l en-de **-lc**`

What's more, in the description above on fairseq's bleu, you also mention using the case insensitive one:

> ...To enable it, use the --online-eval option or to use the BLEU score value as the training stopping condition use the --target-bleu $TGT option. **The BLEU scores computed are case insensitive**. The BLEU is computed by the internal fairseq algorithm which implementation can be found in the fairseq/bleu.py script.

However, according to scaling 18, both their tokenized BLEU and sacreBLEU are case sensitive:

> We measure **case-sensitive** tokenized BLEU with multi-bleu.pl

> SacreBLEU hash: BLEU+**case.mixed**+lang.en-{de,fr}+ numrefs.1+smooth.exp+test.wmt14/full+tok.13a+ version.1.2.9

Therefore, I think there's a clear inconsistent setting between your repo and their paper. I wonder whether the reported BLEU scores below are also case-insensitive sacreBLEU? If so,  there will be a 0.5-0.8 score gap between your reproduction and their original work. Maybe not averaging the checkpoints can exaplain that gap, and I'm here just trying to make sure which BLEU spec is currently using. Thank you very much!

**Comment by jbaczek** [comment]
It is common in DL reseach that different papers use slightly different metrics making their results incomplarable. We've chosen to use sacreBLEU to alleviate this issue with an external tool that requires minimal code changes. If you want to compare another model with our results please use script provided in the README
