### ISSUE TITLE
UNet_3D_Medical Accuracy issue

### ISSUE THREAD

**Issue by hsdrhsr** [NVIDIA/DeepLearningExamples#1022]
Excuse me, I have trained an UNet_3D network on the Brain Tumor Segmentation 2019 dataset, but the average dice score is only 0.71. What other methods did you use to measure 0.88?

**Comment by mmarcinkiewicz** [comment]
The reported score is from a binary classification - the WholeTumor class. We are preparing a new release where we probably will include MeanDice as well to avoid confusion.

**Comment by hsdrhsr** [comment]
Ok, I see. Thanks for the reply.
