### ISSUE TITLE
[FastPitch/PyThorch] Question: how big should be model file? What is it dependent on?

### ISSUE THREAD

**Issue by vonLeebpl** [NVIDIA/DeepLearningExamples#1033]
It's not an issue, just question.
I adapted FastPitch training to polish changing few files, extending symbols, changing cleaners, etc.
Now when a training started I can see my model file is over 500MB.
I understand polish language has more characters than english however difference is quite big.
I train it with arpabet = 0.
What is it dependent on? Is this something wrong? Inference properly loads model from checkpoint btw.

**Comment by alancucki** [comment]
Hi @vonLeebpl ,

sorry for a late reply. During training, the optimizer state takes 2x disk space than model parameters. Note that when you're done training, you can safely remove the `optimizer` key from the checkpoint and reduce it size for future inference.

As for language-dependent parameters, those only increase for the initial symbol embedding table, which should be negligible for Polish when compared to English.
