### ISSUE TITLE
[DLRM/PyTorch] Should tables labelled "Batch size / GPU" be "Global batch size"?

### ISSUE THREAD

**Issue by rkindi** [NVIDIA/DeepLearningExamples#1039]
Related to **Model/Framework(s)** 
DLRM/PyTorch

**Describe the bug**
In the README for DLRM, the tables for many of the experiments say "Batch size/GPU" with 64k as the value. When I think of batch size / GPU, this makes me think of local batch size. However, [this line](https://github.com/NVIDIA/DeepLearningExamples/blob/db06ff533bf96fc256ce595c171eedae18f7f3ba/PyTorch/Recommendation/DLRM/dlrm/scripts/dist_main.py#L79) and [this line](https://github.com/NVIDIA/DeepLearningExamples/blob/db06ff533bf96fc256ce595c171eedae18f7f3ba/PyTorch/Recommendation/DLRM/dlrm/scripts/dist_main.py#L38) in combination suggest the global batch size is 64k (i.e. for 8 gpus, the Batch size / GPU should be 8192).

**To Reproduce**
N/A

**Expected behavior**
Expect that the batch size/gpu is actually 64k/number of gpus.

**Environment**
N/A

**Comment by tgrel** [comment]
Hi @rkindi, yes this is a typo. We will fix it in an upcoming release. Thank you for bringing this up!
