### ISSUE TITLE
[tarcotron2][train.py]amp.state_dict() in LoadCheckPoint and SaveCheckPoint error

### ISSUE THREAD

**Issue by doodoo997** [NVIDIA/DeepLearningExamples#1040]
Related to Tacotron2

**Describe the bug**
amp.state_dict() in LoadCheckPoint and SaveCheckPoint error

**To Reproduce**
1. normal train step 
2.It shows save check point error, that amp not found in amp.state_dict()  

**Expected behavior**
Cause without form apex import amp, using torch.cuda.amp will send scaler argument in SaveCheckPoint function and switch it scaler.state_dict()

**Environment**
Please provide at least:
* Container version:  I dont use container, just virture environment of python 3.6, pytorch 1.9,and requirment.txt pip installment
* GPUs in the system: 4* Tesla V100 SXM2
* CUDA  version : 10.2
* Driver Version: 440.64.00

**Comment by alancucki** [comment]
Hi @doodoo997 ,

thanks for reporting this! It was fixed in https://github.com/NVIDIA/DeepLearningExamples/commit/7ce175430ff9af25b040ffe2bceb5dfc9d2e39ad .
