### ISSUE TITLE
[FastPitch-1.1/PyTorch] Unable to estimate pitch when sampling rate is 8kHz

### ISSUE THREAD

**Issue by yerzhan7orazayev** [NVIDIA/DeepLearningExamples#1041]
I would like to prepare dataset, i.e., pitch estimation, for FastPitch-1.1 training when the sample rate of audio is 8 kHz.
However, I am getting the following assertion error from fastpitch/data_function.py line 94. Namely, assert np.abs(mel_len - pitch_mel.shape[0]) <= 1.0 .

I have changed only sample rate argument to 8000 while running the prepare_dataset.py . Is there anything that I am doing incorrectly?

Thanks.

**Comment by alancucki** [comment]
Hi @yerzhan7orazayev ,

sorry for a late reply.

It's a bug, you'd need to add a `sr=8000` kwarg to `librosa.load` [here](https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/SpeechSynthesis/FastPitch/fastpitch/data_function.py#L92) and `librosa.pyin` [here](https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/SpeechSynthesis/FastPitch/fastpitch/data_function.py#L93) .
