### ISSUE TITLE
[DeepLearningExamples/PyTorch/nnUnet]  Why I get a lot of dependent child images after build docker nnUnet?

### ISSUE THREAD

**Issue by PolinaDruzhinina** [NVIDIA/DeepLearningExamples#1050]
Related to **DeepLearningExamples/PyTorch/Segmentation/nnUnet** 
**Describe the bug**
When I, as the guide says, build the nnU-Net PyTorch NGC container, Dockerfile creates not only a Docker image named nnunet, but also 10 <None> images with different Image ID. Each image takes from 14.5 to 15 GB, which is actually a lot of memory. 
When i try to delete them using ` rmi -f` i get the corresponding error:
Error response from daemon: conflict: unable to delete .... (cannot be forced) - image has dependent child images

**To Reproduce**
1. 
```
git clone https://github.com/NVIDIA/DeepLearningExamples
cd DeepLearningExamples/PyTorch/Segmentation/nnUNet
```
2. 
```
docker build -t nnunet 
```

**Expected behavior**
Is it possible to make sure that child images are not created and so much memory is not wasted?

**Environment**
Please provide at least:
* Container version : PyTorch NGC container
* Docker version:  20.10.8, build 3967b7d
* GPUs in the system: tesla v100-pcie-32gb
* CUDA driver version:  Driver Version: 450.80.02    CUDA Version: 11.0

**Comment by michal2409** [comment]
I can't reproduce the bug and have only one docker image. Please provide the list of dependent child images.

**Comment by PolinaDruzhinina** [comment]
When docker is building in each step I see                                                                                                                                                                           
Step 13/13 : ADD . /workspace/nnunet_pyt                                                                                                                                                                   
 ---> Using cache                                                                                                                                                                                          
 ---> a5439c0efccc     
and then, if I look at the docker images that have appeared i can see the same ids:
 
REPOSITORY               TAG         IMAGE ID       CREATED              SIZE                                                                                                                              
<none>                   <none>      6fd3e8fb2895   About a minute ago   15.2GB                                                                                                                            
nnunet                   latest      a5439c0efccc   About a minute ago   15.2GB                                                                                                                            
<none>                   <none>      06cda5f7eea8   About a minute ago   15.2GB                                                                                                                            
<none>                   <none>      e71e4c32cad5   About a minute ago   15.2GB                                                                                                                            
<none>                   <none>      3c7165c2f76b   2 minutes ago        15.1GB                                                                                                                            
<none>                   <none>      1374f08e790e   2 minutes ago        14.9GB                                                                                                                            
<none>                   <none>      ae08dea90024   2 minutes ago        14.9GB                                                                                                                            
<none>                   <none>      2675450a3950   2 minutes ago        14.9GB                                                                                                                            
<none>                   <none>      4468c4e12a21   2 minutes ago        14.9GB                                                                                                                            
<none>                   <none>      d43118f90343   2 minutes ago        14.5GB                                                                                                                            
<none>                   <none>      ff4dc44f5f99   2 minutes ago        14.5GB                                                                                                                            
nvcr.io/nvidia/pytorch   21.11-py3   6eae00e8ee65   5 weeks ago          14.5GB
    Just in case, I saved the logs, they can be viewed at the 
[link]( https://drive.google.com/file/d/1LaLxrKoH2bt_rGJFME9sgbAbcxB526lF/view?usp=sharing)

**Comment by michal2409** [comment]
The logs you attached are looking good. Have you tried cleaning all docker images and building it once again? Maybe these are some old images you built for nnUNet?
