### ISSUE TITLE
[pyTorch/nnUnet] - DataModule class in data_module.py 

### ISSUE THREAD

**Issue by Shavi123** [NVIDIA/DeepLearningExamples#1053]
Hi,
I am going through the repo to understand how DALI is used for augmentation. I noticed that in data_module.py prepare_data() function is missing in DataModule class. I am new to PyTorch lightning but official documents says DataModule requires prepare_data() function.

**Comment by michal2409** [comment]
Hi @Shavi123,

The prepare_data() function is not required in DataModule - see docs [here](https://pytorch-lightning.readthedocs.io/en/latest/extensions/datamodules.html#prepare-data). Also, PyTorch Lightning DataModule is independent from DALI data loading.

**Comment by Shavi123** [comment]
Thanks for the response @michal2409 . understood the concept now.
