### ISSUE TITLE
Issue creating singularity image from the Dockerfile

### ISSUE THREAD

**Issue by nisargjoshi10** [NVIDIA/DeepLearningExamples#1054]
Hi,

I am trying to create a singularity image from the Dockerfile using the `singularity build` command but I'm running into this issue

`FATAL:   Unable to build from Dockerfile: while parsing definition: Dockerfile: failed to parse deffile header: invalid header keyword found: arg from_image_name=nvcr.io/nvidia/pytorch`

I'm new to using docker so not sure if I'm using the wrong command. Would appreciate your help.

Thanks,
Nisarg

**Comment by piotrm-nvidia** [comment]
Can you share full command you are running?

All our Dockerfiles are designed for CI scripts so it is possible to change base container

Example:
https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/Segmentation/nnUNet/Dockerfile#L1

ARG defines variable, which is later used in second line for FROM command.

Please consider checking Docker and Singularity documentation.

There is some question similar to yours at Stackoverflow:
https://stackoverflow.com/questions/66272215/porting-docker-build-commands-to-singularity
