### ISSUE TITLE
Use Tacotron2 or other speech synthesis with Linux speech-dispatcher

### ISSUE THREAD

**Issue by Jcwscience** [NVIDIA/DeepLearningExamples#1060]
Would it be possible to link one of the speech synthesis engines into the Linux speech dispatcher system? So that the default linux voice was neural network generated?

**Comment by alancucki** [comment]
Hi @Jcwscience ,

speech-dispatcher communicates with the synthesizers via sockets. It would require implementing a server wrapper for the inference script provided in our repository.

**Comment by Jcwscience** [comment]
I have a basic pipeline set up already, so I'll look at the documents. I didn't realize it used sockets, that makes it much easier. 

Still complicated but not as bad, Thanks for the quick reply!

**Comment by alancucki** [comment]
The docs in the speech-dispatcher [repo](https://github.com/brailcom/speechd) are quite exhaustive, with examples of the Python API.

Unfortunately, the repository is GPL-licensed, so it's unlikely that a module could be contributed from DLE (mostly Apache 2.0).
