### ISSUE TITLE
[WaveGlow/PyTorch] Questions about running inference of WaveGlow only

### ISSUE THREAD

**Issue by chankl3579** [NVIDIA/DeepLearningExamples#1071]
Hi, thank you for sharing all the pretrained models. 

I am looking for a vocoder that could construct audio from acoustic features so I am trying if I can use the WaveGlow solely. 
I have read the introductions on PyTorch official website, but find that the source codes are much more complicated. 

I can see in README that, by default, WaveGlow is working under 22050 sampling rate, STFT window size 1024 and hop size 256. 
But I cannot find where to add arguments for changing the settings, or where these hyperparameters are declared. 
Sorry for a silly question. Thank you.

**Comment by conceptofmind** [comment]
I believe the config file is what you are looking for to change these parameters: https://github.com/NVIDIA/waveglow/blob/master/config.json

**Comment by chankl3579** [comment]
Oh, sorry, I was too focused on the .py files. 
Thank you very much!!
