### ISSUE TITLE
[FastPitch] How to save alignments to speed up training

### ISSUE THREAD

**Issue by johannahom** [NVIDIA/DeepLearningExamples#1074]
Hi there,

Great work!

I have moved to the latest fastpitch with the internal alignment model (which works great), but it is rather slow.
Of course in the old model, I was passing my own ground truth durations so that I didn't have to repeat that step every time.

I noticed in the prepare_dataset.py file that the alignment priors can be saved, but in the train.py script there is no option to specify that we already have computed the alignments.

Is there a way save the alignments for my files so that I can skip this step when using the same data? It would really speed things up.

Thanks!

**Comment by alancucki** [comment]
Hi @johannahom.

terribly sorry for replying late!

> I noticed in the prepare_dataset.py file that the alignment priors can be saved, but in the train.py script there is no option to specify that we already have computed the alignments.

Alignment priors are used by the alignment module. They are costly to calculate (they're 2D) but we use image interpolation with a couple of prototype priors of different shapes to speed it up. I guess at this point there is no real reason to pre-calculate alignment priors.

The option to supply alignments has been removed entirely. Right now I suggest to modify `fastpitch/data_function.py` based on its older versions from our repository to restore that functionality. I'll probably bring it back in the next update.

**Comment by johannahom** [comment]
@alancucki, not a problem! 

I will look at the older version. We also have some code with MFA as it is easier to use for multiple different speakers without retraining tacotron. 

It would be great to see it back in the next update. I think often it's nice to be able to look into exactly what the alignments are doing.

Thanks!
