### ISSUE TITLE
[nnUNet/PyTorch] dllogger installation issue when building docker image

### ISSUE THREAD

**Issue by tjhendrickson** [NVIDIA/DeepLearningExamples#1075]
Related to **Model/Framework(s)** 
*nnUNet/PyTorch*

**Describe the bug**
I followed the instructions to build nnUNet as laid out [here](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Segmentation/nnUNet#quick-start-guide), but quickly ran into the issue.

**To Reproduce**
1. git clone git@github.com:NVIDIA/DeepLearningExamples.git
2. cd DeepLearningExamples/PyTorch/Segmentation/nnUNet/
2. sudo docker build -t nnunet .

**Expected behavior**
I expected the image to build

**Comment by jan-golda** [comment]
Hi @tjhendrickson 

I am unable to reproduce this, the build was completed successfully for me (log: [issue-1075.log](https://github.com/NVIDIA/DeepLearningExamples/files/8046867/issue-1075.log)).

Could you please share the console output showing what has happened in your case? 
Thanks!

**Comment by tjhendrickson** [comment]
Adding the argument "--network host" to my "docker build" call resolved my issue.

**Comment by jan-golda** [comment]
Good to hear that :)
From my experience the behaviour without `--network host` is very host-specific.

Could you please close this issue since the problem was resolved?

**Comment by tjhendrickson** [comment]
Sure thing, thanks for your help @jan-golda!
