### ISSUE TITLE
[UNet_Medical/TF2] runtime/arguments.py line95 may write error

### ISSUE THREAD

**Issue by zhengsen2022** [NVIDIA/DeepLearningExamples#1077]
is this right?
PARSER.set_defaults(augment=False) -- >  PARSER.set_defaults(benchmark=False)

**Comment by mmarcinkiewicz** [comment]
Hey @zhengsen2022 yes, you are right. This piece of code is not used anyway, if you don't want augmentation, simply don't pass the `--augment` flag. I'll remove the extra code in the next revision to eliminate any confusion.

Thank you for reporting that!

**Comment by mmarcinkiewicz** [comment]
Please reopen if you have any further questions.
