### ISSUE TITLE
Fast Pitch 1.1 - Shorter words like "Hello" seem to synthesize with noise.

### ISSUE THREAD

**Issue by ArEnSc** [NVIDIA/DeepLearningExamples#1082]
@alancucki 
Hey been playing with Fast Pitch 1.1 I recently trained cloned a voice of a popular actress through fine tuning. I have to say it works very well.
This is the sample of the actress saying 
1."hello." https://vocaroo.com/19eH8fIlVgyo
2."hello" https://vocaroo.com/12FZFQ9etJHd
3."Hi" https://voca.ro/1d2z0J2L8hsJ sounds like you are underwater.
4."Hi." https://voca.ro/1eqfw4vvm3qy
5."This a hello and a good bye." https://voca.ro/17VrLsCcLlwC

Notice that hello appears to be poorly synthesized, or short words without a period?

Why would that be the case? do you have any tips for short words or words that sound off? another one is Engine. 

I am guessing the only thing we can really do is modify the pronunciation dictionary and add in words that are missing? 
I noticed Hello is not in there, when I tried Hell low, it sounded closer.

Thanks let me know your thoughts!

**Comment by alancucki** [comment]
Hi @ArEnSc !

> Notice that hello appears to be poorly synthesized, or short words without a period?
> Why would that be the case? do you have any tips for short words or words that sound off? another one is Engine.

I only have a common sense answer, that what your model learned reflects what's in the data. Many public corpora don't have single words. The same applies to ending sentences with a period `.` . If utterances in the corpus are long sentences split on silence (like in corpora derived from audiobooks), the model will learn to condition the intonation of the suffix on `.`, which then means "this utterance is not finished".

One trick for single/short words is to synthesize a longer utterance (like you did in 5.) and cut out the interesting word. That is straightforward, given that the model returns precise alignments. Decrease the energy on surrounding spaces, to ensure they become silence, to make the word cleanly stand out.

> I am guessing the only thing we can really do is modify the pronunciation dictionary and add in words that are missing?
> I noticed Hello is not in there, when I tried Hell low, it sounded closer.

Hello is present in cmudict in two variants. You can bypass text processing and synthesize the phonetic transcription directly. Try synthesizing `{HH AH0 L OW1}.` and `{HH EH0 L OW1}.` as text input to the model.

**Comment by ArEnSc** [comment]
nevermind I read the encoder code found the ambigous arpanet was set to ignore
