### ISSUE TITLE
[BERT/PyTorch] Forever looping in function ”distribute_articles_over_shards“ within PyTorch/LanguageModeling/BERT/data/TextSharding.py

### ISSUE THREAD

**Issue by XinyuYe-Intel** [NVIDIA/DeepLearningExamples#1083]
Related to **BERT/PyTorch** 

**Describe the bug**
For BERT pretraining datasets preprocessing, stuck in the loop ***while len(consumed_article_set) < len(self.articles)*** in function ***distribute_articles_over_shards*** within **PyTorch/LanguageModeling/BERT/data/TextSharding.py**, with message **\"Distributing data over shards: 852 articles remaining.\"** showing thousands of times.

**To Reproduce**
1. Following instructions in section **Quick Start Guide** in **PyTorch/LanguageModeling/BERT/README.md**.
2. Launch with command **/workspace/bert/data/create_datasets_from_start.sh wiki_books**.

**Expected behavior**
Stuck in the looping with message **Distributing data over shards: 852 articles remaining.** showing thousands of times.

**Environment**
Please provide at least:
* Container version: pytorch:20.06-py3
* GPUs in the system: 1x A100-40GB
* CUDA driver version: 470.57.02

**Comment by sharathts** [comment]
Hi. We are in the process of updating the data processing and dataloader with our next update which is due in around a week. With this, you shouldn't encounter the above issue, stay tuned.

Closing. Feel free to reopen if you have more questions.

**Comment by XinyuYe-Intel** [comment]
Okay, I'm looking forward to it. 
I also want to know that will you optimize the function **segment_articles_into_sentences** while doing text sharding in the next update? Since current way of segmenting articles using single process is extremely time consuming, and I implemented a simple version of multiprocessing for this, but still takes around twenty hours to finish. I'm wondering that whether change the dict into list to store the articles and sentences will help.

**Comment by sharathts** [comment]
We pushed the update.  Data prep has been made much faster. Please refer to LDDL in the readme.
