### ISSUE TITLE
[BERT/PyTorch] NVFuser doesn't work 

### ISSUE THREAD

**Issue by sjlee0407** [NVIDIA/DeepLearningExamples#1094]
Related to **BERT/PyTorch** 

**Describe the bug**
1. When running 'bash scripts/run_pretraining.sh', NVFuser doesn't work and below is error log.
/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py:1110: UserWarning: FALLBACK path has been taken. This is an indication that codegenFailed for some reason. To debug try disable codegen fallback path via setting the env variable`export PYTORCH_NVFUSER_DISABLE_FALLBACK=1` (Triggered internally at  /opt/pytorch/pytorch/torch/csrc/jit/codegen/cuda/manager.cpp:230.)
2. When I use 'export PYTORCH_NVFUSER_DISABLE_FALLBACK=1', error occurs and below is error log.
RuntimeError: current_stack_.back() == allocate_loop_infoINTERNAL ASSERT FAILED at "/opt/pytorch/pytorch/torch/csrc/jit/codegen/cuda/lower_alias_memory.cpp":670, please report a bug to PyTorch. lower_alias_memory : expr outer loop inconsistent with allocate

**To Reproduce**
1. In the BERT/PyTorch folder, 'bash scripts/docker/build.sh'
2. In the BERT/PyTorch folder, 'bash scripts/docker/launch.sh'
3. In the '/workspace/bert/' folder, 'bash scrips/run_pretraining.sh'  (using LDDL)

**Expected behavior**
I think that NVFuser doesn't work. 
I want to get about 3x higher sequences/sec (78 -> 210) using a single A100 and 512 sequence length as you show in the README.md file.

**Environment**
* Container version: pytorch 21.11-py3
* GPUs in the system: 1x A100-PCIe-80GB
* CUDA driver version: 470.63.01

**Comment by sharathts** [comment]
Could you share your full logs?

**Comment by shangw-nvidia** [comment]
@sjlee0407 My guess is that you were using a version of the NGC PyTorch image that didn't yet have the "complete" nvfuser. Which version were you using?

**Comment by sjlee0407** [comment]
@sharathts I will show you my full logs. 
Although I got the 'codegenFailed' log, training continues.
However, the throughput is similar with earlier version (78 sequences/sec) than new version (210 sequences/sec).
Below is my full logs. 


```
root@gpu09:/workspace/bert# bash scripts/run_pretraining.sh 
Container nvidia build =  29224839
/workspace/bert/data/pretrain/custom/
Logs written to /workspace/bert/results/bert_lamb_pretraining.pyt_bert_pretraining_phase1_fp16_gbs4096.220316032539.log
+ '[' -z /workspace/bert/results/bert_lamb_pretraining.pyt_bert_pretraining_phase1_fp16_gbs4096.220316032539.log ']'
+ tee /workspace/bert/results/bert_lamb_pretraining.pyt_bert_pretraining_phase1_fp16_gbs4096.220316032539.log
+ python3 -m torch.distributed.launch --nproc_per_node=1 /workspace/bert/run_pretraining.py --input_dir=/workspace/bert/data/pretrain/custom/ --output_dir=/workspace/bert/results/checkpoints --config_file=bert_configs/large.json --vocab_file=vocab/vocab --train_batch_size=4096 --max_seq_length=512 --max_predictions_per_seq=80 --max_steps=16 --warmup_proportion=0.2843 --num_steps_per_checkpoint=200 --learning_rate=6e-3 --seed=12439 --fp16 --gradient_accumulation_steps=128 --do_train --json-summary /workspace/bert/results/dllogger.json --num_workers=4
device: cuda:0 n_gpu: 1, distributed training: True, 16-bits training: True
DLL 2022-03-16 03:25:42.250000 - PARAMETER Config : ["Namespace(allreduce_post_accumulation=False, allreduce_post_accumulation_fp16=False, amp=False, checkpoint_activations=False, config_file='bert_configs/large.json', cuda_graphs=False, disable_jit_fusions=False, disable_progress_bar=False, do_train=True, fp16=True, gradient_accumulation_steps=128, init_checkpoint=None, init_loss_scale=1048576, input_dir='/workspace/bert/data/pretrain/custom/', json_summary='/workspace/bert/results/dllogger.json', learning_rate=0.006, local_rank=0, log_freq=1.0, loss_scale=0.0, max_predictions_per_seq=80, max_seq_length=512, max_steps=16.0, n_gpu=1, no_dense_sequence_output=False, num_steps_per_checkpoint=200, num_train_epochs=3.0, num_workers=4, output_dir='/workspace/bert/results/checkpoints', phase1_end_step=7038, phase2=False, profile=False, profile_start=0, resume_from_checkpoint=False, resume_step=-1, seed=12439, skip_checkpoint=False, steps_this_run=16.0, train_batch_size=32, use_env=False, vocab_file='vocab/vocab', warmup_proportion=0.2843)"] 
/opt/conda/lib/python3.8/site-packages/torch/jit/_recursive.py:234: UserWarning: 'bias' was found in ScriptModule constants,  but it is a non-constant parameter. Consider removing it.
  warnings.warn("'{}' was found in ScriptModule constants, "
LDDL - 2022-03-16 03:25:50,368 - datasets.py:128:__init__ - node-0 - WARNING : lost 242/64180722=0.00037706026429556213% samples in total
LDDL - 2022-03-16 03:25:50,380 - datasets.py:128:__init__ - node-0 - WARNING : lost 507/28537851=0.0017765878727168348% samples in total
LDDL - 2022-03-16 03:25:50,389 - datasets.py:128:__init__ - node-0 - WARNING : lost 200/858312=0.023301550019107272% samples in total
LDDL - 2022-03-16 03:25:50,398 - datasets.py:128:__init__ - node-0 - WARNING : lost 288/81696=0.35252643948296125% samples in total
LDDL - 2022-03-16 03:25:50,407 - datasets.py:128:__init__ - node-0 - WARNING : lost 253/21245=1.1908684396328548% samples in total
LDDL - 2022-03-16 03:25:50,416 - datasets.py:128:__init__ - node-0 - WARNING : lost 222/8414=2.638459710007131% samples in total
LDDL - 2022-03-16 03:25:50,425 - datasets.py:128:__init__ - node-0 - WARNING : lost 234/4330=5.404157043879907% samples in total
LDDL - 2022-03-16 03:25:50,434 - datasets.py:128:__init__ - node-0 - WARNING : lost 378/10106=3.7403522659806057% samples in total
get_bert_pretrain_data_loader took 0.1984866709972266 s!
DLL 2022-03-16 03:25:50.434231 - PARAMETER SEED : 12439 
DLL 2022-03-16 03:25:50.434301 - PARAMETER train_start : True 
DLL 2022-03-16 03:25:50.434336 - PARAMETER batch_size_per_gpu : 32 
DLL 2022-03-16 03:25:50.434372 - PARAMETER learning_rate : 0.006 
Iteration:   0%|          | 0/2928136 [00:00<?, ?it/s]LDDL - 2022-03-16 03:25:50,532 - datasets.py:243:__iter__ - node-0 - WARNING : epoch = 0
LDDL - 2022-03-16 03:25:50,852 - datasets.py:243:__iter__ - node-0 - WARNING : epoch = 0
LDDL - 2022-03-16 03:25:50,926 - datasets.py:243:__iter__ - node-0 - WARNING : epoch = 0
LDDL - 2022-03-16 03:25:50,997 - datasets.py:243:__iter__ - node-0 - WARNING : epoch = 0
LDDL - 2022-03-16 03:25:51,117 - datasets.py:243:__iter__ - node-0 - WARNING : epoch = 0
LDDL - 2022-03-16 03:25:51,192 - datasets.py:243:__iter__ - node-0 - WARNING : epoch = 0
LDDL - 2022-03-16 03:25:51,266 - datasets.py:243:__iter__ - node-0 - WARNING : epoch = 0
LDDL - 2022-03-16 03:25:51,343 - datasets.py:243:__iter__ - node-0 - WARNING : epoch = 0
Iteration:   0%|          | 2/2928136 [00:05<1852:28:53,  2.28s/it]/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py:1110: UserWarning: FALLBACK path has been taken. This is an indication that codegenFailed for some reason. To debug try disable codegen fallback pathvia setting the env variable`export PYTORCH_NVFUSER_DISABLE_FALLBACK=1` (Triggered internally at  /opt/pytorch/pytorch/torch/csrc/jit/codegen/cuda/manager.cpp:230.)
  return forward_call(*input, **kwargs)
Iteration:   0%|          | 127/2928136 [01:28<380:32:54,  2.14it/s]DLL 2022-03-16 03:27:19.101995 - Training Epoch: 0 Training Iteration: 0  average_loss : 11.291284561157227  learning_rate : 0.0013190292520448565  skipped_steps : 1 
DLL 2022-03-16 03:27:19.102167 - PARAMETER loss_scale : 524288.0 
DLL 2022-03-16 03:27:19.102285 - PARAMETER checkpoint_step : 0 
Iteration:   0%|          | 255/2928136 [02:33<383:51:01,  2.12it/s]DLL 2022-03-16 03:28:24.101791 - Training Epoch: 0 Training Iteration: 1  average_loss : 11.291284561157227  learning_rate : 0.0013190292520448565  skipped_steps : 1 
DLL 2022-03-16 03:28:24.104208 - PARAMETER loss_scale : 262144.0 
Iteration:   0%|          | 383/2928136 [03:32<377:32:51,  2.15it/s]DLL 2022-03-16 03:29:23.595382 - Training Epoch: 0 Training Iteration: 1  average_loss : 11.288694381713867  learning_rate : 0.0013190292520448565  skipped_steps : 2 
DLL 2022-03-16 03:29:23.596893 - PARAMETER loss_scale : 131072.0 
Iteration:   0%|          | 511/2928136 [04:32<378:15:26,  2.15it/s]DLL 2022-03-16 03:30:22.999941 - Training Epoch: 0 Training Iteration: 1  average_loss : 11.282665252685547  learning_rate : 0.0013190292520448565  skipped_steps : 3 
DLL 2022-03-16 03:30:23.001943 - PARAMETER loss_scale : 65536.0 
Iteration:   0%|          | 639/2928136 [05:31<381:35:26,  2.13it/s]DLL 2022-03-16 03:31:22.562602 - Training Epoch: 0 Training Iteration: 1  average_loss : 11.289952278137207  learning_rate : 0.0013190292520448565  skipped_steps : 4 
DLL 2022-03-16 03:31:22.564822 - PARAMETER loss_scale : 32768.0 
Iteration:   0%|          | 767/2928136 [06:30<376:21:22,  2.16it/s]DLL 2022-03-16 03:32:21.867723 - Training Epoch: 0 Training Iteration: 1  average_loss : 11.285426139831543  learning_rate : 0.0013190292520448565  skipped_steps : 5 
DLL 2022-03-16 03:32:21.876657 - PARAMETER loss_scale : 32768.0 
.........
........
```

**Comment by sjlee0407** [comment]
@shangw-nvidia  I will share using command, version log, and commit version.

```
# bash DeepLearningExamples/PyTorch/LanguageModeling/BERT/scripts/docker/build.sh 
# bash DeepLearningExamples/PyTorch/LanguageModeling/BERT/scripts/docker/launch.sh 

=============
== PyTorch ==
=============

NVIDIA Release 21.11 (build 29224839)
PyTorch Version 1.11.0a0+b6df043
```


```
commit 1c7f6137d89ae25fad2c65de5f318f759c6fcbed (HEAD)
Author: Sharath Turuvekere Sreenivas <sharatht@nvidia.com>
Date:   Thu Mar 10 03:07:42 2022 -0800

    [BERT/PyT] Updated links to checkpoints and README
```

Thank you!

**Comment by sharathts** [comment]
@sjlee0407 The issue you are encountering is because you have `allreduce_post_accumulation=False, allreduce_post_accumulation_fp16=False`

Torchscript/NVFuser currently works with the above two flags set to true. Setting the above two to true will also increase performance orthogonally.

Closing issue. Feel free to reopen if you have more questions.

**Comment by sjlee0407** [comment]
@sharathts Thanks for your kind explanation, and I solved the problem (NVFuser works!).
However, I re-opened the issue because I have a lot of questions about before/after applying NVFuser.

When I analyzed the effect of NVFuser using Nsight compute/systems, I found that NVFuser supports many optimization techniques, but I didn’t identify some of the optimization techniques.

Question 1) 
In my opinion, if I set the batch size, NVFuser seems to process by dividing the batch size into several micro-batch. Is that correct?

I guessed this through the experiments using Nsight systems. 
I will explain this situation using the figure below. I used sequence length 128 and batch size 256 for the experiment.
- When I didn’t apply NVFuser, the execution time was constant for each iteration like the upper graph and took about 665ms per iteration.
- However, when NVFuser is applied, the execution time varies for each iteration. For example, the blue box takes 462ms in one iteration and the yellow box takes 234ms in the next iteration. When I checked the HMMA instruction and the number of data accesses through the Nsight compute, there was a double difference between the two iterations.
![image](https://user-images.githubusercontent.com/20793298/159124689-063efc41-fa8d-4a11-8e17-6b2aecae5386.png)

I also guessed the reason for this behavior is presumably to reduce DRAM access by fitting the activation data to the cache.

Question 2)
If my assumption is correct, I want to ask further questions.
If the NVFuser divides the batch size into two micro-batch, I think that the number of operations (FLOPs) per layer also reduces by half.

However, when I profile all of the layers using Nsight compute, FLOPs of batched matrix multiplication (BMM) layers are further reduced rather than matrix multiplication (MM).

Thus, I want to know which optimization techniques are applied to the BMM layers.


Layers  | Operation types | FLOPs <br/> (256 batch) | FLOPs <br/> (128 micro-batch, NVFuser)
-- | -- | -- | --
Key/Query/Value <br/> (Self-Attention) | MM | 68,719,476,736 | 34,359,738,368 <br/> (twice smaller)
Attention score/Context <br/> (Self-Attention) | BMM | 8,589,934,592 | 2,147,483,648 <br/> (4 times smaller)
Fully connected (FC) 1 <br/> (Self-Attention) | MM | 68,719,476,736 | 34,359,738,368 <br/> (twice smaller)
FC 2 / FC 3(Feed forward) | MM | 274,877,906,944 | 137,438,953,472 <br/> (twice smaller)

Thank you!

**Comment by sjlee0407** [comment]
Thanks for the kind explanation, and I solved the problem (NVFuser works!).

**Comment by fqhd** [comment]
> 

How do you set those variables to true? Are they environment variables to set with
```python
import os
 os.ENVIRON['allreduce_post_accumulation']='True'
 os.ENVIRON['allreduce_post_accumulation_fp16']='True'
```
before import pytorch? Or do you have to set them as compiler flags when building pytorch from source?
Please help as I am facing the same issue.
