### ISSUE TITLE
can not download criteo 1TB click dataset for DLRM

### ISSUE THREAD

**Issue by xiwei777** [NVIDIA/DeepLearningExamples#1098]
i want to train DLRM using NGC, but can not can not download criteo 1TB click dataset
at this tutorial,https://catalog.ngc.nvidia.com/orgs/nvidia/resources/dlrm_for_pytorch/quick-start-guide
at step2, can not download  dataset from http://labs.criteo.com/2013/12/download-terabyte-click-logs/
download url is can not access

**Comment by future-xy** [comment]
I just met the problem too,
```
curl: (6) Could not resolve host: azuremlsampleexperiments.blob.core.windows.net
```
I was wondering if there is any other link to download the dataset?

**Comment by AGeille** [comment]
Dear all a transition solution has been set up and we are discussing with several partners to set a list of mirror sites. 
The links are the following:
https://storage.googleapis.com/criteo-cail-datasets/day_0.gz
**up to**
https://storage.googleapis.com/criteo-cail-datasets/day_23.gz
Criteo's website is about to be updated
