### ISSUE TITLE
[BERT/PyTorch] can not use fused_lamb

### ISSUE THREAD

**Issue by Hannibal046** [NVIDIA/DeepLearningExamples#1101]
Related to **BERT/PyTorch** 

**Describe the bug**
can not `from lamb_amp_opt.fused_lamb import FusedLAMBAMP`
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/38466901/160133131-4f2c81f4-bbc8-4458-a7d9-29791abc017b.png">

I find the `libtorch_cuda_cu.so` is located at `/opt/conda/lib/python3.8/site-packages/torch/lib`. After adding it  to the `LD_LIBRARY_PATH`, there is another error.
<img width="1588" alt="image" src="https://user-images.githubusercontent.com/38466901/160134096-fb2aa0e8-6a76-45b2-94f9-e367414d3370.png">

**To Reproduce**
1. install pytorch from source
2. git clone https://github.com/NVIDIA/DeepLearningExamples.git
3. cd DeepLearningExamples/PyTorch/LanguageModeling/BERT
4. pip install --no-cache-dir tqdm boto3 requests six ipdb h5py nltk progressbar onnxruntime tokenizers git+https://github.com/NVIDIA/dllogger wget -q
5. conda install -y jemalloc
6. pip install ./lddl -q
7. python -m nltk.downloader punkt
8. pip install ./lamb_amp_opt/ -q

**Expected behavior**
successfully use fused_lamb

**Environment**
Please provide at least:
using in-house docker image 
<img width="501" alt="image" src="https://user-images.githubusercontent.com/38466901/160135026-181c1b41-bf65-4505-8e88-d8d765289e91.png">

**Comment by sharathts** [comment]
It is typically recommended to use the the provided docker file and NGC PyTorch image.

Installing from source isn't recommended as you might have compatibility issues like the one you are facing.

**Comment by Hannibal046** [comment]
Hi,  for some reason, I can not use provided docker from NGC PyTorch image. So I have to install PyTorch from source. I fix this by first uninstall existing torch.
