### ISSUE TITLE
README file about how to train FastPitch without docker environment

### ISSUE THREAD

**Issue by JohnHerry** [NVIDIA/DeepLearningExamples#1118]
The instruction about FastPitch are how to work in the docker container. But I want to make it from scratch, I am using virtualenv, Is there any plan about such instuction or README file?

**Comment by alancucki** [comment]
Hi @JohnHerry ,

Run `pip install -r requirements.txt` in the root directory of FastPitch and you should be good to go.

In case you'd have trouble setting up libraries/framework/CUDA toolkit/etc., look up what's actually [shipped in the NGC Docker container](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_22-03.html#rel_22-03) FastPitch builds on. The model should work fine on any container no older than [21.05-py3](https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/SpeechSynthesis/FastPitch/Dockerfile#L15) .

**Comment by JohnHerry** [comment]
> Hi @JohnHerry ,
> 
> Run `pip install -r requirements.txt` in the root directory of FastPitch and you should be good to go.
> 
> In case you'd have trouble setting up libraries/framework/CUDA toolkit/etc., look up what's actually [shipped in the NGC Docker container](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_22-03.html#rel_22-03) FastPitch builds on. The model should work fine on any container no older than [21.05-py3](https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/SpeechSynthesis/FastPitch/Dockerfile#L15) .

Thank you for help, I will have a try.

**Comment by JohnHerry** [comment]
> > Hi @JohnHerry ,
> > Run `pip install -r requirements.txt` in the root directory of FastPitch and you should be good to go.
> > In case you'd have trouble setting up libraries/framework/CUDA toolkit/etc., look up what's actually [shipped in the NGC Docker container](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_22-03.html#rel_22-03) FastPitch builds on. The model should work fine on any container no older than [21.05-py3](https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/SpeechSynthesis/FastPitch/Dockerfile#L15) .
> 
> Thank you for help, I will have a try.

I can run it now, thanks.
