### ISSUE TITLE
How to use LAMB optimizer ?

### ISSUE THREAD

**Issue by Hannibal046** [NVIDIA/DeepLearningExamples#1123]
Hi Great Team, 
I just want to know what is the right way to use NVLAMB optimizer. I check the code here https://github.com/NVIDIA/DeepLearningExamples/blob/3e8897f7855ff475d69699e66c8f668f6191dfa4/PyTorch/LanguageModeling/BERT/lamb_amp_opt/main.py#L38-L78

And  I write a test example with PolyWarmUpScheduler, but it seems there is something wrong with the combination of optimizer and lr_scheduler.
```
from lamb_amp_opt.fused_lamb import FusedLAMBAMP
from schedulers import PolyWarmUpScheduler
import torch
import matplotlib.pyplot as plt

device = torch.device("cuda")

lr = 1
total_steps = 100
warmup_proportion = 0.1

model = torch.nn.Linear(10,1).to(device)

# optimizer = torch.optim.Adam(m.parameters(),lr = lr)
optimizer = FusedLAMBAMP(model.parameters(),lr=lr,)
   
lr_scheduler = PolyWarmUpScheduler(optimizer,
                                    warmup=warmup_proportion,
                                    total_steps=total_steps,
                                    base_lr=lr,
                                    device=device)
lrs = []
loss_fct = torch.nn.MSELoss()
for _ in range(total_steps):
    output = model(torch.rand(2,10).to(device))
    labels = torch.rand(2,1).to(device)
    loss = loss_fct(output,labels)
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
    lr_scheduler.step()
    lrs.append(optimizer.param_groups[0]['lr'].item())
plt.plot(lrs)
```
This is what I got 
<img width="475" alt="test ipynb — mybert  SSH: 45a3159k71 zicp vip  2022-05-01 10-47-41" src="https://user-images.githubusercontent.com/38466901/166130061-0bf59b12-4fe2-4d97-a435-2e2731dedbbd.png">

And I also check official `Adam` optimizer. Nothing changed.
Do I misunderstand something about `LAMB` optimizer and  `PolyWarmUpScheduler` ? Thanks so much !

**Comment by Hannibal046** [comment]
OK, I find that adding `optimizer.setup_fp32_params()` after initialization of LAMB optimizer will do.

<img width="481" alt="test ipynb — mybert  SSH: 45a3159k71 zicp vip  2022-05-01 11-16-41" src="https://user-images.githubusercontent.com/38466901/166130705-b67e2dd4-8b65-41f7-a080-759405d760b3.png">

So, just to be clearly. To properly use `LAMB` optimizer and corresponding `lr_scheduler`, do I complete all necessary steps ?

**Comment by sharathts** [comment]
Looks like you have all the requires steps. The step you missed is contained in here https://github.com/NVIDIA/DeepLearningExamples/blob/3e8897f7855ff475d69699e66c8f668f6191dfa4/PyTorch/LanguageModeling/BERT/run_pretraining.py#L368
