### ISSUE TITLE
use feed_dict to benchmark fast transformer and BERT

### ISSUE THREAD

**Issue by levyfan** [NVIDIA/DeepLearningExamples#113]
The benchmark (DeepLearningExamples/FasterTransformer/sample/tensorflow/transformer_fp16.py) now only copy the input once and run 500 times computation. The time reported only includes the CUDA computational kernels and gemm. It it better to copy inputs every iteration and report the overall latency as this is the most common scenario in real applications.

https://github.com/NVIDIA/DeepLearningExamples/blob/81b1b024e155884431d968ddf1dace7e85ada9b2/FasterTransformer/sample/tensorflow/transformer_fp16.py#L43

For example by using feed_dict and placeholder, 

```
from_data = np.random.randn(batch_size, seq_len, hidden_dim)
from_tensor = tf.placeholder(tf.float16, shape=[batch_size, seq_len, hidden_dim])
...
for i in range(ite):
    sess.run(output_own, feed_dict={from_tensor: from_data})
```

**Comment by IrishCoffee** [comment]
This is just a sample, not for time measurement.

Actually, data copy can be overlapped with computation. Thus, only measure the computation is ok.

**Comment by levyfan** [comment]
Another thing: could you provide a "mixed precision" version (computeType=CUDA_R_32F, type=CUDA_R_16F)?

**Comment by IrishCoffee** [comment]
You can modify the code as you need.
