### ISSUE TITLE
[FastPitch/1.1]  About the cmudict initialization

### ISSUE THREAD

**Issue by JohnHerry** [NVIDIA/DeepLearningExamples#1132]
Related to **Model/Framework(s)** 

Pytorch/SpeechSynthesis/FastPitch/

**Describe the bug**
 
I am not quite sure. just see the train.py: line 354

I think it may should be
···
if args.p_arpabet > 0.0 and args.p_arpabet < 1.0:
    cmudict.initialize()
···

because when  args.p_arpabet = 1.0,  it will train completely on phonemes,  I think it may not need cmudict any more.

**Comment by rygopu** [comment]
Yes, when args.p_arpabet > 0.0 , i.e when = 1 , It'll be trained on phonetic representations. So for every word / sentence in the input, encode_text function calls the get_arpabet function which looks up CMUDICT for the relevant phonetic representations. If a word has multiple pronunciations, you can choose the "first" / "random" / "last" by setting the appropriate flag in the config. 

Also, You could also choose phonemes for specific word (in that case you have to pass in the word with curly braces {sample} ) or choose entire sentence (In this case you don't need to wrap it using curly braces)

**Comment by JohnHerry** [comment]
> Yes, when args.p_arpabet > 0.0 , i.e when = 1 , It'll be trained on phonetic representations. So for every word / sentence in the input, encode_text function calls the get_arpabet function which looks up CMUDICT for the relevant phonetic representations. If a word has multiple pronunciations, you can choose the "first" / "random" / "last" by setting the appropriate flag in the config.
> 
> Also, You could also choose phonemes for specific word (in that case you have to pass in the word with curly braces {sample} ) or choose entire sentence (In this case you don't need to wrap it using curly braces)

It is interesting to support a word-phoneme-mixture as input, but the text encoder,  which may work well for European languages, is not friendly for others.
