### ISSUE TITLE
[BERT/Pytorch] pretrain_config.sh for bert_base

### ISSUE THREAD

**Issue by mx8435** [NVIDIA/DeepLearningExamples#1138]
Related to **Model/Framework(s) or something else (describe)** 

*Examples:* 
* *PyTorch*
* *AMP* 

**Describe the solution you'd like**
I wanna reproduce bert-base pretraining using the framework, but only bert-large pretraining config is found. Can you provide pretraining config for A100x8 1 Node. Thanks.

**Comment by sharathts** [comment]
The same hyperparameters used for the large model should work for training the base model. You can use the same config, replacing `large.json` to `base.json` for the model parameters.
