### ISSUE TITLE
Missing BERT Inference with TensorRT

### ISSUE THREAD

**Issue by lakshaykc** [NVIDIA/DeepLearningExamples#1147]
Related to **Tensorflow/BERT/Inference** 

**Describe the bug**
I'm trying to follow this [demo](https://catalog.ngc.nvidia.com/orgs/nvidia/resources/bert_tensorrt_from_tensorflow/quick-start-guide) but it appears that trt directory https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/LanguageModeling/BERT/trt does not exist. Has the above demo 'BERT Inference with TensorRT' been removed from the repo or moved somewhere else? 

**To Reproduce**
The following documentation and issues refer to a trt directory that does not exist.
1. https://github.com/NVIDIA/DeepLearningExamples/issues/396#issuecomment-584296255
2. https://github.com/NVIDIA/DeepLearningExamples/commit/6c0b5e36b444134978e8e8c5b273715f8a64f626
3. https://catalog.ngc.nvidia.com/orgs/nvidia/resources/bert_tensorrt_from_tensorflow/quick-start-guide
 

**Expected behavior**
NA

**Environment**
NA

**Comment by meatybobby** [comment]
BERT Inference with TensorRT has been move to [TensorRT repository](https://github.com/NVIDIA/TensorRT/tree/main/demo/BERT)
