### ISSUE TITLE
[FasterTransformer] speedup on T4 issue

### ISSUE THREAD

**Issue by qiaohaijun** [NVIDIA/DeepLearningExamples#115]
### Environment requirements
- CMake  3.14.6
- CUDA 10.0
- CUDNN 7.4.2
- Python 2.7
- Tensorflow 1.13
- GCC 6

---

I run performance test on T4. use `transformer_fp16.py.`
https://github.com/NVIDIA/DeepLearningExamples/blob/master/FasterTransformer/sample/tensorflow/transformer_fp16.py
when Batch_size is {8,16,32}, XLA is better. 

---

<batch_size, layers, eq_len, head_num, size_per_head> | Tensorflow XLA on T4 FP16 (in ms) | Faster Transformer T4 FP16 (in ms) | Speedup | GEMM 参数
-- | -- | -- | -- | --
(1, 6, 32, 12, 64) | 1.889802 ms | 1.194158 ms | 1.583 | 107,100,107,114,111
(2, 6, 32, 12, 64) | 1.940294 ms | 1.277116 ms | 1.519 | 107,100,107,101,115
(4, 6, 32, 12, 64) | 2.257926 ms | 1.715474 ms | 1.316 | 107,100,107,102,100
(8, 6, 32, 12, 64) | 2.82261 ms | 2.83554 ms | 0.95 | 107,100,107,115,105
(16, 6, 32, 12, 64) | 4.363834 ms | 4.560086 ms | 0.96 | 100,110,107,107,99
(32, 6, 32, 12, 64) | 7.870094 ms | 8.690178 ms | 0.915 | 100,99,107,100,111
(64, 6, 32, 12, 64) | 15.913654 ms | 14.668242 ms | 1.084 | 100,103,110,100,115
(128, 6, 32, 12, 64) | 30.419768 ms | 25.81849 ms | 1.178 | 110,106,110,99,100
(256, 6, 32, 12, 64) | 58.770124 ms | 50.166238 ms | 1.172 | 103,103,103,109,115
(512, 6, 32, 12, 64) | 121.467958 ms | 98.644416 ms | 1.231 | 103,103,103,108,100

---

**Is my test result correct?**

**Comment by IrishCoffee** [comment]
I just tested several cases.  The environment is the same as you listed. For some corner cases you listed here, Faster Transformer still achieves better performance. Please check your GPU plck during the execution. Using nvidia-smi dmon.

<batch_size, layers, eq_len, head_num, size_per_head> | Tensorflow XLA on T4 FP16 (in ms) | Faster Transformer T4 FP16 (in ms) | Tensorflow XLA / Faster Transformer Tensorflow OP Speedup | GEMM 参数 | Faster Transformer C++ |
-- | -- | -- | -- | -- | -- |
(8, 6, 32, 12, 64) |  3.02 ms | 2.33 ms | 1.296 | 110, 99, 110, 100, 107 | 1.4 ms
(16, 6, 32, 12, 64) | 4.48 ms | 3.2 ms | 1.4 | 103, 103, 110, 107, 107 | 2.31 ms
(16, 6, 32, 12, 64) | 7.7 ms | 5.7 ms | 1.35 | 103, 105, 110, 107, 107 | 4.2 ms
(512, 6, 32, 12, 64) | 117.87 ms | 85.196 ms | 1.3835 |  99, 99, 106, 100, 100 | 57.05ms 

Using Faster Transformer in Tensorflow brings extra overhead. The best performance can be achieved with its C++ interface. You can use bin/transformer_fp16 to test the performance of C++. I also listed the performance number of C++ in the last column for your reference.

**Comment by IrishCoffee** [comment]
CPU I used is Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz
T4 has been boosted to the highest frequency.

**Comment by qiaohaijun** [comment]
@IrishCoffee Use your gemm config. I have reproduced your results.

I got the parameters by run 'bin/gemm_fp16' manually, I would like to ask, how these parameters are searched.

**Comment by qiaohaijun** [comment]
@IrishCoffee cuda 10.0 or cuda 10.1?

**Comment by IrishCoffee** [comment]
CUDA 10.0.

Just loop over all algorithms to find the best one.
https://github.com/NVIDIA/DeepLearningExamples/blob/master/FasterTransformer/tools/gemm_test/gemm_fp16.cu
