### ISSUE TITLE
[BERT/Tensorflow2] Documentation for Multi-GPU without Horovod

### ISSUE THREAD

**Issue by teddyroland** [NVIDIA/DeepLearningExamples#1163]
Before the feature request, a clarifying question: **What is the expected use case of the multi-gpu flags in run_pretraining.py?**

In particular, I'm looking at the following variables.
`FLAGS.scale_loss`, defined in `common_flags.py`
`FLAGS.num_gpus`, defined in `official/utils/flags/_base.py `
`FLAGS. distribution_strategy`, defined in `official/utils/flags/_base.py`
If there are others that I have missed, please let me know.

Were these variables implemented primarily for testing purposes (i.e. for comparison with the horovod implementation)? Were they necessary for TPU implementation, and GPU support was added for completeness?

(My questions are prompted by the response to #553.)

**Describe the solution you'd like**
A roadmap for pretraining BERT with multiple GPUs without using Horovod. This would include a template for the command-line that passes arguments into `run_pretraining.py`. For example:

`python run_pretraining.py --num_gpu=8 --distribution_strategy=mirrored --scale_loss ...`

Ideally, the roadmap would also include the calculation of batch size when using `distribution_strategy`, due to a possible bug.

**Is your feature request related to a problem? Please describe.**
In the use case I am describing, there appear to be bugs relating to global batch size and XLA. They will be opened as separate tickets. This feature request is for general guidance, and it is possible that the bug reports will be rendered moot.

**Comment by meatybobby** [comment]
The project is only tested with Horovod. I would suggest to try [Tensorflow's repository](https://github.com/tensorflow/models/tree/master/official/nlp) for running without Horovod and TPU.

**Comment by teddyroland** [comment]
@meatybobby Thanks.

Going back to my initial question: are the flags I mentioned intended for use with multiple TPUs?

**Comment by meatybobby** [comment]
The flags is for comparison the performance of MirroredStrategy and Horovod on GPU.

**Comment by teddyroland** [comment]
I gather from your reply and #553 that there was an internal round of testing on MirroredStrategy and that it was rejected in favor of Horovod. Does that mean that the variables I mentioned are a holdover from the early tests, with no current use?

**Comment by meatybobby** [comment]
Yes, currently the flags are not used.

**Comment by teddyroland** [comment]
Got it. Thanks again.
