### ISSUE TITLE
[BERT/TensorFlow2] Global Batch Size for Multi-GPU, without Horovod

### ISSUE THREAD

**Issue by teddyroland** [NVIDIA/DeepLearningExamples#1164]
Related to **BERT/TensorFlow2** 
Bug appears in scenario where `run_pretraining.py` is called with multiple GPUs, but not using the `horovod` library. I have opened a separate feature request (#1163) for general guidance.

**Describe the bug**
Currently, the logging in 'official/modeling/model_training_utils.py' reports `total_sentences` as if there were only one GPU, in the use-case I am describing.

This is due to the way `global_batch_size` gets counted. Currently, the variable is defined as
```
global_batch_size = FLAGS.train_batch_size * num_accumulative_step
if hvd:
      global_batch_size *= hvd.size()
```
The `global_batch_size` appears to be scaled by the number of replicas when `horovod` is used but not for TensorFlow's `distribution_strategy`.

**To Reproduce**

Run `python run_pretraining.py --num_gpu=2 --distribution_strategy=mirrored --scale_loss`, along with required arguments like `--input_files`, `--bert_config_file`, etc

**Expected behavior**
Expect that logging to stdout ([line 601](https://github.com/NVIDIA/DeepLearningExamples/blob/048370a0df5debb1fe366401a0b8204724d38bb4/TensorFlow2/LanguageModeling/BERT/official/modeling/model_training_utils.py#L601) in `model_training_utils.py`) will report `total_sentences` equal to `train_batch_size * num_accumulative_step * num_gpus * total_running_steps`

**Comment by meatybobby** [comment]
The batch size with MirroredStrategy would be global batch([Tensorflow's document](https://www.tensorflow.org/api_docs/python/tf/distribute/MirroredStrategy)). However, our tests are all with Horovod and we can't guarantee the training of MirroredStrategy.

**Comment by teddyroland** [comment]
Excellent. Yes, I see that `get_per_replica_batch_size` gets called inside of `run_pretraining.py` so that makes sense. Thanks for confirming.
