### ISSUE TITLE
[ELECTRA / TF2] docker build error: returned a non-zero code 1

### ISSUE THREAD

**Issue by goreng2** [NVIDIA/DeepLearningExamples#1167]
Related to **ELECTRA / TF2** 

**Describe the bug**
Hi, I tried to [this](https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow2/LanguageModeling/ELECTRA#quick-start-guide).
At the step 2: `bash scripts/docker/build.sh`, I encounter the below error
```
$ bash scripts/docker/build.sh
Sending build context to Docker daemon  1.129MB
Step 1/27 : ARG FROM_IMAGE_NAME=nvcr.io/nvidia/tensorflow:20.07-tf2-py3
Step 2/27 : FROM ${FROM_IMAGE_NAME} AS tokenizers_amd64
 ---> eb9f8c3d29b5
Step 3/27 : WORKDIR /wheelhouse
 ---> Using cache
 ---> 52899ff67725
Step 4/27 : RUN pip download tokenizers==0.7.0
 ---> Using cache
 ---> 7390e7bf538e
Step 5/27 : FROM quay.io/pypa/manylinux2014_aarch64 as tokenizers_arm64
 ---> 4da096c082d2
Step 6/27 : ARG PYVER=38
 ---> Using cache
 ---> abeec716d7e9
Step 7/27 : RUN yum install -y openssl-devel
 ---> [Warning] The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
 ---> Running in 96afef5e19a7
exec /bin/sh: exec format error
The command '/bin/sh -c yum install -y openssl-devel' returned a non-zero code: 1
```
reference: [Dockerfile](https://github.com/NVIDIA/DeepLearningExamples/blob/174b3d40bfc26f2adcf252676d38d6d5ffa7cbdc/TensorFlow2/LanguageModeling/ELECTRA/Dockerfile#L26)

**To Reproduce**
1. Clone the repository.
```
git clone https://github.com/NVIDIA/DeepLearningExamples.git
cd DeepLearningExamples/TensorFlow2/LanguageModeling/ELECTRA
```
2. Build ELECTRA on top of the NGC container.
```
bash scripts/docker/build.sh
```

**Expected behavior**
build docker images

**Environment**
Please provide at least:
* Container version (e.g. pytorch:19.05-py3): [Dockerfile](https://github.com/NVIDIA/DeepLearningExamples/blob/master/TensorFlow2/LanguageModeling/ELECTRA/Dockerfile)
* GPUs in the system: (e.g. 8x Tesla V100-SXM2-16GB): 4x NVIDIA RTX A6000-48GB
* CUDA driver version (e.g. 418.67): 510.73.08

**Comment by sharathts** [comment]
Are you trying to build on ARM? This repo doesn't support ARM currently.

**Comment by goreng2** [comment]
I find there are 2 parts in `Dockerfile`

One is for ARM, Another is for x86.

So I have to comment out upper chunk of [Dockerfile](https://github.com/NVIDIA/DeepLearningExamples/blob/eb3571096d13f04a71c802b005000f488a8f0139/TensorFlow2/LanguageModeling/ELECTRA/Dockerfile) and use from [here](https://github.com/NVIDIA/DeepLearningExamples/blob/eb3571096d13f04a71c802b005000f488a8f0139/TensorFlow2/LanguageModeling/ELECTRA/Dockerfile#L49)
