### ISSUE TITLE
FasterTransformer batch size 1 importance of CPU

### ISSUE THREAD

**Issue by jackkosaian** [NVIDIA/DeepLearningExamples#118]
The [performance results](https://github.com/NVIDIA/DeepLearningExamples/tree/master/FasterTransformer#performance) for batch size 1 inference with the FasterTransformer lists the following:
```
When batch size equals to 1, the Tensorflow execution time 
really depends on the CPU you are using.
```

Could someone explain why this is the case? Is this something unique to FasterTransformer?

Thanks!

**Comment by IrishCoffee** [comment]
For the case that batch size equals to 1, the bottleneck of original TensorFlow implementation is GPU kernel launch. This operation highly depends on the CPU you are using. Thus, we claim that "When batch size ......"

**Comment by jackkosaian** [comment]
I see. Thank you for the clarification!
