### ISSUE TITLE
TimeSeriesPredictionPlatform Creating Docker Two dependency errors

### ISSUE THREAD

**Issue by DaveBGld** [NVIDIA/DeepLearningExamples#1184]
[Following instructions from the Quick Starte here](https://github.com/NVIDIA/DeepLearningExamples/tree/master/Tools/PyTorch/TimeSeriesPredictionPlatform#quick-start-guide)

I get the following errors when running 

`
docker build -t tspp .
`
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
typer 0.3.2 requires click<7.2.0,>=7.1.1, but you have click 8.1.3 which is incompatible.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
triton-model-analyzer 1.7.0 requires matplotlib>=3.3.4, but you have matplotlib 3.3.2 which is incompatible.

```

The complete output is attached
[docker creation log.txt](https://github.com/NVIDIA/DeepLearningExamples/files/9242752/docker.creation.log.txt)

Thanks for any help!

Dave

**Comment by jbaczek** [comment]
Hi, @DaveBGld.
In the logs you've provided I can see that you use image `nvcr.io/nvidia/pytorch:21.09-py3` which might be not compatible with the code in the repository. Is there any reason why do you need this specific image?
If not then please use the Dockerfile provided in the repository which points to `nvcr.io/nvidia/pytorch:22.04-py3`
https://github.com/NVIDIA/DeepLearningExamples/blob/master/Tools/PyTorch/TimeSeriesPredictionPlatform/Dockerfile#L2

**Comment by DaveBGld** [comment]
Thanbks jbaczek for your comment!

I did nothing to select that image other that I am working on a unet tao custom model that I started in January, and that's why that image may be in my system. I am SUPER AFRAID to bring a new image because it was literally PAINFUL to get all versions of CUDA, tensorRT, cuDNN, cuBLAS and OpenCV and ROS to synchronize. I still suffer from PTSD from that... 

My ultimate goal however is to be able to run locally NVIDIA's entry to a **Kaggle competition [here](https://www.kaggle.com/code/anmolgupta11090/jpx-tokyo-stock-prediction-with-nvidia-tspp)**  which is based on TimeSeriesPredictionPlatform and are having trouble getting all requirements... (boy do I miss npm).

Until I find a solution to that toolchain version challenge (I haven't seen a way to control which version of the docker is loaded by tao), I can't really create the TimeSeriesPredictionPlatform docker, so I'm trying to build a conda virtualenv by hand for the kaggle notebook, and that is giving me trouble with installed modules (hydra-core) reporting that "No module named 'hydra_utils'"


Thanks!!

**Comment by anmolgupt** [comment]
Hi @DaveBGld, hydra_utils file is [here](https://github.com/NVIDIA/DeepLearningExamples/blob/master/Tools/PyTorch/TimeSeriesPredictionPlatform/hydra_utils.py). In the Dockerfile, we set PYTHONPATH to point to the TSPP directory: [here](https://github.com/NVIDIA/DeepLearningExamples/blob/master/Tools/PyTorch/TimeSeriesPredictionPlatform/Dockerfile#L41). In the kaggle notebook, TSPP directory path is added [here](https://www.kaggle.com/code/anmolgupta11090/jpx-tokyo-stock-prediction-with-nvidia-tspp?scriptVersionId=98566934&cellId=12). Is the TSPP directory path set in your environment?

**Comment by DaveBGld** [comment]
Thanks @anmolgupt. I was able to integrate the hydra utils in your comment. 

I am using a copy of your kaggle notebook (version 2 of 2) and you just helped me get over the Setup and installations section on a local conda environment.

Truthful thanks!!

Dave
