### ISSUE TITLE
How to run the ResNet-50 Pytorch on multi-node?

### ISSUE THREAD

**Issue by ZJLi2013** [NVIDIA/DeepLearningExamples#1188]
looks the current code only support single node / multi gpu training.

**Comment by mmarcinkiewicz** [comment]
Multinode training should work out of the box, providing you are using slurm+pyxis.

Are there any concrete issues you are facing?

**Comment by ZJLi2013** [comment]
> Multinode training should work out of the box, providing you are using slurm+pyxis.
> 
> Are there any concrete issues you are facing?

thanks for replying, I tried the command from [readme](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Classification/ConvNets/resnet50v1.5)

```sh
python ./multiproc.py --nnodes 2 --nproc_per_node 8 ./main.py --arch resnet50 -c fanin --label-smoothing 0.1 --amp --static-loss-scale 256 <path to imagenet>
``` 

it create 2 process groups, each has 8 process, and on one node, while I suppose it should be one group with 16 processes. 

how should to use multi-nodes then?

**Comment by ZJLi2013** [comment]
solved, due to `--node_rank ${SLURM_NODEID}` should be runtime defined. thanks again
