### ISSUE TITLE
Why do batched transforms in the dataloader?

### ISSUE THREAD

**Issue by shizidushu** [NVIDIA/DeepLearningExamples#1190]
https://github.com/NVIDIA/DeepLearningExamples/blob/475cff63464736d836e1113a9839fc176bf67b38/TensorFlow2/Segmentation/UNet_Medical/data_loading/data_loader.py#L126-L128

I notice the batched transforms in the code. Does this make the data loading process faster?

**Comment by mmarcinkiewicz** [comment]
Faster? Possibly. We are expanding dims to accommodate the TF API. For example [Crop and resize](https://www.tensorflow.org/api_docs/python/tf/image/crop_and_resize) requires `A 4-D tensor of shape [batch, image_height, image_width, depth]. Both image_height and image_width need to be positive.`
