### ISSUE TITLE
[SE3Transformer/pytorch]: hardcoded number of feature makes it hard to modify.

### ISSUE THREAD

**Issue by aosokin** [NVIDIA/DeepLearningExamples#1203]
In the example for SE3Transformer, the number of node features is hardcoded in the custom collate function:
https://github.com/NVIDIA/DeepLearningExamples/blob/63cbbdc2588f7925a4e5cc30bc6e0cb51d9c166a/DGLPyTorch/DrugDiscovery/SE3Transformer/se3_transformer/data_loading/qm9.py#L105

Instead, it should use the class attribute already containign this information:
```python
node_feats = {'0': batched_graph.ndata['attr'][:, :self.NODE_FEATURE_DIM, None]} 
```
This improvement will make it much easier to work with the example for different feature representations of the QM9 dataset.

**Comment by milesial** [comment]
Hi, thank you for raising this, it's indeed a good idea. I'll update the code this week, also doing this with `EDGE_FEATURE_DIM` for edge features.

**Comment by milesial** [comment]
Fixed in https://github.com/NVIDIA/DeepLearningExamples/commit/f4b9bdfd2f3bc4a096f01d17526ff8e7aa9121f2

**Comment by aosokin** [comment]
Thanks a lot! And thanks for the great code!
