### ISSUE TITLE
[Model]  The pytorch/detection/SSD/ssd's dowload Link is wrong!

### ISSUE THREAD

**Issue by lyj-de-husband** [NVIDIA/DeepLearningExamples#1211]
Related to **Model** 

**Describe the bug**
The file(pytorch/detection/SSD/ssd/entrypoints.py) is using a wrong download link at line:199
The right link is "https://api.ngc.nvidia.com/v2/models/nvidia/dle/ssd__pyt_ckpt/versions/20.06.0_amp/files/nvidia_ssdpyt_amp_200703.pt"

**Environment**
* Container version :torch==1.11.0+cu113

**Comment by nv-kkudrynski** [comment]
Hi. The old link has been fixed and both should work now. Thanks for issuing this bug.
