### ISSUE TITLE
[EfficientNet/TensorFlow2] broken link on readme

### ISSUE THREAD

**Issue by peterjpxie** [NVIDIA/DeepLearningExamples#1237]
Related to **Model/Framework(s)** 
EfficientNet/TensorFlow2

**Describe the bug**
![image](https://user-images.githubusercontent.com/12903395/206602900-6708baa3-0cbc-4e02-9d98-09f96c2ddd3e.png)

**To Reproduce**
Click the link on main readme

**Comment by ntajbakhsh** [comment]
Links were fixed. Please close the bug if you are happy with the result.
