### ISSUE TITLE
Query BlockSize with correct function

### ISSUE THREAD

**Issue by wchen61** [NVIDIA/DeepLearningExamples#1238]
Should use corresponding func to query block size with or without NCHW.

https://github.com/NVIDIA/DeepLearningExamples/blob/eb3571096d13f04a71c802b005000f488a8f0139/PyTorch/Segmentation/MaskRCNN/pytorch/maskrcnn_benchmark/csrc/cuda/ROIAlign_cuda.cu#L506
https://github.com/NVIDIA/DeepLearningExamples/blob/eb3571096d13f04a71c802b005000f488a8f0139/PyTorch/Segmentation/MaskRCNN/pytorch/maskrcnn_benchmark/csrc/cuda/ROIAlign_cuda.cu#L584

**Comment by ntajbakhsh** [comment]
Can you be more specific about the bug and how it's affecting you?

**Comment by wchen61** [comment]
> Can you be more specific about the bug and how it's affecting you?

Hi, @ntajbakhsh. 
I can run this model, but just found the code is not align if I run with NHWC mode.

cudaOccupancyMaxPotentialBlockSize will return different gridSize for RoIAlignBackwardFeature and RoIAlignBackwardFeatureNHWC.
