### ISSUE TITLE
[SE3Transformer/pytorch] Multiplication error in the ConvSE3

### ISSUE THREAD

**Issue by Siyeong-Lee** [NVIDIA/DeepLearningExamples#1250]
I am a beginner of SE3-Transformer. I wanted to train the qm9 dataset by dividing the input type into two, so I modified the code as follows.

### data_loading/qm9.py
```python
        # get node features
        # original : node_feats = {'0': batched_graph.ndata['attr'][:, :self.NODE_FEATURE_DIM, None]}
        node_feats = {'0': batched_graph.ndata['attr'][:, :5, None],
                      '1': batched_graph.ndata['attr'][:, 5:6, None]}
```

### runtime/training.py
```python
# the original value of datamodule.NODE_FEATURE_DIM in QM9:  6
model = SE3TransformerPooled(
        fiber_in=Fiber({0: 5, 1: 1}), # original: Fiber({0: datamodule.EDGE_FEATURE_DIM})
        fiber_out=Fiber({0: args.num_degrees * args.num_channels}),
        fiber_edge=Fiber({0: datamodule.EDGE_FEATURE_DIM}),
        output_dim=1,
        tensor_cores=using_tensor_cores(args.amp),  # use Tensor Cores more effectively
        **vars(args)
)
```

In this case, it stops with the error shown below.
```shell
RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [8910, 1] but got: [8910, 3].
```
I think that self-attention should be performed even if SE3-transformer has multiple input types. But I would like to know why it is not working.

**Comment by milesial** [comment]
What are you trying to achieve? The 6th feature you are extracting here is the proton number, which is an invariant scalar (1D). Here you are passing this scalar as a type-1 feature which is for 3D vectors, and the model expects a 3D vector so it errors as it should.

**Comment by Siyeong-Lee** [comment]
@milesial Thank you for quick reply. 

You're right.  I lacked understanding of the original paper.  

My purpose is to break the symmetric in the +z direction in pointcloud classification (SE3-transformer +z in the SE3-transformer work).     
I thought this idea would be implemented through a method similar to the way mentioned above.

Even if the meaning is wrong in the QM9 dataset, I wanted to make sure that the SE3-transformer works normally by making the shape of the input the same.

Your comment made me think deeply about this work. Thank you.

**Comment by milesial** [comment]
Yes, for point cloud experiments using +z, I suggest code like this:

```
absolute_z = points[:, -1]

# position relative to neighbors
relative_pos = points[src] - points[dst]
relative_z = relative_pos[:, -1].clone()
relative_pos_no_z = relative_pos.clone()
relative_pos_no_z[:, -1] = 0
feat = torch.stack([relative_pos, relative_pos_no_z], dim=1)
edge_feats = {'0': relative_z[..., None, None], '1': feat}
node_feats = {'0': absolute_z[..., None, None]}
```

With the model defined with:
```
fiber_in=Fiber({0: 1}),
fiber_edge=Fiber({0: 1, 1: 2}),
```

That way you have two 3D edge features: one vector and one vector with z=0. You also have one 1D edge feature: the relative z component. You have one 1D node feature: the absolute z component.

You can find more insight in this discussion about ScanObjectNN https://github.com/FabianFuchsML/se3-transformer-public/issues/13

**Comment by Siyeong-Lee** [comment]
Thank you for the detailed answers. Following your advice, I will refer to the issue you mentioned.
