### ISSUE TITLE
[Model] Mismatch of model bert-base-sst2 vocab

### ISSUE THREAD

**Issue by cwlseu** [NVIDIA/DeepLearningExamples#1275]
The vocab size of the model [bert-base-uncased-sst2](https://catalog.ngc.nvidia.com/orgs/nvidia/models/bert_pyt_ckpt_base_ft_sst2_amp_128/files) is 30528, this [vocab](https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/LanguageModeling/BERT/vocab/vocab) size is mismatch. I have checked multiple models one after another, and there are similar problems. For example [bert-dist-6L-768D-uncased-sst2](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/dle/models/bert_pyt_ckpt_distilled_6l_768d_ft_sst2_amp/files)

**Comment by sharathts** [comment]
This is known, we pad the vocab size to a multiple of 8, [here](https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/LanguageModeling/BERT/run_pretraining.py#L383-L384) for higher training speed.

Hence we instantiate a vocabulary of size 30528 in the model (though actual vocabulary contains 30522 tokens). The last 6 embeddings are untouched and training works as expected.

**Comment by cwlseu** [comment]
@sharathts Got it, thanks for your explanation
