### ISSUE TITLE
nnunet example dali pipeline loader thinking some grayscale images are rbg

### ISSUE THREAD

**Issue by rachelglenn** [NVIDIA/DeepLearningExamples#1278]
I have a cloned version of the nnunet example:
https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/Segmentation/nnUNet/data_loading/dali_loader.py
on my github site:
https://github.com/rachelglenn/MIST/blob/no_tf_records/data_loading/dali_loader.py
I have checked that my code runs with several different grayscale databases. Now I am trying a new dataset.  
 I have checked that all images are scalar grayscale images (no multichannel information). The dali loader is loading some (not all) images as if they are rgb. This is the error that I am seeing: 

Training Started | 2023-03-21 19:14:22.692101

Starting fold 0...
image shape DataNode(name="__Cast_9", device="cpu")
using optimizer adam
Learning rate: 0.000300
image size-----> (2, 256, 256, 32, 1) (2, 256, 256, 32, 1)
mask size-----> (2, 256, 256, 32, 1) (2, 256, 256, 32, 1)
Fold 0: Epoch 1/125
 1/55 [..............................] - ETA: 30:26 - loss: 1.0640image size-----> (2, 256, 256, 32, 1) (2, 256, 256, 32, 1)
mask size-----> (2, 256, 256, 32, 1) (2, 256, 256, 32, 1)
 2/55 [>.............................] - ETA: 9s - loss: 1.0607   image size-----> (2, 256, 256, 32, 1) (2, 256, 256, 32, 1)
mask size-----> (2, 256, 256, 32, 1) (2, 256, 256, 32, 1)
 3/55 [>.............................] - ETA: 9s - loss: 1.0513Traceback (most recent call last):
  File "/rglenn1/segLiverWkspce/docker_mist/latest_MIST/main.py", line 84, in <module>
    main(args)
  File "/rglenn1/segLiverWkspce/docker_mist/latest_MIST/main.py", line 72, in main
    runtime.run()
  File "/rglenn1/segLiverWkspce/docker_mist/latest_MIST/runtime/run.py", line 423, in run
    self.train()
  File "/rglenn1/segLiverWkspce/docker_mist/latest_MIST/runtime/run.py", line 285, in train
    for global_step, (image, mask) in enumerate(train_loader):
  File "/rglenn1/support_packages/miniconda/conda_gpu4/envs/tf_gpu4_env/lib/python3.10/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 766, in __next__
    return self._next_internal()
  File "/rglenn1/support_packages/miniconda/conda_gpu4/envs/tf_gpu4_env/lib/python3.10/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 749, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
  File "/rglenn1/support_packages/miniconda/conda_gpu4/envs/tf_gpu4_env/lib/python3.10/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 3017, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/rglenn1/support_packages/miniconda/conda_gpu4/envs/tf_gpu4_env/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 7209, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.FailedPreconditionError: {{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:GPU:0}} Batch output at index '0' from DALI pipeline is not uniform - individual samples have different dimensions. This output cannot be represented as single, dense Tensor, which is required by TensorFlow. Ensure that all the samples that you produce in given batch have equal shape. Got shapes: [256,256,32,3], [256,256,32,1] [Op:IteratorGetNext]

I have tried to find a way in the dali pipline to specify that the numpy images being read in are grayscale. However, I have had no luck. I have tried the following type of code:

shapes = fn.cast(fn.peek_image_shape(img), dtype=types.FLOAT)  
        print("image shape", shapes)
        #if shapes[-1] > 1:
        #  img = fn.color_space_conversion(img, image_type=types.RGB , output_type=types.GRAY )

Env:
Build cuda_11.6.r11.6/compiler.30794723_0
NVIDIA-SMI 460.32.03 
tensorflow                    2.10.0
Python 3.10.8

**Comment by michal2409** [comment]
Hello @rachelglenn, after reviewing the error log, it appears that there might be images in your dataset with both 3 and 1 channels. To ensure that the pipeline can process your data correctly, please make sure that all images in your dataset have an equal number of channels.

**Comment by rachelglenn** [comment]
Yes, I have checked that all images are grayscale. I print out the shape of the mask and image before they are saved as numpy files.

mask size-----> (2, 256, 256, 32, 1) (2, 256, 256, 32, 1)
image size-----> (2, 256, 256, 32, 1) (2, 256, 256, 32, 1)

**Comment by michal2409** [comment]
The NumPy arrays with single 3D image should have 4 dimensions (Depth, Height, Width, Channel). Not sure why you are having 5D tensors, but maybe that's the reason.

**Comment by rachelglenn** [comment]
Thanks, I will check that out.

Rachel

**Comment by rachelglenn** [comment]
Thanks, I found the issue. It was with the datset.
