### ISSUE TITLE
Unused `model_state` variable in Resnet50 builder

### ISSUE THREAD

**Issue by rmccorm4** [NVIDIA/DeepLearningExamples#128]
Hi,

https://github.com/NVIDIA/DeepLearningExamples/blob/71fdde7200d222c05e907de8135de40c90d569d2/PyTorch/Classification/RN50v1.5/image_classification/resnet.py#L259

model_state being unused in [this function](https://github.com/NVIDIA/DeepLearningExamples/blob/71fdde7200d222c05e907de8135de40c90d569d2/PyTorch/Classification/RN50v1.5/image_classification/resnet.py#L259) caused incorrect results for my model and this took me a while to figure out.

I think it would be helpful if this argument was either updated to be used or removed completely.

Thanks,
Ryan

**Comment by asulecki** [comment]
Thanks, this will be fixed in the next release.
