### ISSUE TITLE
Why fp16 audio example in Tacotron2 is so noisy?

### ISSUE THREAD

**Issue by ide8** [NVIDIA/DeepLearningExamples#129]
https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/SpeechSynthesis/Tacotron2/audio

**Comment by nvpstr** [comment]
https://github.com/NVIDIA/DeepLearningExamples/pull/132

**Comment by nvpstr** [comment]
There was an error during publishing. It should be fixed now. Thanks.
