### ISSUE TITLE
BERT, run_classifier.py, got `ValueError: max() arg is an empty sequence ` error

### ISSUE THREAD

**Issue by wxp16** [NVIDIA/DeepLearningExamples#131]
when do inference by setting `--do_predict=true`, the variable of `time_list ` is empty. So when execute `cf_50 = max(time_list[:int(len(time_list) * 0.50)])`, got `ValueError: max() arg is an empty sequence
`

**Comment by swethmandava** [comment]
Should be fixed in #138
