### ISSUE TITLE
[FasterTransformer] INT8 support

### ISSUE THREAD

**Issue by jackkosaian** [NVIDIA/DeepLearningExamples#137]
Is there any plan to support INT8 (e.g., for Turing Tensor Cores)?

Thanks!

**Comment by IrishCoffee** [comment]
No plan in the near future.

Using int8 will not bring too much speedup based on our evaluation.

**Comment by jackkosaian** [comment]
I see. Can you provide intuition as to why INT8 won't bring much speedup? Are there benchmarks for this that you can share?

**Comment by IrishCoffee** [comment]
When using int8, we have to quantize the input and dequantize the output. This will bring some extra overhead.

Int8 will bring some speedups in some networks. I will share some numbers once there is a conclusion.
