### ISSUE TITLE
faster tranformer cause "cross_check False "

### ISSUE THREAD

**Issue by wykdg** [NVIDIA/DeepLearningExamples#141]
environment
centos 7 
tensorflow-gpu 1.13.1
cuda10 
cudnn 7.6
gcc 7.3 

i compile  the tf_op,following https://github.com/NVIDIA/DeepLearningExamples/issues/114
it can run ,but always return the same 

how can i fix it ,thanks

**Comment by wykdg** [comment]
addition
python 3.6 with conda

**Comment by IrishCoffee** [comment]
You are testing fp16 or fp32?

For fp16, if the diff number is something like 0.02, the answer is right.

**Comment by wykdg** [comment]
fp32，and the max diff  is 3.              
I compile the code without any modify.

**Comment by IrishCoffee** [comment]
What commands do you use to run the transformer_fp32.py? 

Did you specify the -DSM when compiling the code? Did you generate a new gemm_config.in?

**Comment by wykdg** [comment]
gemm_config.in was generate by gemmfp32
DSM i have try 60 61 70 75
I run the check with commond "transformer_fp32.py 2 2 2 2 2" .And some other parmamters, but all of them are wrong ,except 1 1 1 1 1 .

**Comment by IrishCoffee** [comment]
Please try with some common configurations. For example, python transformer_fp32.py 1 12 128 12 64 to test the case batch size = 1, seq_len = 128, 12 layers with bert base.

**Comment by IrishCoffee** [comment]
2 2 2 2 2 are meaningless parameters. Especially the settings of the head_num and size_per_head.

**Comment by wykdg** [comment]
here is the result of "python transformer_fp32.py 1 12 128 12 64 "
cross_check False
max diff 4.412327
min diff 6.79539e-06


maybe there is something wrong with abi ?

**Comment by IrishCoffee** [comment]
What GPU do you use? What DSM values did you set?

What's the content of the gemm_config.in you generated?

**Comment by wykdg** [comment]
GPU is tesla M40,Driver Version: 418.67 
DSM, i had try 60 61 70
gemm_config.in is 
"13
13
13
6
2
"

**Comment by IrishCoffee** [comment]
The compute capability of M40 is 52.  You can have a try but I am not sure whether the code can be executed correctly on M40.
