### ISSUE TITLE
Clarify Tensorflow 1.14 oom issue

### ISSUE THREAD

**Issue by rllin-fathom** [NVIDIA/DeepLearningExamples#142]
In [1], there is this note,

> There is an issue in TensorFlow 1.14 that increases the GPU memory footprint of certain models such as BERT. As a result, training may need to be performed with a reduced batch size.

Hard to find the equivalent issue tracking this in https://github.com/tensorflow/tensorflow/issues.  Could someone point to it?

[1] https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/rel_19.07.html#rel_19.07

**Comment by nv-kkudrynski** [comment]
No longer relevant
