### ISSUE TITLE
cublasGemmStridedBatchedEx       Compute Type

### ISSUE THREAD

**Issue by fxrhhx** [NVIDIA/DeepLearningExamples#143]
I want to know why  I set  Compute Type as CUDA_R_16F and A,B,C Data Type as CUDA_R_16F ,the result of matrix multiplication is 0 . But when set compute tyep as CUDA_R_32F and A,B,C as CUDA_R_16F ,the answer is right.

**Comment by mwawrzos** [comment]
Is the question related to some code from this repository?

**Comment by fxrhhx** [comment]
yes. the file path : DeepLearningExamples/FasterTransformer/tools/gemm_test/gemm_fp16.cu

**Comment by IrishCoffee** [comment]
Compute Type means what precision will be used in the accumulator.  CUDA_R_32F (fp32 precision) has higher precision. For Faster Transformer, CUDA_R_16F is ok.

**Comment by fxrhhx** [comment]
if  I set compute type as CUDA_R_32F in gemm_fp16.cu ,what impact on the performance compare with compute type CUDA_R_16F

**Comment by IrishCoffee** [comment]
Using CUDA_R_32F invokes different gemm kernels, which are a little bit slower than the kernels invoked by CUDA_R_16F. You can use nvprof to see what kernels are be invoked.

**Comment by fxrhhx** [comment]
Thanks a lot.
