### ISSUE TITLE
How to set clip_norm for Transformer?

### ISSUE THREAD

**Issue by yaoyiran** [NVIDIA/DeepLearningExamples#146]
When I was running transformer code on another dataset, it shows the following after several epochs (I have reset the minimum loss scale to a very small number but it still happens):

| WARNING: overflow detected, setting loss scale to: 0.5
| WARNING: overflow detected, setting loss scale to: 0.25
| WARNING: overflow detected, setting loss scale to: 0.125
| WARNING: overflow detected, setting loss scale to: 0.0625
| WARNING: overflow detected, setting loss scale to: 0.03125
| WARNING: overflow detected, setting loss scale to: 0.015625
| WARNING: overflow detected, setting loss scale to: 0.0078125
| WARNING: overflow detected, setting loss scale to: 0.00390625
| WARNING: overflow detected, setting loss scale to: 0.001953125
| WARNING: overflow detected, setting loss scale to: 0.0009765625
| WARNING: overflow detected, setting loss scale to: 0.00048828125
| WARNING: overflow detected, setting loss scale to: 0.000244140625
| WARNING: overflow detected, setting loss scale to: 0.0001220703125
| WARNING: overflow detected, setting loss scale to: 6.103515625e-05
| WARNING: overflow detected, setting loss scale to: 3.0517578125e-05
| WARNING: overflow detected, setting loss scale to: 1.52587890625e-05
| WARNING: overflow detected, setting loss scale to: 7.62939453125e-06
| WARNING: overflow detected, setting loss scale to: 3.814697265625e-06
| WARNING: overflow detected, setting loss scale to: 1.9073486328125e-06
| WARNING: overflow detected, setting loss scale to: 9.5367431640625e-07
| WARNING: overflow detected, setting loss scale to: 4.76837158203125e-07
| WARNING: overflow detected, setting loss scale to: 2.384185791015625e-07
| WARNING: overflow detected, setting loss scale to: 1.1920928955078125e-07
| WARNING: overflow detected, setting loss scale to: 5.960464477539063e-08
| WARNING: overflow detected, setting loss scale to: 2.9802322387695312e-08
| WARNING: overflow detected, setting loss scale to: 1.4901161193847656e-08
Traceback (most recent call last):
  File "/workspace/translation/train.py", line 499, in <module>
    distributed_main(args)
  File "/workspace/translation/distributed_train.py", line 40, in main
Traceback (most recent call last):
  File "/workspace/translation/train.py", line 499, in <module>
    single_process_main(args)
  File "/workspace/translation/train.py", line 106, in main
    distributed_main(args)
  File "/workspace/translation/distributed_train.py", line 40, in main
    train(args, trainer, task, epoch_itr)
  File "/workspace/translation/train.py", line 158, in train
    single_process_main(args)
  File "/workspace/translation/train.py", line 106, in main
    log_output = trainer.train_step(sample, update_params=True, last_step=(i == len(itr)-1))
  File "/workspace/translation/fairseq/trainer.py", line 167, in train_step
    train(args, trainer, task, epoch_itr)
  File "/workspace/translation/train.py", line 158, in train
    log_output = trainer.train_step(sample, update_params=True, last_step=(i == len(itr)-1))
  File "/workspace/translation/fairseq/trainer.py", line 167, in train_step
    grad_norm = self._all_reduce_and_rescale(grad_denom, sample is not None)
  File "/workspace/translation/fairseq/fp16_trainer.py", line 329, in _all_reduce_and_rescale
    grad_norm = self._all_reduce_and_rescale(grad_denom, sample is not None)
  File "/workspace/translation/fairseq/fp16_trainer.py", line 329, in _all_reduce_and_rescale
    ).format(self.args.min_loss_scale))
    ).format(self.args.min_loss_scale))
Exception: Minimum loss scale reached (1e-08). Your loss is probably exploding. Try lowering the learning rate, using gradient clipping or increasing the batch size.
Exception: Minimum loss scale reached (1e-08). Your loss is probably exploding. Try lowering the learning rate, using gradient clipping or increasing the batch size.

So I guess I may need to set the  --clip-norm parameter when training. The default clip_norm is 0 and in the training log, it shows sth. like the following:
| epoch 002:   6000 / 7872 loss=5.173, nll_loss=3.627, ppl=12.36, wps=71222, ups=2.0, wpb=36154, bsz=1165, num_updates=6930, lr=0.00051975, gnorm=76174.198, clip=100%, oom=0, loss_scale=8.000, wall=3488

Does clip=100% mean that all gradients are not clipped? If I set --clip-norm = 0.1, does that mean all gradients whose norm are greater than 0.1 will be abandoned? Do you have any suggestion on a typical clip_norm, say, 0.01 or 0.6?

**Comment by jbaczek** [comment]
Hi! Clip norm is the maximal value  of the tensor's norm. If the value is 0 gradient is not clipped at all.
Here it's called https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/Translation/Transformer/fairseq/trainer.py#L278
And here is the definition:
https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/Translation/Transformer/fairseq/utils.py#L364
This value is problem specific
