### ISSUE TITLE
argument manual_fp16=False in apply_gradients()

### ISSUE THREAD

**Issue by FruVirus** [NVIDIA/DeepLearningExamples#152]
In optimization.py, apply_gradients() takes the argument "manual_fp16" with a default value of False. However, there is no way to pass in this argument via optimizer.apply_gradients if use_fp=True.

If manual_fp16 is True, should the optimizer default to the sub-classed AdamWeightDecayOptimizer? In addition, does it make sense for both manual_fp16 and use_fp16 to have a value of True at the same time?

**Comment by swethmandava** [comment]
manual_fp16 is set to True when you want to manually cast variables to fp16 and perform mixed precision training. 
use_fp16 is set to True when you want to use AMP (abstraction for performing mixed precision training without actually coding it all by simply setting an environment variable. More details on AMP can be found here: https://developer.nvidia.com/automatic-mixed-precision)

So you do not need to pass use_fp16 to the optimizer. we simply set the environment variable TF_ENABLE_AUTO_MIXED_PRECISION_GRAPH_REWRITE=1 when use_fp16 is True and that takes care of everything.

manual_fp16 and use_fp16 are hence two ways of doing the same thing and shouldn't both be enabled. We will throw an error if that is the case in the future.
