### ISSUE TITLE
Wrong device_id in dali_train_loader for RN50v1.5

### ISSUE THREAD

**Issue by Shenggan** [NVIDIA/DeepLearningExamples#159]
I suppose this will be the same as `args.local_rank` not the rank in the world.

https://github.com/NVIDIA/DeepLearningExamples/blob/e25c23e14ab470a7024927c9b6cd15c7d5067fcf/PyTorch/Classification/RN50v1.5/image_classification/dataloaders.py#L124

https://github.com/NVIDIA/DeepLearningExamples/blob/e25c23e14ab470a7024927c9b6cd15c7d5067fcf/PyTorch/Classification/RN50v1.5/image_classification/dataloaders.py#L147

**Comment by Shenggan** [comment]
And `async` is deprecated after PyTorch version 1.0,  and replaced by `non_blocking`.

https://github.com/NVIDIA/DeepLearningExamples/blob/e25c23e14ab470a7024927c9b6cd15c7d5067fcf/PyTorch/Classification/RN50v1.5/image_classification/dataloaders.py#L202-L203

**Comment by asulecki** [comment]
The local variable should be named `rank` instead of `local_rank`, since for dataset sharding we want to split dataset on all the workers.

Will be fixed in next release.

**Comment by Shenggan** [comment]
Thanks for reply @asulecki. But the rank will assign to the device_id in:
https://github.com/NVIDIA/DeepLearningExamples/blob/e25c23e14ab470a7024927c9b6cd15c7d5067fcf/PyTorch/Classification/RN50v1.5/image_classification/dataloaders.py#L133

So I think it will use wrong device when distributed.

**Comment by asulecki** [comment]
That's right, if used in distributed environment it won't work. This script is not officialy supporting distributed, but this issue will be fixed in next release.
