### ISSUE TITLE
how to use FasterTransformer with tf trained ckpt model

### ISSUE THREAD

**Issue by bikong2** [NVIDIA/DeepLearningExamples#160]
hi,

if i have trained a bert based model with tensorlfow, which saved in format of ckpt. what can i do to transform ckpt based model to FasterTransformer model, and how could i integrate the transformed model into my pipline code?
is there an example?

thanks,

**Comment by IrishCoffee** [comment]
We cannot support using ckpt directly.

Please follow sample/tensorflow_bert to see how to use this OP in your current pipeline.
