### ISSUE TITLE
No OpKernel was registered to support Op 'BertTransformer'

### ISSUE THREAD

**Issue by leerumor** [NVIDIA/DeepLearningExamples#161]
I got this when running tensorflow demos and bert:
```
InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'BertTransformer' used by node bert/encoder/layer_0/BertTransformer (defined at <string>:148) with these attrs: [from_seq_len=128, size_per_head=64, batch_size=8, to_seq_len=128, T=DT_FLOAT, head_num=12]
Registered devices: [CPU, XLA_CPU]
Registered kernels:
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_FLOAT]

         [[node bert/encoder/layer_0/BertTransformer (defined at <string>:148) ]]
```
I use:
tensorflow=1.13.1
python=2.7

I checked my /build/lib/libtf_fastertransformer.so and it is successfully imported

**Comment by IrishCoffee** [comment]
Please check your environment. 

"Registered devices: [CPU, XLA_CPU]" It seems that tensorflow didn't recognize any available GPUs on your node.

**Comment by leerumor** [comment]
> Please check your environment.
> 
> "Registered devices: [CPU, XLA_CPU]" It seems that tensorflow didn't recognize any available GPUs on your node.

Thank you, I should install tensorflow-gpu instead of tensorflow
