### ISSUE TITLE
multi-node distributed training support?

### ISSUE THREAD

**Issue by Engineering-Course** [NVIDIA/DeepLearningExamples#162]
I'm training Jasper on LibriSpeech.
It is reported that training with  (8x V100 32G) GPUs needs 100 hrs with a batch size of 64. 
However, we only have 2080Ti GPUs, of which the batch size is 8. The total training time will be daunting.
So I wonder when will this repo support for multi-node distributed training?

**Comment by nvpstr** [comment]
We are already adding multi-gpu support for some of the models, e.g. https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/LanguageModeling/BERT#multi-node.

Stay tuned.
