### ISSUE TITLE
fp16 cross_check false

### ISSUE THREAD

**Issue by colourful-tree** [NVIDIA/DeepLearningExamples#167]
env:
ubuntu           18.04
python:           3.6.8
GCC:               8.0.1
tensorflow:     1.13.0-rc2
CUDA:             10.0

1. I install in tensorflow mode with V100 :
cmake -DSM=70 -DCMAKE_BUILD_TYPE=Release -DBUILD_TF=ON -DTF_PATH=/usr/local/lib/python2.7/dist-packages/tensorflow .. # Tensorflow mode

2. and then generate the gemm_config.in with:
 ./build/bin/gemm_fp16 100 32 12 64
 run with:
  python transformer_fp16.py 100 12 32 12 64

But i got some result like:
![GetImage](https://user-images.githubusercontent.com/17588577/63313094-ef7adb80-c335-11e9-93f6-233a9f78660d.png)

So, we can see that FasterTransformer output have a big diff vs OriginTransformer in fp16 like 0.0332, and then i try run OriginTransformer twice,  the diff is 0.007812.

My problem is:
1.FasterTransformer the diff 0.0332 is big or not? whether or not  affect convergence? because OriginTransformer run twice is only 0.007812.
2.why diff(0.0332 vs 0.007812) is different, i think this maybe because FasterTransformer  fuse some ops, but OriginTransformer don't, so maybe the Intermediate variable will cause the different?

**Comment by IrishCoffee** [comment]
So far we think 0.0332 diff means the computation result is correct.

The big diff may come from using FP16 accumulator in the matrix multiplication. Using FP16 as the accumulator type has better performance than FP32.

You can see the final result of the entire pipeline, for example, F1 score of a SQUAD task. The score is roughly the same.

**Comment by colourful-tree** [comment]
okay, thanks for your response.
1、> Using FP16 as the accumulator type has better performance than FP32
that make me a little confused, you mean fp16 accumulator type better than fp32?
2、No matter FP16 is better than FP32 or FP32 is better than FP16. Now, we only consider the situation of fp16, why OriginTransformer diff is 0.007812, and FasterTransformer is 0.0332, this make me confused too, because as far as i know FasterTransformer fuse 50+ ops to 16 ops, but i think these will not leed to the diff.
Thx~

**Comment by colourful-tree** [comment]
> So far we think 0.0332 diff means the computation result is correct.
> 
> The big diff may come from using FP16 accumulator in the matrix multiplication. Using FP16 as the accumulator type has better performance than FP32.
> 
> You can check the final result of the entire pipeline, for example, F1 score of a SQUAD task. The score is roughly the same.

**Comment by IrishCoffee** [comment]
When calling cublasGemmEx to calculate the gemm in FP16, we can choose the datatype of A,B,C as FP16 and the computeType as FP16 or FP32.

**Comment by colourful-tree** [comment]
> When calling cublasGemmEx to calculate the gemm in FP16, we can choose the datatype of A,B,C as FP16 and the computeType as FP16 or FP32.

how to change computeType as FP16 or FP32? is there any example to show this config?

**Comment by IrishCoffee** [comment]
You can use grep -R "computeType" in the source directory to find and change all corresponding occurences.

**Comment by IrishCoffee** [comment]
The diff also comes from fusing OPs since it may change the orders.

**Comment by colourful-tree** [comment]
> You can use grep -R "computeType" in the source directory to find and change all corresponding occurences.

yeap, i got it.



> The diff also comes from fusing OPs since it may change the orders.

ok, that is more make sense.

**Comment by IrishCoffee** [comment]
Can we close the issue now?
