### ISSUE TITLE
Resume TensorFlow-BERT training based on last checkpoint

### ISSUE THREAD

**Issue by AnakTeka** [NVIDIA/DeepLearningExamples#170]
Is there anyway to resume training based on the last checkpoint that were created?

**Comment by swethmandava** [comment]
Yes, you can.

1. Pass --output_dir="path_to_checkpoint_folder" if you want to resume from the latest checkpoint in the folder and use both weights and global step. 
2. Pass --init_checkpoint="path_to_checkpoint" if you only want to resume to use weights and not the global step. For example, if you want to finetune using a pretrained checkpoint, you don't want to use the global step count of pretraining.

**Comment by AnakTeka** [comment]
> Yes, you can.
> 
> 1. Pass --output_dir="path_to_checkpoint_folder" if you want to resume from the latest checkpoint in the folder and use both weights and global step.
> 2. Pass --init_checkpoint="path_to_checkpoint" if you only want to resume to use weights and not the global step. For example, if you want to finetune using a pretrained checkpoint, you don't want to use the global step count of pretraining.

Thanks!
