### ISSUE TITLE
run_pretraining always drops remainder even during evaluation

### ISSUE THREAD

**Issue by FruVirus** [NVIDIA/DeepLearningExamples#177]
The input_fn builder for run_training has drop_remainder=True as default in the call to tf.contrib.data.map_and_batch(). This results in remainder batches being dropped even for evaluation.

**Comment by swethmandava** [comment]
Yes, thanks for pointing it out. For BERT, we only used eval set during pretraining as a sanity check since it is then evaluated on downstream tasks. Will fix it in next release

**Comment by swethmandava** [comment]
Fixed in #246

**Comment by FruVirus** [comment]
thanks @swethmandava!
