### ISSUE TITLE
Create Pretraining Dataset silently fails to use Wikipedia Data

### ISSUE THREAD

**Issue by ashaw596** [NVIDIA/DeepLearningExamples#181]
Creating a Issue for visibility since this fails silently and datasets have to be regenerated after it's fixed.

I believe currently, due to a bug in the path of the wikipedia, the single_formatted wikipedia file is empty.

Created a PR to fix in https://github.com/NVIDIA/DeepLearningExamples/pull/179.
My hdf5 data /workspace/bert/data/hdf5_lower_case_1_seq_len_512_max_pred_80_masked_lm_prob_0.15_random_seed_12345_dupe_factor_5 is now 70 GB with the wikipedia data.

**Comment by sharathts** [comment]
Thanks for pointing this out. This will be fixed in the PR https://github.com/NVIDIA/DeepLearningExamples/pull/182
