### ISSUE TITLE
transformer_fp32 core

### ISSUE THREAD

**Issue by huangjq0617** [NVIDIA/DeepLearningExamples#185]
./transformer_fp32 1 12 128 12 64
Device TITAN V
before allocate free 11.00 GB total 11.75 GB
After allocate free 10.96 GB used 0.79 GB total 11.75 GB
[FT][CALL] BertEncoderTransformer 
[FT][CALL] OpenMultiHeadAttention 
gemm_config.in is not found
loading GEMM algorithms error, using default GEMM algorithms
gemm_config.in is not found
loading GEMM algorithms error, using default GEMM algorithms!
[FT][CALL] initialize 
[FT][CALL] initialize 
[FT][CALL] forward 
[FT][CALL] forward 
transformer_fp32: xxx/DeepLearningExamples/FasterTransformer/fastertransformer/cuda/open_attention.cu:329: void fastertransformer::cuda::OpenMultiHeadAttention<OpType_>::multiHeadAttr_nofuse_kernelLauncher(cudaStream_t, cublasHandle_t, fastertransformer::cuda::OpenMultiHeadAttention<OpType_>::DataType_*, const DataType_*, fastertransformer::cuda::OpenMultiHeadAttention<OpType_>::DataType_*, const DataType_*, fastertransformer::cuda::OpenMultiHeadAttention<OpType_>::DataType_*, const DataType_*, const DataType_*, fastertransformer::cuda::OpenMultiHeadAttention<OpType_>::DataType_*, int, int, int, int, fastertransformer::cuda::OpenMultiHeadAttention<OpType_>::DataType_) [with fastertransformer::OperationType OpType_ = (fastertransformer::OperationType)0; cudaStream_t = CUstream_st*; cublasHandle_t = cublasContext*; fastertransformer::cuda::OpenMultiHeadAttention<OpType_>::DataType_ = float]: Assertion `k > 1024' failed.
Aborted (core dumped)

**Comment by IrishCoffee** [comment]
Did you compile the code with Release mode?

**Comment by IrishCoffee** [comment]
No action. Close the bug.
