### ISSUE TITLE
faster transformer:  Segmentation fault when "./bin/gemm_fp16 16 128 12 64"

### ISSUE THREAD

**Issue by Lier007** [NVIDIA/DeepLearningExamples#188]
I can compile it successfully. 
step:   ./bin/gemm_fp16 16 128 12 64, I got:

./bin/gemm_fp16 16 128 12 64
Device  
***FP16 Gemm Testing***
-----------------------------
GEMM test 0: [M: 2048, K: 768, N: 768] from_tensor * weightQ/K/V, attr * output_kernel
[FT][ERROR] CUDA runtime error: CUDA driver version is insufficient for CUDA runtime version /home/yons/Bert-master/bert/FasterTransformer/tools/gemm_test/gemm_fp16.cu:107 
[FT][ERROR] CUDA runtime error: CUDA driver version is insufficient for CUDA runtime version /home/yons/Bert-master/bert/FasterTransformer/tools/gemm_test/gemm_fp16.cu:108 
[FT][ERROR] CUDA runtime error: CUDA driver version is insufficient for CUDA runtime version /home/yons/Bert-master/bert/FasterTransformer/tools/gemm_test/gemm_fp16.cu:109 
Segmentation fault (core dumped)

cuda:10.0
driver/nvidia/version:410.104
gcc:7.4.0
python3.6
Tensorflow 1.13.1
cmake:3.14.4

**Comment by IrishCoffee** [comment]
Could you provide your compiling command and the GPU you are using?

**Comment by Lier007** [comment]
compiling command： cmake -DSM=xx -DCMAKE_BUILD_TYPE=Release -DBUILD_TF=ON -DTF_PATH=/root/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow ..
GPU： 2080Ti

“step 1: ./bin/gemm_fp16 16 128 12 64” is ok now.
But step2: python build/transformer_fp32.py 1 12 32 12 64, I got error:
Traceback (most recent call last):
  File "build/transformer_fp32.py", line 22, in <module>
    transformer_op_module = tf.load_op_library(os.path.join('./lib/libtf_fastertransformer.so'))
  File "/root/anaconda3/envs/faster2/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: ./lib/libtf_fastertransformer.so: cannot open shared object file: No such file or directory

**Comment by IrishCoffee** [comment]
compiling command： cmake -DSM=xx -DCMAKE_BUILD_TYPE=Release -DBUILD_TF=ON -DTF_PATH=/root/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow .

=> You should specify the xx with the compute capability of your own GPU, like 75 in your case.

**Comment by Lier007** [comment]
Thank you very much! It's OK Now. 
But I got a lot of prints like "Unknown compute capability (7, 5) .Defaulting to telling LLVM that we're compiling for sm_30". Does it matter

**Comment by IrishCoffee** [comment]
This is XLA warnings. It doesn't affect the performance of faster transformer.

**Comment by Lier007** [comment]
Thanks a lot. It really helped me.

**Comment by IrishCoffee** [comment]
You are welcome. So we close the bug now.
