### ISSUE TITLE
run_pretraining shuffles data twice inside the if-block starting on line 385

### ISSUE THREAD

**Issue by FruVirus** [NVIDIA/DeepLearningExamples#189]
Is there a reason the data is shuffled twice inside this if-block? If not, which is the preferred shuffling to use: 

1) d = d.shuffle(buffer_size=len(input_files)) on line 389 or
2) d = d.shuffle(buffer_size=100) on line 401

**Comment by swethmandava** [comment]
https://github.com/NVIDIA/DeepLearningExamples/blob/3233abd7da1b9f39ca8e4df723074ffc645bb3d3/TensorFlow/LanguageModeling/BERT/run_pretraining.py#L444 Shuffles input file names uniformly

https://github.com/NVIDIA/DeepLearningExamples/blob/3233abd7da1b9f39ca8e4df723074ffc645bb3d3/TensorFlow/LanguageModeling/BERT/run_pretraining.py#L456 Shuffles the data within those files using a smaller shuffle buffer
