### ISSUE TITLE
logic check for number of TFRecords when doing multi-GPU training

### ISSUE THREAD

**Issue by FruVirus** [NVIDIA/DeepLearningExamples#192]
This isn't quite an issue but more of a question.

In run_pretraining.py, the number of TFRecord files must be >= hvd.size(). In run_classifier.py, a single data file is given and then TFRecords are generated from this single file so that the number of TFRecord files >= hvd.size().

In both cases, the data is then sharded in the input_fn_builder() at a later point.

I understand the data sharding process but I don't quite get why the number of TFRecords must initially be >= hvd.size(). Isn't the sharding process enough?

Any clarification would be appreciated. Thanks!

**Comment by FruVirus** [comment]
my guess is that this logic check is to ensure perfect data parallelism when doing multi-GPU training. If # of TFRecords < # of GPUs, then you can potentially have random shuffles that have overlapping data.

**Comment by swethmandava** [comment]
run_pretraining.py splits the tfrecords between each gpu and iterates over them repeatedly. In the case when #TFRecords < #GPUs, some gpus get none and result in horovod shutdown.
