### ISSUE TITLE
cross check fail when initializer_range = 1.0

### ISSUE THREAD

**Issue by duduscript** [NVIDIA/DeepLearningExamples#196]
```sh
➜  build git:(master) ✗ python transformer_fp32.py 1 12 32 12 64
....
185 layer_11/attention/output/LayerNorm/gamma:0 (768,)
186 layer_11/intermediate/dense/kernel:0 (768, 3072)
187 layer_11/intermediate/dense/bias:0 (3072,)
188 layer_11/output/dense/kernel:0 (3072, 768)
189 layer_11/output/dense/bias:0 (768,)
190 layer_11/output/LayerNorm/beta:0 (768,)
191 layer_11/output/LayerNorm/gamma:0 (768,)
#################################
cross_check False
max diff 3.1314976
min diff 3.8146973e-06
2019-09-09 11:10:57.349108: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcupti.so.10.0 locally
original costs 7.619796 ms
optimized costs 3.415072 ms
```

```py
39c39
< initializer_range = 1.0
---
> initializer_range = 0.02
184c184
<                       initializer_range=1.0,
---
>                       initializer_range=0.02,
342c342
< #config.graph_options.optimizer_options.global_jit_level = tf.OptimizerOptions.ON_1
---
> config.graph_options.optimizer_options.global_jit_level = tf.OptimizerOptions.ON_1
```

**Comment by IrishCoffee** [comment]
We only tested the default BERT settings, like 0.02. 

You can test the code with real data, not by random numbers. If the result is still wrong, you can dump the weight files and let us know.

**Comment by duduscript** [comment]
Hi @IrishCoffee , I am sorry I can not provide the weights file.
I view the weights in my model and the range is [-5, 5],  and there is a great max diff between two results. I find FastTransformer is not suit the situation that parameters range is bigger than 0.2 both in my experiments and the tf test code in this repo.
The cross check error you can repeat when change the initializer_range to 1.0 or some value bigger than 0.2 as the diff I provide. And I really hope that you can fix this problem.

**Comment by IrishCoffee** [comment]
We use many fast math calculations with low precision and it works for the default settings.

Maybe for range [-5, 5], the faster transformer cannot meet the precision requirement. 

I use 1.0 and tested with 1 layer, the diff is 1e-5, larger than 12 layers's diff with 0.02.

When I increase the layers from 1 to 2, the diff is greater than 1.0f.

**Comment by duduscript** [comment]
Could you provide more detail about fast math calculations  with low precision in fast transformer implementation?

**Comment by IrishCoffee** [comment]
You can review the .cu source code.
