### ISSUE TITLE
"loading GEMM algorithms error", when running "python profile_bert_inference.py xxx"

### ISSUE THREAD

**Issue by Lier007** [NVIDIA/DeepLearningExamples#197]
Command: python profile_bert_inference.py xxx
Print: "loading GEMM algorithms error, using default GEMM algorithms
gemm_config.in is not found"
When debugging, the print occurs here: 
profile_util.py, line 81
res.append(sess.run(fetches, options=profiler.run_options, run_metadata=profiler.run_metadata))

**Comment by IrishCoffee** [comment]
Please follow README step 1 to generate gemm_config.in for your case.

**Comment by Lier007** [comment]
I have generated gemm_config.in in the folder "build", and copied this file to the current path “sample/tensorflow_bert”. 
Is the path wrong?

**Comment by IrishCoffee** [comment]
It should be build path.

**Comment by Lier007** [comment]
thank you so much. I't OK now. The problem occured because of my wrong usage of remote debugging in docker with pycharm.

**Comment by IrishCoffee** [comment]
You are welcome(#^.^#)
