### ISSUE TITLE
No module named 'fused_dropout_add_cuda' in transformers translation pytorch

### ISSUE THREAD

**Issue by flip-arunkp** [NVIDIA/DeepLearningExamples#209]
Hi,

I am trying to train the transformers translation model as per the instructions. I am using docker environment. But when I train I get the error "ModuleNotFoundError: No module named 'fused_dropout_add_cuda'". I see the cpp cu files in "fairseq/models/fused_dropout_add" folder. How do i compile them and be accessed from pytorch.

Thanks

**Comment by jbaczek** [comment]
Hi,
Are you using provided docker container? 'fused_dropout_add_cuda' is installed installed inside container together with fairseq.

**Comment by nvcforster** [comment]
It shouldn't be required in our container, but a build can be performed using `python3 setup.py build develop`. Please let us know if this solves the problem (and if it occurred using our Docker image).

**Comment by ischlag** [comment]
I have the same problem. I follow the instructions in https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Translation/Transformer

That Dockerfile starts from nvcr.io/nvidia/pytorch:19.06-py3

`python3 setup.py build develop`
This won't work because setup.py doesn't contain the builds for fused_dropout_add_cuda anymore. But even if you fix this by loading a previous setup.py, you'll get an error with respect to FusedAdam. 

After I have built and run as per the instructions ...
`docker build . -t your.repository:transformer`
`nvidia-docker run -it --rm --ipc=host your.repository:transformer bash`
... there is no `fused_dropout_add_cuda` module. However, fairseq is installed. 

Does anyone know how I actually train the translation model? Apparently the instructions are deprecated. 

```
root@a253e54085e6:/workspace/translation# pip list
Package                       Version         Location              
----------------------------- --------------- ----------------------
absl-py                       0.8.0           
alabaster                     0.7.12          
apex                          0.1             
appdirs                       1.4.3           
ascii-graph                   1.5.1           
asn1crypto                    0.24.0          
atomicwrites                  1.3.0           
attrs                         19.2.0          
audioread                     2.1.8           
Babel                         2.7.0           
backcall                      0.1.0           
beautifulsoup4                4.8.0           
bleach                        3.1.0           
boto3                         1.9.240         
botocore                      1.12.240        
certifi                       2019.9.11       
cffi                          1.12.3          
chardet                       3.0.4           
Click                         7.0             
codecov                       2.0.15          
conda                         4.7.12          
conda-build                   3.18.9          
conda-package-handling        1.6.0           
coverage                      4.5.4           
cryptography                  2.7             
cxxfilt                       0.2.0           
cycler                        0.10.0          
cymem                         2.0.2           
Cython                        0.28.4          
cytoolz                       0.9.0.1         
DataProperty                  0.43.1          
decorator                     4.4.0           
defusedxml                    0.6.0           
dill                          0.2.9           
docutils                      0.15.2          
entrypoints                   0.3             
fairseq                       0.5.0           /workspace/translation
filelock                      3.0.12          
flake8                        3.7.8           
Flask                         1.1.1           
future                        0.17.1          
glob2                         0.7             
grpcio                        1.24.0          
h5py                          2.10.0          
html2text                     2019.9.26       
hypothesis                    4.38.1          
idna                          2.8             
imageio                       2.5.0           
imagesize                     1.1.0           
importlib-metadata            0.23            
inflect                       2.1.0           
ipdb                          0.12.2          
ipykernel                     5.1.2           
ipython                       7.8.0           
ipython-genutils              0.2.0           
itsdangerous                  1.1.0           
jedi                          0.15.1          
Jinja2                        2.10.1          
jmespath                      0.9.4           
joblib                        0.14.0          
json5                         0.8.5           
jsonschema                    3.0.2           
jupyter-client                5.3.3           
jupyter-core                  4.5.0           
jupyter-tensorboard           0.1.10          
jupyterlab                    1.0.4           
jupyterlab-server             1.0.6           
jupytext                      1.2.4           
kiwisolver                    1.1.0           
libarchive-c                  2.8             
librosa                       0.6.3           
lief                          0.9.0           
llvmlite                      0.28.0          
lmdb                          0.97            
Mako                          1.1.0           
Markdown                      3.1.1           
MarkupSafe                    1.1.1           
maskrcnn-benchmark            0.1             
matplotlib                    3.1.1           
mbstrdecoder                  0.8.1           
mccabe                        0.6.1           
mistune                       0.8.4           
mlperf-compliance             0.0.10          
mock                          3.0.5           
more-itertools                7.2.0           
msgfy                         0.0.7           
msgpack                       0.6.1           
msgpack-numpy                 0.4.3.2         
murmurhash                    1.0.2           
nbconvert                     5.6.0           
nbformat                      4.4.0           
networkx                      2.0             
nltk                          3.4.5           
notebook                      6.0.1           
numba                         0.43.1          
numpy                         1.17.2          
nvidia-dali                   0.14.0          
onnx                          1.5.0           
opencv-python                 3.4.1.15        
packaging                     19.2            
pandas                        0.24.2          
pandocfilters                 1.4.2           
parso                         0.5.1           
pathvalidate                  0.29.0          
pexpect                       4.7.0           
pickleshare                   0.7.5           
Pillow-SIMD                   5.3.0.post1     
pip                           19.3.1          
pkginfo                       1.5.0.1         
plac                          0.9.6           
pluggy                        0.13.0          
preshed                       2.0.1           
progressbar                   2.5             
prometheus-client             0.7.1           
prompt-toolkit                2.0.9           
protobuf                      3.9.2           
psutil                        5.6.3           
ptyprocess                    0.6.0           
py                            1.8.0           
pybind11                      2.4.2           
pycocotools                   2.0+nv0.3.1     
pycodestyle                   2.5.0           
pycosat                       0.6.3           
pycparser                     2.19            
pycuda                        2019.1.2        
pydot                         1.4.1           
pyflakes                      2.1.1           
Pygments                      2.4.2           
pyOpenSSL                     19.0.0          
pyparsing                     2.4.2           
pyrsistent                    0.15.4          
PySocks                       1.7.1           
pytablewriter                 0.46.1          
pytest                        5.2.0           
pytest-cov                    2.7.1           
pytest-pythonpath             0.7.3           
python-dateutil               2.8.0           
python-nvd3                   0.15.0          
python-slugify                3.0.4           
pytools                       2019.1.1        
pytz                          2019.2          
PyWavelets                    1.0.3           
PyYAML                        5.1.2           
pyzmq                         18.1.0          
regex                         2018.1.10       
requests                      2.22.0          
resampy                       0.2.2           
revtok                        0.0.3           
ruamel-yaml                   0.15.46         
s3transfer                    0.2.1           
sacrebleu                     1.2.10          
sacremoses                    0.0.19          
scikit-image                  0.15.0          
scikit-learn                  0.21.3          
scipy                         1.3.1           
Send2Trash                    1.5.0           
sentencepiece                 0.1.83          
setuptools                    41.2.0          
six                           1.12.0          
snowballstemmer               1.9.1           
SoundFile                     0.10.2          
soupsieve                     1.9.3           
sox                           1.3.7           
spacy                         2.0.16          
Sphinx                        2.2.0           
sphinx-rtd-theme              0.4.3           
sphinxcontrib-applehelp       1.0.1           
sphinxcontrib-devhelp         1.0.1           
sphinxcontrib-htmlhelp        1.0.2           
sphinxcontrib-jsmath          1.0.1           
sphinxcontrib-qthelp          1.0.2           
sphinxcontrib-serializinghtml 1.1.3           
SSD                           0.1             
subword-nmt                   0.3.3           
tabledata                     0.9.1           
tabulate                      0.8.5           
tensorboard                   2.0.0           
tensorrt                      6.0.1.5         
terminado                     0.8.2           
testpath                      0.4.2           
text-unidecode                1.3             
thinc                         6.12.1          
toml                          0.10.0          
toolz                         0.10.0          
torch                         1.3.0a0+24ae9b5 
torchtext                     0.4.0           
torchvision                   0.5.0a0         
tornado                       6.0.3           
tqdm                          4.31.1          
traitlets                     4.3.2           
typepy                        0.6.0           
typing                        3.7.4.1         
typing-extensions             3.7.4           
ujson                         1.35            
Unidecode                     1.1.1           
urllib3                       1.24.2          
wcwidth                       0.1.7           
webencodings                  0.5.1           
Werkzeug                      0.16.0          
wheel                         0.33.6          
wrapt                         1.10.11         
yacs                          0.1.6           
zipp                          0.6.0          
```

**Comment by jbaczek** [comment]
Thank you for pointing that out! There was indeed a change in that part of code. A quick solution is to remove files and directories: `fused_dropout_add`, `fused_dropout_add.py`, `fused_relu_dropout`, `fused_relu_dropout.py`. As well as commenting out installing newest APEX in Dockerfile. We plan to update this model in couple days.

**Comment by flytoni** [comment]
> Thank you for pointing that out! There was indeed a change in that part of code. A quick solution is to remove files and directories: `fairseq/models/fused_dropout_add`, `fairseq/models/fused_dropout_add.py`, `fairseq/models/fused_relu_dropout`, `fairseq/models/fused_relu_dropout.py`.You need also to comment out installing newest APEX in the Dockerfile. We plan to update this model in couple days.

Hi @nvpstr, is this issue fixed? I'm still running into the same issue and I don't see any update to https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Translation/Transformer for 8 months.

**Comment by jbaczek** [comment]
We are currently preparing a new release which should be pushed in next few days. This issue is absent in the next version.

**Comment by gheniablaamd** [comment]
Hi,
I am seeing the same problem. If the code was updated?  If not, is there any work around?

====
python3.6 -m torch.distributed.launch --nproc_per_node 8 train.py /data/wmt14_en_de_joined_dict --arch transformer_wmt_en_de_big_t2t --share-all-embeddings --optimizer adam --adam-betas '(0.9, 0.997)' --adam-eps "1e-9" --clip-norm 0.0 --lr-scheduler inverse_sqrt --warmup-init-lr 0.0 --warmup-updates 4000 --lr 0.0006 --min-lr 0.0 --dropout 0.1 --weight-decay 0.0 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 5120 --seed 1 --target-bleu 28.3 --ignore-case --fp16 --save-dir /workspace/checkpoints --distributed-init-method env://
Traceback (most recent call last):
  File "train.py", line 36, in <module>
    from fairseq import data, distributed_utils, options, progress_bar, tasks, utils, bleu, tokenizer
  File "/workspace/DeepLearningExamples/PyTorch/Translation/Transformer/fairseq/options.py", line 28, in <module>
    from fairseq.models import ARCH_MODEL_REGISTRY, ARCH_CONFIG_REGISTRY
  File "/workspace/DeepLearningExamples/PyTorch/Translation/Transformer/fairseq/models/__init__.py", line 63, in <module>
    importlib.import_module('fairseq.models.' + module)
  File "/opt/conda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/workspace/DeepLearningExamples/PyTorch/Translation/Transformer/fairseq/models/fused_dropout_add.py", line 16, in <module>
    import fused_dropout_add_cuda
ModuleNotFoundError: No module named 'fused_dropout_add_cuda'
Traceback (most recent call last):
  File "train.py", line 36, in <module>
    from fairseq import data, distributed_utils, options, progress_bar, tasks, utils, bleu, tokenizer
  File "/workspace/DeepLearningExamples/PyTorch/Translation/Transformer/fairseq/options.py", line 28, in <module>
    from fairseq.models import ARCH_MODEL_REGISTRY, ARCH_CONFIG_REGISTRY
  File "/workspace/DeepLearningExamples/PyTorch/Translation/Transformer/fairseq/models/__init__.py", line 63, in <module>
    importlib.import_module('fairseq.models.' + module)
  File "/opt/conda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/workspace/DeepLearningExamples/PyTorch/Translation/Transformer/fairseq/models/fused_dropout_add.py", line 16, in <module>
    import fused_dropout_add_cuda
ModuleNotFoundError: No module named 'fused_dropout_add_cuda'
Traceback (most recent call last):
  File "train.py", line 36, in <module>
    from fairseq import data, distributed_utils, options, progress_bar, tasks, utils, bleu, tokenizer
  File "/workspace/DeepLearningExamples/PyTorch/Translation/Transformer/fairseq/options.py", line 28, in <module>
    from fairseq.models import ARCH_MODEL_REGISTRY, ARCH_CONFIG_REGISTRY
  File "/workspace/DeepLearningExamples/PyTorch/Translation/Transformer/fairseq/models/__init__.py", line 63, in <module>
    importlib.import_module('fairseq.models.' + module)
  File "/opt/conda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/workspace/DeepLearningExamples/PyTorch/Translation/Transformer/fairseq/models/fused_dropout_add.py", line 16, in <module>
    import fused_dropout_add_cuda
ModuleNotFoundError: No module named 'fused_dropout_add_cuda'
Traceback (most recent call last):
  File "train.py", line 36, in <module>
    from fairseq import data, distributed_utils, options, progress_bar, tasks, utils, bleu, tokenizer
  File "/workspace/DeepLearningExamples/PyTorch/Translation/Transformer/fairseq/options.py", line 28, in <module>
    from fairseq.models import ARCH_MODEL_REGISTRY, ARCH_CONFIG_REGISTRY
  File "/workspace/DeepLearningExamples/PyTorch/Translation/Transformer/fairseq/models/__init__.py", line 63, in <module>
    importlib.import_module('fairseq.models.' + module)
  File "/opt/conda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/workspace/DeepLearningExamples/PyTorch/Translation/Transformer/fairseq/models/fused_dropout_add.py", line 16, in <module>
    import fused_dropout_add_cuda
ModuleNotFoundError: No module named 'fused_dropout_add_cuda'
Traceback (most recent call last):
  File "train.py", line 36, in <module>
    from fairseq import data, distributed_utils, options, progress_bar, tasks, utils, bleu, tokenizer
  File "/workspace/DeepLearningExamples/PyTorch/Translation/Transformer/fairseq/options.py", line 28, in <module>
    from fairseq.models import ARCH_MODEL_REGISTRY, ARCH_CONFIG_REGISTRY
  File "/workspace/DeepLearningExamples/PyTorch/Translation/Transformer/fairseq/models/__init__.py", line 63, in <module>
    importlib.import_module('fairseq.models.' + module)
  File "/opt/conda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/workspace/DeepLearningExamples/PyTorch/Translation/Transformer/fairseq/models/fused_dropout_add.py", line 16, in <module>
    import fused_dropout_add_cuda
ModuleNotFoundError: No module named 'fused_dropout_add_cuda'

====

**Comment by nv-kkudrynski** [comment]
Already updated.
