### ISSUE TITLE
Nothing happens on bash scripts/train_tacotron2.sh

### ISSUE THREAD

**Issue by mrgloom** [NVIDIA/DeepLearningExamples#21]
Nothing happens on bash scripts/train_tacotron2.sh, output folder is also empty.

I'm not using docker, but installed requirements.txt under virtualenv.

**Comment by GrzegorzKarchNV** [comment]
hi, is there any output at all? do you have the dataset downloaded into ./LJSpeech-1.1 folder?

**Comment by mrgloom** [comment]
If I remember correctly running `python -m multiproc train.py -m Tacotron2 -o ./output/ -lr 1e-3 --epochs 2001 -bs 80 --weight-decay 1e-6 --grad-clip-thresh 1.0 --cudnn-benchmark=True --log-file ./output/nvlog.json --anneal-steps 500 1000 1500 --anneal-factor 0.1 --fp16-run` was not producing output, but running without `-m multiproc` was producing an error, so `-m multiproc` just hide errors, producing no output.

**Comment by nvpstr** [comment]
Could you try using docker? There are too many things that may be different in your configuration.

**Comment by nvpstr** [comment]
Our scripts work in the containers prepared by NVIDIA in which all DL libraries and frameworks are tested. 
We cannot guarantee they will work in any library/framework configuration.

**Comment by nvpstr** [comment]
As there is no answer for more than a month I assume that the problem was solved, therefore I am closing this issue.
