### ISSUE TITLE
Is the toronto corpus still availiable?

### ISSUE THREAD

**Issue by forjiuzhou** [NVIDIA/DeepLearningExamples#211]
There is code python3 /workspace/bookcorpus/download_files.py in BooksDownloader. But I can't find this script.

**Comment by nvcforster** [comment]
Hi, it is available still. Does it work if you run `python3 /workspace/bert/data/bertPrep.py --action download --dataset bookscorpus`?

The Dockerfile should be cloning the bookcorpus scripts into /workspace/bookcorpus when the image is built. I tested a build of a fresh clone of our DL examples just now to verify it is building correctly. If files are missing, please verify there are not errors during the Docker build.
