### ISSUE TITLE
Why is PyTorch/Distributed deleted?

### ISSUE THREAD

**Issue by seungwonpark** [NVIDIA/DeepLearningExamples#23]
Hi, I was searching for tutorials/examples of distributed learning with PyTorch. I found contents of `PyTorch/Distributed` very useful, but it became unavailable since commit hash 7a8544e0a24df6c0fec06c044e5901de63b50ccd. Why is it deleted?

**Comment by nvpstr** [comment]
The aim of this repo is to provide mixed-precision multi-gpu domain-specific examples, which are tested with recent DL Framework releases. We removed the code that is no longer supported, or that is placed somewhere else. 

However we are planning to prepare a jupyter notebooks with step by step instructions how to introduce mixed precision and multi-gpu for training and inference. We will take your suggestions into account.
