### ISSUE TITLE
TensorFlow BERT optimizer apply_gradients(): manual_fp16 is never used

### ISSUE THREAD

**Issue by LiweiPeng** [NVIDIA/DeepLearningExamples#230]
In the TensorFlow BERT optimizer apply_gradients() code, the manual_fp16 parameter is never used, see code below. Is this expected or a bug?

https://github.com/NVIDIA/DeepLearningExamples/blob/master/TensorFlow/LanguageModeling/BERT/optimization.py#L201.

https://github.com/NVIDIA/DeepLearningExamples/blob/master/TensorFlow/LanguageModeling/BERT/optimization.py#L171

**Comment by thorjohnsen** [comment]
Hi Liwei,

That looks like a bug, thanks for spotting it! I think it would cause master parameters to become fp16 tensors when --manual_fp16 is used, which would hurt convergence. We will verify and fix it.

Thanks,
Thor

**Comment by LiweiPeng** [comment]
Thanks @thorjohnsen  for the followup.

**Comment by LiweiPeng** [comment]
@thorjohnsen I have another question related to BERT mixed precision. The BERT automatic mixed precision (AMP) implementation seems to require the user to use Nvidia tensorflow container. Do you have plan to add logic to use tensorflow native's AMP in tf version >= 1.14?

**Comment by swethmandava** [comment]
AMP is officially supported in TF 1.14: https://www.tensorflow.org/api_docs/python/tf/train/experimental/enable_mixed_precision_graph_rewrite
We still recommend our containers for best performance

**Comment by LiweiPeng** [comment]
Thanks @swethmandava for the details. Where can I get some perf comparison between TF 1.14's AMP and Nvidia's container AMP?

**Comment by David-Levinthal** [comment]
manual_fp is the default for run_pretraining_adam.sh, is this also effected?
