### ISSUE TITLE
bert image build fail

### ISSUE THREAD

**Issue by stevewyl** [NVIDIA/DeepLearningExamples#231]
Quite strange.
When I try to run the command `bash scripts/docker/build.sh`
![image](https://user-images.githubusercontent.com/12755003/65583796-6e58d900-dfb2-11e9-9c5e-8e51b8779489.png)
It tells me that I need a new image called tensorrtserver_client. I cannot find it in NGC  container lists. So I search this new image on Google and found it in [NVIDIA TensorRT Inference Server Document](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/quickstart.html#building-with-docker). And following build the tensorrtserver_client image by command `docker build --pull -t tensorrtserver .`. But still got the following error
![image](https://user-images.githubusercontent.com/12755003/65583965-bd067300-dfb2-11e9-9569-e70b12c440fe.png)
Related NGC images have been installed
![image](https://user-images.githubusercontent.com/12755003/65584649-cb08c380-dfb3-11e9-8fe3-6a66fea54947.png)

Has anyone encountered this similar error?

**Comment by swethmandava** [comment]
tensorrtserver_client and tensorrtserver are different images. 

tensorrtserver is built here:
https://github.com/NVIDIA/DeepLearningExamples/blob/870969d93379b84f00308e0910bebcbcff88ada4/TensorFlow/LanguageModeling/BERT/scripts/docker/build.sh#L3

tensorrtserver_client is built here:
https://github.com/NVIDIA/DeepLearningExamples/blob/870969d93379b84f00308e0910bebcbcff88ada4/TensorFlow/LanguageModeling/BERT/scripts/docker/build.sh#L8

Can you try building the client and tell us what error you get? Thanks!

**Comment by stevewyl** [comment]
@swethmandava I found it this command `git submodule update --init --recursive` got the error. I should run this command at `DeepLearingExamples` not `DeepLearningExamples/TensorFlow/LanguageModeling/BERT`, you may change the [Quick Start 
Guide](https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/LanguageModeling/BERT#quick-start-guide) of README.
Now everything goes well : P Thanks for your reply!
