### ISSUE TITLE
Mask RCNN container has some issue with Apex

### ISSUE THREAD

**Issue by codeyogi911** [NVIDIA/DeepLearningExamples#232]
I build the image using this file:
[Dockerfile](https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/Segmentation/MaskRCNN/pytorch/Dockerfile)
But after i run training using the command:
`bash scripts/train.sh`
I get the following error:
`Traceback (most recent call last):
  File "tools/train_net.py", line 265, in <module>
    main()
  File "tools/train_net.py", line 257, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 107, in train
    model, optimizer = amp.initialize(model, optimizer, opt_level=amp_opt_level)
AttributeError: module 'apex.amp' has no attribute 'initialize'`
Please help!

**Comment by sharathts** [comment]
This should be fixed in the PR https://github.com/NVIDIA/DeepLearningExamples/pull/233. Thanks for bringing it up.
