### ISSUE TITLE
Feedback of faster transformer

### ISSUE THREAD

**Issue by stanislashzc** [NVIDIA/DeepLearningExamples#235]
Hi, NVIDIA's faster transformer is good to use, but I also get the problem is that it's really hard to reference NV's faster transformer work in my project, since it's under DeepLearningExamples second folder. I really want the direct reference to faster transformer, just the same way as TensorRT or nvidia-docker.

**Comment by nvpstr** [comment]
There is no separate repo, and there is no plan for that.
