### ISSUE TITLE
NaN loss while training LJSpeech-1.1 with Tacotron2

### ISSUE THREAD

**Issue by plkmo** [NVIDIA/DeepLearningExamples#236]
Steps to reproduce:
run prepare_dataset.sh
run train tacotron2.sh

I am not using any docker containers to run, just on my local PyTorch environment. 
Have disabled apex.parallel by commenting out line 42 in train.py. Also commented out log_hardware() in line 326 of train.py
Specs: PyTorch=1.2.0, CUDA=10.0, Windows 10 Pro
*** Tried with Ubuntu 18.04 with the same error
Any ideas? Thanks

```
Traceback (most recent call last):
  File "train.py", line 514, in <module>
    main()
  File "train.py", line 434, in main
    raise Exception("loss is NaN")
Exception: loss is NaN
```

**Comment by GrzegorzKarchNV** [comment]
as a quick fix, try replacing `byte()` with `bool()`:
https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/SpeechSynthesis/Tacotron2/common/utils.py#L37

**Comment by plkmo** [comment]
> as a quick fix, try replacing `byte()` with `bool()`:
> https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/SpeechSynthesis/Tacotron2/common/utils.py#L37

This seems to fix the problem. Thank you.
