### ISSUE TITLE
TF run_pretraining_adam.sh not consistent with readme nor data_download

### ISSUE THREAD

**Issue by David-Levinthal** [NVIDIA/DeepLearningExamples#238]
very minor issue
the readme for the TF branch suggests the invocation of pretraining with Adam should be
bash scripts/run_pretraining_adam.sh <train_batch_size_per_gpu> <eval_batch_size> <learning_rate_per_gpu> <precision> <use_xla> <num_gpus> <warmup_steps> <train_steps> <save_checkpoint_steps> <create_logfile>

but the 10th argument is not create_logfile but rather the model size
so the readme needs a touch up
further the data directory name is not consistent with the data_download script

echo "Container nvidia build = " $NVIDIA_BUILD_ID

train_batch_size=${1:-14}
eval_batch_size=${2:-8}
learning_rate=${3:-"1e-4"}
precision=${4:-"manual_fp16"}
use_xla=${5:-"true"}
num_gpus=${6:-8}
warmup_steps=${7:-"10000"}
train_steps=${8:-1144000}
save_checkpoints_steps=${9:-5000}
bert_model=${10:-"large"}
num_accumulation_steps=${11:-1}
seq_len=${12:-512}
max_pred_per_seq=${13:-80}

DATA_DIR=data/tfrecord/lower_case_1_seq_len_${seq_len}_max_pred_${max_pred_per_seq}_masked_lm_prob_0.15_random_seed_12345_dupe_factor_5_shard_1472_test_split_10/books_wiki_en_corpus

which should read
DATA_DIR=data/tfrecord/lower_case_1_seq_len_${seq_len}_max_pred_${max_pred_per_seq}_masked_lm_prob_0.15_random_seed_12345_dupe_factor_5_shard_256_test_split_20/books_wiki_en_corpus

like I said..very minor

**Comment by David-Levinthal** [comment]
sorry..I left out that this refers to the Tensorflow encoding of Bert

**Comment by swethmandava** [comment]
Thanks, will fix it.

**Comment by swethmandava** [comment]
Fixed in #246

**Comment by David-Levinthal** [comment]
the Readme also states the performance listed in the tables as
Performance (in sentences per second) is the steady state throughput.
it is actually sequences per second...the variable is called sent_per_sec
but if one looks at how it is calculated it should be sequences per second
the data has 128 or 512 words/sequence and the number of sentences is not
necessarily fixed
:-)
