### ISSUE TITLE
Inconsistent posted benchmarks for BERT

### ISSUE THREAD

**Issue by lapolonio** [NVIDIA/DeepLearningExamples#240]
The repo: https://github.com/NVIDIA/DeepLearningExamples/blob/master/TensorFlow/LanguageModeling/BERT/README.md#inference-performance-nvidia-tesla-t4-1x-t4-16g
![image](https://user-images.githubusercontent.com/1810412/65989472-cc286d80-e457-11e9-8086-450a897adcfa.png)

is inconsistent with NVIDIA Tesla Deep Learning Product Performance:
https://developer.nvidia.com/deep-learning-performance-training-inference
![image](https://user-images.githubusercontent.com/1810412/65989421-abf8ae80-e457-11e9-88ed-de0eee96a0ba.png)

Is this repo not updated with TensorRT 6.0?

**Comment by swethmandava** [comment]
Results reported under this repo are using native TensorFlow framework. The developer blog you linked reports inference performance numbers using TensorRT.

**Comment by lapolonio** [comment]
that's confusing since the [bert-base](https://ngc.nvidia.com/catalog/models?orderBy=modifiedDESC&query=BERT&quickFilter=&filters=) link on the developer nvidia site leads to here: https://ngc.nvidia.com/catalog/model-scripts/nvidia:bert_for_tensorflow/quickStartGuide which points to this repo.
