### ISSUE TITLE
HTTP Error 403: Forbidden when downloading BERT data

### ISSUE THREAD

**Issue by tylerjthomas9** [NVIDIA/DeepLearningExamples#247]
I built the Tensorflow container, and it runs successfully. However, I am running into 403 error when attempting to download all the pretraining data for BERT. I am running *bash scripts/data_download.sh* to download all the pretraining data. Some of the data, such as the BERT pre trained weights and Wikipedia corpus, comes through without any issues. We have checked the firewall on our end, and do not see anything that would cause a HTTP error.

![smashwords403](https://user-images.githubusercontent.com/36181311/66402036-c37ced80-e9a9-11e9-9fe7-44219b145e1d.PNG)

**Comment by swethmandava** [comment]
#37 #90 

It is a BooksCorpus server/Maintainance issue

**Comment by tylerjthomas9** [comment]
Both of those pages reference a HTTP Error 503, which is a different error than the HTTP Error 403. Both of those appear to be failing because the server is overloaded, which is not the case with the HTTP Error 403. HTTP Error 403 is caused when you are forbidden from accessing the data on a page.

**Comment by tylerjthomas9** [comment]
Closing issue, because resolution was found. "you can just ignore the bookscorpus files that are missing. They dont exist anymore on the web. This is a known issue on the original BERT repo."
