### ISSUE TITLE
How can I download BookCorpus without container?

### ISSUE THREAD

**Issue by yifding** [NVIDIA/DeepLearningExamples#250]
Since I am using the remote LINUX machine without root and container. I am trying to download the BookCorpus data and find it doesn't work. How can i find the "/workspace/bookcorpus/download_files.py" or where should I find the data?

    def download(self):
        bookscorpus_download_command = 'python3 /workspace/bookcorpus/download_files.py --list /workspace/bookcorpus/url_list.jsonl --out'
        bookscorpus_download_command += ' ' + self.save_path + '/bookscorpus'
        bookscorpus_download_command += ' --trash-bad-count'
        bookscorpus_download_process = subprocess.run(bookscorpus_download_command, shell=True, check=True)

**Comment by swethmandava** [comment]
#37 
/workspace/bookscorpus is cloned from this repository https://github.com/soskek/bookcorpus

**Comment by yifding** [comment]
Thank you so much
