### ISSUE TITLE
PyTorch Detection/SSD "CUDA driver version is insufficient for CUDA runtime version"

### ISSUE THREAD

**Issue by Ethereal-Coder** [NVIDIA/DeepLearningExamples#251]
PyTorch Detection/SSD throw "CUDA driver version is insufficient for CUDA runtime version" when "./examples/SSD300_FP16_4GPU.sh . /coco --save"

`Traceback (most recent call last):
  File "./main.py", line 14, in <module>
    from src.data import get_train_loader, get_val_dataset, get_val_dataloader, get_coco_ground_truth
  File "/workspace/src/data.py", line 10, in <module>
    from src.coco_pipeline import COCOPipeline, DALICOCOIterator
  File "/workspace/src/coco_pipeline.py", line 25, in <module>
    from nvidia.dali.pipeline import Pipeline
  File "/opt/conda/lib/python3.6/site-packages/nvidia/dali/__init__.py", line 17, in <module>
    from . import ops
  File "/opt/conda/lib/python3.6/site-packages/nvidia/dali/ops.py", line 19, in <module>
    from nvidia.dali import backend as b
  File "/opt/conda/lib/python3.6/site-packages/nvidia/dali/backend.py", line 28, in <module>
    Init(OpSpec("CPUAllocator"), OpSpec("PinnedCPUAllocator"), OpSpec("GPUAllocator"))
RuntimeError: CUDA runtime API error cudaErrorInsufficientDriver (35):
CUDA driver version is insufficient for CUDA runtime version
`

**Comment by szmigacz** [comment]
Dockerfile in PyTorch SSD pulls `pytorch:19.08-py3`. According to the [Frameworks supports matrix](https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html) for 19.08 release: 
```Release 19.08 is based on CUDA 10.1.243, which requires NVIDIA driver release 418.87.
However, if you are running on Tesla (Tesla V100, Tesla P4, Tesla P40, or Tesla P100), you may use NVIDIA driver release 384.111+ or 410.
The CUDA driver's compatibility package only supports particular drivers.```

Your error message suggests that your driver is too old, you can check the version by calling the `nvidia-smi` command.
