### ISSUE TITLE
[FasterTransformer]In Tensorflow demos, faster transformer is slower than original transformer.

### ISSUE THREAD

**Issue by nilbibi** [NVIDIA/DeepLearningExamples#254]
I have test the code on Titan RTX.

In C++ demos, I get the correct resut.
`[batch_size 1 seq_len 32 12 transformer layers] costs 1.45 ms`
But, in tensorflow demos, I get the below result.
```
# python transformer_fp16.py 1 12 32 12 64
original costs 4.61138 ms
optimized costs 51.12479999999999 ms
```
what's wrong in the tensorflow demos?

**Comment by IrishCoffee** [comment]
Could you please provide the compiling commands, GPU and CUDA version you are using?
Did you generate the gemm_config.in?

**Comment by nilbibi** [comment]
I run in docker "nvcr.io/nvidia/tensorflow:19.08-py3"(CUDA: 10.1; tensorflow: 1.14.0;) and GPU is Titan RTX(compute capability=75).
And I generate the gemm_config.in again, in tensorflow demos, the optimized model is still slower than the original one.

**Comment by nilbibi** [comment]
I found that when batch_size is 32, optimized model is faster than original one, but when batch_size is 1, optimized model‘s latency is almost same as orignal one. Thanks.

**Comment by IrishCoffee** [comment]
@nilbibi When batch size equals to 1, the tensorflow OP brings big overhead. The transformer layer execution time actually is much shorter than the time that python reports.

**Comment by nilbibi** [comment]
![image](https://user-images.githubusercontent.com/42854098/66806074-301f5b80-ef59-11e9-9ae9-ce2231faa313.png)
This picture is the profile result, and  I have several problems.
1. why does the tensorflow op bring so big overhead, what does the program do at this stage?
2. Is the tensorflow native op get smaller overhead than custom one, and  what about ops in tf.contrib?
