### ISSUE TITLE
rank vs local_rank when creating TFRecords

### ISSUE THREAD

**Issue by FruVirus** [NVIDIA/DeepLearningExamples#258]
In run_classifier, hvd.rank() is used to split the train examples among the GPUs.

In run_squad, hvd.local_rank() is used instead.

Which method is the correct one to use in the general case?

In addition, shouldn't hvd.all_reduce() be used in both cases to ensure that the GPUs are synchronized after the tfrecord writing process?

**Comment by swethmandava** [comment]
hvd.rank() would be correct in general. hvd.allreduce is redundant and not necessary.

**Comment by FruVirus** [comment]
thank you!
