### ISSUE TITLE
Book Corpus download link

### ISSUE THREAD

**Issue by GeondoPark** [NVIDIA/DeepLearningExamples#262]
Will you no longer provide a list of Book Corpus download links?

**Comment by swethmandava** [comment]
BookCorpus download is still supported

https://github.com/NVIDIA/DeepLearningExamples/blob/f2fe0904cf646cf7e1341069f838d57242358c55/TensorFlow/LanguageModeling/BERT/data/create_datasets_from_start.sh#L19

**Comment by GeondoPark** [comment]
Thank you for answering. 
And I saw that the code used crawler from here. 
https://github.com/soskek/bookcorpus

When I run the crawler, if I download too many files, I get a 404Error or 403Forbidden, so I can't crawl anymore. Is there any way or where can I get permission?
Can you tell me if you know how?
Thank you,

**Comment by swethmandava** [comment]
#247 #37 #90

It is a BooksCorpus server/Maintainance issue
