### ISSUE TITLE
Different sentence tokenizer's impact. 

### ISSUE THREAD

**Issue by wxiaopei** [NVIDIA/DeepLearningExamples#265]
Has anyone measured the total truncated tokens by using different sentence tokenizer? Compared with NLTK, spacy can generate more short sentences.  Intuitively, the less tokens are truncated, the better of the trained language model. 
Thanks.

**Comment by nv-kkudrynski** [comment]
Transformer was upgraded with sentence-piece as a alternative tokenizer. As for now, we are not planning further experiments.
