### ISSUE TITLE
Running evaluation on SQuAD dataset during training

### ISSUE THREAD

**Issue by FruVirus** [NVIDIA/DeepLearningExamples#269]
Is it possible to have an EVAL mode for the tf.estimator for SQuAD during training? This could be useful to see the F1/EM score on the SQuAD dev dataset as training progresses.

**Comment by swethmandava** [comment]
TensorFlow's estimator API to [train_and_evaluate ](https://www.tensorflow.org/api_docs/python/tf/estimator/train_and_evaluate) has considerable [limitations](https://github.com/tensorflow/tensorflow/issues/13895). [InMemoryEvaluatorHook](https://www.tensorflow.org/api_docs/python/tf/estimator/experimental/InMemoryEvaluatorHook) seems to be a good alternative, although experimental. Feel free to send in a PR if you test it

**Comment by FruVirus** [comment]
@swethmandava 

i can certainly look into this.

Question---Will InMemoryEvaluatorHook work for master process evaluation during multi-GPU training?

**Comment by swethmandava** [comment]
InMemoryEvaluatorHook documentation says multi-node distributed mode is currently not supported. 
Did you face any issues with train_and_evaluate?

**Comment by FruVirus** [comment]
neither `train_and_eval` nor the in memory evaluator hook works with multi-node training using the Estimator API. This is a really frustrating limitation of the `tf.estimator` API.
