### ISSUE TITLE
Tacotron2 on colab: RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by artificialnouveau** [NVIDIA/DeepLearningExamples#270]
When running Tacotron2 on google colab, I get the following error after running `audio = waveglow.infer(mel)`

---------------------------------------------------------------------------

`_RuntimeError                              Traceback (most recent call last)` 
`<ipython-input-10-a6ced0eab0c3> in <module>()>` 
      `5 with torch.no_grad():` 
     ` 6     _, mel, _, _ = tacotron2.infer(sequence)` 
`----> 7     audio = waveglow.infer(mel)` 
     ` 8 audio_numpy = audio[0].data.cpu().numpy()` 
     ` 9 rate = 22050` 

`2 frames` 

`/root/.cache/torch/hub/nvidia_DeepLearningExamples_torchhub/PyTorch/SpeechSynthesis/Tacotron2/waveglow/model.py in forward(self, z, reverse)` 
`     75                     W_inverse = W_inverse.half()` 
`     76                 self.W_inverse = W_inverse` 
`---> 77             z = F.conv1d(z, self.W_inverse, bias=None, stride=1, padding=0)` 
`     78             return z` 
`     79         else:` 

`RuntimeError: CUDA error: invalid device function_`

**Comment by GrzegorzKarchNV** [comment]
Hi,
What GPU are you using? Are you using docker container from the Tacotron2 repository? Have you pulled the latest version of the repo?
