### ISSUE TITLE
WARNING: `nvJPEGDecoder` is now deprecated. Use `ImageDecoder` instead read 0 files from 0 directories

### ISSUE THREAD

**Issue by krislu603** [NVIDIA/DeepLearningExamples#271]
I follow READ.md to run benchmark training with 1 GPU, but it always shows up "WARNING: `nvJPEGDecoder` is now deprecated. Use `ImageDecoder` instead read 0 files from 0 directories".

OS: Ubuntu 18.04.3 LTS (GNU/Linux 4.15.7-041507-generic x86_64)
Nvidia Driver: 430.26 / 396.26
Nvidia GPU: Tesla T4 / Tesla P4
Tag: nvcr.io/nvidia/pytorch:19.10-py3 /pytorch:19.9-py3 / pytorch:19.8-py3 / pytorch:19.7-py3
Image: ILSVRC2012_img

================================================================

root@fa9873ffb986:/workspace/examples/resnet50v1.5# python ./main.py --arch resnet50 --training-only -p 1 --raport-file benchmark.json --epochs 1 --prof 100 /data/imagement/
=> creating model '('resnet50', 'classic')'
Version: {'net': <class 'image_classification.resnet.ResNet'>, 'block': <class 'image_classification.resnet.Bottleneck'>, 'layers': [3, 4, 6, 3], 'widths': [64, 128, 256, 512], 'expansion': 4, 'num_classes': 1000}
Config: {'conv': <class 'torch.nn.modules.conv.Conv2d'>, 'conv_init': 'fan_out', 'nonlinearity': 'relu', 'last_bn_0_init': False, 'activation': <function <lambda> at 0x7f4396642d08>}
WARNING: `HostDecoderRandomCrop` is now deprecated. Use `ImageDecoderRandomCrop` instead
read 1281167 files from 1000 directories
WARNING: `nvJPEGDecoder` is now deprecated. Use `ImageDecoder` instead
read 0 files from 0 directories
Traceback (most recent call last):
  File "./main.py", line 336, in <module>
    main(args)
  File "./main.py", line 272, in main
    val_loader, val_loader_len = get_val_loader(args.data, args.batch_size, 1000, False, workers=args.workers, fp16=args.fp16)
  File "/workspace/examples/resnet50v1.5/image_classification/dataloaders.py", line 219, in gdvl
    pipe.build()
  File "/opt/conda/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 305, in build
    self._pipe.Build(self._names_and_devices)
RuntimeError: [/opt/dali/dali/pipeline/operators/reader/loader/file_loader.h:108] Assert on "Size() > 0" failed: No files found.
Stacktrace (33 entries):
[frame 0]: /opt/conda/lib/python3.6/site-packages/nvidia/dali/libdali.so(+0xc716e) [0x7f42640ba16e]
[frame 1]: /opt/conda/lib/python3.6/site-packages/nvidia/dali/libdali.so(+0x17267e) [0x7f426416567e]
[frame 2]: /opt/conda/lib/python3.6/site-packages/nvidia/dali/libdali.so(+0x1a38df) [0x7f42641968df]
[frame 3]: /opt/conda/lib/python3.6/site-packages/nvidia/dali/libdali.so(std::_Function_handler<std::unique_ptr<dali::OperatorBase, std::default_delete<dali::OperatorBase> > (dali::OpSpec const&), std::unique_ptr<dali::OperatorBase, std::default_delete<dali::OperatorBase> > (*)(dali::OpSpec const&)>::_M_invoke(std::_Any_data const&, dali::OpSpec const&)+0xc) [0x7f4264118d0c]
[frame 4]: /opt/conda/lib/python3.6/site-packages/nvidia/dali/libdali.so(+0x1f2384) [0x7f42641e5384]
[frame 5]: /opt/conda/lib/python3.6/site-packages/nvidia/dali/libdali.so(dali::InstantiateOperator(dali::OpSpec const&)+0x34e) [0x7f42641e47be]
[frame 6]: /opt/conda/lib/python3.6/site-packages/nvidia/dali/libdali.so(dali::OpGraph::InstantiateOperators()+0xb9) [0x7f42640e0679]
[frame 7]: /opt/conda/lib/python3.6/site-packages/nvidia/dali/libdali.so(dali::Pipeline::Build(std::vector<std::pair<std::string, std::string>, std::allocator<std::pair<std::string, std::string> > >)+0xd68) [0x7f4264254868]
[frame 8]: /opt/conda/lib/python3.6/site-packages/nvidia/dali/backend_impl.cpython-36m-x86_64-linux-gnu.so(+0x2cebf) [0x7f43962d0ebf]
[frame 9]: /opt/conda/lib/python3.6/site-packages/nvidia/dali/backend_impl.cpython-36m-x86_64-linux-gnu.so(+0x1fee3) [0x7f43962c3ee3]
[frame 10]: python(_PyCFunction_FastCallDict+0x154) [0x55729d8fcc54]
[frame 11]: python(+0x199c0e) [0x55729d984c0e]
[frame 12]: python(_PyEval_EvalFrameDefault+0x30a) [0x55729d9a775a]
[frame 13]: python(+0x193c5b) [0x55729d97ec5b]
[frame 14]: python(+0x199b95) [0x55729d984b95]
[frame 15]: python(_PyEval_EvalFrameDefault+0x30a) [0x55729d9a775a]
[frame 16]: python(+0x192e66) [0x55729d97de66]
[frame 17]: python(+0x193ed6) [0x55729d97eed6]
[frame 18]: python(+0x199b95) [0x55729d984b95]
[frame 19]: python(_PyEval_EvalFrameDefault+0x10cc) [0x55729d9a851c]
[frame 20]: python(+0x19329e) [0x55729d97e29e]
[frame 21]: python(+0x193ed6) [0x55729d97eed6]
[frame 22]: python(+0x199b95) [0x55729d984b95]
[frame 23]: python(_PyEval_EvalFrameDefault+0x30a) [0x55729d9a775a]
[frame 24]: python(PyEval_EvalCodeEx+0x329) [0x55729d97f9b9]
[frame 25]: python(PyEval_EvalCode+0x1c) [0x55729d98075c]
[frame 26]: python(+0x215744) [0x55729da00744]
[frame 27]: python(PyRun_FileExFlags+0xa1) [0x55729da00b41]
[frame 28]: python(PyRun_SimpleFileExFlags+0x1c3) [0x55729da00d43]
[frame 29]: python(Py_Main+0x613) [0x55729da04833]
[frame 30]: python(main+0xee) [0x55729d8ce88e]
[frame 31]: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f43b3a72b97]
[frame 32]: python(+0x1c3160) [0x55729d9ae160]

root@fa9873ffb986:/workspace/examples/resnet50v1.5#

================================================================

root@ae5e18d95e16:/workspace/examples/resnet50v1.5/resnet50v1.5# nvidia-smi
Wed Oct 30 07:38:30 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.26       Driver Version: 430.26       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:86:00.0 Off |                    0 |
| N/A   36C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
root@ae5e18d95e16:/workspace/examples/resnet50v1.5/resnet50v1.5#

**Comment by nv-kkudrynski** [comment]
Should no longer be relevant. ResNet50 was upgraded to use DALI library.
