### ISSUE TITLE
Tensorflow/bert/scripts/run_pretraining* scripts not consistent with data_download

### ISSUE THREAD

**Issue by David-Levinthal** [NVIDIA/DeepLearningExamples#272]
the create_datascripts_from_start.sh has the following commands to make the tfrecord tree
# Create TFRecord files Phase 1
python3 ${BERT_PREP_WORKING_DIR}/bertPrep.py --action create_tfrecord_files --dataset books_wiki_en_corpus --max_seq_length 128 \
 --max_predictions_per_seq 20 --vocab_file ${BERT_PREP_WORKING_DIR}/download/google_pretrained_weights/uncased_L-24_H-1024_A-16/vocab.txt

# Create TFRecord files Phase 2
python3 ${BERT_PREP_WORKING_DIR}/bertPrep.py --action create_tfrecord_files --dataset books_wiki_en_corpus --max_seq_length 512 \
 --max_predictions_per_seq 80 --vocab_file ${BERT_PREP_WORKING_DIR}/download/google_pretrained_weights/uncased_L-24_H-1024_A-16/vocab.txt

this creates directories
lower_case_1_seq_len_128_max_pred_20_masked_lm_prob_0.15_random_seed_12345_dupe_factor_5_shard_256_test_split_20
and
lower_case_1_seq_len_512_max_pred_80_masked_lm_prob_0.15_random_seed_12345_dupe_factor_5_shard_256_test_split_20

not (as taken from the scripts/run_pretraining_lamb_phase1.sh)
INPUT_FILES="$DATA_DIR/tfrecord/lower_case_1_seq_len_${seq_len}_max_pred_${max_pred_per_seq}_masked_lm_prob_0.15_random_seed_12345_dupe_factor_5_shard_1472_test_split_10
all the scripts in the tensorflow tree seem to have this very minor issue

**Comment by swethmandava** [comment]
Fixed in #246

**Comment by David-Levinthal** [comment]
sorry..I missed that the default shard count was switched to 1472
