### ISSUE TITLE
Faster Transformer make error

### ISSUE THREAD

**Issue by hexiaoyupku** [NVIDIA/DeepLearningExamples#278]
Hi, 
I failed to make the faster transformer. My environment is : V100 GPU, Cuda10, tensorflow 1.13.1, cmake 3.15.5, gcc 5.4.0, python 2.7

My make command is : 
cmake -DSM=70 -DCMAKE_BUILD_TYPE=Release -DBUILD_TF=ON -DTF_PATH=/root/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow ..

I got the Error:
-- The CXX compiler identification is GNU 5.4.0
-- The CUDA compiler identification is NVIDIA 10.0.130
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/local/cuda-10.0/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda-10.0/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda-10.0 (found suitable version "10.0", minimum required is "10.0")
-- Found CUDA: /usr/local/cuda-10.0 (found version "10.0")
-- Assign GPU architecture (sm=70)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/FasterTransformer/build

In the build/CMakeFiles/CMakeError.log:
Run Build Command(s):/usr/bin/make cmTC_2e459/fast && /usr/bin/make -f CMakeFiles/cmTC_2e459.dir/build.make CMakeFiles/cmTC_2e459.dir/build
make[1]: Entering directory '/home/FasterTransformer/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_2e459.dir/src.cxx.o
/usr/bin/c++    -DCMAKE_HAVE_LIBC_PTHREAD   -o CMakeFiles/cmTC_2e459.dir/src.cxx.o -c /home/hFasterTransformer/build/CMakeFiles/CMakeTmp/src.cxx
Linking CXX executable cmTC_2e459
/dev/pkgs/cmake-3.15.5-Linux-x86_64/bin/cmake -E cmake_link_script CMakeFiles/cmTC_2e459.dir/link.txt --verbose=1
/usr/bin/c++   -DCMAKE_HAVE_LIBC_PTHREAD    CMakeFiles/cmTC_2e459.dir/src.cxx.o  -o cmTC_2e459 
CMakeFiles/cmTC_2e459.dir/src.cxx.o：在函数‘main’中：
src.cxx:(.text+0x3c)：对‘pthread_create’未定义的引用
src.cxx:(.text+0x48)：对‘pthread_detach’未定义的引用
src.cxx:(.text+0x59)：对‘pthread_join’未定义的引用
src.cxx:(.text+0x6d)：对‘pthread_atfork’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_2e459.dir/build.make:86: recipe for target 'cmTC_2e459' failed
make[1]: *** [cmTC_2e459] Error 1
make[1]: Leaving directory '/home/FasterTransformer/build/CMakeFiles/CMakeTmp'
Makefile:121: recipe for target 'cmTC_2e459/fast' failed
make: *** [cmTC_2e459/fast] Error 2

Desire for help. Thanks !!!

**Comment by IrishCoffee** [comment]
Sorry, I haven't met this issue before. My CMAKE version is 3.8.0. Maybe you can use this version for a quick test.

**Comment by IrishCoffee** [comment]
NO action. Close.
