### ISSUE TITLE
Clarification on  NVIDIA Achieves 4X Speedup on BERT Neural Network

### ISSUE THREAD

**Issue by asispatra** [NVIDIA/DeepLearningExamples#28]
On December 12, 2018 NVIDIA published that [NVIDIA Achieves 4X Speedup on BERT Neural Network](https://news.developer.nvidia.com/nvidia-achieves-4x-speedup-on-bert-neural-network/). We can see the following data in the news:
![image](https://user-images.githubusercontent.com/4022122/56277449-014b3880-6122-11e9-9ab4-653a93fbc2e6.png)

Is the data on `pre-training` or `fine tuning`?

**Comment by dsalvator** [comment]
These data are for pre-training.
