### ISSUE TITLE
Verify downloaded datasets

### ISSUE THREAD

**Issue by tlinjordet** [NVIDIA/DeepLearningExamples#284]
Hello, 

Can someone please confirm that the following directory sizes are reasonable after downloading data with `bash scripts/data_download.sh`?

```
676K    CoLA
611M    MNLI
1.6M    MRPC
125M    bookscorpus
9.7G    google_pretrained_weights
30M     squad
46G     wikicorpus_en
```

We are aware that the bookscorpus is incomplete, but the documentation refers to 170+ GB of training data, while we have only 56 GB under `data/download`. 

Thanks.

**Comment by Montantes** [comment]
Mine numbers are different. I ran the script `bash scripts/data_download.sh`  on 11/12/19
---------------------------------------------
bookscorpus - 0 Items,  0 KB
CoLA- 12 items, totaling 1.5 MB
google_pretrained_weights- 49 items, totalling 10.3 GB
MNLI- 13 items, totalling 1.4 GB
MRPC- 6 items, totalling 3.0 MB
squad- 8 items, totalling 81.7 MB
wikicorpus_en- 1 item, with size 0 bytes

**Comment by swethmandava** [comment]
The raw downloads take up:

12G	bookscorpus
71G wikicorpus_en/enwiki-20200101-pages-articles-multistream.xml
78M squad
2.8G glue
5.1G pretrained_models_google

tfrecords and hdf5 files, after preprocessing take upwards of 1TB

We will post scripts to verify some of the datasets in the future. Thanks for your patience :)

**Comment by vilmara** [comment]
Hi @swethmandava, I am getting a bunch of errors downloading the datasets, is there another way to download those? does Nvidia post the script to verify the datasets?.

**Comment by swethmandava** [comment]
You can just ignore the bookscorpus files that are missing. They dont exist anymore on the web.

#247 #262
