### ISSUE TITLE
What's the minimum requirement for GPU when train the WaveGlow?

### ISSUE THREAD

**Issue by xinzheshen** [NVIDIA/DeepLearningExamples#288]
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 5.93 GiB total capacity; 4.50 GiB already allocated; 22.81 MiB free; 282.59 MiB cached)  When I train the WaveGlow model eventhough set the batchsize 1.
My device GPU is GTX1060 (6G), can it  train the model by tuning the parameters? Thank you.

python train.py -m WaveGlow -d /home/shenxz/dataset -o ./output/ -lr 1e-4 --epochs 1001 -bs 1 --segment-length  8000 --weight-decay 0 --grad-clip-thresh 65504.0 --cudnn-enabled --cudnn-benchmark --log-file ./output/nvlog.json --amp-run

**Comment by GrzegorzKarchNV** [comment]
Even with batch size = 1, WaveGlow still requires about 8.5 GB of memory, since the model itself is quite large. Try changing some of the parameters, e.g. wn-channels (reduce it from 512 to 256). Bear in mind, though, that the training on your GPU might take very long time (>30 days for sure).

**Comment by xinzheshen** [comment]
Thank you very much.

**Comment by xinzheshen** [comment]
@GrzegorzKarchNV Hello，do you have trained the TTS model for Chinese mandarin? Recently I use your tacotron2 model to train for mandarin dataset with the default parameters except the cleaner type, but the result is bad. Could you give me any suggestions? Thank you.

**Comment by GrzegorzKarchNV** [comment]
Hi @xinzheshen, 
How big is the dataset? Could you provide the validation loss? Looks like the model might be overfitting.
Since there are a few requests about non-English datasets, we're planning to enhance our repository with the possibility to train on such datasets. Stay tuned!
