### ISSUE TITLE
Not able to run same batchsize as the document with same GPU: Bert For TensorFlow

### ISSUE THREAD

**Issue by asispatra** [NVIDIA/DeepLearningExamples#29]
In the document [Bert For TensorFlow](https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/LanguageModeling/BERT), it is suggested that for pre-training, we can use batch size 14 for fp16 on V100 32G GPU.
![image](https://user-images.githubusercontent.com/4022122/56278055-28563a00-6123-11e9-958d-385c8338eec4.png)
I have run the same command and getting OOM error. But this command with batchsize 13 `bash scripts/run_pretraining.sh 13 8 5e-5 fp16_xla 8 5000 2285000 5000 true` works fine.

So can anyone tell why batch-size 14 is failing for the same GPU?

**Comment by qijiaxing** [comment]
Hi, I am able to use batch size 16 for large model on V100 32GB, using docker nvidia/tensorflow:19.03. FYI.

**Comment by asispatra** [comment]
@qijiaxing Thanks for the information. The information you have put that is for pre-training only, right? not for Fine-tuning.

**Comment by qijiaxing** [comment]
> @qijiaxing Thanks for the information. The information you have put that is for pre-training only, right? not for Fine-tuning.

Yes, pre-training only. Didn't try Fine-tuning yet.
