### ISSUE TITLE
Any plans to implement ALBERT?

### ISSUE THREAD

**Issue by hairzooc** [NVIDIA/DeepLearningExamples#296]
Hi,
Do you guys have any plan to implement ALBERT which has been SOTA for many downstream tasks so called GLUE and squad stuffs.
It would be very helpful for me :)

**Comment by djstrong** [comment]
It requires 3 things:
* SOP (sentence order prediction) instead of NSP (next sentence prediction)
* shared parameters across layers
* added embeddings projection at the beginning

**Comment by sharathts** [comment]
At the moment, we are busy working on other great things. Stay tuned for updates. Feel free to open a PR meanwhile.
