### ISSUE TITLE
BERT TensorFlow Benchmark Script not Logging properly Performance(sent/sec)

### ISSUE THREAD

**Issue by Montantes** [NVIDIA/DeepLearningExamples#300]
I ran the training benchmark for BERT Tensorflow https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/LanguageModeling/BERT#training-performance-benchmark

the  `scripts/finetune_train_benchmark.sh large true 2 squad`

The benchmarks took about 2 days to complete, however the squad_training_benchmark_bert_large_gpu_2.log file has no data in it, (see attached) im positive the training did work, as the results displayed in my terminal, and have checkpoints for all however the log file shows no Performance(sent/sec) data. 

Has anyone else ran into this issue with running finetune_train_benchmark.sh?

[squad_training_benchmark_bert_large_gpu_2.log](https://github.com/NVIDIA/DeepLearningExamples/files/3853663/squad_training_benchmark_bert_large_gpu_2.log)

**Comment by swethmandava** [comment]
the directory in which the files were written to was missing and fixed [here](https://github.com/NVIDIA/DeepLearningExamples/pull/283/commits/2a93a1efa9cf447aa8cb85f56628ab98f04fdc1a)
