### ISSUE TITLE
Image with no detection will get error

### ISSUE THREAD

**Issue by pcshih** [NVIDIA/DeepLearningExamples#301]
When SSD does not detect anything, there will be an error below

utils.py
`bboxes_out, labels_out, scores_out = torch.cat(bboxes_out, dim=0), \
               torch.tensor(labels_out, dtype=torch.long), \
               torch.cat(scores_out, dim=0)`

bboxes_out labels_out scores_out will be empty due to no detection.

**Comment by skierat** [comment]
@pcshih Isn't this caught by https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/Detection/SSD/src/utils.py#L211
If not can you provide more details to reproduce the issue?
Thanks

**Comment by aoikaneko** [comment]
@skierat I encountered the same error with utils downloaded from PyTorch Hub, i.e.
`utils = torch.hub.load('NVIDIA/DeepLearningExamples:torchhub', 'nvidia_ssd_processing_utils')`:

`File "/****/.cache/torch/hub/NVIDIA_DeepLearningExamples_torchhub/PyTorch/Detection/SSD/src/utils.py", line 197, in decode_single
    bboxes_out, labels_out, scores_out = torch.cat(bboxes_out, dim=0), \
RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors.  Available functions are [CUDATensorId, CPUTensorId, VariableTensorId]`

Manually adding https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/Detection/SSD/src/utils.py#L211-L212 to the utils.py solved the issue.
I guess the script in PyTorch Hub is a bit old. Could you update it?
Thank you!
