### ISSUE TITLE
I know  the model is trained with mixed precision using Tensor Cores on NVIDIA Volta and Turing GPUs. the Pascal architecture(1080Ti) can be trained?

### ISSUE THREAD

**Issue by ccsone** [NVIDIA/DeepLearningExamples#302]

**Comment by mwawrzos** [comment]
1. Which model?
2. Yes, it can. The Tensor Cores in Volta and Turing architectures give you a performance speedup, but it is not a requirement. Especially, instructions include information, how to run training with FP32 precision, which is not using Tensor Cores.

**Comment by ccsone** [comment]
@mwawrzos  okay   thanks your answer, i try to use  four 1080ti GPUs  to train  SSD net of NVIDIA/DeepLearningExamples with coco data . it always come out this error"ValueError: Tensor conversion requested dtype string for Tensor with dtype float32: 'Tensor("arg0:0", shape=(), dtype=float32, device=/device:CPU:0)'" i can‘s focus on where the error point is.

**Comment by mwawrzos** [comment]
Can you provide the command you use to start training?
Can you list the directory with the dataset?

**Comment by skierat** [comment]
@ccsone : Most likely your input path is not correct.
Please check whether this line https://github.com/NVIDIA/DeepLearningExamples/blob/master/TensorFlow/Detection/SSD/configs/ssd320_full_8gpus.config#L189
corresponds to your tfrecords generated by download_all.sh script
Please let us know whether you solved the issue.
Thanks
