### ISSUE TITLE
Input transform is incorrect in examples of PyTorch SSD

### ISSUE THREAD

**Issue by AskAukNuTutor** [NVIDIA/DeepLearningExamples#304]
Thank you for your code.

In some inference examples in PyTorch SSD, eg
DeepLearningExamples/PyTorch/Detection/SSD/examples/inference.ipynb ,
DeepLearningExamples/PyTorch/Detection/SSD/examples/SSD300_inference.py ,
the input transform pipeline seems wrong.

In these examples, input image is transformed by
    img = rescale(img, 300, 300)
    img = crop_center(img, 300, 300)
    img = normalize(img).

However, in the SSD training, input is transformed by
    transforms.Resize((300, 300)),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])

**Comment by AskAukNuTutor** [comment]
Sorry for self-reply, but I misunderstood the code.

The transform of 
resize + normalize with mean=[0.485, 0.456, 0.406] and std=[0.229, 0.224, 0.225]
was only used in the "validation" phase in the code, not in the training phase (anyway DALICOCOIterator is so complicated for me..).

Then, how should I detect all objects in an image of "non-squared" size, instead of the center-cropped one?

**Comment by skierat** [comment]
I am not sure if I understand your question.
The code should work with all input resolutions.
Each input image is resized to 300x300 as the network can operate only on this input sizes.
I think that 'img = crop_center(img, 300, 300)' step can be omitted as the shape should be already 300x300.
If your input images are very 'non-squere' (e.g. 800x9000) and you are afraid of artefacts of resizing you can chunk your image into several images (e.g. 10* 800x900) and detect all objects on each chunk.

**Comment by AskAukNuTutor** [comment]
Thanks. Now I understand that the network can operate (resized) images of size 300x300. And I think the input image should be normalized with mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225].
