### ISSUE TITLE
Fix spelling of "iteration" in PyTorch/Detection/SSD/src/logger.py

### ISSUE THREAD

**Issue by davemq** [NVIDIA/DeepLearningExamples#307]
"iteration" is misspelled as "iteraion" in PyTorch/Detection/SSD/src/logger.py:

    print('epoch: {}\titeraion: {}\tloss: {}'.format(epoch, iteration, loss))

**Comment by skierat** [comment]
Thanks for pointing this out. It will be fixed in the next release.
