### ISSUE TITLE
may should start from f_start_id

### ISSUE THREAD

**Issue by pkuyym** [NVIDIA/DeepLearningExamples#310]
https://github.com/NVIDIA/DeepLearningExamples/blob/7d772b8bc9f48d5d955490b1b658335be9085a7b/PyTorch/LanguageModeling/BERT/run_pretraining.py#L475
 Seems the program would not enter the loop if there's only one training file.

**Comment by sharathts** [comment]
Thank you for bringing the corner case up. It has been fixed in https://github.com/NVIDIA/DeepLearningExamples/pull/312
