### ISSUE TITLE
I run "bash ./examples/SSD320_FP16_8GPU.sh /checkpoints" script,  has "ValueError: Tensor conversion requested dtype string for Tensor with dtype float32: 'Tensor("arg0:0", shape=(), dtype=float32, device=/device:CPU:0)'    "error,how can i solve it or focus on it?

### ISSUE THREAD

**Issue by ccsone** [NVIDIA/DeepLearningExamples#313]
How to fix this mistake

**Comment by skierat** [comment]
Most likely your input path is not correct.
Please check whether this line https://github.com/NVIDIA/DeepLearningExamples/blob/master/TensorFlow/Detection/SSD/configs/ssd320_full_8gpus.config#L189
corresponds to your tfrecords generated by download_all.sh script
