### ISSUE TITLE
Error in running the script 'run_preprocessing.sh' of 'Transformer'

### ISSUE THREAD

**Issue by allenguo92** [NVIDIA/DeepLearningExamples#314]
Hi,

I tried to use your code to do implemention of my own model which is based on Transformer. However, when I finished configuretion with the following instruction:

[Transformer](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Translation/Transformer)

and ran the script 'run_preprocessing.sh' in section 'Quick Start Guide', the error emerged as:

![image](https://user-images.githubusercontent.com/4317838/69454928-46170c00-0da2-11ea-949d-715f02768521.png)

Also, I find the [relevant issue](https://github.com/NVIDIA/DeepLearningExamples/issues/35) and do as what it refer. However, it still does not work.

Any suggestions for solving the problem?

Regards

**Comment by passing2961** [comment]
Hi, 

I have the same problem that you mentioned.

How did you solve it? 

Best
Regards

**Comment by passing2961** [comment]
Thank you for your kind answer.

I resolve this issue by removing `EpochBatchIterator` class and `fairseq.data.batch_C`. 

Maybe I think it was redundant things that you mentioned.

Thanks

**Comment by jbaczek** [comment]
This is actually a quite relevant module. First try to install fairseq and then check if module has compiled and is present in `fairseq/data` . If something is still wrong after that, please post the error message
