### ISSUE TITLE
TensorFlow BERT Dockerfile build error 'invalid from flag value trt: pull access denied for trt, repository does not exist or may require 'docker login'

### ISSUE THREAD

**Issue by Montantes** [NVIDIA/DeepLearningExamples#318]
When building BERT TensorFlow Container `bash scripts/docker/build.sh ` step 11 I get the following error: 

_Step 11/18 : COPY --from=trt /workspace/install/ /workspace/install/
invalid from flag value trt: pull access denied for trt, repository does not exist or may require 'docker login'_

I noticed there was an update several hours that went live... it was working fine on previous release, I was at least able to build the docker container. (full output log attached)

[BERT error.log](https://github.com/NVIDIA/DeepLearningExamples/files/3892898/BERT.error.log)

**Comment by swethmandava** [comment]
Can you try #352 ? Thanks!

**Comment by Montantes** [comment]
Latest build still fails

COPY failed: stat /var/lib/docker/overlay2/0a53323a4e45f0b9fac9d584e47e4f59623025b9a41828b8c34c1631bebb4eaa/merged/workspace/install: no such file or directory

[BERT_TF_dockerfile_error.log](https://github.com/NVIDIA/DeepLearningExamples/files/4041615/BERT_TF_dockerfile_error.log)

**Comment by swethmandava** [comment]
sorry I wasn't clear, you needed to pull from the PR. It is now merged and the latest build should work ok.
