### ISSUE TITLE
BERT: AMP is slower than fp32

### ISSUE THREAD

**Issue by sandyhouse** [NVIDIA/DeepLearningExamples#32]
I ran Bert pretraining with tensorflow 1.12 and horovod 0.13.8, not with the NGC container.
But I got worse performance with mixed precision using amp than that with fp32.

I use cuda 9.0 and cuDNN 7.1.

The command lines to run pretraining with and without amp are as follows:
./run_pretraining.sh 32 8 5e-5 fp32 1, and
./run_pretraining.sh 32 8 5e-5 amp 1

Any suggestion?

**Comment by sandyhouse** [comment]
The GPU device used is V100.

**Comment by swethmandava** [comment]
The [TensorFlow 19.04](https://docs.nvidia.com/deeplearning/dgx/tensorflow-release-notes/rel_19.04.html#rel_19.04) container uses CUDA 10.1 and CUDNN 7.5. 

I suspect that tensor core kernels are not being called resulting in no speedup. You can confirm that by doing this:
nvprof --log-file results/nvprof_log.txt python run_pretraining.py <arguments>
If you see *s884* in kernel names, it confirms that you are indeed using TensorCore kernels.

**Comment by sandyhouse** [comment]
Thanks for your rely @swethmandava .
The tensor core kernels are not called, as there are no 's884' in kernel names. 
But how to call tensor core kernels?
I read the following article (https://developer.nvidia.com/automatic-mixed-precision), but have no idea.

**Comment by swethmandava** [comment]
AMP is not supported in TF 1.12. It is supported in TF in our containers since 19.03. You can use "fp16" or "fp16_xla" instead of "amp" if you are not using the container. To call tensor kernels for fp16 operations, you'd also need the latest software stack (CUDA, cuDNN, cuBLAS, etc). 

I'd suggest you use the ngc containers for reproducibility in performance numbers.

**Comment by sandyhouse** [comment]
Thanks. I'll try it,

**Comment by jconwayNV** [comment]
FYI - AMP is officially supported in TF 1.14: https://www.tensorflow.org/api_docs/python/tf/train/experimental/enable_mixed_precision_graph_rewrite
We still recommend our containers for best performance
