### ISSUE TITLE
Zerodivision error when running mixed precision for GNMT

### ISSUE THREAD

**Issue by ljl199141** [NVIDIA/DeepLearningExamples#326]
Hi,

I followed the steps and used the command "python3 -m launch train.py --seed 2 --train-global-batch-size 1024".  But I ran into this zerodivision error. Is there a way to avoid it?
![image](https://user-images.githubusercontent.com/31768364/70000853-a6c7e680-1510-11ea-9fac-7cbda49559d3.png)

Thanks!

**Comment by nv-kkudrynski** [comment]
Can you check if this is still an issue after last updates?
