### ISSUE TITLE
When will the transformer decoder be released?

### ISSUE THREAD

**Issue by leerumor** [NVIDIA/DeepLearningExamples#327]
Hi! Thanks for the great Fastertransformer, my team has benefited a lot from it.
I remember there was a live held by NVIDIA a few weeks ago, the speaker mentioned to release the Decoder version soon. I'd like to ask if you still have this plan and when will the decoder be released? 
Thanks :)

**Comment by byshiue** [comment]
The decoder version of FasterTransformer is released, now.
