### ISSUE TITLE
CUDA out of memory error

### ISSUE THREAD

**Issue by shradda8** [NVIDIA/DeepLearningExamples#333]
when trying to run pytorch command bash scripts/train_tacotron2, i get the following error 

RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 11.17 GiB total capacity; 10.82 GiB already allocated; 19.31 MiB free; 10.85 GiB reserved in total by PyTorch)

How can i fix this?
I tried torch.cuda.empty_cache() but it didnt help

**Comment by shradda8** [comment]
Below is the full error log, please assist

:::NVLOGv0.2.2 Tacotron2_PyT 1575484405.244794607 (/workspace/tacotron2/dllogger/logger.py:279) run_start
:::NVLOGv0.2.2 Tacotron2_PyT 1575484405.253022671 (/workspace/tacotron2/dllogger/logger.py:251) cpu_info: {"num": 12, "name": "Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz"}
:::NVLOGv0.2.2 Tacotron2_PyT 1575484405.260179281 (/workspace/tacotron2/dllogger/logger.py:251) mem_info: {"ram": "110G"}
:::NVLOGv0.2.2 Tacotron2_PyT 1575484405.413818359 (/workspace/tacotron2/dllogger/logger.py:251) gpu_info: {"driver_version": "440.33.01", "num": 2, "name": ["Tesla K80", "Tesla K80"], "mem": ["11441 MiB", "11441 MiB"]}
:::NVLOGv0.2.2 Tacotron2_PyT 1575484405.416563272 (/workspace/tacotron2/dllogger/logger.py:251) args: {"output_directory": "./output/", "dataset_path": "./", "model_name": "Tacotron2", "log_file": "./output/nvlog.json", "anneal_steps": ["500", "1000", "1500"], "anneal_factor": 0.1, "epochs": 1501, "epochs_per_checkpoint": 50, "checkpoint_path": "", "seed": 1234, "dynamic_loss_scaling": true, "amp_run": true, "cudnn_enabled": true, "cudnn_benchmark": false, "disable_uniform_initialize_bn_weight": false, "use_saved_learning_rate": false, "learning_rate": 0.001, "weight_decay": 1e-06, "grad_clip_thresh": 1.0, "batch_size": 128, "grad_clip": 5.0, "load_mel_from_disk": false, "training_files": "filelists/ljs_audio_text_train_filelist.txt", "validation_files": "filelists/ljs_audio_text_val_filelist.txt", "text_cleaners": ["english_cleaners"], "max_wav_value": 32768.0, "sampling_rate": 22050, "filter_length": 1024, "hop_length": 256, "win_length": 1024, "mel_fmin": 0.0, "mel_fmax": 8000.0, "rank": 0, "world_size": 2, "dist_url": "tcp://localhost:23456", "group_name": "group_name", "dist_backend": "nccl", "mask_padding": false, "n_mel_channels": 80, "n_symbols": 148, "symbols_embedding_dim": 512, "encoder_kernel_size": 5, "encoder_n_convolutions": 3, "encoder_embedding_dim": 512, "n_frames_per_step": 1, "decoder_rnn_dim": 1024, "prenet_dim": 256, "max_decoder_steps": 2000, "gate_threshold": 0.5, "p_attention_dropout": 0.1, "p_decoder_dropout": 0.1, "decoder_no_early_stopping": false, "attention_rnn_dim": 1024, "attention_dim": 128, "attention_location_n_filters": 32, "attention_location_kernel_size": 31, "postnet_embedding_dim": 512, "postnet_kernel_size": 5, "postnet_n_convolutions": 5}
Initializing Distributed
Done initializing distributed
:::NVLOGv0.2.2 Tacotron2_PyT 1575484406.454308510 (/workspace/tacotron2/dllogger/logger.py:251) run_start
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Warning:  multi_tensor_applier fused unscale kernel is unavailable, possibly because apex was installed without --cuda_ext --cpp_ext. Using Python fallback.  Original ImportError was: ImportError('/opt/conda/lib/python3.6/site-packages/amp_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E',)
Warning:  apex was installed without --cpp_ext.  Falling back to Python flatten and unflatten.
:::NVLOGv0.2.2 Tacotron2_PyT 1575484409.762578964 (/workspace/tacotron2/dllogger/logger.py:251) train_loop
:::NVLOGv0.2.2 Tacotron2_PyT 1575484409.763598680 (/workspace/tacotron2/dllogger/logger.py:251) train_epoch_start: 0
Batch: 0/48 epoch 0
:::NVLOGv0.2.2 Tacotron2_PyT 1575484413.035915852 (/workspace/tacotron2/dllogger/logger.py:251) train_iter_start: 0
Traceback (most recent call last):
  File "train.py", line 501, in <module>
    main()
  File "train.py", line 413, in main
    y_pred = model(x)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/tacotron2/tacotron2/model.py", line 668, in forward
    encoder_outputs, targets, memory_lengths=input_lengths)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/tacotron2/tacotron2/model.py", line 501, in forward
    mask)
  File "/workspace/tacotron2/tacotron2/model.py", line 427, in decode
    attention_weights_cat, mask)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/tacotron2/tacotron2/model.py", line 108, in forward
    attention_hidden_state, processed_memory, attention_weights_cat)
  File "/workspace/tacotron2/tacotron2/model.py", line 91, in get_alignment_energies
    processed_query + processed_attention_weights + processed_memory))
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/wrap.py", line 53, in wrapper
    return orig_fn(*args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 11.17 GiB total capacity; 10.59 GiB already allocated; 7.31 MiB free; 10.86 GiB reserved in total by PyTorch)

**Comment by Montantes** [comment]
Some things to consider that may help you fix this problem.
- Did you try to use a smaller batch size? Try 64 instead of 128 and see if you still get the error.
- Is there another process running using that may be using the GPU?  
- What’s your GPU memory consumption is reported before you run this command? (use the nvidia-smi command).
- what type/model of GPU are you using?

**Comment by shradda8** [comment]
![image](https://user-images.githubusercontent.com/57967822/70243285-4dde9500-1740-11ea-869e-8ce774a708e4.png)
@Montantes

**Comment by shradda8** [comment]
issue

**Comment by shradda8** [comment]
Issue cleared by reducing the batch size.
I have proceeded for inference and I get the RuntimeError: CUDA error: no kernel image is available for execution on the device. Below is the error log:

:::NVLOGv0.2.2 Tacotron2_PyT 1575648678.727481842 (/workspace/tacotron2/dllogger/logger.py:251) cpu_info: {"num": 12, "name": "Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz"}
:::NVLOGv0.2.2 Tacotron2_PyT 1575648678.738536119 (/workspace/tacotron2/dllogger/logger.py:251) mem_info: {"ram": "110G"}
:::NVLOGv0.2.2 Tacotron2_PyT 1575648688.904395342 (/workspace/tacotron2/dllogger/logger.py:251) gpu_info: {"driver_version": "440.33.01", "num": 2, "name": ["Tesla K80", "Tesla K80"], "mem": ["11441 MiB", "11441 MiB"]}
:::NVLOGv0.2.2 Tacotron2_PyT 1575648688.905199289 (/workspace/tacotron2/dllogger/logger.py:251) args: {"input": "/phrases/phrases.txt", "output": "output/", "tacotron2": null, "waveglow": null, "sigma_infer": 0.9, "denoising_strength": 0.01, "sampling_rate": 22050, "amp_run": false, "log_file": "nvlog.json", "include_warmup": false, "stft_hop_length": 256}
Traceback (most recent call last):
  File "inference.py", line 275, in <module>
    main()
  File "inference.py", line 218, in main
    denoiser = Denoiser(waveglow).cuda()
  File "/workspace/tacotron2/waveglow/denoiser.py", line 57, in __init__
    bias_audio = waveglow.infer(mel_input, sigma=0.0).float()
  File "/workspace/tacotron2/waveglow/model.py", line 262, in infer
    audio = self.convinv[k](audio, reverse=True)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/tacotron2/waveglow/model.py", line 72, in forward
    W_inverse = W.float().inverse()
RuntimeError: CUDA error: no kernel image is available for execution on the device

**Comment by GrzegorzKarchNV** [comment]
Hi @shradda8 which docker version are you using?

**Comment by GrzegorzKarchNV** [comment]
Hi @shradda8 I'm closing this issue since the problem seems to  be solved in https://github.com/NVIDIA/DeepLearningExamples/issues/308
