### ISSUE TITLE
Tacotron2 inference error "AttributeError: 'RecursiveScriptModule' object has no attribute 'forward'

### ISSUE THREAD

**Issue by IrishCoffee** [NVIDIA/DeepLearningExamples#334]
Hi,

When using the trained tacotron2 and waveglow models to do inference, I met the following error.  "AttributeError: 'RecursiveScriptModule' object has no attribute 'forward'

The inference command I used is

python inference.py --tacotron2 output/checkpoint_Tacotron2_0 --waveglow output/checkpoint_WaveGlow_100 -o output/ --include-warmup -i phrases/phrase.txt --amp-run

The docker image is nvcr.io/nvidia/pytorch:19.11-py3.

Is there any idea about this error? Thanks.

**Comment by GrzegorzKarchNV** [comment]
HI @IrishCoffee could you please post the whole error log? is your Tacotron2 repository up to date?

**Comment by fosimoes** [comment]
The same happened to me. 
I made things work by substituting the following line in 'inference.py'

mel, mel_lengths = jitted_tacotron2(sequences_padded, input_lengths)
with
mel, mel_lengths = tacotron2(sequences_padded, input_lengths)

Although I am not sure if this has any side-effect...

**Comment by GrzegorzKarchNV** [comment]
@fosimoes using `tacotron2` instead of `jitted_tacotron2` means that your inference won't benefit from the TorchScript optimizations and your inference will be slower
@IrishCoffee @fosimoes please check the latest repo update and let us know if you still get the error
