### ISSUE TITLE
[SSD/pytorch] DALICOCOIterator fails for newer pytorch containers

### ISSUE THREAD

**Issue by kilianbreathnach** [NVIDIA/DeepLearningExamples#335]
The Dockerfile for the example has in the first line

`FROM nvcr.io/nvidia/pytorch:19.08-py3`

but the NVIDIA NGC registry now contains a version 19.11. However, if I include any version past 19.09, the following error occurs:

```
Traceback (most recent call last):
  File "main.py", line 266, in <module>
    train(train_loop_func, logger, args)
  File "main.py", line 136, in train
    train_loader = get_train_loader(args, args.seed - 2**31)
  File "/workspace/src/data.py", line 25, in get_train_loader
    train_loader = DALICOCOIterator(train_pipe, 118287 / args.N_gpu)
  File "/workspace/src/coco_pipeline.py", line 151, in __init__
    self._first_batch = self.next()
  File "/workspace/src/coco_pipeline.py", line 253, in next
    return self.__next__();
  File "/workspace/src/coco_pipeline.py", line 166, in __next__
    outputs.append(p.share_outputs())
  File "/opt/conda/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 397, in share_outputs
    with self._check_api_type_scope(types.PipelineAPIType.SCHEDULED) as check:
  File "/opt/conda/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 201, in _check_api_type_scope
    self._check_api_type(type)
  File "/opt/conda/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 187, in _check_api_type
    ", but trying to use: " + str(type))
RuntimeError: Mixing pipeline API type. Currently used: 0, but trying to use: 2
```

Here, when the first outputs are called from the pipeline being iterated over, the api type of the pipeline is checked against `types.PipelineAPIType.SCHEDULED`, which has value 2. However, the pipeline, when built, gets value 0.

I don't know why this occurs, if it is due to DALI, or pytorch. And I don't know how to describe this issue to one of those projects (I suppose it is maybe even a NGC issue?) so I am reporting it here.

The only step necessary to reproduce this bug is to change the value of the pytorch container version in the first line of the Docker file, from "08" to "10" or "11". Then build the container and run one of the example scripts inside it.

**Comment by cliffwoolley** [comment]
Thanks for the report, @kilianbreathnach .

@ptrblck @JanuszL for visibility

**Comment by JanuszL** [comment]
@kilianbreathnach - Tl;dr:
removing [this](https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/Detection/SSD/src/data.py#L34L35) should help 

Longer version:
DALI provides different [APIs to run the data pipeline](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/advanced_topics.html#running-dali-pipeline). They provide different granularity of control and are not supposed to be mixed. In the most recent DALI release available in NGC there is an additional check added that prevents API from being mixed. SSD model available here has not been updated yet to pass this check.

**Comment by kilianbreathnach** [comment]
That worked for me, thank you!
