### ISSUE TITLE
No module named 'glow'

### ISSUE THREAD

**Issue by jglozma** [NVIDIA/DeepLearningExamples#337]
I am trying to run example with TRTIS described on https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/SpeechSynthesis/Tacotron2/notebooks/trtis

When running step that was supposed to produce ONNX model I have got following error

**python export_waveglow_trt.py --waveglow waveglow_256channels_ljs_v3.pt --wn-channels 256 --amp-run**
_:::NVLOGv0.2.2 None 1575584732.593067884 (/workspace/tacotron2/dllogger/logger.py:251) args: {"waveglow": "waveglow_256channels_ljs_v3.pt", "output": "waveglow.onnx", "amp_run": true, "sigma_infer": 0.6}
Traceback (most recent call last):
  File "export_waveglow_trt.py", line 158, in <module>
    main()
  File "export_waveglow_trt.py", line 155, in main
    export_onnx(parser, args)
  File "export_waveglow_trt.py", line 117, in export_onnx
    waveglow = load_and_setup_model('WaveGlow', parser, args.waveglow, args.amp_run)
  File "/workspace/tacotron2/inference.py", line 122, in load_and_setup_model
    state_dict = torch.load(checkpoint)['state_dict']
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 422, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 609, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'glow'_

**Comment by jglozma** [comment]
I found glow.py in https://github.com/NVIDIA/waveglow. Next hurdle to overcome is 

_root@b5fb39a822ce:/workspace/tacotron2# python export_waveglow_trt.py --waveglow waveglow_256channels.pt --wn-channels 256 --amp-run
:::NVLOGv0.2.2 None 1575856662.273496628 (/workspace/tacotron2/dllogger/logger.py:251) args: {"waveglow": "waveglow_256channels.pt", "output": "waveglow.onnx", "amp_run": true, "sigma_infer": 0.6}
/opt/conda/lib/python3.6/site-packages/torch/serialization.py:489: SourceChangeWarning: source code of class 'glow.WaveGlow' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/opt/conda/lib/python3.6/site-packages/torch/serialization.py:489: SourceChangeWarning: source code of class 'torch.nn.modules.conv.ConvTranspose1d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/opt/conda/lib/python3.6/site-packages/torch/serialization.py:489: SourceChangeWarning: source code of class 'glow.WN' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/opt/conda/lib/python3.6/site-packages/torch/serialization.py:489: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv1d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/opt/conda/lib/python3.6/site-packages/torch/serialization.py:489: SourceChangeWarning: source code of class 'glow.Invertible1x1Conv' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "export_waveglow_trt.py", line 158, in <module>
    main()
  File "export_waveglow_trt.py", line 155, in main
    export_onnx(parser, args)
  File "export_waveglow_trt.py", line 117, in export_onnx
    waveglow = load_and_setup_model('WaveGlow', parser, args.waveglow, args.amp_run)
  File "/workspace/tacotron2/inference.py", line 122, in load_and_setup_model
    state_dict = torch.load(checkpoint)['state_dict']
KeyError: 'state_dict'_

**Comment by GrzegorzKarchNV** [comment]
Hi @jglozma how did you train your checkpoint? Does it come from the  https://github.com/NVIDIA/waveglow repository?

**Comment by jglozma** [comment]
Hi,

I have not done any training myself yet. I downloaded two checkpoints from NGC
https://ngc.nvidia.com/catalog/models/nvidia:waveglow_ljs_256channels/files
- the latest waveglow_256channels_ljs_v3.pt
- few month ago waveglow_256channels.pt

Both checkpoints produce the same error above

**Comment by GrzegorzKarchNV** [comment]
please download the checkpoint from https://ngc.nvidia.com/models/nvidia:waveglow256pyt_fp16

**Comment by jglozma** [comment]
It worked. Thanks for your help!

**Comment by kb-rahul** [comment]
@GrzegorzKarchNV : I am unable to access the model from the link. Has anything changed recently?

**Comment by jglozma** [comment]
it is there. By default, it opens at "Overview". Click on "File Browser" and you will see it

**Comment by kb-rahul** [comment]
Thanks

**Comment by MuruganR96** [comment]
> please download the checkpoint from https://ngc.nvidia.com/models/nvidia:waveglow256pyt_fp16

@GrzegorzKarchNV sir, i have tried it, but facing error. can you please look into this issue. https://github.com/NVIDIA/DeepLearningExamples/issues/763#issue-748083074
