### ISSUE TITLE
[TensorFlow] Horovod detection is not compatible with srun / PMI

### ISSUE THREAD

**Issue by samcmill** [NVIDIA/DeepLearningExamples#339]
Related to TensorFlow/All

**Describe the bug**
When using `srun` to start a distributed training job all but 1 rank aborts.  The output reports that only a single GPU is being used:

```
:::NVLOGv0.2.3 None 1576012163.294904232 (runner.py:387) Num GPUs: 1
```

**To Reproduce**
```
srun -n 8 --mpi=pmi2 python ./main.py --mode=training_benchmark --use_tf_amp --warmup_steps=200 --batch_size=256 --data_dir=/data/imagenet --results_dir=/tmp/resnet
```

**Expected behavior**
The behavior should be the same as using `mpirun`, which uses all 8 GPUs.

```
mpirun -n 8 python ./main.py --mode=training_benchmark --use_tf_amp --warmup_steps=200 --batch_size=256 --data_dir=/data/imagenet --results_dir=/tmp/resnet
```

**Environment**
Please provide at least:
* Container version: tensorflow:19.11-tf1-py3
* GPUs in the system: 8x Tesla V100-SXM2-16GB
* CUDA driver version: 418.87

The root cause is faulty logic in `is_using_hvd()`.  It currently requires that both the `OMPI_COMM_WORLD_RANK` and `OMPI_COMM_WORLD_SIZE` environment variables must be set in order to use Horovod.  When using `srun` with PMI, it should instead check that the `PMI_RANK` and `PMI_SIZE` environment variables are set.  

If I manually change the logic to the following then `srun` works as expected:

```
def is_using_hvd():
    ompi_vars = ["OMPI_COMM_WORLD_RANK", "OMPI_COMM_WORLD_SIZE"]
    pmi_vars = ["PMI_RANK", "PMI_SIZE"]

    if all([var in os.environ for var in ompi_vars]) or all([var in os.environ for var in pmi_vars]):
        return True
    else:
        return False
```

**Comment by nv-kkudrynski** [comment]
Resolved.
