### ISSUE TITLE
Same batch size is OK on single GPU but out of memory on multiple GPUs

### ISSUE THREAD

**Issue by rabbitwayne** [NVIDIA/DeepLearningExamples#340]
I am running BERT Tensorflow version. The maximum batch size on one GPU is 86 for BERT large on V100 with 32GB memory. But when running on 4 GPUs, the maximum single-GPU batch size can only be about 48. Batch sizes larger than this get out of memory error. This is strange. Why running on multiple cards could reduce the batch size on a single GPU?

**Comment by swethmandava** [comment]
Can you attach your logs, please?

**Comment by nv-kkudrynski** [comment]
Closing. No reponse for a long time.
