### ISSUE TITLE
how to extend to support chinese TTS [Model/Framework or something else] Feature requested

### ISSUE THREAD

**Issue by gaoyuqi** [NVIDIA/DeepLearningExamples#341]
Related to **Model/Framework(s) or something else (describe)** 

*Examples:* 
* *GNMT/PyTorch* 
* *AMP* 
* *Tensorflow 2.0*
* *Jupyter notebooks*

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by GrzegorzKarchNV** [comment]
@gaoyuqi thanks for your interest in the TTS; in order to support Chinese, a relevant text cleaner is required, among other things. I'll keep this issue open for any developments to support Chinese language

**Comment by GrzegorzKarchNV** [comment]
Since there are a few requests about non-English datasets, we're planning to enhance our repository with the possibility to train on such datasets. Stay tuned!

**Comment by lightwithshadow** [comment]
Training the model on the Chinese data set, the epoch to 500 alignment effect is not ideal; 

![alignment_0](https://user-images.githubusercontent.com/32893346/97245919-0faa0280-1837-11eb-93e0-1a54165fd491.png)

Except for modifying the symbols in symbols.py to the Chinese pinyin character set;
Set the parameter ext-cleaners=basic_cleaners of train.py and inference.py; 

are there other places that need to be modified? thx！

**Comment by GrzegorzKarchNV** [comment]
Hi @lightwithshadow have you checked the discussion on https://github.com/NVIDIA/tacotron2/issues/17 ?
