### ISSUE TITLE
Installation instructions for dllogger refers to a publicly inaccessible gitlab-master repository

### ISSUE THREAD

**Issue by animohan** [NVIDIA/DeepLearningExamples#346]
Here are the current instructions for dllogger on this page https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/Segmentation/UNet_Industrial/dllogger

git clone https://gitlab-master.nvidia.com/dl/JoC/DLLogger.git
pip install DLLogger/.

Installation instructions for dllogger refers to a publicly inaccessible gitlab-master repository

**Comment by asulecki** [comment]
@nvpstr  who is the code owner of UNet_Industrial ?

**Comment by vinhngx** [comment]
I guess just remove this line as dllogger repo is included in UNet
`git clone https://gitlab-master.nvidia.com/dl/JoC/DLLogger.git`

**Comment by nvpstr** [comment]
we changed the logging. it should be updated with the next release soon.

**Comment by nv-kkudrynski** [comment]
Resolved.
