### ISSUE TITLE
[BERT] nvidia_driver_440.33.01: VolumeDriver.Create Error

### ISSUE THREAD

**Issue by arnepeine** [NVIDIA/DeepLearningExamples#351]
Related to **Model/Framework(s)** 
*(e.g. GNMT/PyTorch or FasterTransformer/All)*

**Describe the bug**
docker: Error response from daemon: create nvidia_driver_440.33.01: VolumeDriver.Create: internal error, check logs for details.
See 'docker run --help'.

Despite having the newest driver version.

**To Reproduce**
1. Successfully built the docker container
2. Launching container with nvidia-docker run   -v $PWD:/workspace/bert   -v $PWD/results:/results   --shm-size=1g   --ulimit memlock=-1   --ulimit stack=67108864   --publish 0.0.0.0:8888:8888   -it bert:latest bash

**Expected behavior**

**Environment**
NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2 7

2 GPU Tesla K80

**Comment by szmigacz** [comment]
I don't think that it's related to bert. Seems like a general issue with nvidia-docker. Similar issues were reported here: https://github.com/NVIDIA/nvidia-docker/issues/142 and here https://github.com/NVIDIA/nvidia-docker/issues/735. The recommended solution is to update to nvidia-docker2 (https://github.com/NVIDIA/nvidia-docker/issues/142#issuecomment-490181877).

Are you already using nvidia-docker2? If so then please report the bug to https://github.com/NVIDIA/nvidia-docker
