### ISSUE TITLE
[Tacotron2-Waveglow/PyTorch] No module named 'dllogger'

### ISSUE THREAD

**Issue by jaeseongyou** [NVIDIA/DeepLearningExamples#357]
Thank you for sharing your project.

After the latest update, the out-of-the-box Tacotron2-Waveglow stopped working; it complains about the absence of 'dllogger'.

Traceback (most recent call last):
  File "train.py", line 48, in <module>
    import dllogger as DLLogger
ModuleNotFoundError: No module named 'dllogger'
Traceback (most recent call last):
  File "train.py", line 48, in <module>
Traceback (most recent call last):
  File "train.py", line 48, in <module>
    import dllogger as DLLogger
ModuleNotFoundError: No module named 'dllogger'
    import dllogger as DLLogger
ModuleNotFoundError: No module named 'dllogger'
Traceback (most recent call last):
  File "train.py", line 48, in <module>
    import dllogger as DLLogger
ModuleNotFoundError: No module named 'dllogger'

**Comment by asulecki** [comment]
Take a look at the Dockerfile of Tacotron2/Waveglow - https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/SpeechSynthesis/Tacotron2/Dockerfile

You can install dllogger by running `pip install  'git+https://github.com/NVIDIA/dllogger'`
