### ISSUE TITLE
[Bert/TensorFlow] Problem with published GPU performance data

### ISSUE THREAD

**Issue by starkhu** [NVIDIA/DeepLearningExamples#359]
When we enter this directory--DeepLearningExamples/TensorFlow/LanguageModeling/BERT/, at the end, when listing the benchmark data under T4, the first three columns of the table [BERT BASE FP16] are strange: seq_len should be an integer such as 128,384, and batch_size should be 1, 2, 4, Such integers are now decimals.

**Comment by swethmandava** [comment]
Should be fixed in #344

**Comment by starkhu** [comment]
> Should be fixed in #344

Incorrect throughput-average provided

**Comment by starkhu** [comment]
now correct data provided.
