### ISSUE TITLE
[FasterTransformer] Run demo crash on P100

### ISSUE THREAD

**Issue by cklsoft** [NVIDIA/DeepLearningExamples#362]
Related to **FasterTransformer** 

**Describe the bug**

When executing the command on P100:

```CUDA_VISIBLE_DEVICES=1  python sample/tensorflow/transformer_fp32.py 1 12 32 12 64```

![image](https://user-images.githubusercontent.com/3956357/71707268-f9eccc00-2e23-11ea-9950-a284b5c76a33.png)

**To Reproduce**
1. cd build
2. cmake -DSM=60 -DCMAKE_BUILD_TYPE=Release -DBUILD_TF=ON -DTF_PATH=/path/to/python2.7/site-packages/tensorflow ..
3. make -j64
4. ./build/bin/gemm_fp32 1 12 32 12 64
5. CUDA_VISIBLE_DEVICES=1  python sample/tensorflow/transformer_fp32.py 1 12 32 12 64

**Environment**
Please provide at least:
* Container version: no use docker
* GPUs in the system: (e.g. 8x Tesla V100-SXM2-16GB): P100
* CUDA driver version (e.g. 418.67): 410.93
* CUDA version: 10
* GCC: 6.4.0
* cmake: 3.8.2

**Comment by IrishCoffee** [comment]
./build/bin/gemm_fp32 1 12 32 12 64 => ./build/bin/gemm_fp32 1 32 12 64

**Comment by cklsoft** [comment]
@IrishCoffee 
Hi, did FastTransformer support CUDA-9.0? I got  the following error when using CUDA-9.0.

![image](https://user-images.githubusercontent.com/3956357/74910041-8e22ea80-53f4-11ea-93f7-e05b85261aa0.png)

**Comment by byshiue** [comment]
We do not support the CUDA 9.0. We have added this limitation in the CMakeLists.txt. So, you should get error message when you use the cmake. 
The reason is because we use lots of instructions which are only supported after cuda 10.0.
