### ISSUE TITLE
inference.py - size mismatch for WN.*.in_layers.*

### ISSUE THREAD

**Issue by welliX** [NVIDIA/DeepLearningExamples#365]
We trained Tacotron2 + waveglow on a GTX 980 (4GB). However we needed to adjust some parameters in order to make it possible to run on this weak GPU - finally the training ran with following parameters different from the default ones:

scripts/train_tacotron2.sh: python -m multiproc train.py -m Tacotron2 -o ./output/ -lr 1e-3 --epochs 1501 -bs  24 --weight-decay 1e-6 --grad-clip-thresh 1.0 --cudnn-enabled --log-file ./output/nvlog.json --anneal-steps 200 500 1000 1500 --anneal-factor 0.1 --amp-run
i.e. '-bs 128' was reduced to '-bs 24'

scripts/train_waveglow.sh: python train.py -m WaveGlow -o ./output/ -lr 1e-4 --epochs 1001 -bs 8 --segment-length 8000 --wn-channels 128 --weight-decay 0 --grad-clip-thresh 65504.0 --cudnn-enabled --cudnn-benchmark --log-file ./output/nvlog.json --training-files filelists/ljs_audio_text_train_filelist.txt --amp-run
i.e. i.e. '-bs 8 --wn-channels 128' instead '-m multiproc -bs 10'

However if we now do inference with the checkpoint models using scripts/docker/interactive.sh an error is thrown due to shape mismatch (by a factor of 4, see below).
May the different values of training parameters (above) be the case for that?
Is there a means to transform into the right format?
Many thanks for any help!!

------------------------------------------------------------------------------------

> :::NVLOGv0.2.2 Tacotron2_PyT 1578392274.934190035 (/workspace/tacotron2/dllogger/logger.py:251) cpu_info: {"num": 8, "name": "Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz"}
:::NVLOGv0.2.2 Tacotron2_PyT 1578392274.939444542 (/workspace/tacotron2/dllogger/logger.py:251) mem_info: {"ram": "15G"}
:::NVLOGv0.2.2 Tacotron2_PyT 1578392275.044200182 (/workspace/tacotron2/dllogger/logger.py:251) gpu_info: {"driver_version": "418.87.01", "num": 1, "name": ["GeForce GTX 980"], "mem": ["4035 MiB"]}
:::NVLOGv0.2.2 Tacotron2_PyT 1578392275.044880867 (/workspace/tacotron2/dllogger/logger.py:251) args: {"input": "phrases/phrase.txt", "output": "output", "tacotron2": "output_tacotron_3/checkpoint_Tacot
ron2_550", "waveglow": "output_waveglow/checkpoint_WaveGlow_950", "sigma_infer": 0.9, "denoising_strength": 0.01, "sampling_rate": 22050, "amp_run": true, "log_file": "nvlog.json", "include_warmup": tru
e, "stft_hop_length": 256}
Selected optimization level O3:  Pure FP16 training.
Defaults for this optimization level are:
enabled                : True
opt_level              : O3
cast_model_type        : torch.float16
patch_torch_functions  : False
keep_batchnorm_fp32    : False
master_weights         : False
loss_scale             : 1.0
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O3
cast_model_type        : torch.float16
patch_torch_functions  : False
keep_batchnorm_fp32    : False
master_weights         : False
loss_scale             : 1.0
Traceback (most recent call last):
  File "inference.py", line 271, in <module>
    main()
  File "inference.py", line 217, in main
    args.amp_run)
  File "inference.py", line 126, in load_and_setup_model
    model.load_state_dict(state_dict)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 837, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for WaveGlow:
        size mismatch for WN.0.in_layers.0.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for WN.0.in_layers.0.weight_g: copying a param with shape torch.Size([256, 1, 1]) from checkpoint, the shape in current model is torch.Size([1024, 1, 1]).
        size mismatch for WN.0.in_layers.0.weight_v: copying a param with shape torch.Size([256, 128, 3]) from checkpoint, the shape in current model is torch.Size([1024, 512, 3]).
        size mismatch for WN.0.in_layers.1.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for WN.0.in_layers.1.weight_g: copying a param with shape torch.Size([256, 1, 1]) from checkpoint, the shape in current model is torch.Size([1024, 1, 1]).
........
.....

**Comment by GrzegorzKarchNV** [comment]
for the inference script, you also need to specify `--wn-channels 128`, otherwise the script assumes the default value of 512. does it help?

**Comment by welliX** [comment]
> for the inference script, you also need to specify `--wn-channels 128`, otherwise the script assumes the default value of 512. does it help?

Cool that was it - didn't expect it to be so easy, since --wn-channels wans't mentioned in the help message I didn't try it ;-)
Many thanks!!
Next steps I plan is to adapt the Tacotron2 + waveglow nets to a completely new voice. Don't know how to do it yet, and will open a new thread here, but maybe you have a hint how to maybe achieve this...??
thanks again!

**Comment by GrzegorzKarchNV** [comment]
happy it works :)

to get a new voice from Tacotron2+WaveGlow you would need a dataset with different speaker, like [this](https://arxiv.org/pdf/1904.02882.pdf).
I think you might be also interested in [NVIDIA's Mellotron](https://nv-adlr.github.io/Mellotron) that can modulate voice conditioned on audio samples.

**Comment by EuphoriaCelestial** [comment]
@GrzegorzKarchNV I got similar error when try to run `exports/export_tacotron2_onnx.py`
`Traceback (most recent call last):
  File "exports/export_tacotron2_onnx.py", line 415, in <module>
    main()
  File "exports/export_tacotron2_onnx.py", line 298, in main
    tacotron2 = load_and_setup_model('Tacotron2', parser, args.tacotron2, False)
  File "./inference.py", line 117, in load_and_setup_model
    model.load_state_dict(state_dict)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Tacotron2:
	size mismatch for embedding.weight: copying a param with shape torch.Size([185, 512]) from checkpoint, the shape in current model is torch.Size([148, 512]).
`
I trained my own tacotron2 model, that why it has diffirent size, what do I need to change in order to run this convert script?
