### ISSUE TITLE
It cause precision error issue after removing add_QKV_bias in FasterTransformer

### ISSUE THREAD

**Issue by zhoushan2186new** [NVIDIA/DeepLearningExamples#367]
Related to **Model/Framework(s)** 
*( FasterTransformer)*

**Describe the bug**
When we set qkv "use_bias=False" in python code, and removing cuda kernel function“add_QKV_bias” from fastertransformer/cuda/open_attention.cu, it would cause precision issue in float32 mode. 
Here is the cross check result before and after remove qkv bias.
Original :
 #################################
cross_check False
max diff 4.027567-06
min diff 0.0
After removing qkv bias:
 #################################
cross_check False
max diff 0.0012447834
min diff 0.0
If ran in float16 mode, the precision error is even bigger.
**To Reproduce**
Need to modify the code of open_attention.cu,open_attention.h,bert_transformer_op.cc  and transformer_fp32.py,etc.

**Expected behavior**
Is there any tips about the reason why this happen? Or Is there any suggestions to avoid?

**Environment**
* Container version (nvcr.io/nvidia/tensorflow:19.10-py3):
* GPUs in the system: ( Tesla V100-SXM2-16GB):
* CUDA driver version ( 418.67):

**Comment by IrishCoffee** [comment]
We fused the transpose operation in this kernel. Not only adding bias.
