### ISSUE TITLE
Option for pre-processing JSUT data

### ISSUE THREAD

**Issue by Arafat4341** [NVIDIA/DeepLearningExamples#370]
Hello! I want to train this implementation of tacotron-2 on jsut data. Is it possible?

**Comment by GrzegorzKarchNV** [comment]
Hi @Arafat4341, we haven't tested it yet but you would need a transliteration cleaner that would transform the Japanese alphabet to ASCII. Since there are a few requests about JSUT dataset, we're planning to enhance our reposotory with the possibility to train on non-English datasets. Stay tuned!
