### ISSUE TITLE
PyTorch Tacotron2 TRT inference latancy is larger than PyTorch native

### ISSUE THREAD

**Issue by un-knight** [NVIDIA/DeepLearningExamples#371]
**Model && Framework(s)**
- PyTorch Tacotron2

**Is your feature request related to a problem? Please describe.**
I compared the latency of pytorch tacotron2, torchscirpt tacotron2 and TRT tacotron2 in the some environment, and surprisingly found that TRT tacotron2 is the slowest one which is really stranger. The following table shows the testing benchmark.

> Tacotron2 TRT engine was exported with default shapes config.

|  | Input size | Tacotron2 latency (s) | Speedup | Precision |
| --- | --- | --- | --- | ---- | 
| PyT + TRT | (1, 167) | 0.908438 | 0.74 | FP32 |
| TS | (1, 167) | 0.527418 | 1.28 | FP32 |
| PyT | (1, 167) | 0.673284 | 1.0 | FP32 |

- PyT + TRT: PyTorch and TensorRT
- TS: TorchScript only
- PyT: PyTorch only

**Describe the solution you'd like**
I think there may be two reasons caused the result:
1. The optimum input config when export ONNX to TRT is (1, 128), while testing input is (1, 167) which may hurt the TRT performance.
2. Translation between pytorch tensor and TRT data causes an overhead, especially during decoder iteration step. 

So I want to get some suggestions to improve TRT tacotron2 performance, thanks!

**Comment by GrzegorzKarchNV** [comment]
Hi @un-knight what is the GPU you are using?
Generally, you should see best PyT+TRT performance in mixed precision setting (i.e., with `--fp16` flag)
