### ISSUE TITLE
[SSD/PyTorch] cannot format image into tensor from uris

### ISSUE THREAD

**Issue by I-M-Russell** [NVIDIA/DeepLearningExamples#372]
Related to **SSD/PyTorch** 
*(e.g. GNMT/PyTorch or FasterTransformer/All)*

**Describe the bug**
When prepare input images for object detection.

**To Reproduce**
1. running [SSD|PyTorch](https://pytorch.org/hub/nvidia_deeplearningexamples_ssd/) with Google Colab
2. following instruction
2. Launch `uris = [
    'http://images.cocodataset.org/val2017/000000397133.jpg',
    'http://images.cocodataset.org/val2017/000000037777.jpg',
    'http://images.cocodataset.org/val2017/000000252219.jpg'
]` and 
`inputs = [utils.prepare_input(uri) for uri in uris]
tensor = utils.prepare_tensor(inputs, precision == 'fp16')`

**Expected behavior**
it will produce a error like that:

`AttributeError                            Traceback (most recent call last)
<ipython-input-7-02bda5dcfeab> in <module>()
----> 1 inputs = [utils.prepare_input(uri) for uri in uris]
      2 tensor = utils.prepare_tensor(inputs, precision == 'fp16')

2 frames
<ipython-input-7-02bda5dcfeab> in <listcomp>(.0)
----> 1 inputs = [utils.prepare_input(uri) for uri in uris]
      2 tensor = utils.prepare_tensor(inputs, precision == 'fp16')

/root/.cache/torch/hub/NVIDIA_DeepLearningExamples_torchhub/hubconf.py in prepare_input(img_uri)
    282         @staticmethod
    283         def prepare_input(img_uri):
--> 284             img = Processing.load_image(img_uri)
    285             img = Processing.rescale(img, 300, 300)
    286             img = Processing.crop_center(img, 300, 300)

/root/.cache/torch/hub/NVIDIA_DeepLearningExamples_torchhub/hubconf.py in load_image(image_path)
    235         def load_image(image_path):
    236             """Code from Loading_Pretrained_Models.ipynb - a Caffe2 tutorial"""
--> 237             img = skimage.img_as_float(skimage.io.imread(image_path))
    238             if len(img.shape) == 2:
    239                 img = np.array([img, img, img]).swapaxes(0, 2)

AttributeError: module 'skimage' has no attribute 'io'`

**Environment**
Please provide at least:
* Container version (e.g. pytorch:1.3.1-py3.6):
* GPUs in the system: (e.g. 1x Tesla P100-PCIE-16GB):
* CUDA driver version (e.g. 418.67):

**Comment by bakeryproducts** [comment]
@I-M-Russell 
skimage.io is a submodule, you can try to import it explicitly
`import skimage.io`
`import skimage.transform #same reason`
`inputs = [utils.prepare_input(uri) for uri in uris]`
