### ISSUE TITLE
Typo in step 3 in the quickstart guide for MXNet

### ISSUE THREAD

**Issue by grzywada** [NVIDIA/DeepLearningExamples#379]
The quick start guide that can be found here: https://github.com/NVIDIA/DeepLearningExamples/tree/master/MxNet/Classification/RN50v1.5#quick-start-guide

 has a typo. In step 3 it says:
nvidia-docker run --rm -it --ipc=host <path to dataset>:/data/imagenet/train-val-recordio-passthrough nvidia_rn50_mx

The -v option is missing. It should be:
nvidia-docker run --rm -it --ipc=host -v <path to dataset>:/data/imagenet/train-val-recordio-passthrough nvidia_rn50_mx

**Comment by nvpstr** [comment]
We will be updating RN50 in MxNet soon. Stay tuned.
