### ISSUE TITLE
Incorrect instructions in the quickstart guide for pytorch resnet 50

### ISSUE THREAD

**Issue by grzywada** [NVIDIA/DeepLearningExamples#380]
The fith step in the quickstart guide that can be found here: https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Classification/ConvNets/resnet50v1.5#quick-start-guide

says that to run the training we should execute:
 ./resnet50v1.5/training directory called ./resnet50v1.5/training/{DGX1, DGX2}_RN50_{AMP, FP16, FP32}_{50,90,250}E.sh.

Those files are not in this folder but a level deeper in the folder hierarchy.

**Comment by asulecki** [comment]
Thanks! Will be fixed in next release.
