### ISSUE TITLE
[Tensorflow-Detection-SSD] what for an arbitary resolution pic which could not be resized to 320*320 

### ISSUE THREAD

**Issue by vxgu86** [NVIDIA/DeepLearningExamples#384]
Related to **Tensorflow-Detection-SSD** 
the input pic is Decreased the input size to 320 x 320
for example, if I am processing pics of 1024*768 resolution, and the pics could not be resized to such a small resolution of 320*320, what should I do to handle this?

**Comment by skierat** [comment]
You can modify fixed_shape_resizer in the config. New sizes should be multiplication of 32.
Please note that the image is randomly cropped first and then resized so maybe 320x320 is not a bad choice.

**Comment by vxgu86** [comment]
thanks I will try.
for example,if the input image is 1024*768, it will be cropped and resized into many mages of 320*320?
I did find this in the SSD code, I will try again

**Comment by vxgu86** [comment]
@skierat thanks

**Comment by vxgu86** [comment]
and, why the resolution changed to 320*320 from 640*640,
is it for accuracy or the time issue?

**Comment by vxgu86** [comment]
@skierat I think the resolution should be as larger as possible, so as to take enough features, why the resolu here is decreased?

**Comment by skierat** [comment]
Yes, each image will be cropped many times and each crop will be resized to 320x320 (in default config). If you set resolution too high (e.g higher then original size) then your crop will be upscaled most of the time what is not very helpful.

In general this is a trade-off. The higher the resolution the more computation and more GPU memory is needed. But with higher resolution you can expect higher accuracy to some extend.
In original SSD paper they use 300x300 resolution. We chose 320x320. But this is just an example so you can adjust the config to your needs.
