### ISSUE TITLE
[Tensorflow/LanguageModelling/BERT] Step is incremented incorrectly in LAMB optimizer

### ISSUE THREAD

**Issue by TIXFeniks** [NVIDIA/DeepLearningExamples#391]
Related to **Model/Framework(s)** 
Tensorflow/LanguageModelling/BERT LAMB optimizer

**Describe the bug**
On [this](https://github.com/NVIDIA/DeepLearningExamples/blob/ad88003e13b1dc92f00a3fabb4ee126dc31d7e97/TensorFlow/LanguageModeling/BERT/optimization.py#L346) line the step is incremented every time the new variable is updated but it is supposed to be the global step 
which leads to incorrect bias correction.

**Comment by swethmandava** [comment]
Fixed in #395 . Thanks for filing the issue :)
