### ISSUE TITLE
BERT Inference Benchmark - TensorRT fails to build engine due to attribute error

### ISSUE THREAD

**Issue by keithachorn-intel** [NVIDIA/DeepLearningExamples#396]
The relevant BERT inference example code is here: [Link](https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/LanguageModeling/BERT/trt) 

Framework: TensorRT (compiled from TensorFlow)
Workload: BERT Inference

**Describe the bug**

Steps to reproduce:
1) Build and launch the NGC container (No issue)
2) Download the pre-trained model using scripts/download_model.sh (No issue)
3) [ERROR HERE] Build the TensorRT engine using builder.py (or indirectly via inference_benchmark.sh.

The error is as follows (the relevant error is: **AttributeError: 'NoneType' object has no attribute 'create_plugin'**):
```
Traceback (most recent call last):
  File "builder.py", line 420, in <module>
    main()
  File "builder.py", line 410, in main
    with build_engine(args.batch_size, args.sequence_length, config, weights_dict) as engine:
  File "builder.py", line 348, in build_engine
    fn = emln_plg_creator.create_plugin("embeddings", pfc)
AttributeError: 'NoneType' object has no attribute 'create_plugin'
Traceback (most recent call last):
  File "perf.py", line 124, in <module>
    main()
  File "perf.py", line 38, in main
    with open(args.engine, 'rb') as f, trt.Runtime(TRT_LOGGER) as runtime, runtime.deserialize_cuda_engine(f.read()) as engine, engine.create_execution_context() as default_context:
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/bert/engines/bert_large_fp16_bs32_seqlen128_benchmark.engine'
```
I've re-run the steps including re-building the Docker image, but resulting in the same error.

**Comment by pranavm-nvidia** [comment]
Hi, usually this happens when the plugins haven't been built correctly. Which GPU are you using? Currently, the plugins are written for Volta and newer (Compute Capability 7.0+)

**Comment by keithachorn-intel** [comment]
I built the 'bert' container built using the included script (based off of the TF NGC container), and tried running on both G4 and V100 (via AWS) with the same error.

I see that there are separate TensorRT and 'TensorRT Inference Server' containers available as well.  Should these make a difference?

**Comment by pranavm-nvidia** [comment]
Yes, you'd need to use the TensorRT container. You can find the instructions in the README: https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/LanguageModeling/BERT/trt#setup
