### ISSUE TITLE
Without docker?

### ISSUE THREAD

**Issue by yimjinkyu1** [NVIDIA/DeepLearningExamples#40]
Can I test these example using tensorflow2.0 alpha without ngc docker ?

**Comment by nvpstr** [comment]
Currently I am afraid the answer is "no". We are planning to deliver TF2 examples and containers soon.

**Comment by jconwayNV** [comment]
We don't officially support that route yet but are working on it, as @nvpstr mentioned.

Unofficially and not a supported path, you should be able to use the compat library in TF 2.0 alpha with our TF examples and match your library versions to our NGC container software stack: https://docs.nvidia.com/deeplearning/dgx/support-matrix/index.html
