### ISSUE TITLE
Checkpoint migration

### ISSUE THREAD

**Issue by m0n0l0c0** [NVIDIA/DeepLearningExamples#400]
Hello! 

Would it be possible to migrate checkpoints from other BERT models to work with your codebase?

Taking RobBERT (dutch BERT model) for instance and load it with your BERT code?
I see a problem with precision, maybe there is some way to convert the checkpoint to FP16 or FP32 precision?

Best :)

**Comment by swethmandava** [comment]
You should be able to load checkpoints for RoBERTa. Can you attach logs in case of failure? Thanks!

**Comment by m0n0l0c0** [comment]
Okay, I'll try and post here if anything arises.

Thanks!

**Comment by ZLKong** [comment]
Hi,

I tried to run run_glue.py with Roberta checkpoints,  but the accuracy is very low. Do you know how to fix it? 

I think I have to change the model loading part from BERT to RoBERT, but I am not sure how to do it. For example:
tokenizer = BertTokenizer(args.vocab_file, do_lower_case=args.do_lower_case, max_len=512)
model = BertForSequenceClassification(config, num_labels=num_labels)


Thanks!
ZLK
