### ISSUE TITLE
How to build the docker image with a specific Mellanox OFED version

### ISSUE THREAD

**Issue by vilmara** [NVIDIA/DeepLearningExamples#424]
Related to **Model/Framework(s) or something else (describe)** 
/DeepLearningExamples/TensorFlow/Classification/RN50v1.5/

**Describe the solution you'd like**
Hi all, how can I install a specific  Mellanox OFED version and overwrite the default MOFED driver version 4.4-1.0.0. included in the Dockerfile?

**Describe alternatives you've considered**
I have modified the Dockerfile as shown below but the docker image is built with version 4.4-1.0.0. instead of  4.7-3
```
FROM nvcr.io/nvidia/tensorflow:19.10-py3

RUN apt-get update

# Download and install Mellanox OFED 4.7-3 with the below commands:
RUN apt-get update && apt-get install -y lsb-core
RUN wget http://www.mellanox.com/downloads/ofed/MLNX_OFED-4.7-3.2.9.0/MLNX_OFED_LINUX-4.7-3.2.9.0-ubuntu18.04-x86_64.tgz && \
    tar -xzvf MLNX_OFED_LINUX-4.7-3.2.9.0-ubuntu18.04-x86_64.tgz && \
    MLNX_OFED_LINUX-4.7-3.2.9.0-ubuntu18.04-x86_64/mlnxofedinstall --user-space-only --without-fw-update --all -q --force && \
    cd .. && \
    rm -rf MLNX_OFED_LINUX-4.7-3.2.9.0-ubuntu18.04-x86_64 && \
    rm -rf *.tgz 
RUN apt-get install dkms -y    

ADD . /workspace/rn50v15_tf
WORKDIR /workspace/rn50v15_tf
RUN pip install -r requirements.txt
```

**Comment by nluehr** [comment]
The container includes several MOFED versions, and tries to detect and match the lib version to what is provided by the host OS. This is done in the entrypoint script `/usr/local/bin/nvidia_entrypoint.sh` .

The 19.10 container includes support for the following MOFED versions:
3.4-1.0.0  4.0-1.0.1  4.0-2.0.2  4.2-1.0.0  4.3-1.0.1  4.4-1.0.0  4.5-1.0.1  5.0-0
3.4-2.0.0  4.0-2.0.0  4.1-1.0.2  4.2-1.2.0  4.3-3.0.2  4.4-2.0.7  4.6-1.0.1  5.0-1.1.8

The latest 20.02-tf1 container adds 4.7-1.0.0 and 4.7-3.2.9 support as well.

If you want to add support for newer MOFED versions to older containers, you should be able to just add the debs to the `/opt/mellanox/DEBS/` directory.

**Comment by vilmara** [comment]
Thanks, working!
