### ISSUE TITLE
[Model] Got bad performance on BERT pre-train

### ISSUE THREAD

**Issue by dawanqu-ai** [NVIDIA/DeepLearningExamples#427]
Hi friends, I need some help. I downloaded the wikipedia and bookcorpus for pre-training BERT large model. I did the same data preprocessing and pre-training task as create_datasets_from_start.sh and run_pretraining.sh, using SQuAD v1.1 to evaluating the performance of model. I pre-trained several times and the results about SQuAD v1.1 f1 score and Exact Match are 90.35/83.54, 89.79/83.26, 1%~2% lower than the scores reported in the readme:
f1/EM(mean)=91.08/84.30  f1/EM(max)=91.29/84.50  f1/EM(min)=90.85/84.17
I'm confused and need help.

**Comment by swethmandava** [comment]
is this in TensorFlow or PyTorch? Could you attach a sample log, please?

**Comment by dawanqu-ai** [comment]
This is in PyTorch. I reset the dup of pretrain data as 10, it got better performance.
