### ISSUE TITLE
there is no act_type in gluon.nn.BatchNorm

### ISSUE THREAD

**Issue by ShawnXuan** [NVIDIA/DeepLearningExamples#429]
https://github.com/NVIDIA/DeepLearningExamples/blob/e663119b51c9460c1632d2169b00fc014c29aea1/MxNet/Classification/RN50v1.5/models.py#L121

I got an error
```
TypeError: __init__() got an unexpected keyword argument 'act_type'
```
And then check API here: https://mxnet.incubator.apache.org/api/python/docs/api/gluon/nn/index.html?highlight=batchnorm#mxnet.gluon.nn.BatchNorm

there is no `act_type` argument in gluon.nn.BatchNorm.

How can I fix it? 
Thanks!

**Comment by hXl3s** [comment]
Not valid anymore with last codebase, closing
