### ISSUE TITLE
Request: Add Horovod to PyTorch NGC

### ISSUE THREAD

**Issue by jarednielsen** [NVIDIA/DeepLearningExamples#430]
I use Horovod to train PyTorch distributed models. Currently I have to install it manually, would love it it came built-in and optimized. Others do the same, see for example https://github.com/horovod/horovod/issues/1706 .

**Describe the solution you'd like**
Add 
```code
RUN HOROVOD_NCCL_LINK=SHARED HOROVOD_NCCL_LIB=/usr/lib/x86_64-linux-gnu HOROVOD_NCCL_INCLUDE=/usr/include HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_GPU_BROADCAST=NCCL HOROVOD_WITH_PYTORCH=1 \
    pip install --no-cache-dir --upgrade horovod
```
to the PyTorch Dockerfile `nvcr.io/nvidia/pytorch:20.03-py3`. Thank you!

**Comment by mcarilli** [comment]
?? i don't maintain NGC.

**Comment by jarednielsen** [comment]
Updating my request slightly; maybe we can put horovod in `nvcr.io/nvidia/pytorch:21.03-py3` 😀

**Comment by ptrblck** [comment]
Thanks for the suggestion @jarednielsen.
We don't have the plan to ship horovod in the PyTorch NGC containers at the moment and will discuss it with our product management. :)
