### ISSUE TITLE
Missing -v in MXNet README.md

### ISSUE THREAD

**Issue by wohlbier** [NVIDIA/DeepLearningExamples#435]
In
https://github.com/NVIDIA/DeepLearningExamples/blob/master/MxNet/Classification/RN50v1.5/README.md

`nvidia-docker run --rm -it --ipc=host <path to dataset>:/data/imagenet/train-val-recordio-passthrough nvidia_rn50_mx`
should read
`nvidia-docker run --rm -it --ipc=host -v <path to dataset>:/data/imagenet/train-val-recordio-passthrough nvidia_rn50_mx`

Thanks.

**Comment by hXl3s** [comment]
Not related to the newest codebase anymore
