### ISSUE TITLE
Flag name typo in the TensorFlow BERT pretraining

### ISSUE THREAD

**Issue by vlarine** [NVIDIA/DeepLearningExamples#44]
There is a flag name typo:

`save_checkpoints_steps` in the python script and in the TensorFlow code:
https://github.com/NVIDIA/DeepLearningExamples/blob/master/TensorFlow/LanguageModeling/BERT/run_pretraining.py

`save_checkpoint_steps` in the bash script:
https://github.com/NVIDIA/DeepLearningExamples/blob/master/TensorFlow/LanguageModeling/BERT/scripts/run_pretraining.sh

**Comment by swethmandava** [comment]
Thanks for the find. Will fix and send an MR asap :)

**Comment by swethmandava** [comment]
#47
