### ISSUE TITLE
[Jasper Speech Recognition] Transfer learning to finetune the pretrained Jasper model

### ISSUE THREAD

**Issue by jeffxtang** [NVIDIA/DeepLearningExamples#443]
I can use [the pretrained Jasper checkpoint](https://ngc.nvidia.com/catalog/models/nvidia:jasperpyt_fp16) to make inference and the results are pretty good with general adult speech, but not good with young kids' speech. So I think I should try to finetune the pretrained model using custom training data to improve the inference results.

It looks like that one can do the transfer learning by generating custom train+val manifest json files, in the same format as librispeech-train/dev-*-wav.json, then modify the CHECKPOINT and train/val_manifest settings in train.sh.

Has anyone successfully completed the finetuning process? How long of the custom data and how many epochs of training would be needed to get good results?  Any shared experiences or suggestions would be appreciated! I'll also share my results with the steps above.

**Comment by borisgin** [comment]
take a look at fine-tuning tutorial in [`NeMo`](https://nvidia.github.io/NeMo/asr/tutorial.html#fine-tuning)

**Comment by alancucki** [comment]
NeMo docs linked @borisgin changed the location.

Updated links:
* [NeMo ASR tutorial](https://raw.githubusercontent.com/alancucki/NeMo/main/tutorials/asr/01_ASR_with_NeMo.ipynb)
* [NeMo docs](https://docs.nvidia.com/deeplearning/nemo/neural_mod_bp_guide/index.html#asr_guidance)
