### ISSUE TITLE
[FastTransformer/v2] Diff is too large when set initializer range of kernel to 1.0 and check fail

### ISSUE THREAD

**Issue by duduscript** [NVIDIA/DeepLearningExamples#449]
Related to **FastTransformer/v2** 
*decoder_sample.py check fail*

**Describe the bug**
when set kernel_initializer_range to 1.0, I run sample code decoder_op and tf_op diff is too large:
`
[[INFO][PYTHON] step:][0][max diff: ][4636.09277][ op val: ][-3438.58032][ tf val: ][1197.51221][False]
[[INFO][PYTHON] step:][1][max diff: ][5524.06885][ op val: ][665.730103][ tf val: ][6189.79883][False]
[[INFO][PYTHON] step:][2][max diff: ][5333.86133][ op val: ][-1368.53186][ tf val: ][3965.32959][False]
[[INFO][PYTHON] step:][3][max diff: ][4942.68359][ op val: ][770.13678][ tf val: ][-4172.54688][False]
[[INFO][PYTHON] step:][4][max diff: ][6546.04932][ op val: ][-4060.80591][ tf val: ][2485.24341][False]
[[INFO][PYTHON] step:][5][max diff: ][5354.49707][ op val: ][3385.18799][ tf val: ][-1969.30933][False]
[[INFO][PYTHON] step:][6][max diff: ][4938.32959][ op val: ][344.073914][ tf val: ][5282.40332][False]
[[INFO][PYTHON] step:][7][max diff: ][5159.90967][ op val: ][1452.45593][ tf val: ][-3707.45361][False]
[[INFO][PYTHON] step:][8][max diff: ][5422.49365][ op val: ][-776.318726][ tf val: ][-6198.8125][False]
[[INFO][PYTHON] step:][9][max diff: ][5085.0957][ op val: ][2174.49756][ tf val: ][-2910.59814][False]
[[INFO][PYTHON] step:][10][max diff: ][5290.83203][ op val: ][2352.96606][ tf val: ][-2937.86621][False]
[[INFO][PYTHON] step:][11][max diff: ][5093.19][ op val: ][3075.73096][ tf val: ][-2017.45898][False]
[[INFO][PYTHON] step:][12][max diff: ][4541.0166][ op val: ][-1558.33508][ tf val: ][2982.6814][False]
[[INFO][PYTHON] step:][13][max diff: ][4910.62793][ op val: ][-5652.39307][ tf val: ][-741.765076][False]
[[INFO][PYTHON] step:][14][max diff: ][4841.81934][ op val: ][-2403.61377][ tf val: ][2438.20581][False]
[[INFO][PYTHON] step:][15][max diff: ][5281.19336][ op val: ][1429.12317][ tf val: ][6710.31641][False]
[[INFO][PYTHON] step:][16][max diff: ][5133.98584][ op val: ][4647.65039][ tf val: ][-486.335571][False]
[[INFO][PYTHON] step:][17][max diff: ][5138.27734][ op val: ][-665.93219][ tf val: ][4472.34521][False]
[[INFO][PYTHON] step:][18][max diff: ][5018.10449][ op val: ][1155.98279][ tf val: ][-3862.12158][False]
[[INFO][PYTHON] step:][19][max diff: ][4955.55859][ op val: ][3181.61572][ tf val: ][-1773.94263][False]
[[INFO][PYTHON] step:][20][max diff: ][4838.26465][ op val: ][2272.82104][ tf val: ][-2565.44336][False]
[[INFO][PYTHON] step:][21][max diff: ][4755.60596][ op val: ][1524.34277][ tf val: ][-3231.26318][False]
[[INFO][PYTHON] step:][22][max diff: ][5201.05176][ op val: ][2830.48][ tf val: ][8031.53174][False]
[[INFO][PYTHON] step:][23][max diff: ][4388.0791][ op val: ][2772.51978][ tf val: ][-1615.55945][False]
[[INFO][PYTHON] step:][24][max diff: ][4075.31152][ op val: ][4369.94336][ tf val: ][294.631927][False]
[[INFO][PYTHON] step:][25][max diff: ][4468.19238][ op val: ][-2972.63623][ tf val: ][1495.55591][False]
[[INFO][PYTHON] step:][26][max diff: ][4011.56201][ op val: ][2344.0957][ tf val: ][-1667.46631][False]
[[INFO][PYTHON] step:][27][max diff: ][4704.7373][ op val: ][5699.88721][ tf val: ][995.150146][False]
[[INFO][PYTHON] step:][28][max diff: ][4042.48975][ op val: ][-1215.4502][ tf val: ][-5257.94][False]
[[INFO][PYTHON] step:][29][max diff: ][4311.31152][ op val: ][3930.74634][ tf val: ][-380.565033][False]
[[INFO][PYTHON] step:][30][max diff: ][4145.04785][ op val: ][1962.33728][ tf val: ][-2182.71045][False]
[[INFO][PYTHON] step:][31][max diff: ][4918.09082][ op val: ][2632.87817][ tf val: ][-2285.2124][False]
`

**To Reproduce**
1. enter docker and build fasttransformer
2. ./bin/decoding_gemm 32 4 8 64 30000 32 768 0
3. ./bin/decoding_sample 32 4 8 64 30000 32 6 768 0
4. set kernel_initializer_range to 1.0
5. python decoder_sample.py \
        --batch_size 32 \
        --beam_width 4 \
        --max_seq_len 32 \
        --head_number 8 \
        --size_per_head 64 \
        --memory_hidden_dim 768 \
        --num_layer 6 \
        --data_type fp32 \
        --decoder_type 2

**Expected behavior**

**Environment**
Please provide at least:
* docker: nvcr.io/nvidia/tensorflow:19.07-py2

**Comment by byshiue** [comment]
It is normal because the initialized range means the variance of normal distribution, so the random initialized weights would be large.
