### ISSUE TITLE
Error while running the pre-trained waveglow model on specific GPU device

### ISSUE THREAD

**Issue by harshbafna** [NVIDIA/DeepLearningExamples#450]
Related to **Model/Framework(s)** 
WaveGlow model for generating speech from mel spectrograms (generated by Tacotron2)

PyTorch/SpeechSynthesis/Tacotron2

**Describe the bug**
I am trying to execute the pre-trained waveglow example given here : https://pytorch.org/hub/nvidia_deeplearningexamples_waveglow/

The example works fine if executed as provided. However, it fails if I change the device from “cuda” to “cuda:1” with following error :

```
File "waveglow_example.py", line 76, in inference
    _, mel, _, _ = self.tacotron2_model.infer(data)
File "/home/ubuntu/.cache/torch/hub/nvidia_DeepLearningExamples_torchhub/PyTorch/SpeechSynthesis/Tacotron2/tacotron2/model.py", line 651, in infer
    encoder_outputs)
 File "/home/ubuntu/.cache/torch/hub/nvidia_DeepLearningExamples_torchhub/PyTorch/SpeechSynthesis/Tacotron2/tacotron2/model.py", line 546, in inference
    not_finished = not_finished*dec
RuntimeError: expected device cuda:0 but got device cuda:1
```

**To Reproduce**

1. Install latest pytorch for CUDA 10.1

```conda install pytorch torchvision cudatoolkit=10.1 -c pytorch```

2. Install dependecy packages 

```pip install numpy scipy librosa unidecode inflect librosa```

3. Run following script (only change from the above example is the device type as "cuda:1" instead of default cuda"

```
import torch
import numpy as np
from scipy.io.wavfile import write

waveglow = torch.hub.load('nvidia/DeepLearningExamples:torchhub', 'nvidia_waveglow')

waveglow = waveglow.remove_weightnorm(waveglow)
waveglow = waveglow.to('cuda:1')
waveglow.eval()

tacotron2 = torch.hub.load('nvidia/DeepLearningExamples:torchhub', 'nvidia_tacotron2')
tacotron2 = tacotron2.to('cuda:1')
tacotron2.eval()

text = "hello world, I missed you"

sequence = np.array(tacotron2.text_to_sequence(text, ['english_cleaners']))[None, :]
sequence = torch.from_numpy(sequence).to(device='cuda:1', dtype=torch.int64)

# run the models
_, mel, _, _ = tacotron2.infer(sequence)
audio = waveglow.infer(mel)
audio_numpy = audio[0].data.cpu().numpy()
rate = 22050

write("audio.wav", rate, audio_numpy)
```

**Expected behavior**
The example should run on all GPU devices

**Environment**
Please provide at least:
* Container version (e.g. pytorch:19.05-py3): Manually installed PyTorch using above given command on a fresh conda environment.
* 8 NVIDIA Tesla V100 GPUs (Using AWS p3.8xlarge instance type)
*  Driver Version: 440.33.01

**Comment by GrzegorzKarchNV** [comment]
Hi @harshbafna, the issue should be fixed now, please let me know if it works for you.

**Comment by harshbafna** [comment]
@GrzegorzKarchNV : Thank you, I will try this out and update.

**Comment by harshbafna** [comment]
@GrzegorzKarchNV : I verified the fix and this works fine on all GPU devices on.

**Comment by GrzegorzKarchNV** [comment]
Great! Closing the bug.
