### ISSUE TITLE
Problem while pulling nvidia docker

### ISSUE THREAD

**Issue by Kmarconi** [NVIDIA/DeepLearningExamples#451]
HI, 

I encountered the issue : unauthorized: authentication required while pulling the nvidia docker. Is it because i'm working on Xavier (JP 4.3) ? 

Regards

**Comment by pribalta** [comment]
@Kmarconi we will need a couple of clarifications:

1) What model are you using?
2) Do you have a user account in [https://ngc.nvidia.com/](NVIDIA GPU Cloud)?

**Comment by Kmarconi** [comment]
Hi, sorry for missing clarifications in my first message. I'm trying to use your SSD tensorflow example and for that, I need to docker pull the tensorflow container from NGC (Yes i have an account on it). But a long time ago, I do remember that there was some kind of a key which was needed to pull containers from ngc but i do not remember my key and where to find it and where to specialize it in my docker file. 

Thanks for the quick reply

**Comment by narankhuut** [comment]
Hi,
Go to https://ngc.nvidia.com/setup and generate your API key there. After that you login to nvcr.io with docker: 
```
docker login nvcr.io

Username: $oauthtoken
Password: <Your Key>
```
Here is a good [example](https://www.pugetsystems.com/labs/hpc/How-To-Setup-NVIDIA-Docker-and-NGC-Registry-on-your-Workstation---Part-4-Accessing-the-NGC-Registry-1115/).

**Comment by pribalta** [comment]
@Kmarconi please follow the steps indicated by @narankhuut. He is indeed... correct! :)

 Thank you very much for your contribution!

**Comment by Kmarconi** [comment]
Thanks !
