### ISSUE TITLE
Inference on multi GPU

### ISSUE THREAD

**Issue by narankhuut** [NVIDIA/DeepLearningExamples#465]
Hi, can there be an option to run BERT inference on multi GPUs? 
Benchmark [results ](https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/LanguageModeling/BERT/trt#benchmarking)were all obtained with single GPU. It would be accelerate performance for BERT Large engines, especially using mixed precision with large batch sizes and sequence lengths.
Thanks

**Comment by pmarcinkiewicz** [comment]
Pls consider using Triton inference server and GRPC load balancer to use multiple GPUs.

This folder contains readme for BERT running in Triton:
https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/LanguageModeling/BERT/triton
