### ISSUE TITLE
3 post-processing layer of Jasper

### ISSUE THREAD

**Issue by pooyafayyaz** [NVIDIA/DeepLearningExamples#473]
Hello all,
I was reading the Jasper paper and I realized that there are 3 layers for post-processing after the B*R layers, I understand that the last layer does something like softmax and it reduces the features to phonemes. but I can't understand what are the 2 previous layers and why the values are such as the paper described. 
I'm going to drop these three layers for sentiment analysis, Is it right to assume that the output of the B*R CNN's is the speech features?

**Comment by alancucki** [comment]
Hi @pooyafayyaz ,
sorry for a late reply. Have you managed to solve your issue by now?

I'm not aware of ablations done at the last layers. Lets name them (`n-2`, `n-1`, and `n`). The `n-2` layer has large kernel and stride 2 -- it significantly increases the receptive field. The `n-1` in my opinion is there to consolidate the context from `n-2`, and the `n`th layer projects into output graphemes. Conv networks for ASR do benefit from large context.

As for the applicability of features to other tasks - it would be best to test them empirically. The rough analogy from CNNs for images should apply - low-level, local features in the early layers, high-level and global in the later ones.
