### ISSUE TITLE
[Tacotron2/Pytorch] when Inference on tritis, model size and model configuration size is different

### ISSUE THREAD

**Issue by qen95** [NVIDIA/DeepLearningExamples#474]
Related to **Model/Framework(s)** 
Pytorch/SpeechSynthesis/Tacotron2/notebooks/trtis
**Describe the bug**
I followed all step of README.md in Pytorch/SpeechSynthesis/Tacotron2/notebooks/trtis
used pretrained data(Tacotron2: tacotron2_1032590_6000_amp, Waveglow: nvidia_waveglow256pyt_fp16)

just changing step in Setup WaveGlow TRT engine, I save engine name waveglow_fp16.engine not model.plan.
Also, In Dockerfile_tritis_client file  change versions which is already installed in my server
`RUN conda install -c conda-forge jupyterlab=1.1.4 ipywidgets=7.5.1 nodejs python-sounddevice librosa unidecode inflect`

During the steps, there are some warnings occurs
step: export_waveglow_onnx
`exports/export_waveglow_onnx.py:143: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
n_half = int(audio.size(1) / 2)
`

step: export_onnx2trt
`[TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] ERROR: (Unnamed Layer* 170) [Slice]: slice size must be positive, size = [0,0,0]
[TensorRT] WARNING: Calling isShapeTensor before the entire network is constructed may result in an inaccurate result.
[TensorRT] WARNING: Myelin graph with multiple dynamic values may have poor performance if they differ. Dynamic values are:  (# 0 (SHAPE sequences)) (# 1 (SHAPE sequences))
`
more warnings like these in export_onnx2trt

anyway It works 
and I can run the TRTIS notebook client. and get URL. of jupyterLab
but when I run notebook.ipynb in jupyterLab , error occurs

> ---------------------------------------------------------------------------
> InferenceServerException                  Traceback (most recent call last)
> <ipython-input-1-0f1abe8a54d8> in <module>
>     271 
>     272 # default text
> --> 273 text_area.value = "The forms of printed letters should be beautiful, and that their arrangement on the page should be reasonable and a help to the shapeliness of the letters themselves."
> 
> /opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py in __set__(self, obj, value)
>     583             raise TraitError('The "%s" trait is read-only.' % self.name)
>     584         else:
> --> 585             self.set(obj, value)
>     586 
>     587     def _validate(self, obj, value):
> 
> /opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py in set(self, obj, value)
>     572             # we explicitly compare silent to True just in case the equality
>     573             # comparison above returns something other than True/False
> --> 574             obj._notify_trait(self.name, old_value, new_value)
>     575 
>     576     def __set__(self, obj, value):
> 
> /opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py in _notify_trait(self, name, old_value, new_value)
>    1137             new=new_value,
>    1138             owner=self,
> -> 1139             type='change',
>    1140         ))
>    1141 
> 
> /opt/conda/lib/python3.7/site-packages/ipywidgets/widgets/widget.py in notify_change(self, change)
>     604                 # Send new state to front-end
>     605                 self.send_state(key=name)
> --> 606         super(Widget, self).notify_change(change)
>     607 
>     608     def __repr__(self):
> 
> /opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py in notify_change(self, change)
>    1174                 c = getattr(self, c.name)
>    1175 
> -> 1176             c(change)
>    1177 
>    1178     def _add_notifiers(self, handler, name, type):
> 
> <ipython-input-1-0f1abe8a54d8> in text_area_change(change)
>     235         display_heatmap(sequence)
>     236     # run tacotron2
> --> 237     mel, mel_lengths, alignments = sequence_to_mel(sequence)
>     238     with plot_spectrogram:
>     239         display_spectrogram(mel, change['new'])
> 
> <ipython-input-1-0f1abe8a54d8> in sequence_to_mel(sequence)
>     133     batch_size = 1
>     134     # call tacotron2
> --> 135     result = infer_ctx_tacotron2.run(input_dict, output_dict, batch_size)
>     136     # get results
>     137     mel = result['mel_outputs_postnet__0'][0] # take only the first instance in the output batch
> 
> /opt/conda/lib/python3.7/site-packages/tensorrtserver/api/__init__.py in run(self, inputs, outputs, batch_size, flags, corr_id)
>    1515 
>    1516         # Run inference...
> -> 1517         self._last_request_id = _raise_if_error(c_void_p(_crequest_infer_ctx_run(self._ctx)))
>    1518 
>    1519         return self._get_results(outputs, batch_size)
> 
> /opt/conda/lib/python3.7/site-packages/tensorrtserver/api/__init__.py in _raise_if_error(err)
>     256         _crequest_error_del(err)
>     257         if not isok:
> --> 258             raise ex
>     259         return ex.request_id()
>     260     return 0
> 
> **InferenceServerException: [inference:0 11] output 'alignments__2' for model 'tacotron2' has shape [761] but model configuration specifies shape [-1,-1]**

just hard coding, I changed shape of alignments__2 in trtis_repo/tacotron2/config.pbtxt file but it occurs another error
`InferenceServerException: [inference:0 11] unexpected shape for output 'alignments__2', model configuration shape is [761], inference shape is [166,764]`

I want to check there are some problem to make onnx or trt engine.
So, I follow quickstart of Pytorch/SpeechSynthesis/Tacotron2 and Pytorch/SpeechSynthesis/Tacotron2/trt examples using same onnx and trt engine.
but both of them run well and I get proper wav file.
So, I think there are no problem in onnx and trt engine.

**To Reproduce**
1. Install '...'
2. Set "..."
2. Launch '...'

**Expected behavior**

**Environment**
Please provide at least:
* Container version (e.g. pytorch:19.05-py3): nvcr.io/nvidia/tensorrtserver:20.01-py3-clientsdk
* GPUs in the system: (e.g. 8x Tesla V100-SXM2-16GB): GeForce RTX 2080 Ti
* CUDA driver version (e.g. 418.67): CUDA Version 10.0.326

**Comment by qen95** [comment]
Even I get this result
**InferenceServerException: [inference:0 20] unexpected shape for output 'alignments__2', model configuration shape is [166,1], inference shape is [166,1]**

**Comment by GrzegorzKarchNV** [comment]
Hi @qen95 could you please update you repo to the latest Tacotron2 update? I've made a bunch of fixes, let's see if they solve your issue.

**Comment by qen95** [comment]
Thanks for your effort @GrzegorzKarchNV  .

I followed process in Pytorch/SpeechSynthesis/Tacotron2/notebooks/trtis/README.md.
But now I met different errors during the steps.
Firstly,  In Dockerfile_tritis_client file  

line 18:  ` WORKDIR /workspace/speech_ai_demo_TTS/ `
line 26:  `RUN cd /workspace/speech_ai_demo__TTS/ `

they have different number of underbar('_') and I change line 18 using two underbar('__') and it works.

Secondly, when I setup tacotron 2 TorchScript using Option 2 with nvidia_tacotron2pyt_fp16_20190427 and tacotron2_1032590_6000_amp (I tried both)

model.pt is well-generated, but it has problem in Run the TRTIS server step

I run TRTIS server using this code

`NV_GPU=0 nvidia-docker run -ti --ipc=host --network=host --rm -p8000:8000 -p8001:8001 -v $PWD/trtis_repo/:/models tensorrtserver:20.01 trtserver --model-store=/models --log-verbose 1`

but error occured on loading tacotron2 model

> ===============================
>
> == TensorRT Inference Server ==
> ===============================
>
> NVIDIA Release 20.01 (build 9326846)
>
> Copyright (c) 2018-2019, NVIDIA CORPORATION.  All rights reserved.
>
> Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
> NVIDIA modifications are covered by the license terms that apply to the underlying
> project or file.
>
> 2020-05-29 07:17:52.345690: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2
> I0529 07:17:52.375352 1 metrics.cc:162] found 1 GPUs supporting NVML metrics
> I0529 07:17:52.380776 1 metrics.cc:171]   GPU 0: GeForce RTX 2080 Ti
> I0529 07:17:52.380925 1 server.cc:112] Initializing TensorRT Inference Server
> I0529 07:17:52.519951 1 pinned_memory_manager.cc:194] Pinned memory pool is created at '0x7fea56000000' with size 268435456
> I0529 07:17:52.520226 1 graphdef_backend_factory.cc:48] Create GraphDefBackendFactory
> I0529 07:17:52.520238 1 savedmodel_backend_factory.cc:48] Create SavedModelBackendFactory
> I0529 07:17:52.520248 1 netdef_backend_factory.cc:46] Create NetDefBackendFactory
> I0529 07:17:52.520257 1 plan_backend_factory.cc:48] Create PlanBackendFactory
> I0529 07:17:52.520264 1 plan_backend_factory.cc:55] Registering TensorRT Plugins
> I0529 07:17:52.520294 1 logging.cc:52] Plugin creator registration succeeded - ::GridAnchor_TRT
> I0529 07:17:52.520306 1 logging.cc:52] Plugin creator registration succeeded - ::NMS_TRT
> I0529 07:17:52.520319 1 logging.cc:52] Plugin creator registration succeeded - ::Reorg_TRT
> I0529 07:17:52.520326 1 logging.cc:52] Plugin creator registration succeeded - ::Region_TRT
> I0529 07:17:52.520336 1 logging.cc:52] Plugin creator registration succeeded - ::Clip_TRT
> I0529 07:17:52.520347 1 logging.cc:52] Plugin creator registration succeeded - ::LReLU_TRT
> I0529 07:17:52.520360 1 logging.cc:52] Plugin creator registration succeeded - ::PriorBox_TRT
> I0529 07:17:52.520372 1 logging.cc:52] Plugin creator registration succeeded - ::Normalize_TRT
> I0529 07:17:52.520388 1 logging.cc:52] Plugin creator registration succeeded - ::RPROI_TRT
> I0529 07:17:52.520397 1 logging.cc:52] Plugin creator registration succeeded - ::BatchedNMS_TRT
> I0529 07:17:52.520408 1 logging.cc:52] Plugin creator registration succeeded - ::FlattenConcat_TRT
> I0529 07:17:52.520416 1 logging.cc:52] Plugin creator registration succeeded - ::CropAndResize
> I0529 07:17:52.520424 1 logging.cc:52] Plugin creator registration succeeded - ::DetectionLayer_TRT
> I0529 07:17:52.520435 1 logging.cc:52] Plugin creator registration succeeded - ::Proposal
> I0529 07:17:52.520446 1 logging.cc:52] Plugin creator registration succeeded - ::ProposalLayer_TRT
> I0529 07:17:52.520455 1 logging.cc:52] Plugin creator registration succeeded - ::PyramidROIAlign_TRT
> I0529 07:17:52.520465 1 logging.cc:52] Plugin creator registration succeeded - ::ResizeNearest_TRT
> I0529 07:17:52.520474 1 logging.cc:52] Plugin creator registration succeeded - ::Split
> I0529 07:17:52.520485 1 logging.cc:52] Plugin creator registration succeeded - ::SpecialSlice_TRT
> I0529 07:17:52.520499 1 logging.cc:52] Plugin creator registration succeeded - ::InstanceNormalization_TRT
> I0529 07:17:52.520510 1 onnx_backend_factory.cc:53] Create OnnxBackendFactory
> I0529 07:17:52.524302 1 libtorch_backend_factory.cc:46] Create LibTorchBackendFactory
> I0529 07:17:52.524318 1 custom_backend_factory.cc:46] Create CustomBackendFactory
> I0529 07:17:52.524325 1 ensemble_backend_factory.cc:47] Create EnsembleBackendFactory
> I0529 07:17:52.525485 1 server_status.cc:55] New status tracking for model 'tacotron2'
> I0529 07:17:52.525499 1 server_status.cc:55] New status tracking for model 'waveglow'
> I0529 07:17:52.525528 1 model_repository_manager.cc:563] AsyncLoad() 'tacotron2'
> I0529 07:17:52.525541 1 model_repository_manager.cc:617] TriggerNextAction() 'tacotron2' version 1: 1
> I0529 07:17:52.525550 1 model_repository_manager.cc:655] Load() 'tacotron2' version 1
> I0529 07:17:52.525557 1 model_repository_manager.cc:675] loading: tacotron2:1
> I0529 07:17:52.525630 1 model_repository_manager.cc:563] AsyncLoad() 'waveglow'
> I0529 07:17:52.525642 1 model_repository_manager.cc:617] TriggerNextAction() 'waveglow' version 1: 1
> I0529 07:17:52.525649 1 model_repository_manager.cc:655] Load() 'waveglow' version 1
> I0529 07:17:52.525628 1 model_repository_manager.cc:730] CreateInferenceBackend() 'tacotron2' version 1
> I0529 07:17:52.525670 1 model_repository_manager.cc:675] loading: waveglow:1
> I0529 07:17:52.525755 1 model_repository_manager.cc:730] CreateInferenceBackend() 'waveglow' version 1
> I0529 07:17:52.580942 1 libtorch_backend.cc:224] Creating instance tacotron2_0_gpu0 on GPU 0 (7.5) using model.pt
> I0529 07:17:52.607147 1 libtorch_backend.cc:66] ~LibTorchBackend::Context
> E0529 07:17:52.612112 1 model_repository_manager.cc:832] failed to load 'tacotron2' version 1: Internal: load failed for libtorch model -> 'tacotron2':
> Unexpected right-hand found in assignment in class body. This is not yet supported.:
> Serialized at code/__torch__/torch/nn/modules/sparse.py:5:25
>   training : bool
>   weight : Tensor
>   sparse : Final[bool] = False
>                          ~~~~~ <--- HERE
>   scale_grad_by_freq : Final[bool] = False
>   embedding_dim : Final[int] = 512
>
> I0529 07:17:52.612148 1 model_repository_manager.cc:617] TriggerNextAction() 'tacotron2' version 1: 0
> I0529 07:17:52.612156 1 model_repository_manager.cc:632] no next action, trigger OnComplete()
> I0529 07:17:52.961304 1 plan_backend.cc:272] Creating instance waveglow_0_gpu0 on GPU 0 (7.5) using waveglow_fp16.engine
> I0529 07:17:56.502373 1 logging.cc:52] Deserialize required 1943240 microseconds.
> I0529 07:17:56.509141 1 plan_backend.cc:409] Created instance waveglow_0_gpu0 on GPU 0 (7.5) with stream priority 0 and optimization profile default[0];
> I0529 07:17:56.509234 1 dynamic_batch_scheduler.cc:180] Starting dynamic-batch scheduler thread 0 at nice 5...
> I0529 07:17:56.509302 1 plan_backend.cc:159] plan backend for waveglow
> name=waveglow
> contexts:
>   name=waveglow_0_gpu0, gpu=0, max_batch_size=1
>   bindings:
>     0: max possible byte_size=266240, buffer=0x7fe98ec4de00 ]
>     1: max possible byte_size=851968, buffer=0x7fe98ec8ee00 ]
>     2: max possible byte_size=851968, buffer=0x7fe935e00000 ]
>
> I0529 07:17:56.526421 1 model_repository_manager.cc:829] successfully loaded 'waveglow' version 1
> I0529 07:17:56.526441 1 model_repository_manager.cc:617] TriggerNextAction() 'waveglow' version 1: 0
> I0529 07:17:56.526450 1 model_repository_manager.cc:632] no next action, trigger OnComplete()
> I0529 07:17:56.526510 1 model_repository_manager.cc:487] GetVersionStates() 'waveglow'
> I0529 07:17:56.526527 1 model_repository_manager.cc:487] GetVersionStates() 'tacotron2'
> I0529 07:17:56.526577 1 dynamic_batch_scheduler.cc:390] Stopping dynamic-batch scheduler thread 0...
> I0529 07:17:56.526622 1 plan_backend.cc:54] ~PlanBackend::Context
> I0529 07:17:56.534624 1 model_repository_manager.cc:806] OnDestroy callback() 'waveglow' version 1
> I0529 07:17:56.534635 1 model_repository_manager.cc:808] successfully unloaded 'waveglow' version 1
> I0529 07:17:56.534643 1 model_repository_manager.cc:617] TriggerNextAction() 'waveglow' version 1: 0
> error: creating server: INTERNAL - failed to load all models

So, I try other option to setup tacotron 2 torchScript which is option 1.

I rename nvidia_tacotron2pyt_jit_fp16 file to model.pt  and then success to run the trtis server and I can run the TRTIS notebook client.

​	cf) when I run notebook client, in README code is 

`docker run -it --rm --network=host --device /dev/snd:/dev/snd --device /dev/usb:/dev/usb speech_ai_tts_only:demo bash ./run_this.sh` 

​	but error was occured  `docker: Error response from daemon: error gathering device information while adding custom device "/dev/usb": no such file or directory.` 

​	so I remove "/dev/usb" and It works well

​	`docker run -it --rm --network=host --device /dev/snd:/dev/snd speech_ai_tts_only:demo bash ./run_this.sh`

But there are another errors occur.

In the first code run in notebook.ipynb, error is

>```
>---------------------------------------------------------------------------
>InferenceServerException                  Traceback (most recent call last)
><ipython-input-1-55c0db352a0e> in <module>
>    251 
>    252 # default text
>--> 253 text_area.value = "The forms of printed letters should be beautiful, and that their arrangement on the page should be reasonable and a help to the shapeliness of the letters themselves."
>
>/opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py in __set__(self, obj, value)
>    583             raise TraitError('The "%s" trait is read-only.' % self.name)
>    584         else:
>--> 585             self.set(obj, value)
>    586 
>    587     def _validate(self, obj, value):
>
>/opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py in set(self, obj, value)
>    572             # we explicitly compare silent to True just in case the equality
>    573             # comparison above returns something other than True/False
>--> 574             obj._notify_trait(self.name, old_value, new_value)
>    575 
>    576     def __set__(self, obj, value):
>
>/opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py in _notify_trait(self, name, old_value, new_value)
>   1137             new=new_value,
>   1138             owner=self,
>-> 1139             type='change',
>   1140         ))
>   1141 
>
>/opt/conda/lib/python3.7/site-packages/ipywidgets/widgets/widget.py in notify_change(self, change)
>    604                 # Send new state to front-end
>    605                 self.send_state(key=name)
>--> 606         super(Widget, self).notify_change(change)
>    607 
>    608     def __repr__(self):
>
>/opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py in notify_change(self, change)
>   1174                 c = getattr(self, c.name)
>   1175 
>-> 1176             c(change)
>   1177 
>   1178     def _add_notifiers(self, handler, name, type):
>
><ipython-input-1-55c0db352a0e> in text_area_change(change)
>    215         display_heatmap(sequence)
>    216     # run tacotron2
>--> 217     mel, mel_lengths, alignments = sequence_to_mel(sequence)
>    218     with plot_spectrogram:
>    219         display_spectrogram(mel, change['new'])
>
><ipython-input-1-55c0db352a0e> in sequence_to_mel(sequence)
>    133     batch_size = 1
>    134     # call tacotron2
>--> 135     result = infer_ctx_tacotron2.run(input_dict, output_dict, batch_size)
>    136     # get results
>    137     mel = result['mel_outputs_postnet__0'][0] # take only the first instance in the output batch
>
>/opt/conda/lib/python3.7/site-packages/tensorrtserver/api/__init__.py in run(self, inputs, outputs, batch_size, flags, corr_id, priority, timeout_us)
>   1587 
>   1588         # Run inference...
>-> 1589         self._last_request_id = _raise_if_error(c_void_p(_crequest_infer_ctx_run(self._ctx)))
>   1590 
>   1591         return self._get_results(outputs, batch_size)
>
>/opt/conda/lib/python3.7/site-packages/tensorrtserver/api/__init__.py in _raise_if_error(err)
>    258         _crequest_error_del(err)
>    259         if not isok:
>--> 260             raise ex
>    261         return ex.request_id()
>    262     return 0
>
>InferenceServerException: [inference:0 11] The output alignments__2 in the model configuration refers to an output index which doesn't exist. This model has 2 outputs
>```



After first run, rerun the code error is changed to

> ```
> ---------------------------------------------------------------------------
> InferenceServerException                  Traceback (most recent call last)
> <ipython-input-2-55c0db352a0e> in <module>
>     251 
>     252 # default text
> --> 253 text_area.value = "The forms of printed letters should be beautiful, and that their arrangement on the page should be reasonable and a help to the shapeliness of the letters themselves."
> 
> /opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py in __set__(self, obj, value)
>     583             raise TraitError('The "%s" trait is read-only.' % self.name)
>     584         else:
> --> 585             self.set(obj, value)
>     586 
>     587     def _validate(self, obj, value):
> 
> /opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py in set(self, obj, value)
>     572             # we explicitly compare silent to True just in case the equality
>     573             # comparison above returns something other than True/False
> --> 574             obj._notify_trait(self.name, old_value, new_value)
>     575 
>     576     def __set__(self, obj, value):
> 
> /opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py in _notify_trait(self, name, old_value, new_value)
>    1137             new=new_value,
>    1138             owner=self,
> -> 1139             type='change',
>    1140         ))
>    1141 
> 
> /opt/conda/lib/python3.7/site-packages/ipywidgets/widgets/widget.py in notify_change(self, change)
>     604                 # Send new state to front-end
>     605                 self.send_state(key=name)
> --> 606         super(Widget, self).notify_change(change)
>     607 
>     608     def __repr__(self):
> 
> /opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py in notify_change(self, change)
>    1174                 c = getattr(self, c.name)
>    1175 
> -> 1176             c(change)
>    1177 
>    1178     def _add_notifiers(self, handler, name, type):
> 
> <ipython-input-2-55c0db352a0e> in text_area_change(change)
>     215         display_heatmap(sequence)
>     216     # run tacotron2
> --> 217     mel, mel_lengths, alignments = sequence_to_mel(sequence)
>     218     with plot_spectrogram:
>     219         display_spectrogram(mel, change['new'])
> 
> <ipython-input-2-55c0db352a0e> in sequence_to_mel(sequence)
>     133     batch_size = 1
>     134     # call tacotron2
> --> 135     result = infer_ctx_tacotron2.run(input_dict, output_dict, batch_size)
>     136     # get results
>     137     mel = result['mel_outputs_postnet__0'][0] # take only the first instance in the output batch
> 
> /opt/conda/lib/python3.7/site-packages/tensorrtserver/api/__init__.py in run(self, inputs, outputs, batch_size, flags, corr_id, priority, timeout_us)
>    1587 
>    1588         # Run inference...
> -> 1589         self._last_request_id = _raise_if_error(c_void_p(_crequest_infer_ctx_run(self._ctx)))
>    1590 
>    1591         return self._get_results(outputs, batch_size)
> 
> /opt/conda/lib/python3.7/site-packages/tensorrtserver/api/__init__.py in _raise_if_error(err)
>     258         _crequest_error_del(err)
>     259         if not isok:
> --> 260             raise ex
>     261         return ex.request_id()
>     262     return 0
> 
> InferenceServerException: [inference:0 14] failed to run model 'tacotron2_0_gpu0
> ```

**Comment by GrzegorzKarchNV** [comment]
Hi @qen95 regarding:

> I run TRTIS server using this code
>
> NV_GPU=0 nvidia-docker run -ti --ipc=host --network=host --rm -p8000:8000 -p8001:8001 -v $PWD/trtis_repo/:/models tensorrtserver:20.01 trtserver --model-store=/models --log-verbose 1
> 
> but error occured on loading tacotron2 model

The Triton (previously TRTIS) version in the README was not updated after the recent changes in `Dockerfile_ctrtis_lient`. Please update your repo and see if it helps.
