### ISSUE TITLE
[Tacotron2/PyTorch] denoiser.py has .cuda() calls and cannot run on CPU

### ISSUE THREAD

**Issue by jfsantos** [NVIDIA/DeepLearningExamples#478]
denoiser.py has .cuda() calls for the stft and audio variables, which makes it not work when instantiated on CPU. 

**To Reproduce**
Instantiate a Denoiser module passing a Waveglow object stored on CPU 

**Expected behavior**
Denoiser would be instantiated on CPU. Instead, it is instantiated partly on the GPU and partly on the CPU (as some parts use the same device as for the Waveglow object passed as an argument).  

**Environment**
* pytorch:20.03-py3):
* GPUs in the system: 1xTesla V100
* CUDA driver version: 440.33.01

**Comment by GrzegorzKarchNV** [comment]
denoiser.py has now .cuda() calls only when cpu_run is not set:
https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/SpeechSynthesis/Tacotron2/waveglow/denoiser.py#L40
