### ISSUE TITLE
How to cite this code

### ISSUE THREAD

**Issue by forresti** [NVIDIA/DeepLearningExamples#479]
Related to **Model/Framework(s) or something else (describe)** 

*Examples:* 
* *GNMT/PyTorch* 
* *AMP* 
* *Tensorflow 2.0*
* *Jupyter notebooks*

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sharathts** [comment]
https://github.com/NVIDIA/DeepLearningExamples/issues/480#issuecomment-623735611
