### ISSUE TITLE
[PyTorch/BERT] How to cite this code?

### ISSUE THREAD

**Issue by forresti** [NVIDIA/DeepLearningExamples#480]
My collaborators and I are writing a paper where we make use of the `DeepLearningExamples/PyTorch/LanguageModeling/BERT` code from this repository. I am wondering if you have any instructions on how to cite this work. Here's what I currently have:

```
@misc{2020_deeplearningexamples,
  author = {NVIDIA},
  title = {Deep Learning Examples for Tensor Cores},
  year = {2020},
  note = {\url{https://github.com/NVIDIA/DeepLearningExamples}}
}
```

But, I am wondering...
* For the above citation, are there authors that I should list?
* Is there a paper or other write-up that I should also cite?

**Comment by sharathts** [comment]
```@misc{2020_deeplearningexamples,
  author = {NVIDIA},
  title = {Deep Learning Examples for Tensor Cores},
  year = {2020},
  note = {\url{https://github.com/NVIDIA/DeepLearningExamples/tree/#commit-hash/PyTorch/LanguageModeling/BERT}}
}
```
Updated the URL to be more specific, pointing to the repo with a commit-hash. Do make sure to replace #commit-hash in the URL with the one that was used.

**Comment by forresti** [comment]
Thanks!
