### ISSUE TITLE
[Tacontron2/pytorch] can not use it on jupyter note book

### ISSUE THREAD

**Issue by drawingsnow** [NVIDIA/DeepLearningExamples#481]
when i use

import torch
waveglow = torch.hub.load('nvidia/DeepLearningExamples:torchhub', 'nvidia_waveglow')

i get :

Downloading: "https://github.com/nvidia/DeepLearningExamples/archive/torchhub.zip" to /home/mist/.cache/torch/hub/torchhub.zip
---------------------------------------------------------------------------
CertificateError                          Traceback (most recent call last)
<ipython-input-2-78edd3125d26> in <module>
      1 import torch
----> 2 waveglow = torch.hub.load('nvidia/DeepLearningExamples:torchhub', 'nvidia_waveglow')

~/.local/lib/python3.6/site-packages/torch/hub.py in load(github, model, *args, **kwargs)
    359     kwargs.pop('verbose', None)
    360 
--> 361     repo_dir = _get_cache_or_reload(github, force_reload, verbose)
    362 
    363     sys.path.insert(0, repo_dir)

~/.local/lib/python3.6/site-packages/torch/hub.py in _get_cache_or_reload(github, force_reload, verbose)
    161         url = _git_archive_link(repo_owner, repo_name, branch)
    162         sys.stderr.write('Downloading: \"{}\" to {}\n'.format(url, cached_file))
--> 163         download_url_to_file(url, cached_file, progress=False)
    164 
    165         with zipfile.ZipFile(cached_file) as cached_zipfile:

~/.local/lib/python3.6/site-packages/torch/hub.py in download_url_to_file(url, dst, hash_prefix, progress)
    392     # We use a different API for python2 since urllib(2) doesn't recognize the CA
    393     # certificates in older Python
--> 394     u = urlopen(url)
    395     meta = u.info()
    396     if hasattr(meta, 'getheaders'):

/usr/lib/python3.6/urllib/request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    221     else:
    222         opener = _opener
--> 223     return opener.open(url, data, timeout)
    224 
    225 def install_opener(opener):

/usr/lib/python3.6/urllib/request.py in open(self, fullurl, data, timeout)
    524             req = meth(req)
    525 
--> 526         response = self._open(req, data)
    527 
    528         # post-process response

/usr/lib/python3.6/urllib/request.py in _open(self, req, data)
    542         protocol = req.type
    543         result = self._call_chain(self.handle_open, protocol, protocol +
--> 544                                   '_open', req)
    545         if result:
    546             return result

/usr/lib/python3.6/urllib/request.py in _call_chain(self, chain, kind, meth_name, *args)
    502         for handler in handlers:
    503             func = getattr(handler, meth_name)
--> 504             result = func(*args)
    505             if result is not None:
    506                 return result

/usr/lib/python3.6/urllib/request.py in https_open(self, req)
   1359         def https_open(self, req):
   1360             return self.do_open(http.client.HTTPSConnection, req,
-> 1361                 context=self._context, check_hostname=self._check_hostname)
   1362 
   1363         https_request = AbstractHTTPHandler.do_request_

/usr/lib/python3.6/urllib/request.py in do_open(self, http_class, req, **http_conn_args)
   1316             try:
   1317                 h.request(req.get_method(), req.selector, req.data, headers,
-> 1318                           encode_chunked=req.has_header('Transfer-encoding'))
   1319             except OSError as err: # timeout error
   1320                 raise URLError(err)

/usr/lib/python3.6/http/client.py in request(self, method, url, body, headers, encode_chunked)
   1252                 encode_chunked=False):
   1253         """Send a complete request to the server."""
-> 1254         self._send_request(method, url, body, headers, encode_chunked)
   1255 
   1256     def _send_request(self, method, url, body, headers, encode_chunked):

/usr/lib/python3.6/http/client.py in _send_request(self, method, url, body, headers, encode_chunked)
   1298             # default charset of iso-8859-1.
   1299             body = _encode(body, 'body')
-> 1300         self.endheaders(body, encode_chunked=encode_chunked)
   1301 
   1302     def getresponse(self):

/usr/lib/python3.6/http/client.py in endheaders(self, message_body, encode_chunked)
   1247         else:
   1248             raise CannotSendHeader()
-> 1249         self._send_output(message_body, encode_chunked=encode_chunked)
   1250 
   1251     def request(self, method, url, body=None, headers={}, *,

/usr/lib/python3.6/http/client.py in _send_output(self, message_body, encode_chunked)
   1034         msg = b"\r\n".join(self._buffer)
   1035         del self._buffer[:]
-> 1036         self.send(msg)
   1037 
   1038         if message_body is not None:

/usr/lib/python3.6/http/client.py in send(self, data)
    972         if self.sock is None:
    973             if self.auto_open:
--> 974                 self.connect()
    975             else:
    976                 raise NotConnected()

/usr/lib/python3.6/http/client.py in connect(self)
   1413 
   1414             self.sock = self._context.wrap_socket(self.sock,
-> 1415                                                   server_hostname=server_hostname)
   1416             if not self._context.check_hostname and self._check_hostname:
   1417                 try:

/usr/lib/python3.6/ssl.py in wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, session)
    405                          suppress_ragged_eofs=suppress_ragged_eofs,
    406                          server_hostname=server_hostname,
--> 407                          _context=self, _session=session)
    408 
    409     def wrap_bio(self, incoming, outgoing, server_side=False,

/usr/lib/python3.6/ssl.py in __init__(self, sock, keyfile, certfile, server_side, cert_reqs, ssl_version, ca_certs, do_handshake_on_connect, family, type, proto, fileno, suppress_ragged_eofs, npn_protocols, ciphers, server_hostname, _context, _session)
    815                         # non-blocking
    816                         raise ValueError("do_handshake_on_connect should not be specified for non-blocking sockets")
--> 817                     self.do_handshake()
    818 
    819             except (OSError, ValueError):

/usr/lib/python3.6/ssl.py in do_handshake(self, block)
   1075             if timeout == 0.0 and block:
   1076                 self.settimeout(None)
-> 1077             self._sslobj.do_handshake()
   1078         finally:
   1079             self.settimeout(timeout)

/usr/lib/python3.6/ssl.py in do_handshake(self)
    692                 raise ValueError("check_hostname needs server_hostname "
    693                                  "argument")
--> 694             match_hostname(self.getpeercert(), self.server_hostname)
    695 
    696     def unwrap(self):

/usr/lib/python3.6/ssl.py in match_hostname(cert, hostname)
    325         raise CertificateError("hostname %r "
    326             "doesn't match either of %s"
--> 327             % (hostname, ', '.join(map(repr, dnsnames))))
    328     elif len(dnsnames) == 1:
    329         raise CertificateError("hostname %r "

CertificateError: hostname 'github.com' doesn't match either of '*.freetls.global.fastly.net', '*.freetls.fastly.net', '*.global.ssl.fastly.net', 'freetls.global.fastly.net'

**Comment by GrzegorzKarchNV** [comment]
Hi @drawingsnow are you using a pytorch container? try using `nvcr.io/nvidia/pytorch:20.03-py3`

**Comment by drawingsnow** [comment]
i am not sure . i used cloud GPU device to train, how to use 'nvcr.io/nvidia/pytorch:20.03-py3'?

i should use it in linux or in jupyter notebook?

**Comment by GrzegorzKarchNV** [comment]
the instructions to run the container are given here: https://ngc.nvidia.com/catalog/containers/nvidia:pytorch

if that doesn't help, please report a bug to https://github.com/pytorch/hub/issues as the error seems to be related to PyTorch Hub
