### ISSUE TITLE
[FasterTransformer]  leak memory

### ISSUE THREAD

**Issue by fengxiaoshuai** [NVIDIA/DeepLearningExamples#488]
Related to **Model/Framework(s)** 
*(FasterTransformer/V2)*

**Describe the bug**
**file**: DeepLearningExamples/FasterTransformer/v2/fastertransformer/decoding_opennmt.h 
**position**：line:108-116
**question**:  some of the memory segments are not freed and leak memory
**example**：K_cache_ = new DataType_ *[2];//I didn't find a place to free memory

**Comment by byshiue** [comment]
Thanks for your reminder. 
You can fix this bug by deleting the pointers in destructor. 
We will fix this bug in next version of FT.
