### ISSUE TITLE
How to speed up transformer model for translation? 

### ISSUE THREAD

**Issue by zhouzebiao** [NVIDIA/DeepLearningExamples#49]
As I said, it can speed up bert model. Can it speed up transformer for translation?

**Comment by swethmandava** [comment]
What can speed up BERT?

**Comment by renganxu** [comment]
@zhouzebiao The transformer model requires sacrebleu_reference.de file, how did you get this file? Thanks.

**Comment by jbaczek** [comment]
`sacrebleu -t wmt14/full -l de-en --echo src > $DATASET_DIR/sacrebleu_reference.de`
This line is contained in `run_preprocessing.sh` script.
