### ISSUE TITLE
[Tacotron 2 And WaveGlow v1.10 For PyTorch] TypeError: get_model() got an unexpected keyword argument 'to_cuda'

### ISSUE THREAD

**Issue by TotzkePaul** [NVIDIA/DeepLearningExamples#491]
TypeError: get_model() got an unexpected keyword argument 'to_cuda'

**Describe the bug**
Error while trying to train.

**To Reproduce**

git clone https://github.com/NVIDIA/DeepLearningExamples.git
cd DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron
I copy LJSpeech-1.1 under Tacotron2
bash scripts/prepare_dataset.sh
bash scripts/docker/build.sh
bash scripts/docker/interactive.sh
bash scripts/prepare_mels.sh
bash scripts/train_tacotron2.sh

root@zzzzzzzz92:/workspace/tacotron2# bash scripts/train_tacotron2.sh
DLL 2020-05-08 05:14:55.753935 - PARAMETER output : ./output/ 
DLL 2020-05-08 05:14:55.754018 - PARAMETER dataset_path : ./ 
DLL 2020-05-08 05:14:55.754070 - PARAMETER model_name : Tacotron2 
DLL 2020-05-08 05:14:55.754105 - PARAMETER log_file : nvlog.json 
DLL 2020-05-08 05:14:55.754138 - PARAMETER anneal_steps : ['500', '1000', '1500'] 
DLL 2020-05-08 05:14:55.754177 - PARAMETER anneal_factor : 0.1 
DLL 2020-05-08 05:14:55.754213 - PARAMETER epochs : 1501 
DLL 2020-05-08 05:14:55.754246 - PARAMETER epochs_per_checkpoint : 50 
DLL 2020-05-08 05:14:55.754279 - PARAMETER checkpoint_path :  
DLL 2020-05-08 05:14:55.754326 - PARAMETER dynamic_loss_scaling : True 
DLL 2020-05-08 05:14:55.754373 - PARAMETER amp_run : True 
DLL 2020-05-08 05:14:55.754430 - PARAMETER cudnn_enabled : True 
DLL 2020-05-08 05:14:55.754482 - PARAMETER cudnn_benchmark : False 
DLL 2020-05-08 05:14:55.754533 - PARAMETER disable_uniform_initialize_bn_weight : False 
DLL 2020-05-08 05:14:55.754576 - PARAMETER use_saved_learning_rate : False 
DLL 2020-05-08 05:14:55.754619 - PARAMETER learning_rate : 0.001 
DLL 2020-05-08 05:14:55.754657 - PARAMETER weight_decay : 1e-06 
DLL 2020-05-08 05:14:55.754701 - PARAMETER grad_clip_thresh : 1.0 
DLL 2020-05-08 05:14:55.754747 - PARAMETER batch_size : 104 
DLL 2020-05-08 05:14:55.754790 - PARAMETER grad_clip : 5.0 
DLL 2020-05-08 05:14:55.754831 - PARAMETER load_mel_from_disk : False 
DLL 2020-05-08 05:14:55.754874 - PARAMETER training_files : filelists/ljs_audio_text_train_filelist.txt 
DLL 2020-05-08 05:14:55.754912 - PARAMETER validation_files : filelists/ljs_audio_text_val_filelist.txt 
DLL 2020-05-08 05:14:55.754958 - PARAMETER text_cleaners : ['english_cleaners'] 
DLL 2020-05-08 05:14:55.755000 - PARAMETER max_wav_value : 32768.0 
DLL 2020-05-08 05:14:55.755048 - PARAMETER sampling_rate : 22050 
DLL 2020-05-08 05:14:55.755104 - PARAMETER filter_length : 1024 
DLL 2020-05-08 05:14:55.755141 - PARAMETER hop_length : 256 
DLL 2020-05-08 05:14:55.755184 - PARAMETER win_length : 1024 
DLL 2020-05-08 05:14:55.755230 - PARAMETER mel_fmin : 0.0 
DLL 2020-05-08 05:14:55.755270 - PARAMETER mel_fmax : 8000.0 
DLL 2020-05-08 05:14:55.755322 - PARAMETER rank : 0 
DLL 2020-05-08 05:14:55.755371 - PARAMETER world_size : 1 
DLL 2020-05-08 05:14:55.755417 - PARAMETER dist_url : tcp://localhost:23456 
DLL 2020-05-08 05:14:55.755472 - PARAMETER group_name : group_name 
DLL 2020-05-08 05:14:55.755510 - PARAMETER dist_backend : nccl 
DLL 2020-05-08 05:14:55.755543 - PARAMETER bench_class :  
DLL 2020-05-08 05:14:55.755584 - PARAMETER model_name : Tacotron2_PyT 
Traceback (most recent call last):
  File "train.py", line 501, in <module>
    main()
  File "train.py", line 335, in main
    uniform_initialize_bn_weight=not args.disable_uniform_initialize_bn_weight)
TypeError: get_model() got an unexpected keyword argument 'to_cuda'

**Environment**
Please provide at least:
* Container version (nvcr.io/nvidia/pytorch:20.03-py3 with Ubuntu 16.04 host):
* GPUs in the system: ( Pascal 1080 GTX TI-11GB):
* CUDA driver version (e.g. 440.33.01): 10.2
I installed nvida-docker2.

**Comment by GrzegorzKarchNV** [comment]
@TotzkePaul this is fixed now, please update your local repo
