### ISSUE TITLE
Update Available Benchmarks also for AMD GPUs

### ISSUE THREAD

**Issue by papadako** [NVIDIA/DeepLearningExamples#492]
Dear all,

I guess it would be of great interest to update the available benchmarks with numbers from AMD GPUs (i.e., Radeon VII, Instincts). This is something that can be done now, right?

**Comment by nvpstr** [comment]
This repository shows how to efficiently use NVIDIA GPU technology. Included implementations are optimized and tested with the most recent framework containers. Comparison with other GPU platforms currently is out of the scope.
