### ISSUE TITLE
[se-resnext101-32x4d/PyTorch] cannot achieve the post T4 inference performance

### ISSUE THREAD

**Issue by suntao2012** [NVIDIA/DeepLearningExamples#495]
i just run the container nvcr.io/nvidia/pytorch:20.01-py3
and goto the /workspace/examples/resnet50v1.5
use the inference cmd: python ./main.py --arch se-resnext101-32x4d -p 1 --raport-file benchmark.json --epochs 1 --prof 100 --evaluate --fp16 -b 128 [DATA DIR]

I got similar FPS on V100-PCIE 16 GB, like 936 imgs/sec;
but i only got 370 imgs/sec on Tesla T4 (already set gpu clock to 1.59GHz), why?

**Comment by nvpstr** [comment]
The numbers for T4 will be updated soon.
