### ISSUE TITLE
Enabling CPU runs causes train.py to fail if bash scripts/train_tacotron2.sh or / train_waveglow.sh is called 

### ISSUE THREAD

**Issue by KDOT2509** [NVIDIA/DeepLearningExamples#496]
Related to **Model/Framework(s)** 
*(e.g. GNMT/PyTorch or FasterTransformer/All)*

**Describe the bug**
Since the feature -- cpu-run was implemeted train.py breaks for me, see the error below:
  File "train.py", line 501, in <module>
    main()
  File "train.py", line 335, in main
    uniform_initialize_bn_weight=not args.disable_uniform_initialize_bn_weight)
TypeError: get_model() got an unexpected keyword argument 'to_cuda'

I guess this due to the changes in get_model() to enable CPU runs and it should be easily fixed with changing the input parameters of get_model()

**To Reproduce**

I followed the quick setup guide within the repository.

**Expected behavior**

get_model is able to to load model for training.

**Environment**
Please provide at least:
* Container version: torch: 1.5.0a0+8f84ded
* GPUs in the system: 4xTesla T4
* CUDA driver version: release 10.2, V10.2.89

***Comment***
First time I am creating an issue. Sorry if something is not clear.

**Comment by GrzegorzKarchNV** [comment]
@KDOT2509 this is fixed now, please update your local repo
