### ISSUE TITLE
[FasterTransformer] A simple bug in trt_model.h

### ISSUE THREAD

**Issue by ligonzheng** [NVIDIA/DeepLearningExamples#498]
Related to **FasterTransformer/v2** 

**Describe the bug**
When I try to compile the FT V2, a bug was occur. Then I check it, I found there is a undefined variable called input_tensor, actually it should be from_tensor. 

**To Reproduce**
cd V2;
mkdir build;
cmake .. -DBUILD_TRT=ON;
make

**Expected behavior**
A bug: 
error: ‘input_tensor’ was not declared in this scope
       assert(input_tensor);

**Comment by byshiue** [comment]
Thanks for your feedback. This bug is solved in #501.
