### ISSUE TITLE
Different versions of docker containers 

### ISSUE THREAD

**Issue by mkfilipiuk** [NVIDIA/DeepLearningExamples#50]
Hi, 

in README you list that TensorFlow 19.03-py3 NGC container is required for this model.
However in Dockerfile you have 19.01:
https://github.com/NVIDIA/DeepLearningExamples/blob/bc64ab1ac585ae5227e30c00441058939b002d94/TensorFlow/Classification/RN50v1.5/Dockerfile#L1

You should change the README or update the tensorflow container version :)

**Comment by nvpstr** [comment]
Usually samples work with previous containers. Of course usually using the most recent one should give more benefits in terms of speedup.
