### ISSUE TITLE
[Transformer/v2] Why the sequence length of encoder and decoding must be the same ?

### ISSUE THREAD

**Issue by ligonzheng** [NVIDIA/DeepLearningExamples#505]
As the title said, why there is this kind of limitation ?
The encoder sequence  is the source sequence  and the decoding sequence is the target sequence ? 
It should be not limited.

**Comment by byshiue** [comment]
This is a bug. The reason is that the `decoding_opennmt.h` use the max_seq_len to allocate the space of `K_mem_cache_` and `V_mem_cahce`, but not the max_memory_seq_len.  
We will fix it in the next version.
