### ISSUE TITLE
[Transformer/V2] two-way buffer to update Mask-attention's KV

### ISSUE THREAD

**Issue by ligonzheng** [NVIDIA/DeepLearningExamples#506]
I can not understand what's the mean of two-way buffer for K_cache and V_cache in decoding_opennmt.h. What the benefit of it ? The update at the end of every step seems like just a copy from one to another. Is it enough to use just one-way buffer ?

**Comment by byshiue** [comment]
The two-way buffers are used in the beam search. 
Assume the beam index in this step is [b1, b2, b3, b4], the beam index of the next step may be [b1, b3, b1, b2]. 
So, using two-way buffers to update the cache is more efficient.
