### ISSUE TITLE
[SSD/PyTorch] View size incompatibility when using example code

### ISSUE THREAD

**Issue by coder543** [NVIDIA/DeepLearningExamples#508]
Related to SSD/PyTorch

**Describe the bug**

I have spent over an hour trying to debug this issue, looking at any example code I could find in the repo, as well as walking through the code and sanity checking what it's doing. I'm an experienced developer in other areas, but I have very little experience with machine learning, so it's difficult for me to understand what is going wrong here.

Using the example code [from here](https://pytorch.org/hub/nvidia_deeplearningexamples_ssd/), I see the following error:

```
$ python .\ssd.py
Using cache found in C:\Users\someuser\/.cache\torch\hub\NVIDIA_DeepLearningExamples_torchhub
Using cache found in C:\Users\someuser\/.cache\torch\hub\NVIDIA_DeepLearningExamples_torchhub
Traceback (most recent call last):
  File ".\ssd.py", line 21, in <module>
    detections_batch = ssd_model(tensor)
  File "C:\Users\someuser\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\someuser\/.cache\torch\hub\NVIDIA_DeepLearningExamples_torchhub\PyTorch\Detection\SSD\src\model.py", line 112, in forward
    locs, confs = self.bbox_view(detection_feed, self.loc, self.conf)
  File "C:\Users\someuser\/.cache\torch\hub\NVIDIA_DeepLearningExamples_torchhub\PyTorch\Detection\SSD\src\model.py", line 97, in bbox_view
    ret.append((l(s).view(s.size(0), 4, -1), c(s).view(s.size(0), self.label_num, -1)))
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```

I don't understand how the size and stride could be wrong, when all of the code involved comes directly from an example, and I did check that the tensors are a somewhat reasonable size:

```
(Pdb) p tensor.size()
torch.Size([3, 3, 300, 300])
```

**To Reproduce**

The full code being used is as follows:

```python
import torch

from matplotlib import pyplot as plt
import matplotlib.patches as patches

precision = 'fp32'
ssd_model = torch.hub.load(
    'NVIDIA/DeepLearningExamples:torchhub', 'nvidia_ssd', model_math=precision)
utils = torch.hub.load(
    'NVIDIA/DeepLearningExamples:torchhub', 'nvidia_ssd_processing_utils')
ssd_model.to('cuda')
uris = [
    'http://images.cocodataset.org/val2017/000000397133.jpg',
    'http://images.cocodataset.org/val2017/000000037777.jpg',
    'http://images.cocodataset.org/val2017/000000252219.jpg'
]
inputs = [utils.prepare_input(uri) for uri in uris]

tensor = utils.prepare_tensor(inputs, precision == 'fp16')
with torch.no_grad():
    detections_batch = ssd_model(tensor) #ERROR: crash occurs on this line

results_per_input = utils.decode_results(detections_batch)
best_results_per_input = [utils.pick_best(
    results, 0.40) for results in results_per_input]

classes_to_labels = utils.get_coco_object_dictionary()
for image_idx in range(len(best_results_per_input)):
    fig, ax = plt.subplots(1)
    # Show original, denormalized image...
    image = inputs[image_idx] / 2 + 0.5
    ax.imshow(image)
    # ...with detections
    bboxes, classes, confidences = best_results_per_input[image_idx]
    for idx in range(len(bboxes)):
        left, bot, right, top = bboxes[idx]
        x, y, w, h = [val * 300 for val in [left,
                                            bot, right - left, top - bot]]
        rect = patches.Rectangle(
            (x, y), w, h, linewidth=1, edgecolor='r', facecolor='none')
        ax.add_patch(rect)
        ax.text(x, y, "{} {:.0f}%".format(
            classes_to_labels[classes[idx] - 1], confidences[idx] * 100), bbox=dict(facecolor='white', alpha=0.5))
plt.show()
```

Simply run the script, and it seemingly _should_ work, but it doesn't.

**Expected behavior**

The example code to perform inference without erroring

**Environment**
Please provide at least:
* Container version (e.g. pytorch:19.05-py3):
* GPUs in the system: (e.g. 8x Tesla V100-SXM2-16GB):
* CUDA driver version (e.g. 418.67):

Windows 10, Python 3.6.1, using Powershell (not WSL)

1 x nVidia GTX 1080 Ti

CUDA 10.2, driver version 442.50

**Comment by RomanLevkovych** [comment]
Hi, did you manage to fix the bug?

**Comment by coder543** [comment]
Nope. Since this appears to be a bug in code associated with this repository, I was hoping that someone from NVIDIA would chime in with a solution, but nothing so far.

**Comment by mwawrzos** [comment]
Hello,

The short answer is, add the line marked with `++`, and the example will work:
```
tensor = utils.prepare_tensor(inputs, precision == 'fp16')
++ tensor = tensor.contiguous()
with torch.no_grad():
    detections_batch = ssd_model(tensor) #now it works
```

The model requires input tensor to be contiguous in memory. The util function (and the tutorial) missed that, but I made MR with a fix.

Please reopen, if the problem is still there.

**Comment by coder543** [comment]
I just tested locally, and it definitely fixes the problem. Thanks for your help! I thought it might be something simple, but I had no idea what to try here.

**Comment by Abdul-Rehman-Astro** [comment]
Thank you Soooooo Much, You just saved My day at IIT Roorkee...
