### ISSUE TITLE
[fast-transformer/v1] CUBLAS_STATUS_ARCH_MISMATCH

### ISSUE THREAD

**Issue by ShenYounger** [NVIDIA/DeepLearningExamples#514]
there is a CUDA runtime error when i execute demo using command
"./transformer_fp32 1 12 128 12 64". i execute demo after running the command "cmake -DSM=37 -DCMAKE_BUILD_TYPE=Release -DBUILD_TRT=ON -DTRT_PATH=/root/TensorRT-5.1.5.0 -DBUILD_TF=ON -DTF_PATH=/root/anaconda2/lib/python2.7/site-packages/tensorflow .." and "./gemm_fp32 1 20 12 64"

the info is listed below：
[Device Tesla K80
before allocate free 11.10 GB total 11.17 GB
After allocate free 11.07 GB used 0.10 GB total 11.17 GB
terminate called after throwing an instance of 'std::runtime_error'
  what():  [FT][ERROR] CUDA runtime error: CUBLAS_STATUS_ARCH_MISMATCH /root/DeepLearningExamples-master/FasterTransformer/v1/fastertransformer/cuda/open_attention.h:171 

Aborted (core dumped)]

i searched internet using the keywords "CUBLAS_STATUS_ARCH_MISMATCH" and i found some info at the webpage https://docs.nvidia.com/cuda/cublas/index.html.  the webpage said the "CUBLAS_STATUS_ARCH_MISMATCH" may be because "the device has a compute capabilites lower than 5.0"

**Environment**
cudnn version: 7.6.4
CUDA Version: 10.0
GPU version: K80
container: nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04

**Comment by ShenYounger** [comment]
@byshiue

**Comment by byshiue** [comment]
We use `cublassGemmEx` to compute the matrix multiplication, and `cublassGemmEx` is only supported for GPU with architecture capabilities equal or greater than 5.0.
However, the architecture capability of K80 is 3.7, so it cannot run the `cublassGemmEx`. 
Please try the gpu with new architecture like Maxwell, Pascal, Volta or Turing.

**Comment by ShenYounger** [comment]
> We use `cublassGemmEx` to compute the matrix multiplication, and `cublassGemmEx` is only supported for GPU with architecture capabilities equal or greater than 5.0.
> However, the architecture capability of K80 is 3.7, so it cannot run the `cublassGemmEx`.
> Please try the gpu with new architecture like Maxwell, Pascal, Volta or Turing.

but i don't have other gpu machine. i want to cry.

**Comment by byshiue** [comment]
Sorry, I cannot help you.
You can try to replace the cublasGemmEx by other cuda gemm APIs, like cubalsSgemm and cublasHgemm.
