### ISSUE TITLE
Pretraining Bert -corrupted record

### ISSUE THREAD

**Issue by BattashB** [NVIDIA/DeepLearningExamples#518]
Hi, I followed each one of the step of quickstart for Bert  pretraining, But when I'm starting to train using:
`bash scripts/run_pretraining_lamb.sh 16 2 8 7.5e-4 5e-4 fp16 true 8 2000 200 7820 100 512 2048 large`
I'm getting this error:
> Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: corrupted record at 53001451
         [[{{node IteratorGetNext}}]]

I ran few times, each time I got different :"at **53001451**"
sometimes it happens after 10 iteration sometime after 20 and so on.
Any idea what I did wrong?
Thanks.

**Comment by swethmandava** [comment]
It seems the tf record is corrupted? Could you try to [recreate the TFRecords](https://github.com/NVIDIA/DeepLearningExamples/blob/3927e1334aeebae4040f81f8fa976393e75aba3c/TensorFlow/LanguageModeling/BERT/data/create_datasets_from_start.sh#L40) and see if that fixes the issue?
