### ISSUE TITLE
[FasterTransformer/v2] Does FT support int8 quantization with tensorRT ?

### ISSUE THREAD

**Issue by ligonzheng** [NVIDIA/DeepLearningExamples#520]
Hello,
    If I use FT as a tensorRT plugin, May I go on to improve the performance with the tensorRT quantization ?

**Comment by byshiue** [comment]
No. The implementation of TensorRT plugin of FT is different to the implementation of TensorRT BERT. FasterTransformer does still not have the implementation on INT 8. 
If you want to use the TensorRT quantization, you need to build the BERT by TensorRT directly. Another option is to wait the FasterTransformer supporting INT 8 in the future.

**Comment by ligonzheng** [comment]
Really thank you for your reply.
