### ISSUE TITLE
Is inference results between PyTorch fp16 and TensorRT16 have typo?

### ISSUE THREAD

**Issue by blacksailer** [NVIDIA/DeepLearningExamples#524]
Hello, noticed that at trt folder may be [incorrect ](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/SpeechRecognition/Jasper/trt#inference-performance-nvidia-t4).

In header #sentences/seconds are written down, but maybe latency should be placed? Because otherwis PyTorch FP16 is far more better that TensorRT fp16 and you should just delete all folder whatsover.

and `walk_benchmark.sh` also grep by `latency` word

**Comment by nv-kkudrynski** [comment]
TensorRT is no longer a separate folder in Jasper repo. Updated version contains throughput and latency numbers in Triton folder.
