### ISSUE TITLE
Nan Values pretrianing Bert Large

### ISSUE THREAD

**Issue by Esaada** [NVIDIA/DeepLearningExamples#529]
Hi, 
First I did the exact steps that are written in the quick start section, same Nvidia docker, same preprocessing.
Now I have  8V100 16GB gpus,  so I had to adjust my hyperparametrs, so this is my command line:

>bash scripts/run_pretraining_lamb.sh 16 2 8 7.5e-4 5e-4 fp16 true 8 2000 200 7820 100  512 2048 large

I'm getting a Nan loss after 3 days of training:

>Skipping time record for  2505  due to checkpoint-saving/warmup overhead
Skipping time record for  2505  due to checkpoint-saving/warmup overhead
ERROR:tensorflow:Model diverged with loss = NaN.
E0526 15:34:12.011717 140569525946176 basic_session_run_hooks.py:760] Model diverged with loss = NaN.
ERROR:tensorflow:Model diverged with loss = NaN.
E0526 15:34:12.012056 139992964126528 basic_session_run_hooks.py:760] Model diverged with loss = NaN.
ERROR:tensorflow:Model diverged with loss = NaN.
ERROR:tensorflow:Model diverged with loss = NaN.
E0526 15:34:12.016564 139828350265152 basic_session_run_hooks.py:760] Model diverged with loss = NaN.
E0526 15:34:12.016430 140295853721408 basic_session_run_hooks.py:760] Model diverged with loss = NaN.
ERROR:tensorflow:Model diverged with loss = NaN.
E0526 15:34:12.017801 139712623675200 basic_session_run_hooks.py:760] Model diverged with loss = NaN.
ERROR:tensorflow:Model diverged with loss = NaN.
E0526 15:34:12.018392 139771539388224 basic_session_run_hooks.py:760] Model diverged with loss = NaN.
ERROR:tensorflow:Model diverged with loss = NaN.
E0526 15:34:12.018638 140298069772096 basic_session_run_hooks.py:760] Model diverged with loss = NaN.
ERROR:tensorflow:Model diverged with loss = NaN.
E0526 15:34:12.019310 139732692191040 basic_session_run_hooks.py:760] Model diverged with loss = NaN.
Traceback (most recent call last):
  File "/workspace/bert/run_pretraining.py", line 707, in <module>
    tf.compat.v1.app.run()
                ................
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/monitored_session.py", line 1426, in run
    run_metadata=run_metadata))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/basic_session_run_hooks.py", line 761, in after_run
    raise NanLossDuringTrainingError
tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.

The training steps before looks without any issues:
>INFO:tensorflow:loss = 7.983827, step = 2494 (1470.451 sec)
I0526 15:17:42.580748 139828350265152 basic_session_run_hooks.py:260] loss = 7.983827, step = 2494 (1470.451 sec)
INFO:tensorflow:loss = 8.053008, step = 2494 (1470.446 sec)
I0526 15:17:42.592079 139771539388224 basic_session_run_hooks.py:260] loss = 8.053008, step = 2494 (1470.446 sec)
INFO:tensorflow:loss = 8.140859, step = 2494 (1470.482 sec)
I0526 15:17:42.603221 140569525946176 basic_session_run_hooks.py:260] loss = 8.140859, step = 2494 (1470.482 sec)
INFO:tensorflow:loss = 8.23104, step = 2494 (1470.451 sec)
INFO:tensorflow:loss = 8.056421, step = 2494 (1470.476 sec)
I0526 15:17:42.603391 140295853721408 basic_session_run_hooks.py:260] loss = 8.23104, step = 2494 (1470.451 sec)
I0526 15:17:42.603374 140298069772096 basic_session_run_hooks.py:260] loss = 8.056421, step = 2494 (1470.476 sec)
INFO:tensorflow:loss = 8.326416, step = 2494 (1470.482 sec)
I0526 15:17:42.605053 139992964126528 basic_session_run_hooks.py:260] loss = 8.326416, step = 2494 (1470.482 sec)
INFO:tensorflow:loss = 7.4290133, step = 2494 (1470.451 sec)
I0526 15:17:42.607876 139712623675200 basic_session_run_hooks.py:260] loss = 7.4290133, step = 2494 (1470.451 sec)
INFO:tensorflow:loss = 8.152052, step = 2494 (1470.485 sec)
I0526 15:17:42.608381 139732692191040 basic_session_run_hooks.py:260] loss = 8.152052, step = 2494 (1470.485 sec)
DLL 2020-05-26 15:23:58.588405 - Iteration: 2500  throughput_train : 872.058 seq/s mlm_loss : 7.3278  nsp_loss : 0.6562  total_loss : 7.9840  avg_loss_step : 7.9702  learning_rate : 0.0048189736  loss_scaler : 131072 
INFO:tensorflow:Saving checkpoints for 2500 into /results/tf_bert_pretraining_lamb_large_fp16_gbs165536_gbs232768_200524102432/phase_1/model.ckpt.
I0526 15:25:13.642299 139712623675200 basic_session_run_hooks.py:606] Saving checkpoints for 2500 into /results/tf_bert_pretraining_lamb_large_fp16_gbs165536_gbs232768_200524102432/phase_1/model.ckpt.
Skipping time record for  2500  due to checkpoint-saving/warmup overhead
Skipping time record for  2500  due to checkpoint-saving/warmup overhead

I can send the full log file if needed.
Am I doing something wrong with my hyperparameter picking? something else?
Thanks.

**Comment by swethmandava** [comment]
Could you link the whole log? that would be helpful, thanks!

**Comment by Esaada** [comment]
Hi, please see attached
[train.log](https://github.com/NVIDIA/DeepLearningExamples/files/4742103/train.log)

**Comment by swethmandava** [comment]
The recipe looks correct. Based on the log, it starts to diverge at around 2k steps. Could it be just a bad seed? I'm unable to reproduce! For reference, here is my training loss vs steps plot

![bert_tf_p1_loss](https://user-images.githubusercontent.com/17828952/108259452-f397dd00-7115-11eb-8b82-22d3b733ae35.png)
