### ISSUE TITLE
[DLRM/PyTorch] Embedding table sizes for performance benchmarking?

### ISSUE THREAD

**Issue by adityaiitb** [NVIDIA/DeepLearningExamples#531]
The training performance benchmarking number for DLRM shows a batch size of 32K on 1 GPU. What were the sizes (vocabulary x embed_size) of the 26 embedding tables? Was it [10**5, 128] for all the 26 tables?

**Comment by idealboy** [comment]
I think you will see each embedding's size on your screen when build the model.

or you can find the embedding size in /data/dlrm/binary*

**Comment by tgrel** [comment]
Hi @adityaiitb Sorry for the late response.

Usually the throughput doesn't change much when changing the sizes of the tables, so this doesn't matter much. Both 26*[100k] and running on the full tables for Criteo 1TB dataset should give essentially the same throughput result.
