### ISSUE TITLE
[FastPitch/Pytorch] Pretrained model link?

### ISSUE THREAD

**Issue by machineko** [NVIDIA/DeepLearningExamples#533]
Related to **FastPitch/Pytorch** 

Are you guys planning on releasing pretrained FastPitch model? 
I would love to try few things with it but I don't have computer power at the moment to train on LJ dataset from scratch :P

**Comment by eilmiv** [comment]
I am currently in the process of training. A pretrained model would be helpful for closer comparison.

**Comment by Yablon** [comment]
I have trained a FastPitch model using the official pipeline. 
But I do not know if the audios are competitive with Tacotron2.

Here are the link and password.
[link](https://pan.baidu.com/s/1hbisz64GVYRF6Mge1Zbekw)
password to extract file:  g3fn

**Comment by NinoSkopac** [comment]
@Yablon Thanks for disk but it's in Chinese so I'm struggling to navigate - I think it's asking me to download and install some software? I'm not comfortable doing that. Could you host the file somewhere else, for example Google Drive, Dropbox, Apple Drive, basically anywhere else? 

I (and others) really appreciate it.

**Comment by NinoSkopac** [comment]
@Yablon Also, I've done a lot of research in the field - if you could share your email I could let you know how does the model you trained compare to tacotron2.

**Comment by Yablon** [comment]
@NinoSkopac Yeah, here is a new [link](https://drive.google.com/file/d/1G0aPQ8sYbZ4BJb0N3rFtvAROKLNYFg0X/view?usp=sharing) on Google Drive.
I have never trained a tacotron2 model using LJSpeech data, so it's hard for me to compare them.
If FastPitch is better, I think a lot of things can be done.

**Comment by gad2103** [comment]
I would also love an English pre-trained model. @NinoSkopac did you ever make any progress?

**Comment by NinoSkopac** [comment]
Hey @gad2103, what do you mean? Yablon posted a link to a pretrained model [above](https://github.com/NVIDIA/DeepLearningExamples/issues/533#issuecomment-646456598) (I haven't verified it myself yet).
