### ISSUE TITLE
[FasterTransformer/v2] Big max error bewteen FT and pytorch

### ISSUE THREAD

**Issue by ligonzheng** [NVIDIA/DeepLearningExamples#537]
Hello, I compare the computing result between FT and pytorch.  The max error is like this:

basic option : batch = 1, embedding_size = 12,  attention_heads = 2
case 1:
arch : only masked_self_attn
seq_length = 30 , decoder_layers = 1,  max_err = 0.02
seq_length = 30, decoder_layers = 36, max_err = 0.02

case 2:
arch : masked_self_attn + add_redusial
seq_length = 30, decoder_layers = 1,   max_err = 0.5
seq_length = 30, decoder_layers = 36, max_err = 3000

So, big problem with the increment of seq_length and decoder_layers. The max_err is unacceptable.
Could you give me some idea ?

**Comment by ligonzheng** [comment]
Maybe the key is I use the add redusial operation which make the error amplified

**Comment by byshiue** [comment]
If you use FP32, max_err 0.02 is not acceptable. 
I am not sure what redusial operation you add, but there are many possible reasons to make the results be different. 
First, FT may not support your setting. We have verified some settings, and write them into README. If your settings are not one of them, we cannot guarantee the correctness. You can check your settings in TensorFlow sample code in the first step.
Second, the model architecture or some operations are different. The decoder of FT is based on the OpenNMT-tf. If you use other library as the baseline, there may be some little different. For example, the position encoding of OpenNMT-py and OpenNMT-tf are different. So, the results of FT and OpenNMT-py would be different.

**Comment by ligonzheng** [comment]
OK ,I had solved it.
Thank you.
