### ISSUE TITLE
[Decoder performance on T4]

### ISSUE THREAD

**Issue by Michael-Xiang-create** [NVIDIA/DeepLearningExamples#541]
In some situation, the elapsed time of FP16 is more than FP32. For example, when batch_size is 1 and seq_len is 32, Decoder in FP16 has 165.88ms, but FP32 only has 111.14ms. Why isn't fp16 always faster than fp32?

**Comment by byshiue** [comment]
If there is no any other additional overhead, then FP16 should be faster than FP32. 
However, TensorFlow does some additional convertion when we use FP16. And the bottleneck for small batch size, like 1, is not bounded by the computing, but other bound. For example, the kernel launch bound. Therefore, the FP16 cannot bring large speedup for GEMM computing, and hence the inference speed of FP16 is slower than the speed of FP32. 
If you observe the performance of decoding, which uses FasterTransformer to do all tranlsation progress, you can find that the performance of FP16 are always better than FP32.
