### ISSUE TITLE
[BERT/TensorFlow] Feature requested: Run BERT without horovod

### ISSUE THREAD

**Issue by guotong1988** [NVIDIA/DeepLearningExamples#544]
TensorFlow1.15 is better. TensorFlow 2.0 is also OK.

Run BERT in one machine with multi-GPU without horovod.

If horovod is not installed, the code in 20200601 will fail because of the line below:

![image](https://user-images.githubusercontent.com/4702353/83389530-eec5b880-a422-11ea-842c-d8ee3be2b4ed.png)

Thank you very much!

**Comment by swethmandava** [comment]
Closing as duplicate #553
