### ISSUE TITLE
[BERT/TensorFlow1.15] What is the speed of multi-GPU on one machine without horovod? 

### ISSUE THREAD

**Issue by guotong1988** [NVIDIA/DeepLearningExamples#553]
Related to **Model/Framework(s) or something else (describe)** 

TensorFlow 1.15

**Is your feature request related to a problem? Please describe.**
No.
I just want to know the speed result for BERT pretraining of multi-GPU on one machine without horovod

**Additional context**
It is a feature request and a question:)

**Comment by swethmandava** [comment]
Do you mean the speedup comparison of horovod vs tensorflow distributed for multi gpu? We haven't tried tensorflow's distributed strategy for Bert Tensorflow but based on some internal experiments on TensorFlow2, we observed horovod's performance is better and hence don't have it on the roadmap.

**Comment by guotong1988** [comment]
horovod is a little hard to install.

**Comment by swethmandava** [comment]
We recommend you use [our containers ](https://ngc.nvidia.com/catalog/containers/nvidia:tensorflow)

**Comment by guotong1988** [comment]
Could you please give me a docker with:
```
tensorFlow 1.15
cuda10
horovod
python3
```
Thank you very much!

**Comment by swethmandava** [comment]
Linking [release notes](https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/index.html) for your reference. Thanks and closing the issue
