### ISSUE TITLE
[BERT/TensorFlow1.15] Variable `rank` not defined？

### ISSUE THREAD

**Issue by guotong1988** [NVIDIA/DeepLearningExamples#554]
**Describe the bug**

![image](https://user-images.githubusercontent.com/4702353/84142350-341f6100-aa87-11ea-9e7c-f5f6fd2b0a03.png)

**To Reproduce**
https://github.com/NVIDIA/DeepLearningExamples/blob/master/TensorFlow/LanguageModeling/BERT/run_pretraining.py#L217

**Comment by swethmandava** [comment]
Should use `self.hvd_rank` instead. Thanks for pointing it out, will fix it.
