### ISSUE TITLE
[Bert/Pytorch] Use spawn start method for Dataloader module

### ISSUE THREAD

**Issue by rashikakheria** [NVIDIA/DeepLearningExamples#563]
Related to **BERT/pytorch** 

**Describe the bug**

Current BERT [pre_training script](https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/LanguageModeling/BERT/run_pretraining.py#L85) uses fork() start method for spawning dataloader workers on UNIX systems. However, the core CUDA runtime itself does not support the fork launch mechanism in PyTorch. From https://pytorch.org/docs/stable/notes/multiprocessing.html

```
CUDA in multiprocessing
The CUDA runtime does not support the fork start method. In Python 3, either the spawn or forkserver start method are

Note:
The start method can be set via either creating a context with multiprocessing.get_context(...) or directly using multiprocessing.set_start_method(...).
```

There are tens of issues on Github where both PyTorch and NVIDIA have said they will not fix this and have asked applications to use the spawn start method instead (Example: https://github.com/pytorch/pytorch/issues/13883).

Is there a reason to still use fork() start method in BERT benchmarking?

**Comment by ptrblck** [comment]
If the `Dataset` doesn't use any `CUDATensors` using multiprocessing through `fork()` should be working on Unix systems.
In other cases you might need to set the `spawn` method as described in the docs (also for Windows, as `fork()` cannot be used).

**Comment by sharathts** [comment]
Closing issue. Feel free to reopen if you have more questions.
