### ISSUE TITLE
Is it possible to directly convert the tensorflow BERT model  to the tensorrt model using the parser？

### ISSUE THREAD

**Issue by silence1114** [NVIDIA/DeepLearningExamples#574]
Is it possible to directly convert the tensorflow BERT model  to the tensorrt model using the parser？rather than building it layer by layer like in the demo.

**Comment by swethmandava** [comment]
Unfortunately, [demoBert](https://github.com/NVIDIA/TensorRT/tree/master/demo/BERT) is the only way to build the tensorRT BERT engine right now
