### ISSUE TITLE
[FasterTransformer/TensorFlow] intermittent inconsistent results of tf_encoder and op_encoder on FP16

### ISSUE THREAD

**Issue by 372046933** [NVIDIA/DeepLearningExamples#604]
Related to **Model/Framework(s)** 
*FasterTransformer/TensoFlow*

**Describe the bug**
The cross check difference threshold between `tf_encoder` and `op_encoder` was set to `2e-2` in `encoder_sample.py` when data type is FP16. I found that with multiple runs(just run the script multiples times in shell). `Max diff` does not stay the same. There are two possible `Max diff`. One of them was larger than `2e-2`.

**To Reproduce**
1. ```
    ./bin/encoder_gemm 1 32 12 64 1
    ./bin/encoder_sample 1 12 32 12 64 1
     ```
2. Launch the following script multiple times.
```
python encoder_sample.py \
        --batch_size 1 \
        --seq_len 32 \
        --head_number 12 \
        --size_per_head 64 \
        --num_layer 12 \
        --data_type fp16 \
        --test_time 1
```
I got two different results as following.
Result 1:
```
[INFO] Encoder Cross check False
[INFO] Max diff 0.021484375
[INFO] min diff 0.0
[INFO] TF decoder time costs. 3.82805 ms
[INFO] OP decoder time costs: 2.7057 ms
```
Result 2:
```
[INFO] Encoder Cross check True
[INFO] Max diff 0.01953125
[INFO] min diff 0.0
[INFO] TF decoder time costs. 4.42715 ms
[INFO] OP decoder time costs: 2.92116 ms
```
Ignore the time cost difference

**Expected behavior**
Since the random seed is fixed. The encoder result should stay the same across run.

**Environment**
Please provide at least:
* Container version (nvcr.io/nvidia/tensorflow:19.07-py2):
* GPUs in the system: (Tesla V100-PCIE-16GB):
* CUDA driver version (418.87.00):

**Comment by 372046933** [comment]
I found that Tesla P100 have a new result.
Result 3:
```
[INFO] Encoder Cross check False
[INFO] Max diff 0.0244140625
[INFO] min diff 0.0
[INFO] TF decoder time costs. 5.99106 ms
[INFO] OP decoder time costs: 7.53603 ms
```

**Comment by byshiue** [comment]
I have checked this problem, and find that the difference Max diff is caused by the TF result are not stable.

**Comment by 372046933** [comment]
Great. But how to justify the difference between P100 and V100? They are running on the same container.

**Comment by byshiue** [comment]
Different generation GPU may use different kernels on many computation.
I do not check that the results of P100 and V100 of FT are same or not. 
But the difference may be also caused by TensorFlow.

**Comment by 372046933** [comment]
@byshiue Thanks. I'll check whether the difference is caused by GPU generation.

**Comment by byshiue** [comment]
Close this issue due to inactivated.
