### ISSUE TITLE
BERT Tensorflow :  Blank screen  in Tensorboard  graph tab.

### ISSUE THREAD

**Issue by whatdhack** [NVIDIA/DeepLearningExamples#609]
Related to **Model/Framework(s)** 
BERT/Tensorflow 

**Describe the bug**
A blank page is displayed  in Tensorboard graph tab.

**To Reproduce**
Just start  Tensorboard and point to the right directory.

**Expected behavior**
A graph should be displayed, instead there is a blank screen.

**Environment**
nvcr.io/nvidia/tensorflow     20.06-tf1-py3

**Comment by xiaocai00** [comment]
This doesn't generate tf.event, could someone help on this?

**Comment by swethmandava** [comment]
You can use [FileWriter](https://www.tensorflow.org/api_docs/python/tf/compat/v1/summary/FileWriter) to write any event files relevant to you
