### ISSUE TITLE
how is horovod installed in nvcr.io/nvidia/tensorflow:19.05-py3?

### ISSUE THREAD

**Issue by rllin-fathom** [NVIDIA/DeepLearningExamples#61]
I'm rebuilding the image against python 3.6

- [x] rebuild tensorflow against python 3.6 with tensorflow fork found at `/opt/tensorflow`
- [ ] install horovod against python 3.6

I've done the first, but the second, I'm unclear how to do given that the nvidia image Dockerfile is not publicly available.

```
RUN ldconfig /usr/local/cuda-10.1/targets/x86_64-linux/lib/stubs && \
    HOROVOD_NCCL_HOME=/usr/local/nccl-2.4.6 \
    HOROVOD_GPU_ALLREDUCE=NCCL \
    HOROVOD_WITH_TENSORFLOW=1 \
    HOROVOD_WITHOUT_PYTORCH=1 \
    HOROVOD_WITHOUT_MXNET=1 \
    pip3 install --no-cache-dir horovod==0.16.1 && \
    ldconfig
```

Unclear how I can specify `HOROVOD_NCCL_HOME` as there doesn't seem to be an `/usr/local/nccl-2.4.6`

**Comment by rllin-fathom** [comment]
according to the error message,
```
    Please specify correct NCCL location with the HOROVOD_NCCL_HOME environment variable or combination of HOROVOD_NCCL_INCLUDE and HOROVOD_NCCL_LIB environment variables.
```

I also tried to set them as 

```
...
    HOROVOD_NCCL_INCLUDE=NCCL_HDR_PATH \
    HOROVOD_NCCL_LIB=NCCL_INSTALL_PATH \...
```

but same error

**Comment by rllin-fathom** [comment]
@benbarsdell perhaps you could point me to how horovod is built/installed on the nvidia image?

**Comment by rllin-fathom** [comment]
@benbarsdell anybody you could point me to perhaps that would know? :)

**Comment by ngochuyenluu** [comment]
I think it is already inside tensorflow:19.05-py3, I trained the Speech Recognition on nvidia docker which use Horovod and tesorflow, they worked perfectly, just pull tensorflow:19.05-py3

**Comment by rllin-fathom** [comment]
@ngochuyenluu please reread the original post.  I am looking for py36 which means I'd have to compile tensorflow and horovod against it

**Comment by rllin-fathom** [comment]
it has been noted that the next version 19.07 will use ubuntu 18.04

> Release 19.07 will instead support Ubuntu 18.04

which should mean it'll default to python3.6, but this is yet to be confirmed
