### ISSUE TITLE
[FastPitch/Pytorch] size mismatch for embedding.weight

### ISSUE THREAD

**Issue by Truong-Thanh-Quang** [NVIDIA/DeepLearningExamples#610]
I use my own pretrained Tacotron2 model FP16 to run extract mels. Error occured:

Traceback (most recent call last):
  File "extract_mels.py", line 290, in <module>
    main()
  File "extract_mels.py", line 199, in main
    forward_is_infer=False, ema=False)
  File "/workspace/fastpitch/inference.py", line 135, in load_and_setup_model
    status += ' ' + str(model.load_state_dict(sd, strict=False))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 879, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Tacotron2:
        size mismatch for embedding.weight: copying a param with shape torch.Size([199, 512]) from checkpoint, the shape in current model is torch.Size([148, 512]).

Please help.

**Comment by kdorichev** [comment]
This error is due to the fact that [by default the length of internal dicttionary used](https://github.com/NVIDIA/DeepLearningExamples/blob/9ba22d1f29d52f9257608bbd39995aeffc991567/PyTorch/SpeechSynthesis/FastPitch/tacotron2/arg_parser.py#L47) which is 148.
Try to pass the argument ```--n-symbols```.

**Comment by Truong-Thanh-Quang** [comment]
Thank @kdorichev!
