### ISSUE TITLE
[FastPitch/Pytorch] ReadMe mistake?

### ISSUE THREAD

**Issue by Westis96** [NVIDIA/DeepLearningExamples#620]
In the ReadMe from FastPitch:

##### Training performance: NVIDIA DGX-1 (8x V100 16GB)

Our results were obtained by running the `./platform/DGX1_FastPitch_{AMP,FP32}_8GPU.sh`
training script in the PyTorch 20.06-py3 NGC container on NVIDIA DGX-1 with
8x V100 16GB GPUs. Performance numbers, in output mel-scale spectrogram frames per second, were averaged over
an entire training epoch.

|Number of GPUs|Batch size per GPU|Frames/s with mixed precision|Frames/s with FP32|Speed-up with mixed precision|Multi-GPU strong scaling with mixed precision|Multi-GPU strong scaling with FP32|
|---:|----------------:|-------:|-------:|-----:|-----:|-----:|
|  1 | 64@AMP, 32@FP32 | 110370 |  41066 | 2.69 | 1.00 | 1.00 |
|  4 | 64@AMP, 32@FP32 | 402368 | 153853 | 2.62 | 3.65 | 3.75 |
|  8 | 32@AMP, 32@FP32 | 570968 | 296767 | 1.92 | 5.17 | 7.23 |

To achieve these same results, follow the steps in the [Quick Start Guide](#quick-start-guide).

###### Expected training time

The following table shows the expected training time for convergence for 1500 epochs:

|Number of GPUs|Batch size per GPU|Time to train with mixed precision (Hrs)|Time to train with TF32 (Hrs)|Speed-up with mixed precision|
|---:|-----------------:|-----:|-----:|-----:|
|  1 | 64@AMP,  32@FP32 | 27.6 | 72.7 | 2.63 |
|  4 | 64@AMP,  32@FP32 |  8.2 | 20.3 | 2.48 |
|  8 | 32@AMP,  32@FP32 |  5.9 | 10.9 | 1.85 |

"Time to train with TF32 (Hrs)"

Should it not be FP32 instead of TF32 as TF32 is a new feature in Ampere not available in Volta?

**Comment by alancucki** [comment]
Hi @Westis96 ,

you are correct, thanks for catching this!
