### ISSUE TITLE
[Bert/TF] Loading my own checkpoint after pretraining

### ISSUE THREAD

**Issue by albert-ba** [NVIDIA/DeepLearningExamples#626]
I'm pretrained a Bert Base model, now I want to fine-tune the model.
So I'm using this command line:
`bash scripts/run_glue.sh MRPC 16 3e-6 fp32 false 8 128 64 base 0.1`

My checkpoint is at this path:
`results/tf_bert_pretraining_adam_base_fp32_gbs112_200630080744`
So I need to change run_glue.py file, and replace:
    `export BERT_DIR=data/download/google_pretrained_weights/uncased_L-12_H-768_A-12`
with :
    `export BERT_DIR=results/tf_bert_pretraining_adam_base_fp32_gbs112_200630080744`

But I keep getting this error:
```
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for results/tf_bert_pretraining_adam_base_fp32_gbs112_20
0630080744/bert_model.ckpt
```

So I tried:
    `export BERT_DIR=results/tf_bert_pretraining_adam_base_fp32_gbs112_200630080744/bert_model.ckpt`
But nothing.

This is how my dir (results/tf_bert_pretraining_adam_base_fp32_gbs112_200630080744/) looks like:
![image](https://user-images.githubusercontent.com/50859478/88802588-f2bc4f80-d1b3-11ea-9ec9-044753b46fb2.png)

One more thing when I'm training with direct run , I'm mean:
```
python3.6 run_classifier.py ....  --init_checkpoint=
/raid/DeepLearningExamples/TensorFlow/LanguageModeling/BERT/results/tf_bert_pretraining_adam_base_fp32_gbs112_200630080744/  
```
It runs smooth.

I'll be happy for your help!
Thanks!

**Comment by swethmandava** [comment]
The folder doesn't have a checkpoint named `results/tf_bert_pretraining_adam_base_fp32_gbs112_200630080744/bert_model.ckpt` The checkpoint seems to be named as `results/tf_bert_pretraining_adam_base_fp32_gbs112_20
0630080744/model.ckpt-1140000`

Please pass the checkpoint since it is non-default.
