### ISSUE TITLE
Tacotron2 Pytorch NCG Container 

### ISSUE THREAD

**Issue by taylerpauls** [NVIDIA/DeepLearningExamples#632]
Hi!

Training this on an aws ec2 instance using a dataset of size 6GB.

In order to build the NCG container successfully I had to put the data outside of the root of the code. 
then when i moved it back in to preprocess_mels.py it runs out of space. Any ideas on what instance is required or what size is required or best ways to optimize container space ?

**Comment by GrzegorzKarchNV** [comment]
Hi @taylerpauls 

for dataset of size 6GB you'll need additional ~4GB for mel spectrograms. Please contact AWS support for details about instances.

**Comment by taylerpauls** [comment]
Yes, I figured it out with the instance, thank you for your reply!

**Comment by GrzegorzKarchNV** [comment]
you're welcome!
