### ISSUE TITLE
when to release the bert tensorrt   for tensorrt 7.1 ? 

### ISSUE THREAD

**Issue by winself** [NVIDIA/DeepLearningExamples#638]
I need to use the tensorrt (version 7.1) . But I run the "builder.py" to get the tensorrt engine.  when I use fp16 ,the error is 

"[TensorRT] ERROR: l0_attention_self_context_layer: could not find any supported formats consistent with input/output data types
[TensorRT] ERROR: ../builder/cudnnBuilderGraphNodes.cpp (743) - Misc Error in reportPluginError: 0 (could not find any supported formats consistent with input/output data types)
[TensorRT] ERROR: ../builder/cudnnBuilderGraphNodes.cpp (743) - Misc Error in reportPluginError: 0 (could not find any supported formats consistent with input/output data types)
[TensorRT] INFO: build engine in 0.977 Sec
Traceback (most recent call last):
  File "builder_ours.py", line 634, in <module>
    main()
  File "builder_ours.py", line 621, in main
    with build_engine(args.batch_size, args.sequence_length, config, weights_dict, args.squad_json, args.vocab_file, calib_cache, args.calib_num) as engine:
AttributeError: __enter__" 

can you give some suggestion?  

looking forward to your reply . 

thank you

**Comment by rajeevsrao** [comment]
@winself We are working on a more complete solution to support int8 inferencing for demoBERT, which is expected towards the end of year. In the meantime you can find the BERT sample for TensorRT 7.1 at this location: https://github.com/NVIDIA/TensorRT/tree/master/demo/BERT

**Comment by winself** [comment]
@rajeevsrao  thank you !  Looking forward to your great work.

**Comment by swethmandava** [comment]
@winself Please refer to #728 . Thanks for your patience :)
