### ISSUE TITLE
Building with Singularity

### ISSUE THREAD

**Issue by abhi060698** [NVIDIA/DeepLearningExamples#64]
How do I build the same file using Singularity instead of Docker

**Comment by swethmandava** [comment]
You will have to create your own recipe file https://singularity.lbl.gov/docs-build-container

**Comment by renganxu** [comment]
@abhi060698 You can just convert the Docker to Singularity easily. I always use the Singularity container. Check how to do that in Figure 11 in our document https://www.emc.com/collateral/technical-documentation/h17354-dl-architecture-guide.pdf. Note that there was a typo: "ngcr.io" should be "nvcr.io"
