### ISSUE TITLE
[BERT/PyTorch] WikiExtractor.py not found

### ISSUE THREAD

**Issue by paulhendricks** [NVIDIA/DeepLearningExamples#641]
Related to **Model/Framework(s)** 
PyTorch/LanguageModeling/BERT

**Describe the bug**
WikiExtractor.py not found - recent changes to https://github.com/attardi/wikiextractor have caused the WikiExtractor.py to be removed. See this issue: https://github.com/attardi/wikiextractor/issues/212

**To Reproduce**

See here: https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/LanguageModeling/BERT#getting-the-data

**Expected behavior**
Updated bertPrep.py to work with modified wikiextractor and successfully process downloaded data.

**Environment**
Please provide at least:
* Container version (e.g. pytorch:19.05-py3): nvcr.io/nvidia/pytorch:20.07-py3
* GPUs in the system: (e.g. 8x Tesla V100-SXM2-16GB): 4x V100
* CUDA driver version (e.g. 418.67): 450.51.05

**Solution**

```
cd /workspace/wikiextractor
git checkout 6408a430fc504a38b04d37ce5e7fc740191dee16
```

**Comment by sharathts** [comment]
wikiextractor comes in the docker image that is built. If you run in the container that is built by following the quick start guide, the error won't occur:
https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/LanguageModeling/BERT/Dockerfile#L22

**Comment by paulhendricks** [comment]
@sharathts - please re-open this issue.

Can you read the above issue? There are changes to the wikiextractor repository that now result in the data preparation steps causing errors. 

I am more than happy to see this issue closed but unfortunately there are some slight changes here that need to take place.

Two solutions:

- Change the git clone within the Dockerfile here to use the 6408a430fc504a38b04d37ce5e7fc740191dee16 commit from Wikiextractor: https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/LanguageModeling/BERT/Dockerfile#L22
- Modify here to work with the updated Wikiextractor package: https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/LanguageModeling/BERT/data/bertPrep.py#L78

**Comment by paulhendricks** [comment]
Quick verification on your end:

```
bash scripts/docker/build.sh
bash scripts/docker/launch.sh
```

And once inside the container: 

```
cat /workspace/wikiextractor/WikiExtractor.py
```

**Comment by sharathts** [comment]
Thank for pointing it out and I encountered the same.

here is the PR to fix it https://github.com/NVIDIA/DeepLearningExamples/pull/645.

I have reopened the issue, feel free to close it if you think the above solution works.
