### ISSUE TITLE
[SSD/PyTorch] random_horiz_flip.cu invalid device function

### ISSUE THREAD

**Issue by Pol52** [NVIDIA/DeepLearningExamples#649]
I have been trying to reproduce the code out of the docker container but I keep getting this error when I run training:

THCudaCheck FAIL file=/home/pinnocenti/vmr/SSD/csrc/random_horiz_flip.cu line=158 error=98 : invalid device function

Have tried reinstalling pytorch with conda as well as building it from source, but nothing changes. 
The gpu is a Nvidia GTX Titan X.
Can anyone point me in some direction?

**Comment by Pol52** [comment]
swapped to a new rtx 2080 and it started working again, probably old architecture on previous gpu. Closing the issue

**Comment by douzsh** [comment]
same error while trianing on V100 with CUDA10.0
