### ISSUE TITLE
Setup Jasper without Docker

### ISSUE THREAD

**Issue by swarajbadhei** [NVIDIA/DeepLearningExamples#656]
Related to /NVIDIA/DeepLearningExamples/tree/master/PyTorch/SpeechRecognition/Jasper

Actually I am working on a remote server where I do not have admin rights to install docker. I really need to know if I can set up Jasper without using Docker. 

It would be of great help if I could do this without docker

GPUs in the system: Tesla P40
 CUDA toolkit version: 10.0

**Comment by alancucki** [comment]
Hi @swarajbadhei ,

sorry for a late reply. Yes, virtual envs are one way to go about it.
