### ISSUE TITLE
[trtis_cpp in Tacotron2/Pytorch] utf-8 support

### ISSUE THREAD

**Issue by itzsimpl** [NVIDIA/DeepLearningExamples#663]
Related to **trtis_cpp in Tacotron2waveglow/Pytorch(s)** 

**Describe the bug**
I'm having issues with utf-8 support. I've successfully trained a model, which requires utf-8 support. In order to do that I had to change the list of acceptable symbols. However when trying to build with the `trtis_cpp` custom TensorRT backaned I'm having issues with utf-8 support. 

1. the `nvcr.io/nvidia/tensorrtserver:20.02-py3` container does not support utf-8, which can be solved by adding `ENV LANG C.UTF-8` to `Dockerfile.trtis`
2. even if I provide a `mapping.txt` with the additional utf-8 characters, I receive errors of the form "Could not find (196) in the alphabet."

**Comment by GrzegorzKarchNV** [comment]
Hi @itzsimpl could you please provide the full error message?
