### ISSUE TITLE
[FasterTransformer/v2.1] A bug of add_QKV_bias

### ISSUE THREAD

**Issue by ligonzheng** [NVIDIA/DeepLearningExamples#664]
Hello,
   At the kernel  add_QKV_bias from file open_attention.cu, the implementation of half has a problem:
    `dst_ptr[target_id]` = __hadd2(src_ptr[tid],  __ldg(&bias_ptr[bias_id]));
  should be changed to : 
     `dst_ptr[tid]` = __hadd2(src_ptr[tid],  __ldg(&bias_ptr[bias_id]));
The q_buf_ and Q are one-in-one, so their index should be consistent. But the target_id has a wrong number when batch > 1 or sequence_len > 1.
    This is my debug print in this kernel ,
tid 32, target_id 64, bias_id 0 
tid 33, target_id 65, bias_id 1 
tid 34, target_id 66, bias_id 2 
tid 35, target_id 67, bias_id 3 
tid 36, target_id 72, bias_id 4 
tid 37, target_id 73, bias_id 5 
tid 38, target_id 74, bias_id 6 
tid 39, target_id 75, bias_id 7 
tid 40, target_id 80, bias_id 8 
tid 41, target_id 81, bias_id 9 
tid 42, target_id 82, bias_id 10 
tid 43, target_id 83, bias_id 11 
tid 44, target_id 88, bias_id 12 
tid 45, target_id 89, bias_id 13 
tid 46, target_id 90, bias_id 14 
tid 47, target_id 91, bias_id 15 
tid 48, target_id 96, bias_id 16 
tid 49, target_id 97, bias_id 17 
tid 50, target_id 98, bias_id 18 
tid 51, target_id 99, bias_id 19 
tid 52, target_id 104, bias_id 20 
tid 53, target_id 105, bias_id 21 
tid 54, target_id 106, bias_id 22 
tid 55, target_id 107, bias_id 23 
tid 56, target_id 112, bias_id 24 
tid 57, target_id 113, bias_id 25 
tid 58, target_id 114, bias_id 26 
tid 59, target_id 115, bias_id 27 
tid 60, target_id 120, bias_id 28 
tid 61, target_id 121, bias_id 29 
tid 62, target_id 122, bias_id 30 
tid 63, target_id 123, bias_id 31 
tid 0, target_id 0, bias_id 0 
tid 1, target_id 1, bias_id 1 
tid 2, target_id 2, bias_id 2 
tid 3, target_id 3, bias_id 3 
tid 4, target_id 8, bias_id 4 
tid 5, target_id 9, bias_id 5 
tid 6, target_id 10, bias_id 6 
tid 7, target_id 11, bias_id 7 
tid 8, target_id 16, bias_id 8 
tid 9, target_id 17, bias_id 9 
tid 10, target_id 18, bias_id 10 
tid 11, target_id 19, bias_id 11 
tid 12, target_id 24, bias_id 12 
tid 13, target_id 25, bias_id 13 
tid 14, target_id 26, bias_id 14 
tid 15, target_id 27, bias_id 15 
tid 16, target_id 32, bias_id 16 
tid 17, target_id 33, bias_id 17 
tid 18, target_id 34, bias_id 18 
tid 19, target_id 35, bias_id 19 
tid 20, target_id 40, bias_id 20 
tid 21, target_id 41, bias_id 21 
tid 22, target_id 42, bias_id 22 
tid 23, target_id 43, bias_id 23 
tid 24, target_id 48, bias_id 24 
tid 25, target_id 49, bias_id 25 
tid 26, target_id 50, bias_id 26 
tid 27, target_id 51, bias_id 27 
tid 28, target_id 56, bias_id 28 
tid 29, target_id 57, bias_id 29 
tid 30, target_id 58, bias_id 30 
tid 31, target_id 59, bias_id 31 

My setting is :
    int batch_size = 1;
    int seq_len = 2;
    int head_num = 16;
    int size_per_head = 4;

**Comment by byshiue** [comment]
Thanks for you feedback. This is not a bug. We do a transpose to convert q:[batch, seq_len, head, size] -> q':[batch, head, seq_len, size].

**Comment by ligonzheng** [comment]
Oh, I get it.
But why we need to do this transpose ?

**Comment by byshiue** [comment]
> Oh, I get it.
> But why we need to do this transpose ?

To compute Q*K by cublas batch gemm
