### ISSUE TITLE
[DLRM-PyT] Quick Start Guide seems to miss something

### ISSUE THREAD

**Issue by LiuJieShane** [NVIDIA/DeepLearningExamples#665]
Following Quick Start Guide
Get error message when start training

Using the Volta-optimized dot interaction kernels
Traceback (most recent call last):
File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main "main", mod_spec)
File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code exec(code, run_globals)
File "/DLRM/dlrm/scripts/main.py", line 26, in from dlrm.model.single import Dlrm
File "/DLRM/dlrm/model/single.py", line 19, in from dlrm.nn.factories import create_interaction
File "/DLRM/dlrm/nn/factories.py", line 17, in from dlrm.nn.embeddings import (
File "/DLRM/dlrm/nn/embeddings.py", line 22, in from dlrm import cuda_ext
File "/DLRM/dlrm/cuda_ext/init.py", line 1, in from .dot_based_interact import dotBasedInteract
File "/DLRM/dlrm/cuda_ext/dot_based_interact.py", line 10, in from dlrm.cuda_ext import interaction_volta as interaction
ImportError: cannot import name 'interaction_volta'

**Comment by tgrel** [comment]
Hi @LiuJieShane could you please share some more information about your setup. Are you running inside a docker container? If yes, do you use the Dockerfile we provided in this repository? Do you mount some other code in the docker container and use this externally mounted files instead of the ones that are copied into the container when building?

This error seems to indicate that one of the custom CUDA kernels used in this model is not present. Some possible reasons:
- It hasn't been compiled by running `pip install --no-cache-dir -e .`
- It was installed but the installation failed for some reason
- It was installed in a different location or a different conda env

**Comment by LiuJieShane** [comment]
my setup
***************************************************************************************************
git clone https://github.com/NVIDIA/DeepLearningExamples
cd DeepLearningExamples/PyTorch/Recommendation/DLRM
docker build -t nvidia_dlrm_pyt .
docker build -t nvidia_dlrm_spark -f Dockerfile_spark . 
mkdir -p data
docker run --runtime=nvidia -it --rm --ipc=host  -v ${PWD}/data:/data nvidia_dlrm_spark bash
cd preproc
./prepare_dataset.sh DGX2 3
./prepare_dataset.sh DGX2 15
./prepare_dataset.sh CPU 15
exit
docker run --runtime=nvidia -it --rm --ipc=host  -v ${PWD}/data:/data nvidia_dlrm_pyt bash
python -m dlrm.scripts.main --mode train --dataset /data/dlrm/binary_dataset/
****************************************************************************************************
 I am running inside the docker container. I think the bug is due to that interaction_volta as interaction is written in CUDA and wrapped by pybind. We should build first and some instructions should be added to the quick start guide.

**Comment by tgrel** [comment]
The kernel should get compiled when building this docker layer: https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/Recommendation/DLRM/Dockerfile#L25
This should trigger building this extension here: https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/Recommendation/DLRM/setup.py#L42

Unfortunately, I've tried and could not reproduce your issue. I've just run these commands to verify that the extension is indeed present:

git clone https://github.com/NVIDIA/DeepLearningExamples
cd DeepLearningExamples/PyTorch/Recommendation/DLRM
docker build -t nvidia_dlrm_pyt .
docker run --runtime=nvidia -it --rm --ipc=host nvidia_dlrm_pyt python -c 'from dlrm.nn.interactions import CudaDotInteraction'

Could you please run those as well on your machine and get back to me with the result?

I can see your stacktrace paths begin with /DLRM. Are you sure you haven't introduced any changes to the code/setup?

Also, what GPU do you use?

**Comment by LiuJieShane** [comment]
1. The paths begin with /DLRM because I use docker run --runtime=nvidia -it --rm --ipc=host -v ${PWD}:/DLRM nvidia_dlrm_pyt bash

2. The GPU I use is GeForce 2080Ti.

3. The result of running docker run --runtime=nvidia -it --rm --ipc=host nvidia_dlrm_pyt python -c 'from dlrm.nn.interactions import CudaDotInteraction' is as belows:

kingsleyl@A41010:~/Projects/DeepLearningExamples/PyTorch/Recommendation/DLRM$ docker run --runtime=nvidia -it --rm --ipc=host nvidia_dlrm_pyt python -c 'from dlrm.nn.interactions import CudaDotInteraction'

=============
== PyTorch ==
=============

NVIDIA Release 20.07 (build 14714849.1)
PyTorch Version 1.6.0a0+9907a3e

Container image Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.

Copyright (c) 2014-2020 Facebook Inc.
Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
Copyright (c) 2011-2013 NYU                      (Clement Farabet)
Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)
Copyright (c) 2015      Google Inc.
Copyright (c) 2015      Yangqing Jia
Copyright (c) 2013-2016 The Caffe contributors
All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying project or file.

NOTE: MOFED driver for multi-node communication was not detected.
      Multi-node communication performance may be reduced.

Using the Volta-optimized dot interaction kernels

**Comment by tgrel** [comment]
This indicates the kernel is compiled correctly. Do you run something like `cd /DLRM` at the beginning to the working directory to the one you mount to the container? If yes, then this would explain the problem – the /DLRM path does not contain the compiled kernels as those are compiled only into `/workspace/dlrm` during the docker build stage.

**Comment by LiuJieShane** [comment]
OK, I think the issue can be closed. Thank you.
