### ISSUE TITLE
Update Readme for Unet Industrial

### ISSUE THREAD

**Issue by aunsid** [NVIDIA/DeepLearningExamples#669]
Step 3 is missing *--gpus all* I suppose. Without it I could not get it to run on my machine.

`
nvidia-docker run -it --rm --gpus all --shm-size=2g --ulimit memlock=-1 --ulimit stack=67108864
-v <path/to/dataset/directory>:/data/ \
-v <path/to/result/directory>:/results \
 unet_industrial:latest
`

**Comment by Bhuvan-21** [comment]
Can I work on this? I am looking for good first issues.

**Comment by aunsid** [comment]
I did provide the solution, didn't i?

**Comment by Bhuvan-21** [comment]
Yeah, but I saw that It wasn't included in the code.
I wanted to ask, should I make the Pull request after making this change?

**Comment by aunsid** [comment]
You could if you wanted to.

**Comment by Bhuvan-21** [comment]
Can any admin/maintainer confirm??

**Comment by pribalta** [comment]
Hi, looks like when this readme was originally posted we were using an older version of nvidia-docker. We'll be updating the readme with your proposed solution. Thanks!
