### ISSUE TITLE
jupyter docker image still requires password

### ISSUE THREAD

**Issue by vinhngx** [NVIDIA/DeepLearningExamples#68]
According to this config file:

[https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/Segmentation/MaskRCNN/pytorch/docker/docker-jupyter/jupyter_notebook_config.py](url)

jupyter password should be empty, but when starting jupyter docker it still requires password.

**Comment by sharathts** [comment]
We don't support jupyter notebook. It's present in order to be compatible with facebook's upstream mask rcnn
