### ISSUE TITLE
RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors.  Available functions are [CPUTensorId, CUDATensorId, QuantizedCPUTensorId, VariableTensorId]

### ISSUE THREAD

**Issue by SaitoAsahi** [NVIDIA/DeepLearningExamples#680]
Related to **Model/Framework(s)** 
an error I have never encountered ever

**Describe the bug**
I got an error message bellow and can't fix it..
RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors.  Available functions are [CPUTensorId, CUDATensorId, QuantizedCPUTensorId, VariableTensorId]

**To Reproduce**
1. use the image set of COCO
2. run the file of inferencing SSD
2. Got The Eroor

**Expected behavior**
the error occur with certain images.
may be the error happens when this SSD model cannot find bounding boxes?

**Comment by lobracost** [comment]
Same here. I figured out that the problem occurs when we pass one-colored frames to the neural net. For example if you open your camera with OpenCV and try to run some object detection with the ssd, everything runs fine until you put a blank white paper on the camera. It then reads an one-colored frame and reproduces this error. When you do video analysis this occurs on shot changes(especially at the beginning or the end of the videos). 

Example:

This video runs fine:
https://www.youtube.com/watch?v=aHhEw9SJ2ec&t=5s

But this throws the above error on the first frames:
https://www.youtube.com/watch?v=sY1S34973zA&t=2s

**Comment by lobracost** [comment]
The problem is that the torch hub model is not updated. I just opened a bug report so it can be updated. See the problem here:
https://github.com/NVIDIA/DeepLearningExamples/issues/685

If you just put these 2 lines of code to your utils.py files it will work. Or you can use the github code instead of torch hub.

**Comment by lobracost** [comment]
If you cannot fix it on your own try the following.

First go to ~/.cache/torch/hub/ and erase everything.
Then, at the point of your code where you load the model write the following:
`
        home_dir = expanduser("~")
        nvidia_dir = home_dir + '/.cache/torch/hub/NVIDIA_DeepLearningExamples_torchhub'
        a = os.path.exists(nvidia_dir)
        if not a:
            model = torch.hub.load('NVIDIA/DeepLearningExamples:torchhub',
                                        'nvidia_ssd', model_math=self.precision)
            
            utils_file = nvidia_dir + '/PyTorch/Detection/SSD/src/utils.py'
            
            with open(utils_file, 'r') as f:
                get_all = f.readlines()

            spaces_str = '    '
            with open(utils_file, 'w') as f:
                for i, line in enumerate(get_all, 1):
                    if i == 196:
                        f.writelines("\n")
                        f.writelines(spaces_str + spaces_str + "if not bboxes_out:\n")
                        f.writelines(spaces_str + spaces_str + spaces_str + "return [torch.tensor([]) for _ in range(3)]\n")
                        f.writelines("\n")
                    else:
                        f.writelines(line)
        else:
            model = torch.hub.load('NVIDIA/DeepLearningExamples:torchhub',
                                        'nvidia_ssd', model_math=self.precision)

        utils = torch.hub.load('NVIDIA/DeepLearningExamples:torchhub',
                                    'nvidia_ssd_processing_utils')

`

This code modifies the utils file the first time you load it and then it is ready to go.

Hope it helped.

**Comment by siyamsajeebkhan** [comment]
> If you cannot fix it on your own try the following.
> 
> First go to
> `~/.cache/torch/hub/`
> and erase everything.
> Then, at the point of your code where you load the model write the following
> 
> ```python
>        home_dir = expanduser("~")
>        nvidia_dir = home_dir + '/.cache/torch/hub/NVIDIA_DeepLearningExamples_torchhub'
>         a = os.path.exists(nvidia_dir)
>         if not a:
>             model = torch.hub.load('NVIDIA/DeepLearningExamples:torchhub',
>                                         'nvidia_ssd', model_math=self.precision)
> 
>             utils_file = nvidia_dir + '/PyTorch/Detection/SSD/src/utils.py'
> 
>             with open(utils_file, 'r') as f:
>                 get_all = f.readlines()
> 
>             spaces_str = '    '
>             with open(utils_file, 'w') as f:
>                 for i, line in enumerate(get_all, 1):
>                     if i == 196:
>                         f.writelines("\n")
>                         f.writelines(spaces_str + spaces_str + "if not bboxes_out:\n")
>                         f.writelines(spaces_str + spaces_str + spaces_str + "return [torch.tensor([]) for _ in range(3)]\n")
>                         f.writelines("\n")
>                     else:
>                         f.writelines(line)
>         else:
>             model = torch.hub.load('NVIDIA/DeepLearningExamples:torchhub',
>                                         'nvidia_ssd', model_math=self.precision)
>         
> ```
> 
> This code modifies the utils file the first time you load it and then it is ready to go.
> 
> Hope it helped.

Thanks a lot! I was stuck with it for a while. Your solution worked fine for me! Just a small correction, it should return torch.tensor([[]]) for the bboxes part instead of torch.tensor([]) as originally it returns a 2-dim tensor. The others are fine with 1-dim.

**Comment by nv-kkudrynski** [comment]
Hi, the 'load' function of Pytorch/hub downloads the requested entrypoint's original repo and puts it into cache. To make sure you are in sync with the latest changes, you can use 'force_reload=True'.
