### ISSUE TITLE
[Tacotron2-Waveglow/PyTorch] tacotron & waveglow trt engine inference ERROR

### ISSUE THREAD

**Issue by RaymondTsao** [NVIDIA/DeepLearningExamples#681]
Related to **Model/Framework(s)** 
[Tacotron2-Waveglow/PyTorch]

**Describe the bug**

I try inference by pre-trained models is ok:
python inference.py --tacotron2 nvidia_tacotron2pyt_fp16_20190427 --waveglow nvidia_waveglowpyt_fp16_20190427 -o output/ --include-warmup -i phrases/phrase_1_64.txt --fp16 --log-file=output/nvlog_fp16.json

Then I try to inference by trt engine,

The follow steps about tacotron + waveglow tensorRT inference, models are from NGC models repository

**1. tacotron exports to onnx :**
python export_tacotron2_onnx.py --tacotron2 nvidia_tacotron2pyt_fp16_20190427 -o exports/ --fp16

**2. waveglow 256 channel exports to onnx :**
python export_waveglow_onnx.py --waveglow audio/nvidia_waveglow256pyt_fp16 --wn-channels 256 -o exports/ --fp16

**3. tacotron & waveglow exports onnx to trt engine :**
python export_onnx2trt.py -o audio/ --encoder exports/encoder.onnx --decoder exports/decoder_iter.onnx --postnet exports/postnet.onnx --waveglow exports/waveglow.onnx --fp16

**4. tacotron & waveglow trt engine inference :**
python inference_trt.py -i test.txt -o audio/ --encoder audio/encoder_fp16.engine --decoder audio/decoder_iter_fp16.engine --postnet audio/postnet_fp16.engine --waveglow audio/waveglow_fp16.engine --fp16

**Then I get the following error:**
[TensorRT] WARNING: TensorRT was linked against cuBLAS 10.2.2 but loaded cuBLAS 10.2.1
[TensorRT] WARNING: TensorRT was linked against cuBLAS 10.2.2 but loaded cuBLAS 10.2.1
[TensorRT] WARNING: TensorRT was linked against cuBLAS 10.2.2 but loaded cuBLAS 10.2.1
[TensorRT] WARNING: TensorRT was linked against cuBLAS 10.2.2 but loaded cuBLAS 10.2.1
Running Tacotron2 Encoder
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::948, condition: profileMaxDims.d[i] >= dimensions.d[i]
[TensorRT] ERROR: Parameter check failed at: engine.cpp::resolveSlots::1092, condition: allInputDimensionsSpecified(routine)
Running Tacotron2 Decoder
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::948, condition: profileMaxDims.d[i] >= dimensions.d[i]
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::948, condition: profileMaxDims.d[i] >= dimensions.d[i]
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::948, condition: profileMaxDims.d[i] >= dimensions.d[i]
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::948, condition: profileMaxDims.d[i] >= dimensions.d[i]
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::948, condition: profileMaxDims.d[i] >= dimensions.d[i]
[TensorRT] ERROR: Parameter check failed at: engine.cpp::resolveSlots::1092, condition: allInputDimensionsSpecified(routine)
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::948, condition: profileMaxDims.d[i] >= dimensions.d[i]
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::948, condition: profileMaxDims.d[i] >= dimensions.d[i]
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::948, condition: profileMaxDims.d[i] >= dimensions.d[i]
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::948, condition: profileMaxDims.d[i] >= dimensions.d[i]
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::948, condition: profileMaxDims.d[i] >= dimensions.d[i]
[TensorRT] ERROR: Parameter check failed at: engine.cpp::resolveSlots::1092, condition: allInputDimensionsSpecified(routine)

steps 1~3 will output model success, but cannot inference.

Any suggestions about this problem? I try to search this error but it's seldom issues about this.

I will thankful if you answer that Orz...

**Comment by jmmarko** [comment]
Based on the log obviously the problem is in the cuBLAS version: "cuBLAS 10.2.2 but loaded cuBLAS 10.2.1". When converting the models it is important that you use the same version of PyTorch as you will use for the inference. Furthermore, the conversion should also be performed on the same graphic card - e.g. if you will perform inference on T4 also the conversion should be done on T4.

[Here](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_20-07.html#rel_20-07) you can check the contents of the PyTorch container. You will also see the info about the cuBLAS version.

**Comment by RaymondTsao** [comment]
> Based on the log obviously the problem is in the cuBLAS version: "cuBLAS 10.2.2 but loaded cuBLAS 10.2.1". When converting the models it is important that you use the same version of PyTorch as you will use for the inference. Furthermore, the conversion should also be performed on the same graphic card - e.g. if you will perform inference on T4 also the conversion should be done on T4.
> 
> [Here](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_20-07.html#rel_20-07) you can check the contents of the PyTorch container. You will also see the info about the cuBLAS version.

Hi, @jmmarko , appreciate for your feedback.

I converted pre-trained models(from NGC models repository) to trt engine & inference on same environment and same GPU(only one), so the version of **Pytorch(1.4.0)** also the same as well. So I confused about this error :(

following are my environment version:
Pytorch(1.4.0)
cuda(10.2.89)
cudnn(7.6.5)

**Comment by jmmarko** [comment]
If you have the same environment that this warning is really strange. Are you using Docker or you have setup the environment locally on the machine by yourself?

**Comment by jmmarko** [comment]
Maybe try it using a Docker since all the environment is already setup there. With this, you will be able to test if there is something missing in your environment. I transformed all the models without any problems so far.

**Comment by RaymondTsao** [comment]
> Maybe try it using a Docker since all the environment is already setup there. With this, you will be able to test if there is something missing in your environment. I transformed all the models without any problems so far.

OK, I will try in Docker. Thank you so much for helping

**Comment by RaymondTsao** [comment]
> Maybe try it using a Docker since all the environment is already setup there. With this, you will be able to test if there is something missing in your environment. I transformed all the models without any problems so far.

hi, @jmmarko, I try to it again in container [follow](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/SpeechSynthesis/Tacotron2/trt)

**but engine inference have OOM error:**

python trt/inference_trt.py -i test.txt --encoder output/encoder_fp16.engine --decoder output/decoder_iter_fp16.engine --postnet output/postnet_fp16.engine --waveglow output/waveglow_fp16.engine -o output/ --fp16

**[TensorRT] ERROR: ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
[TensorRT] ERROR: FAILED_ALLOCATION: std::exception
Traceback (most recent call last):
  File "trt/inference_trt.py", line 385, in <module>
    main()
  File "trt/inference_trt.py", line 344, in main
    sequences = sequences.to(torch.int16)
RuntimeError: CUDA error: out of memory**

have any suggestions? thank a lot.

**Comment by jmmarko** [comment]
The problem is with the memory of your GPU. Which GPU do you use? Use can check how much memory is used by running nvidia-smi. I would guess that the problem is in your test.txt. Try with a very short text (1 line, 130 chars) to see if it works.

**Comment by RaymondTsao** [comment]
> The problem is with the memory of your GPU. Which GPU do you use? Use can check how much memory is used by running nvidia-smi. I would guess that the problem is in your test.txt. Try with a very short text (1 line, 130 chars) to see if it works.

Hi, @jmmarko, appreciate you still feedback : )

I use only one **GeForce RTX 2080 Ti.**

**my test.txt is like following:**

The forms of printed letters should be beautiful.
She sells seashells by the seashore, shells she sells are great
The forms of printed letters should be beautiful.

and I try even ONLY one or two words also out of memory.... :(

**Comment by jmmarko** [comment]
Ok, this is getting really strange now... 11GB of RAM should be more than enough. So I don't have any good idea what else could go wrong. You can also try and follow the instructions provided in the folder trtis_cpp, and see if this will work for you.

What is your usecase anyway? How would you like to use it in the end?

**Comment by RaymondTsao** [comment]
> Ok, this is getting really strange now... 11GB of RAM should be more than enough. So I don't have any good idea what else could go wrong. You can also try and follow the instructions provided in the folder trtis_cpp, and see if this will work for you.
> 
> What is your usecase anyway? How would you like to use it in the end?

@jmmarko , ok, I will try in trtis_cpp folder, thanks your reply : )

I just need to decrease my own model synthesis time on GPU.
Did you really speedup your inference time by tensorrt engine ?

**Comment by jmmarko** [comment]
Yes, you do. In that case, the other option _trtis_cpp_ will be even better because it ensemble both models, so that all (whole synthesis) is done on the GPU, and it uses the Triton server. Give it a try.

**Comment by RaymondTsao** [comment]
> Yes, you do. In that case, the other option _trtis_cpp_ will be even better because it ensemble both models, so that all (whole synthesis) is done on the GPU, and it uses the Triton server. Give it a try.

Hi, @jmmarko. trtis_cpp is work, grateful for your help. : )

**Comment by ivangtorre** [comment]
@jmmarko I have been also doing some trials and it seems that 11GB are not enough.
I finally succedeed with a Titan 12GB Pascal but modifying the file "tensorrt/convert_onnx2trt.py"

I modified Postnet shapes to:
```
shapes=[{"name": "mel_outputs", "min": (1,80,32), "opt": (1,80,768), "max": (1,80,1300)}]`
```

And the WaveGlow shapes to:
```
shapes=[{"name": "mel", "min": (1,80,32),  "opt": (1,80,768),  "max": (1,80,1300)},
        {"name": "z",   "min": (1,8,1024), "opt": (1,8,24576), "max": (1,8,41600)}]
```
