### ISSUE TITLE
[BERT/PyT] Last data_file seems to be skipped during training

### ISSUE THREAD

**Issue by mindest** [NVIDIA/DeepLearningExamples#682]
Related to **BERT/PyTorch** 

**Describe the problem**
In the `run_pretraining.py` file, the training loop starting from [this line](https://github.com/NVIDIA/DeepLearningExamples/blob/8588e9834cff6fe7601e772eb3bb99f7f565c495/PyTorch/LanguageModeling/BERT/run_pretraining.py#L572) seems to iterate for only `num_files-1` times, leaving the last dataloader from the last data file unused. If there is only one file in the input_dir, the outer while True loop will iterates forever.

**Comment by sharathts** [comment]
Thank you for pointing this out, it will be fixed in our next update.
