### ISSUE TITLE
[Model/Framework] Update Torch Hub Model

### ISSUE THREAD

**Issue by lobracost** [NVIDIA/DeepLearningExamples#685]
Related to **Model/Framework(s)** 

**Describe the bug**
There is an issue connected with some bugs reported. The torch hub code for the model is not updated and this lines https://github.com/NVIDIA/DeepLearningExamples/blob/5d36b4fd2fe559b141df0eb1ae8688a329012569/PyTorch/Detection/SSD/src/utils.py#L211-L212 are missing from the  utils.py file. 

Since the code is not updated, it throws an error when there are no objects to detect in the image.

The error is the following:

RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat. This usually means that this function requires a non-empty list of Tensors. Available functions are [CPUTensorId, CUDATensorId, QuantizedCPUTensorId, VariableTensorId]

**To Reproduce**

Use the torch hub model by running the following commands:

`model = torch.hub.load('NVIDIA/DeepLearningExamples:torchhub',
                                    'nvidia_ssd', model_math=self.precision)

utils = torch.hub.load('NVIDIA/DeepLearningExamples:torchhub',
                                    'nvidia_ssd_processing_utils')
 `

Then run the model on an empty image (i.e. a black or white frame etc).

**Comment by nv-kkudrynski** [comment]
Hi, the 'load' function of Pytorch/hub downloads the requested entrypoint's original repo and puts it into cache. To make sure you are in sync with the latest changes, you can use 'force_reload=True'.
