### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by deepakjangr** [NVIDIA/DeepLearningExamples#695]
I am using:
NVIDIA GeForce GT 710. 
Python 3.6.9

![image](https://user-images.githubusercontent.com/68359532/93918891-9f392e80-fd2a-11ea-80ae-244bed8c3f16.png)
![image](https://user-images.githubusercontent.com/68359532/93917888-356c5500-fd29-11ea-981e-1f25fc36abbe.png)
![image](https://user-images.githubusercontent.com/68359532/93918012-5fbe1280-fd29-11ea-84e9-c870ddc30b52.png)
![image](https://user-images.githubusercontent.com/68359532/93918216-a6ac0800-fd29-11ea-9395-ae558a38e136.png)

After running this:
![image](https://user-images.githubusercontent.com/68359532/93918842-8cbef500-fd2a-11ea-89c6-a3aa69083e05.png)

I am facing the RuntimeError: CUDA error: no kernel image is available for execution on the device. 

Appreciate your effort if you could help.

**Comment by GrzegorzKarchNV** [comment]
@deepakjangr could you clarify how the execution in the first and last snippet differ? What is the relation to the code in the screenshots?
