### ISSUE TITLE
No APEX in the Jupyter docker container for PyTorch/Segmentation/MaskRCNN/

### ISSUE THREAD

**Issue by vinhngx** [NVIDIA/DeepLearningExamples#70]
When running the demo notebook Mask_R-CNN_demo from the Jupyter docker built with 

DeepLearningExamples/PyTorch/Segmentation/MaskRCNN/pytorch/docker/docker-jupyter/Dockerfile

I encountered the below error:

/notebooks/maskrcnn-benchmark/maskrcnn_benchmark/layers/nms.py in <module>
      3 from maskrcnn_benchmark import _C
      4 
----> 5 from apex import amp
      6 
      7 # Only valid with fp32 inputs - give AMP the hint

ModuleNotFoundError: No module named 'apex'

**Comment by sharathts** [comment]
https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/Segmentation/MaskRCNN/pytorch/Dockerfile

You would want to build with the above Dockerfile
