### ISSUE TITLE
[Performance of INT8] Feature requested

### ISSUE THREAD

**Issue by Rivendile** [NVIDIA/DeepLearningExamples#703]
It's exciting to see the open source of Fast Transformer v3.0. However, I don't find the performance of INT8 on applications codes in the README.md, while FP32 and FP16 are both analyzed. Where can I find these results?

**Comment by byshiue** [comment]
You can find the performance comparison at subsection "Performance on INT8 without quantizing residual connection" in https://github.com/NVIDIA/DeepLearningExamples/tree/master/FasterTransformer/v3.0#encoder-performance-on-t4-and-tensorflow

**Comment by Rivendile** [comment]
This subsection shows the time and speedup, but it doesn't show the exact match / F1 score like https://github.com/NVIDIA/DeepLearningExamples/tree/master/FasterTransformer/v3.0#performance-on-application-codes-of-tensorflow

**Comment by byshiue** [comment]
https://github.com/NVIDIA/DeepLearningExamples/tree/master/FasterTransformer/v3.0/bert-tf-quantization

**Comment by Rivendile** [comment]
Thanks for your timely reply :)

**Comment by Rivendile** [comment]
The quantization in DeepLearningExamples/FasterTransformer/v3.0/bert-tf-quantization is fake quantizaton which uses FP32 to calculate the quantized values. However, the speedup is tested using INT8 which is 8 bits. Are they the same? Or is there something I misunderstand? Looking forward to your reply.

**Comment by hxbai** [comment]
`bert-tf-quantization` is only for training. You should train a checkpoint and import it with FT tensorflow op. FasterTransformer op does inference in INT8 precision. The whole workflow is in `Evaluate the accuracy of FasterTransformer under INT8` part of README.

**Comment by Rivendile** [comment]
Thanks for your reply.
Besides, I would appreciate it if the mechanism and optimizations taken for INT8 will be made more clearly in the README.
