### ISSUE TITLE
[FastPitch/Pytorch] Multi-speaker setup unclear

### ISSUE THREAD

**Issue by DanRuta** [NVIDIA/DeepLearningExamples#707]
Related to **FastPitch/Pytorch** 

Multi-speaker usage is described in section 3.3.1 of the paper (https://arxiv.org/pdf/2006.06873.pdf), but instructions for how to use multiple speaker data is not described in the README, not is it supported in the code, as far as I can tell from an initial glance.

Has this been left out of the public version of the code, left for personal implementations, or am I overlooking anything?

Thank you

**Comment by alancucki** [comment]
Hi Dan!
Yes, this has been an experimental feature implemented only in the internal version.
We'll add it in the public repository in mid-October, although full examples on multispeaker datasets will arrive later.

**Comment by DanRuta** [comment]
Ah, I see. Thanks for getting back about that, I will keep my eyes open for new commits

**Comment by siddiquelatif** [comment]
> Hi Dan!
> Yes, this has been an experimental feature implemented only in the internal version.
> We'll add it in the public repository in mid-October, although full examples on multispeaker datasets will arrive later.

Hi @alancucki 

Did multi-speaker training is included in the public repository yet? 

Thanks

**Comment by DanRuta** [comment]
Thank you kindly for this, I am working through it, and can confirm it's coming along ok for 5 similar sounding female speakers.

Are you aware of any limitations, such as maximum number of speakers before quality degradation?

I plan to explore this further. Would you have any advice/intuitions for optimising the training for scaling to a larger set of speakers, with more variety (eg male/female)? Eg, hyperparams that should be adjusted for longer/more varied training time/data, or perhaps architecture tweaks?

Thank you for any help

**Comment by alancucki** [comment]
Glad to hear you got it to work. I haven't tried yet scaling up to more speakers, but it's certainly on the roadmap.

With more training data you might want to try to widen the model, for instance by doubling these:
```
--symbols-embedding-dim
--in-fft-d-head
--out-fft-d-head
--in-fft-output-size
--out-fft-output-size
--dur-predictor-filter-size
--pitch-predictor-filter-size
```
or by having two attention heads instead of one.

**Comment by DanRuta** [comment]
Thank you kindly for all the help. I will experiment with these. Great work!
I will close the original issue now.

**Comment by ArEnSc** [comment]
@alancucki I was wondering about this setup as well, and have a couple of questions
For the best results should I be using the 1500.pt pre trained FastSpeech Model, and just resume training at that point with the extra data?  or should I be starting from scratch ?
