### ISSUE TITLE
[FastPitch/Pytorch]  Style transfer

### ISSUE THREAD

**Issue by bkoch4142** [NVIDIA/DeepLearningExamples#709]
How would one go about doing style transfer/changing prosody of the model? Could you explain how to condition on speaker embeddings?

**Comment by alancucki** [comment]
Hi @bkoch4142,
let me break down the question:
* Conditioning on speaker embeddings is described in the [FastPitch paper](https://arxiv.org/abs/2006.06873); we'll add it in the public repository in mid-October.
* Changing the prosody boils down to modifying pitch vectors. You can implement a custom [pitch transform](https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/SpeechSynthesis/FastPitch/pitch_transform.py#L5) that will be called during inference. We'll post Jupyter notebooks with examples in mid/late-October.
* Style transfer is not explicitly supported in this model, but see [Flowtron](https://github.com/NVIDIA/flowtron).
