### ISSUE TITLE
[FastTransformer/Pytorch] Input error, TorchScript FP16 with and without FastTransformer

### ISSUE THREAD

**Issue by Sun-Knight-Soral** [NVIDIA/DeepLearningExamples#717]
Hi, i tried SQUAD demo in FastTransformer 3.0, and got good results. However, when i tried:
```
bash pytorch/scripts/run_squad.sh ths fp16
```
I got error:
```
DeepLearningExamples/FasterTransformer/v3.0/build/pytorch/run_squad.py(474): main
DeepLearningExamples/FasterTransformer/v3.0/build/pytorch/run_squad.py(489): <module>
RuntimeError: expected scalar type Float but found Half
```
And when i tried:
```
bash pytorch/scripts/run_squad.sh thsext fp16
```
i got:
```
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "DeepLearningExamples/FasterTransformer/v3.0/build/pytorch/utils/encoder.py", line 116, in forward
    def forward(self, hidden_states, attention_mask, sequence_lengths=torch.Tensor(0).to(torch.int).cuda()):
        for i in range(self.layer_num):
            hidden_states = self.encoders[i].forward(hidden_states, attention_mask, sequence_lengths)
                            ~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        return (hidden_states,)
RuntimeError: Inconsistency of Tensor type: input
```

Only in TorchScript and FP16 mode i will get problem, my environment:
- T4, CUDA 10.2
- Pytorch 1.6.0

**Comment by byshiue** [comment]
We cannot reproduce this problem. 
Do you test on the image we recommend? (‘nvcr.io/nvidia/pytorch:20.07-py3’)
If yes, do you change any codes? 
If not, can you try this image?

**Comment by Sun-Knight-Soral** [comment]
> We cannot reproduce this problem.
> Do you test on the image we recommend? (‘nvcr.io/nvidia/pytorch:20.07-py3’)
> If yes, do you change any codes?
> If not, can you try this image?

I am sorry that i must run this in my own environment. It seems like a problem of TorchScript, maybe you can tell me the pytorch you use or give me some suggestion? My pytorch was installed by:
```
pip3 install torch
```

**Comment by Sun-Knight-Soral** [comment]
> > We cannot reproduce this problem.
> > Do you test on the image we recommend? (‘nvcr.io/nvidia/pytorch:20.07-py3’)
> > If yes, do you change any codes?
> > If not, can you try this image?
> 
> I am sorry that i must run this in my own environment. It seems like a problem of TorchScript, maybe you can tell me the pytorch you use or give me some suggestion? My pytorch was installed by:
> 
> ```
> pip3 install torch # Pytorch 1.6.0 for CUDA 10.2
> ```
> 
> Thank you very much!

Hi, i got these error with Pytorch 1.6.0. However, with Pytorch 1.5.0, everything is ok.

**Comment by hxbai** [comment]
Hi `bash pytorch/scripts/run_squad.sh ths fp16` runs the model all in pytorch and no FT module is used.

https://github.com/huggingface/transformers/issues/1344#issuecomment-689285426
From this issue, I think this may be a bug of pytorch. We will track this issue continually.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this bug if you still have any problem.
