### ISSUE TITLE
[Tacotron2-Waveglow/PyTorch] Tacotron2 model unavailable in torch.hub

### ISSUE THREAD

**Issue by neychev** [NVIDIA/DeepLearningExamples#725]
Related to **Tacotron2-Waveglow/PyTorch** 

**Describe the bug**
```
import torch
tacotron2 = torch.hub.load('nvidia/DeepLearningExamples:torchhub', 'nvidia_tacotron2')
```
The command above (origins in [this](https://pytorch.org/hub/nvidia_deeplearningexamples_tacotron2/) example) attempts to download the pretrained model from the link below. However, the file is not present there and 404 is returned.
https://api.ngc.nvidia.com/v2/models/nvidia/tacotron2pyt_fp32/versions/1/files/nvidia_tacotron2pyt_fp32_20190306.pth

It was working some time ago (~3 month).

**To Reproduce**
Run the command above or refer to the PyTorch example: https://pytorch.org/hub/nvidia_deeplearningexamples_tacotron2/

Or directly run the Colab notebook: [link](https://colab.research.google.com/github/pytorch/pytorch.github.io/blob/master/assets/hub/nvidia_deeplearningexamples_tacotron2.ipynb)

**Expected behavior**
Model is downloaded like expected or the docs are changed.

**Environment**
Please provide at least:
Colab notebook with GPU runtime or local machine with Ubuntu 18.04 and RTX 2070

* Container version: Ubuntu 18.04 with PyTorch 1.6.0
* GPUs in the system: RTX 2070
* CUDA driver version: 440.100

**Comment by SolomidHero** [comment]
Also, both model checkpoints (`fp16` and `fp32`) are unavailable

**Comment by jiashenC** [comment]
Also related to [this issue](https://github.com/NVIDIA/DeepLearningExamples/issues/721).

**Comment by alvarobartt** [comment]
Hi @neychev, @SolomidHero and @jiashenC! I just created a PR that should fix this issue! Let's wait until they merge it into the torchhub branch so as to be able to work again with `torch.hub`.

**Comment by nv-kkudrynski** [comment]
The issue is fixed. Also, we will soon make an update to benefit from the recently uploaded checkpoints.
