### ISSUE TITLE
[BERT/TF TRT] Cannot download models as they no longer exist.

### ISSUE THREAD

**Issue by GreatA1exander** [NVIDIA/DeepLearningExamples#726]
Related to **Bert on TF TRT** 

**Describe the bug**
The network downloading script is no longer working as the networks seem to have disappeared from NGC. Is there an alternative location for these networks?

**To Reproduce**
Run the script/download_model.sh with any options.
Observe a failed to find error.

trtuser@69b542deeb5c:/workspace/bert$ ./scripts/download_model.sh base fp32 128 v1_1
Downloading BERT-base with fine-tuned precision fp32 and sequence length 128 from NGC
Error: nvidia/bert_tf_v1_1_base_fp32_128:2 could not be found.

**Expected behavior**
For the network to exist and be downloaded.

**Environment**
Please provide at least:
* Container version (e.g. pytorch:19.05-py3): the tensorrt container, the newest version
* GPUs in the system: (e.g. 8x Tesla V100-SXM2-16GB): Nvidia Titan V
* CUDA driver version (e.g. 418.67): 450.80.02

**Comment by swethmandava** [comment]
You can find updated models in the [data download script here](https://github.com/NVIDIA/DeepLearningExamples/blob/03c5a9fd9b25dc799608418f87c69f131489ec9f/TensorFlow/LanguageModeling/BERT/data/create_datasets_from_start.sh#L44)

Additionally, you can also search for bert models in the [ngc catalog](https://ngc.nvidia.com/catalog/models) directly.
