### ISSUE TITLE
not able to import NVIDIA_DeepLearningExamples_torchhub

### ISSUE THREAD

**Issue by BalajiB197** [NVIDIA/DeepLearningExamples#730]
import torch

>>> precision = 'fp32'
>>> ssd_model = torch.hub.load('NVIDIA/DeepLearningExamples:torchhub', 'nvidia_ssd', model)

Not able to find the SSD model, I do development in both local machines and in colab. Now for the past two days not able to import the Deeplearningexamples in my colab. May I know the exact reason ??? It works fine local in my machine as the cache is not cleared

**Comment by alvarobartt** [comment]
Hi! Please find this issue reference (and somehow solved) in this PR #727 Anyway, the SSD FP32 model is no longer available on NVIDIA Catalog Models, you can check its availability at https://ngc.nvidia.com/catalog/models?orderBy=modifiedDESC&pageNumber=1&query=&quickFilter=models&filters=

**Comment by nv-kkudrynski** [comment]
The issue is fixed. Also, we will soon make an update to benefit from the recently uploaded checkpoints.
