### ISSUE TITLE
[Bert/TensorFlow] is the V100 fine-tune training performance correct ?

### ISSUE THREAD

**Issue by chuangsiye** [NVIDIA/DeepLearningExamples#738]
Related to **Bert/TensorFlow** 

**Describe the bug**
Do we really have a huge performance increase for FP32 in DGX-1-32GB version only?  purely from batch size increase in fine-tune? 
I don't see this huge improvement in pre-train.
Fine-tune perf:  A100 TF32 : V100 FP32 2:1
Pre-train perf:  A100 TF32 : V100 FP32 6:1

Is it still from sequence length = 384 for fine-tune? or is it from sequence length = 128?

![image](https://user-images.githubusercontent.com/73901575/98013948-fe17ba80-1e35-11eb-8445-4b61ab99a470.png)

![image](https://user-images.githubusercontent.com/73901575/98014708-f3a9f080-1e36-11eb-8a53-145fd57a9794.png)

It is from this commit
https://github.com/NVIDIA/DeepLearningExamples/commit/96138d508700ffc5f281dddb6f87b7d8a1cfb568

![image](https://user-images.githubusercontent.com/73901575/98013804-cc9eef00-1e35-11eb-8576-dee690287592.png)

**To Reproduce**
1. Install '...'
2. Set "..."
2. Launch '...'

**Expected behavior**

**Environment**
Please provide at least:
* Container version (e.g. pytorch:19.05-py3):
* GPUs in the system: (e.g. 8x Tesla V100-SXM2-16GB):
* CUDA driver version (e.g. 418.67):

**Comment by idealboy** [comment]
I had the same question, and when I tried to finetune on squadv1.1 with batchsize=12 ,  I only got a lower performance:14 sentences/sec, which is far from your released target.

I took this job on dgx-1 32G(8xv100) launched with tensorflow:20.06-tf1-py3, should I configure an extra environment on my host?

I found this docker image is  based on cuda-11.

Thank you very match.

[Photo]

**Comment by swethmandava** [comment]
@chuangsiye yes we do see a perf benefit by increasing batch size. 

@idealboy Our reported scores seem to be for BS=24 with mixed precision on DGX1 v32g. Could you try the same and let us know?

**Comment by chuangsiye** [comment]
> @chuangsiye yes we do see a perf benefit by increasing batch size.
> 
> @idealboy Our reported scores seem to be for BS=24 with mixed precision on DGX1 v32g. Could you try the same and let us know?

Hi @swethmandava , thanks for your reply.
I think we were discussing FP32 only here, so based on the data in the file, it is 32.72 for batch 10.  Batch will increase perf but 32.72 is too far from the data similar in pre-training.  
I think @idealboy 's data is somehow an evidence of my guess.

**Comment by chuangsiye** [comment]
@swethmandava  I consider rerunning it in V100 is very short.  Can you help rerun it with same config /knobs and help share the log file which can prove the performance data?

**Comment by swethmandava** [comment]
@chuangsiye You're right - sorry I missed that. It was a copy error - updated in PR. Happy to share logs with you as well :)
