### ISSUE TITLE
What does this allreduce barrier accomplish?

### ISSUE THREAD

**Issue by rllin-fathom** [NVIDIA/DeepLearningExamples#74]
https://github.com/NVIDIA/DeepLearningExamples/blob/2acfcb263a5189937c2183450b55b740c6801f5c/TensorFlow/LanguageModeling/BERT/run_squad.py#L1306

**Comment by swethmandava** [comment]
Waits for all ranks to finish writing temporary files https://github.com/NVIDIA/DeepLearningExamples/blob/2acfcb263a5189937c2183450b55b740c6801f5c/TensorFlow/LanguageModeling/BERT/run_squad.py#L1288

Without it, you sometimes get warning messages like "Missing rank : x"

**Comment by rllin-fathom** [comment]
ah, do you know why a blocking step like that doesn't need to exist between train and eval steps?

**Comment by swethmandava** [comment]
eval is only done on 1 GPU

**Comment by rllin-fathom** [comment]
makes sense, thanks!
