### ISSUE TITLE
what is 'encoder_gemm' in FasterTransformer?

### ISSUE THREAD

**Issue by harryhan618** [NVIDIA/DeepLearningExamples#743]
In FasterTransformer, it is recommended that every time `encoder_gemm` should be run first. May I ask why? It generates 'gemm_config.in' file. But I couldn't find anywhere that uses this file. 
Is it purely used for GPU warm up?

**Comment by byshiue** [comment]
encoder_gemm will run all possible gemm configuration and find the best one, and write into "gemm_config.in". 
In FT, "bert_encoder_transformer.h" and "open_attention.h" will load the file.
