### ISSUE TITLE
[UNet_3D_Medical/Tensorflow] OOM for training with batch size 1

### ISSUE THREAD

**Issue by GuntherZhong** [NVIDIA/DeepLearningExamples#750]
Related to **UNet_3D_Medical/Tensorflow** 
*(e.g. GNMT/PyTorch or FasterTransformer/All)*

**Describe the bug**

Follow the instructions of the README, I got the repeatable training results for batch size 2 for 8 gpus with xla, amp and augment on a server with V100 32GB. However, For batch size 1 with 16k steps or even a little larger steps,  the program crashed and no response in the SSH terminal, I have to restart the server.

**To Reproduce**
1. Install '...'
2. Set "..."
2. Launch '...'

**Expected behavior**

**Environment**
Please provide at least:
* Container version (e.g. pytorch:19.05-py3): TensorFlow 20.06-tf1-py3
* GPUs in the system: (e.g. 8x Tesla V100-SXM2-16GB): 8x Tesla V100-SXM2-32GB
* CUDA driver version (e.g. 418.67): 450.51.05

**Comment by mmarcinkiewicz** [comment]
Hey @GuntherZhong . Thanks for letting us know, we are working on a solution.

**Comment by mmarcinkiewicz** [comment]
@GuntherZhong we are preparing a larger release for U-Net3D, with some more changes and improvements.
In the meantime, you could use the following code to mitigate the OOM issues with batch size = 1. 
Go to https://github.com/NVIDIA/DeepLearningExamples/blob/master/TensorFlow/Segmentation/UNet_3D_Medical/dataset/data_loader.py#L117 (data_loader.py, train_fn(), line 117, just before the `return` statement) and paste.

```python
if self._batch_size == 1:
    options = dataset.options()
    options.experimental_optimization.map_and_batch_fusion = False
    dataset = dataset.with_options(options)
```
