### ISSUE TITLE
[Model]Do you have benchmark data for QuartzNet?

### ISSUE THREAD

**Issue by zjyuan** [NVIDIA/DeepLearningExamples#757]
I am looking for benchmark data for QuartzNet(I care about inference time). I can only find data for [Jasper](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/SpeechRecognition/Jasper/tensorrt). Really appreciate if you can share the data.

**Comment by alancucki** [comment]
Hi @zjyuan ,
we're likely to publish QuartzNet soon with benchmarks in the same setup as Jasper. Then you'd be able to compare them apples to apples. Stay tuned.

**Comment by zjyuan** [comment]
thank you
