### ISSUE TITLE
[DLRM/Pytorch] NCCL error while running dist_main.py

### ISSUE THREAD

**Issue by KaizhaoLiang** [NVIDIA/DeepLearningExamples#761]
PyTorch DLRM

**Describe the bug**
setup as in the instruction on AWS p4x24 A100 instance with CUDA version 11.0

**To Reproduce**
1. docker run --runtime=nvidia -it --rm --ipc=host  -v ${PWD}/data:/data nvidia_dlrm_pyt bash
2. python -u -m torch.distributed.launch --use_env --nproc_per_node 8 -m dlrm.scripts.dist_main --mode train --dataset /data/ [--amp]

**Expected behavior**
```
003eef401da7:621:696 [3] NCCL INFO Channel 00 : 3[201d0] -> 6[a01c0] via P2P/IPC/read
  File "/workspace/dlrm/dlrm/scripts/dist_main.py", line 402, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
003eef401da7:619:697 [1] NCCL INFO Channel 00 : 1[101d0] -> 6[a01c0] via P2P/IPC/read
  File "/workspace/dlrm/dlrm/scripts/dist_main.py", line 221, in main
    output = model(numerical_features, categorical_features, batch_sizes_per_gpu).squeeze()
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 577, in __call__
003eef401da7:620:698 [2] NCCL INFO Channel 00 : 2[201c0] -> 6[a01c0] via P2P/IPC/read
    result = self.forward(*input, **kwargs)
  File "/workspace/dlrm/dlrm/model/distributed.py", line 152, in forward
    self._feature_order, self._device_feature_order)
  File "/workspace/dlrm/dlrm/model/distributed.py", line 54, in forward
    torch.distributed.all_to_all(bottom_output_buffer, list(local_bottom_outputs.split(batch_sizes_per_gpu, dim=0)))
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1700, in all_to_all
    work = _default_pg.alltoall(output_tensor_list, input_tensor_list, opts)
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:32, unhandled cuda error, NCCL version 2.7.6
```

**Environment**
Please provide at least:
* Container version (e.g. pytorch:20.07-py3):
* GPUs in the system: (e.g. 8x A100-SXM4-40GB):
* CUDA driver version (e.g. 450.80.02):

**Comment by wfu-fb** [comment]
following this. since I think I hit the same issue.

**Comment by mkfilipiuk** [comment]
Hi @KaizhaoLiang and @wfu-fb,

Thanks for letting us know about the issue - we will investigate this issue and let you know when we'll have something.

Best,
Michał

**Comment by mkfilipiuk** [comment]
Hi @KaizhaoLiang and @wfu-fb,

We've just released a new DLRM code with a new framework container that should solve this issue.
Please, pull the latest changes and try to run the training again.

Let me know if that succeeds or not.

Best,
Michał Filipiuk
