### ISSUE TITLE
[FasterTransformer/effective transformer] using wrong offset to remove seq padding 

### ISSUE THREAD

**Issue by gssplayer** [NVIDIA/DeepLearningExamples#768]
Related to **FasterTransformer/effective transform** 

**Describe the bug**
In Kernel remove_sequence_length_padding, the offset to get real location in source padding tensor is wrong.

Current impl:
`template<typename T>
__global__ void remove_sequence_length_padding(const T* src, T* tgt,
                                              const int* tmp_mask_offset,
                                              int* mask_offset,
                                              const int n)
{
  const int tid = threadIdx.x;
  const int bid = blockIdx.x;
  mask_offset[bid] = tmp_mask_offset[bid];

  // the src_seq_id is not right, which should be mask_offset[bid], no need add bid.
  const int src_seq_id = bid + mask_offset[bid];
  const int tgt_seq_id = bid;

  for(int i = tid; i < n; i += blockDim.x)
  {
    tgt[tgt_seq_id * n + i] = src[src_seq_id * n + i];
  }
}`

**Expected behavior**
Change: 
  const int src_seq_id = bid + mask_offset[bid];
to:
  const int src_seq_id = mask_offset[bid];

**Comment by byshiue** [comment]
Thanks for your suggestion. After checking, there is no bug for the offset. You can check the definition of the offset in the readme.

**Comment by gssplayer** [comment]
ok, I understand, thx.
