### ISSUE TITLE
[BERT/Pytorch] Nvidia A100 PCIE issues 

### ISSUE THREAD

**Issue by helson73** [NVIDIA/DeepLearningExamples#771]
Related to DeepLearningExamples/PyTorch/LanguageModeling/BERT/run_squad.py

**Describe the bug**
1. A100 GPU (PCI-E version) failed to run in parallel (num_gpu >= 2)
2. Can't reproduce [https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/LanguageModeling/BERT#fine-tuning-nvidia-dgx-a100-8x-a100-40gb](url), TF32 is even slower than FP32.

**To Reproduce**
1. Install Ubuntu 18.04.5 LTS (4.15.0-124-generic)
2. Install Nvidia driver 450.80.02 (data center/Linux 64)
3. Install docker and nvidia-docker2 with instruction [https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html](url)
4. Follow instructions from [https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/LanguageModeling/BERT#quick-start-guide](url)
5. Launch `bash scripts/run_squad.sh /workspace/checkpoints/<downloaded_checkpoint>` in the contrainer.

**Expected behavior**
1. DLL log hangs at `DLL 2020-12-01 09:29:29.842056 - PARAMETER steps : ****` (if num_gpu >= 2 in DeepLearningExamples/PyTorch/LanguageModeling/BERT/scripts/run_squad.sh)
2. Nvidia-smi shows each GPU only consumes around 6-70W (if num_gpu >= 2 in DeepLearningExamples/PyTorch/LanguageModeling/BERT/scripts/run_squad.sh)
3. Speed at TF32 precision is only 4.8 it/s (compared to 14 it/s at FP16, 5 it/s at FP32) (if set num_gpu=1 and precision='tf32' in DeepLearningExamples/PyTorch/LanguageModeling/BERT/scripts/run_squad.sh)

**Environment**
Please provide at least:
* Container version : nvcr.io/nvidia/pytorch-20.06-py3
* GPUs in the system: 4 x Nvidia A100 40GB (PCI-E ver.)
* CPU: 2 x Intel Xeon 16Cores/32Threads
* RAM: 256GB
* SSD: 4 x Samsung PM963 7.98TB
* OS: Ubuntu 18.04.5 server LTS
* kernel version: 4.15.0-124-generic
* Nvidia driver version: 450.80.02 (data center version, download from [https://www.nvidia.com/Download/driverResults.aspx/165294/en-us](url) )

**Comment by sharathts** [comment]
Hello, just to confirm, are you building the container from Dockerfile and running in the container using bash scripts/docker/build.sh and bash scripts/docker/launch.sh ?

BERT is CPU dependent and seems like your CPU setup differs from the typical DGX A100.

**Comment by helson73** [comment]
> Hello, just to confirm, are you building the container from Dockerfile and running in the container using bash scripts/docker/build.sh and bash scripts/docker/launch.sh ?
> 
> BERT is CPU dependent and seems like your CPU setup differs from the typical DGX A100.

Yeah I did run container using 'build.sh' and 'launch.sh'.
And my system is not DGX and my CPU is different with DGX's CPU indeed.
But I don't understand how it's related, I tested exactly the same way in another machine (AMD CPU with 8 x RTX 3090), but everything works fine.

**Comment by sharathts** [comment]
Hi helson73.  To follow up, does this issue still exist and are you still able to reproduce it?

**Comment by helson73** [comment]
> Hi helson73. To follow up, does this issue still exist and are you still able to reproduce it?

Hi, 
So far the first issue (Parallelism) is solved by updating the BIOS.
About the second issue (TF32), I am going to test it with recently released NGC image. I will tell you the result after the test.
Thanks.

**Comment by sharathts** [comment]
Closing the issue. Feel free to post more questions if any.

**Comment by World-Worst-Detector** [comment]
> > Hi helson73. To follow up, does this issue still exist and are you still able to reproduce it?
> 
> Hi,
> So far the first issue (Parallelism) is solved by updating the BIOS.
> About the second issue (TF32), I am going to test it with recently released NGC image. I will tell you the result after the test.
> Thanks.

Hi,

I have the same issue GPU parallel issue as you. Can you give more information about how to update the BIOS? Thank you for your help. I really appreciate it.

**Comment by helson73** [comment]
> > > Hi helson73. To follow up, does this issue still exist and are you still able to reproduce it?
> > 
> > 
> > Hi,
> > So far the first issue (Parallelism) is solved by updating the BIOS.
> > About the second issue (TF32), I am going to test it with recently released NGC image. I will tell you the result after the test.
> > Thanks.
> 
> Hi,
> 
> I have the same issue GPU parallel issue as you. Can you give more information about how to update the BIOS? Thank you for your help. I really appreciate it.

It's depends on your server's manufacturer, in my case, it's a Gigabytes rack server and I found the latest BIOS file on their website and flash it. 
Before you do that, it's better to connect to the manufacturer to figure out what's the exact reason causes this. In many case, updating BIOS will cause system malfunction, you should know exactly what you are doing.

**Comment by World-Worst-Detector** [comment]
> > > > Hi helson73. To follow up, does this issue still exist and are you still able to reproduce it?
> > > 
> > > 
> > > Hi,
> > > So far the first issue (Parallelism) is solved by updating the BIOS.
> > > About the second issue (TF32), I am going to test it with recently released NGC image. I will tell you the result after the test.
> > > Thanks.
> > 
> > 
> > Hi,
> > I have the same issue GPU parallel issue as you. Can you give more information about how to update the BIOS? Thank you for your help. I really appreciate it.
> 
> It's depends on your server's manufacturer, in my case, it's a Gigabytes rack server and I found the latest BIOS file on their website and flash it.
> Before you do that, it's better to connect to the manufacturer to figure out what's the exact reason causes this. In many case, updating BIOS will cause system malfunction, you should know exactly what you are doing.

Thank you so much for the explanation.
