### ISSUE TITLE
[DLRM/Pytorch] Is there a multi-machine distributed result?

### ISSUE THREAD

**Issue by MeioJane** [NVIDIA/DeepLearningExamples#774]
In readme, DGX-2 with 16 V100 GPUs which means there is a machine with 16 GPUs or there are two machines and one machine with 8 GPUs?

**Comment by mkfilipiuk** [comment]
Hi @MeioJane,

DGX-2 is a name of one of our machines. 
You can read more about it here: [https://www.nvidia.com/en-us/data-center/dgx-2/](https://www.nvidia.com/en-us/data-center/dgx-2/)

I'm closing this issue as it's not really an issue, but if you have any more questions, feel free to post it down here.

Best,
Michał
