### ISSUE TITLE
gradient registry has no entry for: BertTransformer

### ISSUE THREAD

**Issue by qiufengyuyi** [NVIDIA/DeepLearningExamples#777]
hi,my env is as follows:
tensorflow 1.14.0rc1-gpu
centos 7
fasttransformer v2.1
i have successfully build fasttransformer and test it using the script. but when i add fasttransformer op to my bert/modeling.py as the tensorflow_bert/sample.md does, and then do bert pretraining, loading a existing pretrained bert ckpt weight, i get the error message as follows :

> LookupError: No gradient defined for operation 'bert/encoder/layer_11/BertTransformer' (op type: BertTransformer)
> W1208 15:49:42.033753 140394764658496 deprecation.py:323] From /opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_grad.py:1205: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use tf.where in 2.0, which has the same broadcast rule as np.where
> Traceback (most recent call last):
>   File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_util.py", line 673, in _GradientsHelper
>     grad_fn = ops.get_gradient_function(op)
>   File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2775, in get_gradient_function
>     return _gradient_registry.lookup(op_type)
>   File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/registry.py", line 97, in lookup
>     "%s registry has no entry for: %s" % (self._name, name))

so how can i solve this issue? 
or i cannot use fasttransformer in this way as a pretraining part ,it can only be used in inference phase?

**Comment by byshiue** [comment]
Yes, you cannot use fastertransformer into pretraining. 
It only supports inference.
