### ISSUE TITLE
[GNMT/Pytorch] Can't get attribute 'default' on <module 'seq2seq.data.tokenizer'

### ISSUE THREAD

**Issue by godspeed5** [NVIDIA/DeepLearningExamples#778]
Related to **Model/Framework(s)** 
*(e.g. GNMT/PyTorch or FasterTransformer/All)*

**Describe the bug**
I get the following error when I run inference with the given instructions:
Can't get attribute 'default' on <module 'seq2seq.data.tokenizer'

**To Reproduce**
Follow the instructions in the Quick Start Guide until setting up the docker, ie, the following line:
bash scripts/docker/interactive.sh
Instead of training I use a pre-trained model to run inference with the following code:
python3 translate.py \
  --input-text "The quick brown fox jumps over the lazy dog" \
  --model gnmt/model_best.pth

**Expected behavior**
The following output is expected:
(...)
0: Translated output:
Der schnelle braune Fuchs springt über den faulen Hund

**Environment**
Please provide at least:
* Container version (e.g. pytorch:19.05-py3): pytorch:20.06-py3
* GPUs in the system: (e.g. 8x Tesla V100-SXM2-16GB): GTX 1660Ti
* CUDA driver version (e.g. 418.67): 455.23.05

**Comment by SundarRamanP2000** [comment]
Facing the same issue, any solutions?

**Comment by szmigacz** [comment]
Can you post a full traceback with the error message?
Which pretrained checkpoint did you load? I just tested with this one: https://ngc.nvidia.com/catalog/models/nvidia:gnmt_pyt_ckpt_amp/files and it worked fine.
