### ISSUE TITLE
[BERT/PyTorch] Wiki dataset does not download

### ISSUE THREAD

**Issue by joehandzik** [NVIDIA/DeepLearningExamples#782]
Related to **BERT/PyTorch** 

**Describe the bug**
Wiki dataset does not download, despite subsequent components downloading from the download script

**To Reproduce**

Follow the readme, attempt to download the dataset within the container.

root@gpu01:/workspace/bert# /workspace/bert/data/create_datasets_from_start.sh wiki_only
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
Working Directory: /workspace/bert/data
Action: download
Dataset Name: wikicorpus_en

Directory Structure:
{ 'download': '/workspace/bert/data/download',
  'extracted': '/workspace/bert/data/extracted',
  'formatted': '/workspace/bert/data/formatted_one_article_per_line',
  'hdf5': '/workspace/bert/data/hdf5_lower_case_1_seq_len_512_max_pred_20_masked_lm_prob_0.15_random_seed_12345_dupe_factor_5',
  'sharded': '/workspace/bert/data/sharded_training_shards_256_test_shards_256_fraction_0.1',
  'tfrecord': '/workspace/bert/data/tfrecord_lower_case_1_seq_len_512_max_pred_20_masked_lm_prob_0.15_random_seed_12345_dupe_factor_5'}

Downloading: https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2

From another terminal:

apollo@gpu01:/raid/DeepLearningExamples/PyTorch/LanguageModeling/BERT/data/download/wikicorpus_en$ ls -altr
total 8
drwxr-xr-x 6 root root 4096 Dec 11 17:21 ..
-rw-r--r-- 1 root root    0 Dec 11 17:30 wikicorpus_en.xml.bz2
drwxr-xr-x 2 root root 4096 Dec 11 17:30 .
apollo@gpu01:/raid/DeepLearningExamples/PyTorch/LanguageModeling/BERT/data/download/wikicorpus_en$ ls -altr
total 8
drwxr-xr-x 6 root root 4096 Dec 11 17:21 ..
-rw-r--r-- 1 root root    0 Dec 11 17:30 wikicorpus_en.xml.bz2
drwxr-xr-x 2 root root 4096 Dec 11 17:30 .
apollo@gpu01:/raid/DeepLearningExamples/PyTorch/LanguageModeling/BERT/data/download/wikicorpus_en$ ls -altr
total 8
drwxr-xr-x 6 root root 4096 Dec 11 17:21 ..
-rw-r--r-- 1 root root    0 Dec 11 17:30 wikicorpus_en.xml.bz2
drwxr-xr-x 2 root root 4096 Dec 11 17:30 .
apollo@gpu01:/raid/DeepLearningExamples/PyTorch/LanguageModeling/BERT/data/download/wikicorpus_en$ ls -altr
total 8
drwxr-xr-x 6 root root 4096 Dec 11 17:21 ..
-rw-r--r-- 1 root root    0 Dec 11 17:30 wikicorpus_en.xml.bz2
drwxr-xr-x 2 root root 4096 Dec 11 17:30 .

**Expected behavior**

Dataset download to complete, or at least make progress!

**Environment**
Please provide at least:
* Container version (e.g. pytorch:19.05-py3): nvcr.io/nvidia/pytorch:20.06-py3
* GPUs in the system: (e.g. 8x Tesla V100-SXM2-16GB): 8 A100 SXM GPUs
* CUDA driver version (e.g. 418.67): Unknown, irrelevant

**Comment by joehandzik** [comment]
Any thoughts on this?

**Comment by sharathts** [comment]
Thank you for pointing out this issue. This has been fixed in https://github.com/NVIDIA/DeepLearningExamples/pull/833

Pull these changes and the download should work as expected.

**Comment by joehandzik** [comment]
Will close this, but we should follow in #840 - I believe the download is still not working as expected, even with the certificate check workaround.

**Comment by sharathts** [comment]
Fixed with #841
