### ISSUE TITLE
[FastPitch/PyTorch] Male quality much worse than female

### ISSUE THREAD

**Issue by DanRuta** [NVIDIA/DeepLearningExamples#783]
Hello, I've been having some issues training FastPitch on male voices, and was wondering if's been successfully done.

I've had decent luck with female voices, ranging from good to very good quality for about 10 voices/models so far (very exciting).
With male voices however, I've not been so lucky. I *just about* got some ok quality sometimes on about 3 voices, but the rest I tried so far (~13) have failed to converge to anything usable (gibberish-like speech mostly, though good pitch!), despite consistently high data quality. The problem is worse when I attempt multi-speaker models.

I was wondering if you've encountered this before / are there any male-specific settings I should take into account, as the pattern is clear. One thing to consider is that I've been fine-tuning the provided (female) LJSpeech model for all models.

I know male speakers are not covered in the paper, but have you had any success training male speaker(s) models, on your end?

Thank you.

**Comment by alancucki** [comment]
Hi Dan,

I haven't trained male voices yet, but this shouldn't be much different from training female voices.

If by gibberish you mean unintelligible, that could mean poor quality of training alignments, or malfunctioning duration predictor during inference. The weak part of the current FastPitch pipeline is its reliance on durations extracted from Tacotron2, which is speaker-dependent. We're working on methods for obtaining speaker-independent alignments that could replace it entirely.

For now, I'd advise to pinpoint the problem. The first thing I'd check would be the distributions of grapheme durations for your male training data. Look closely for outliers - and those would be overly long durations.

btw I'm glad to hear that the female voices come out well!

**Comment by DanRuta** [comment]
Hello,

I can confirm that after finally upgrading my hardware and being able to train Tacotron2 models, male voices now sound just as good as the female voices. Before that, tinkering with the dataset to remove extreme samples like you mentioned also helped.

Thank you for the help! I'm excited to see where you will take FastPitch next, if you are still working on it!
