### ISSUE TITLE
DLRM running on P40 support Feature requested

### ISSUE THREAD

**Issue by suhmily** [NVIDIA/DeepLearningExamples#793]
Related to DLRM model

*Examples:* 
* *dlrm/PyTorch 

**Is your feature request related to a problem? Please describe.**
I tried to build dlrm on P40 while failed. I wonder if merlin can work well on P40 GPU.

**Describe the solution you'd like**
pytorch/dlrm docker supports P40 and cuda10

**Comment by mkfilipiuk** [comment]
Hi @suhmily,

Could you share a bit more details how exactly the build fails?
P40 is quite old GPU but maybe we can get DLRM working there.

Best,
Michał

**Comment by suhmily** [comment]
dlrm.cuda_ext.interaction_ampere & dlrm.cuda_ext.interaction_volta can only be compiled with "arch=compute_70", while P40 only sopports "arch=compute_60"

**Comment by mkfilipiuk** [comment]
Ok, that's what I expected: our DLRM model has a few custom CUDA kernels, which were implemented for Volta and Ampere architecture and they now cannot get compiled. What we can do, is to remove them. There are three places where you have to remove a few lines of code:
1. ./Dockerfile - remove the last line (`RUN pip install --no-cache-dir -e .` - this one)
2.  ./dlrm/nn/interactions.py - remove line 17 (`from dlrm.cuda_ext import dotBasedInteract`)
3. ./dlrm/nn/embeddings.py - remove lines 22 and 23 (`from dlrm import cuda_ext` and `from dlrm.cuda_ext.fused_gather_embedding import BuckleEmbeddingFusedGatherFunction`)

Now, you should be able to build the docker image and run the code inside using this line:  
`python -m dlrm.scripts.main --mode train --dataset <path to dataset> --embedding_type joint --interaction_op dot`
These two arguments at the end are crucial to get it running without these custom ops.

Let me know if that helps!

**Comment by suhmily** [comment]
File "/workspace/dlrm/dlrm/nn/embeddings.py", line 194, in forward
    return [BuckleEmbeddingFusedGatherFunction.apply(self.weight, categorical_inputs, self.offsets, self.amp_train)]
NameError: name 'BuckleEmbeddingFusedGatherFunction' is not defined

**Comment by mkfilipiuk** [comment]
@suhmily, do you need any more assistance? If not, then I'd proceed to close the issue.

**Comment by suhmily** [comment]
Sure, thanks for help.
