### ISSUE TITLE
[FasterTransformer] sample/transformer_trt failed in fp16 mode

### ISSUE THREAD

**Issue by lujq96** [NVIDIA/DeepLearningExamples#794]
Related to FasterTransformer/TensorRT

**Describe the bug**
When running transformer_trt.cc in fp16 mode, I met several CUDA Error during forward. 
```
CUDA Error: CUDA_ERROR_INVALID_VALUE CUDA Error: CUDA_ERROR_INVALID_VALUE /usr/local/app/workspace/ljq/DeepLearningExamples-master/FasterTransformer/v3.1/fastertransformer/trt_fused_multihead_attention/fused_multihead_attention_v2.h 507
[FT][ERROR] CUDA runtime error: invalid configuration argument /usr/local/app/workspace/ljq/DeepLearningExamples-master/FasterTransformer/v3.1/fastertransformer/trt_fused_multihead_attention/qkvToContext.cu:137

[FT][ERROR] CUDA runtime error: invalid configuration argument /usr/local/app/workspace/ljq/DeepLearningExamples-master/FasterTransformer/v3.1/fastertransformer/cuda/open_attention.h:626
```
And the result seems to be not correct.
By printing out the params, I found that params.b: -2, which should be a non-negative number as gridDim.y.

**To Reproduce**
Just run the transformer_trt with fp16=1

**Expected behavior**
No error should be found and the result should be same as other sample transformers.

**Environment**
Please provide at least:
* Container version: self-made container
* GPUs in the system: Tesla T4-16GB
* CUDA driver version: 440.33
* CUDA version: 10.2.89

**Comment by byshiue** [comment]
Sorry, we have deprecated the TensorRT plugin since FasterTransformer 3.1 version because TensorRT already has BERT implementation.
We will add the explanation of it and delete the TensorRT plugin codes since next version. Thanks for your feedback.
