### ISSUE TITLE
[FasterTransformer] Allow compiling of compute capability independent binaries

### ISSUE THREAD

**Issue by mingruimingrui** [NVIDIA/DeepLearningExamples#797]
Sometimes we cannot ensure that the build and run time environment uses the same exact hardware.

Having binaries that are compatible across multiple types of GPUs would make FasterTransformer much easier to prebuild development images for or for production use cases.

**Comment by byshiue** [comment]
Thanks for your suggestion. We will add a parser of sm version and hence user can use multiple sm versions in the same time.
Currently, you can add the multiple sms you need into line https://github.com/NVIDIA/DeepLearningExamples/blob/master/FasterTransformer/v3.1/CMakeLists.txt#L84.
