### ISSUE TITLE
[ResNet50/Pytorch] Cannot reproduce reported accuracy on mixed precision training

### ISSUE THREAD

**Issue by notabigfish** [NVIDIA/DeepLearningExamples#800]
Related to **ResNet50/Pytorch** 

**Describe the bug**
Question 1. We have run this script https://github.com/NVIDIA/DeepLearningExamples/blob/46ff3707e04683e41b79af0f94a74e45f8016786/PyTorch/Classification/ConvNets/resnet50v1.5/training/AMP/DGX1_RN50_AMP_90E.sh and wanted to reproduce the reported mixed precision acc top-1 (77.09 +/- 0.10) but failed. Following are our experiment results:

    O1 Exp1: 76.54
    O1 Exp2: 76.13
    O1 Exp3: 76.34

Question 2. Results of O0 and FP32 are quite different. We have used https://github.com/NVIDIA/DeepLearningExamples/blob/46ff3707e04683e41b79af0f94a74e45f8016786/PyTorch/Classification/ConvNets/resnet50v1.5/training/FP32/DGX1_RN50_FP32_90E.sh to run FP32 results and https://github.com/NVIDIA/DeepLearningExamples/blob/46ff3707e04683e41b79af0f94a74e45f8016786/PyTorch/Classification/ConvNets/resnet50v1.5/training/AMP/DGX1_RN50_AMP_90E.sh with opt_level setting "O0" and difference loss_scales in main.py to run O0. We have the following results:
    FP32: 77.02
    O0 Exp1: 76.39 (loss scale = 128)
    O0 Exp2: 76.33 (loss scale = 1)
 
**To Reproduce**
Question1:
    1. pull docker
    2. run https://github.com/NVIDIA/DeepLearningExamples/blob/46ff3707e04683e41b79af0f94a74e45f8016786/PyTorch/Classification/ConvNets/resnet50v1.5/training/AMP/DGX1_RN50_AMP_90E.sh
Question 2:

**Environment**
Please provide at least:
* Container version: pytorch:20.06-py3
* GPUs in the system: 8x Tesla V100-SXM2-32GB

We are confused, why cannot we reproduce the reported acc. Should we use another commit? Thank you very much!

**Comment by asulecki** [comment]
Hi, thanks for your questions!

From the second question I infer that you did change the code (at least to enable O0 AMP level), did you introduce any changes before running the setup mentioned in question 1?

APEX's AMP is being deprecated and it is no longer supported, we will be moving to PyT native AMP really soon.
