### ISSUE TITLE
[FasterTransformer] Container not support GTX 3060 TI

### ISSUE THREAD

**Issue by syw2014** [NVIDIA/DeepLearningExamples#803]
Related to **Model/Framework(s) or something else (describe)** 

I have choose nvcr.io/nvidia/tensorflow:20.03-tf1-py3 container,but final shows bellow:
WARNING: Detected NVIDIA GeForce RTX 3060 Ti GPU, which is not yet supported in this version of the container
ERROR: No supported GPU(s) detected to run this container

My Envirnment:
CUDA:11.1
GPU: GeForce RTX 3060 Ti

**Comment by byshiue** [comment]
https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html shows the cuda version of the NGC images. 
nvcr.io/nvidia/tensorflow:20.03-tf1-py3 only contains cuda 10.1, so it can not run on RTX 3060 Ti. You need to use newer images.
