### ISSUE TITLE
[FastPitch/PyTorch] What is speaker_emb_weight in multispeaker model?

### ISSUE THREAD

**Issue by Piteryo** [NVIDIA/DeepLearningExamples#807]
In an update from October 2020 multispeaker training was added to fastpitch model. Speaker embedding is an actual PyTorch embedding, these weights are learned throughout the model training. But there is also "speaker_emb_weight" parameter on which extracted embeddings are multiplied. From the code, it seems that this parameter should be some kind of scalar which should come from args. But there is no any comments/info about it in documentation and args parser. What should this scalar be like and why do we need it?

**Comment by alancucki** [comment]
Hi @Piteryo
seems like leftover code. In the current setup speaker embeddings are trainable, so multiplying them by a reasonably-sized scalar should have no effect.
Thanks for reporting this, I'll remove this param in the next release.
