### ISSUE TITLE
[Transformer/Pytorch] Why README.md said Transformer ONNX is not supported but the code has onnx export function?

### ISSUE THREAD

**Issue by jalola** [NVIDIA/DeepLearningExamples#808]
Related to **Transformer/Pytorch,ONNX** 

**Describe the bug**
I see that Transformer model in [README.md](https://github.com/NVIDIA/DeepLearningExamples) does not support ONNX yet, but there is a ONNX export function in [Transformer module](https://github.com/NVIDIA/DeepLearningExamples/blob/2badf6e8e4103be233047e47bce0fbe0129e8dc5/PyTorch/Translation/Transformer/scripts/deployer_lib.py#L678)

Another question:
I want to export the [TransformerEncoder module](https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/Translation/Transformer/fairseq/models/transformer.py#L182) (not the whole Transformer model) to onnx and serve it on Triton Inference server. I wonder if this is possible? Because as I notice that the nn.TransformerEncoder from official Pytorch crashing on Triton server.

Thanks for any idea,

**Comment by jbaczek** [comment]
Exporting Transformer to ONNX is possible but running full inference is cumbersome because Triton does not support autoregressive models yet (so you can't perform beam search). If you want to export encoder only and run it on Triton it should be doable with the code provided.

**Comment by jalola** [comment]
Thanks, I have not tried this repo encoder. Anyway, I could run the encoder on Triton with TensorRT from this Pytorch code
https://github.com/dhlee347/pytorchic-bert/blob/master/models.py
