### ISSUE TITLE
[SSD-ResNet50/Pytorch] Where could I download SSD-ResNet50 pre trained model checkpoint ?

### ISSUE THREAD

**Issue by SeedKunY** [NVIDIA/DeepLearningExamples#812]
When I execute python examples/SSD300_inference.py, cannot find SSD300v1.1.pt. However, I don't want to train the model to get a checkpoint, so is there any link to download this?

**Comment by Sangu80** [comment]
@SeedKunY you can use this to check them out "python ./main.py --backbone resnet50 --checkpoint ./models/epoch_*.pt --data /coco" or "python ./main.py --backbone resnet50 --mode evaluation --checkpoint ./models/epoch_*.pt --data /coco"

**Comment by nv-kkudrynski** [comment]
https://catalog.ngc.nvidia.com/orgs/nvidia/models/ssd_pyt_ckpt_amp
