### ISSUE TITLE
What is the difference of this repo from https://github.com/NVIDIA/tacotron2

### ISSUE THREAD

**Issue by yerzhan7orazayev** [NVIDIA/DeepLearningExamples#814]
Hello,

Is there any major difference from the other repo at https://github.com/NVIDIA/tacotron2 ?

Thanks,
Yerzhan.

**Comment by GrzegorzKarchNV** [comment]
Hi @yerzhan7orazayev, this repo has scripts that are easy to use and it provides the best reproducible results on different NVIDIA GPU architectures using technologies like mixed precision, inference on Triton Inference Server, or inference on TensorRT.
This repo was actually derived from the repo at https://github.com/NVIDIA/tacotron2.
