### ISSUE TITLE
I got "killed" when I create instance from sharded files. 

### ISSUE THREAD

**Issue by TonyTangYu** [NVIDIA/DeepLearningExamples#820]
Related to **Pytorch/LanguageModeling**

I followed the instruction and preprocess the downloaded 'bookscorpus' dataset. The sharding action went well. But in the 'creat_hdf5_files' action, I got “killed” when creating instance from sharded files, for both sequence length 128 case and sequence length 512 case. Since there is no more information about the error, I have no idea how to fix it. 
Could you do me a favor? Thanks a lot.

**Comment by sharathts** [comment]
Did data download, formatting and sharding happen as expected? Can you check if the respective directories aren't empty?

Can you also attach the full log, it is essential to debug.

**Comment by TonyTangYu** [comment]
@sharathts Thanks for your reply! Data downloading, formatting and sharding just happened as expected!  The respective directories are not empty. For both the 'bookscorpus' and 'wikipedia_en' datasets, this issue exists.

I don't know whether the full log could provide any useful information or not. The log is as follows:

> [nltk_data] Downloading package punkt to /home/tangyu/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
Working Directory: /hdd/BERT/data/data_bert_NVIDIA
Action: create_hdf5_files
Dataset Name: wikicorpus_en
> Directory Structure:
> { 'download': '/hdd/BERT/data/data_bert_NVIDIA/download',
>   'extracted': '/hdd/BERT/data/data_bert_NVIDIA/extracted',
>  'formatted': '/hdd/BERT/data/data_bert_NVIDIA/formatted_one_article_per_line',
>  'hdf5': 
>'/hdd/BERT/data/data_bert_NVIDIA/hdf5_lower_case_1_seq_len_128_max_pred_20_masked_lm_prob_0.15_random_seed_12345_dupe_factor_5',
  'sharded': '/hdd/BERT/data/data_bert_NVIDIA/sharded_training_shards_1_test_shards_1_fraction_0.1',
  'tfrecord': 
>'/hdd/BERT/data/data_bert_NVIDIA/tfrecord_lower_case_1_seq_len_128_max_pred_20_masked_lm_prob_0.15_random_seed_12345_dupe_factor_5'}
> creating instance from 
>/hdd/BERT/data/data_bert_NVIDIA/sharded_training_shards_1_test_shards_1_fraction_0.1/wikicorpus_en/wikicorpus_en_training_0.txt
> Killed
> creating instance from 
>/hdd/BERT/data/data_bert_NVIDIA/sharded_training_shards_1_test_shards_1_fraction_0.1/wikicorpus_en/wikicorpus_en_test_0.txt
>  69%|██████████████████████████████████████▌                 | 11202420/16278496 [54:15<29:11, 2897.97it/s]
> Killed

Looking forward to your reply!

**Comment by sharathts** [comment]
@TonyTangYu how many training and testing shards are you creating, before running create hdf5?

Fewer the number of shards, the more memory each hdf5 shard creation takes. It could be that your system running out of resources. Can you trying increasing the number of shards in `bertPrep.py` ?

**Comment by TonyTangYu** [comment]
@sharathts Thank you! I will give it a try!

**Comment by TonyTangYu** [comment]
@sharathts Is there any experience with the number of shards when I have two 1080Ti? Thanks again for your help!

**Comment by sharathts** [comment]
This is RAM dependant. I would suggest increasing by 2x each time until failure is avoided. Around 1024-2048 shards should typically do it. How many shards are you creating currently?

**Comment by TonyTangYu** [comment]
@sharathts Thanks for your quick reply! I only created one shard before. It took me months to finish the distributed sharding. Is there any chance that you provide the finished datasets, Wikipedia_En and BooksCorpus? I really appreciate it! I am afraid that it will take me another several  months to finish this process. :'-(

**Comment by sharathts** [comment]
One shard takes too much memory, hence the need to create multiple shards.

Unfortunately we cannot provide final datasets due to legal restrictions. Once the raw data has been downloaded and formatted, sharding should take a few hours.

**Comment by TonyTangYu** [comment]
@sharathts  I am trying to create multiple shards. However, creating multiple shards is just as slow as creating one shard which I did months ago. I am afraid that this will also cost me about three months. This is a big problem for me. Is there any tips with which I could finish sharding in hours?  I have downloaded and formatted the raw data, wikipedia_en.

**Comment by sharathts** [comment]
The entire data prep process takes ~30 hours on a DGX-1 16G machine. Sharding is the most compute intensive and shouldn't typically take more than 24 hours. This is all CPU based.

3 months for data prep seems like there if something off with your setup.

**Comment by TonyTangYu** [comment]
@sharathts I followed the setup in the bertPrep.py before. Which hyperparameters could I change besides the number of shards?

**Comment by sharathts** [comment]
@TonyTangYu Sorry, by setup, I mean your system setup, resources available etc.

For bertPrep.py, you should use default hyperparameters.
