### ISSUE TITLE
[BERT/PyTorch] One more process runs when creating h5 files on the first loop

### ISSUE THREAD

**Issue by myoons** [NVIDIA/DeepLearningExamples#826]
## Describe the Bug

![n_processes](https://user-images.githubusercontent.com/67945103/106780280-2c05d880-668b-11eb-8354-0d753380c345.jpg)

As you can see, although n_processes is set to 4, 5 processes are running on the first loop. 4 processes run afterward, as expected.

## To Reproduce
For instance, the below command runs 5 processes, instead of 4 processes, on the first loop when creating h5 files.

```python
python3 /workspace/bert/data/bertPrep.py \
    --action create_hdf5_files \
    --dataset Merged \
    --vocab_file ./vocab/vocab.txt \
    --n_processes 4
```

## Environment
* torch 1.7.1
* torchvision 0.8.2
* Default Docker Image in BERT repository

## Solution
Please modify L165 in bertPrep.py as follows.

### AS-IS
```python
if shard_id % args.n_processes == 0 and shard_id > 0:
    bert_preprocessing_process.wait()
```
### TO-BE
```python
if (shard_id + 1) % args.n_processes == 0:
    bert_preprocessing_process.wait()
```

**Comment by sharathts** [comment]
Thank you for pointing this out. This seems to be one-off but not affecting correctness, am I right?

**Comment by myoons** [comment]
Yes. It doesn't affect the correctness. But, since unexpected situation arises and also making h5 files takes a lot memories, I think it would be better to revise it.

**Comment by sharathts** [comment]
Thank you. We will revisit and fix it in our next update. Closing bug.

**Comment by myoons** [comment]
Ok. Thanks
