### ISSUE TITLE
where to find the file sacrebleu_reference.de

### ISSUE THREAD

**Issue by renganxu** [NVIDIA/DeepLearningExamples#83]
I try to run the pytorch transformer model in this repository. But the runtime failed at the following line:
with open(os.path.join(args.data, 'sacrebleu_reference.de'), 'r') as reference:

Here it tries to open the file sacrebleu_reference.de. But where to get this file? The run_preprocessing.sh script didn't generate this file and I also could not find it online. So how do we get this file? Thanks.

**Comment by jbaczek** [comment]
You can get it by appending `sacrebleu -t wmt14/full -l de-en --echo src > $DATASET_DIR/sacrebleu_reference.de` to the `run_preprocessing.sh` script.
This issue will be fixed in the next release.
