### ISSUE TITLE
Is it possible to train voices and models with fastpitch using CPU only and/or without NVIDIA Container Toolkit/docker? (doubt)

### ISSUE THREAD

**Issue by cesm1980** [NVIDIA/DeepLearningExamples#831]
I am new to these things and from everything i read from the instructions on the repository and google after a few hours, i am unsure if its worth all the trouble of trying to set up the nvidia docker, ubuntu, wsl2, and even joining insider programs in microsoft and nvidia, which i never had done before and seems a massive hassle to me, and i want to be sure it's worth joining all those programs.

I say this because apparently my new graphics card is not suited for training fastpitch/deep learning, perhaps my cpu would even be faster for fastpitch training ??

NVIDIA GEFORCE GTX 1060 SUPER 6GB
INTEL CORE I9 9900KF

From what i seen online, unfortunately my card doesnt have tensor cores and not enough vram for deep learning, so i ask, it there a way to train fastpitch models without using gpu and all those requirements such as the nvidia toolkit, drivers, wsl, etc etc and using only CPU? Note that i dont mind if it's slow or not, i really want to be able to use text to speech, using fastpitch so i wonder if perhaps the cpu could be faster than this card OR if despite the card being weak for deep learning.

**Comment by ArEnSc** [comment]
I don't think you would be able to even with the 3080 the batch size I work with is like 16, and it would take 2 days 48 hours to train, with a CPU I think you would be waiting a very long time

**Comment by cesm1980** [comment]
yeah... anyway just the hassle to get the cuda toolkit and dependencys to run, specially the thing of having the join the microsoft insider program and installing builds, which i dont want to do specially if i cant even take advantage of the gpu at all (it would be ridulous to do that JUST to use cpu!), definetly make me give up on this repository, BUT i found another one, the mozzila TTS one which i was finally able to use it without having to use insider builds or specific cuda drivers, sure, i will be running on cpu and very slow but at least the training can even be resumed later.

So, regarding the training time, oh well, i will have to do by cpu nevertheless, there's no way i can spend hundreds of dollars in a decent gpu for this, i have no other choice unfortunately, i only hope that i can get good results with the mozilla tts, because so far i havent found a way to use fastpitch or the other models in this repository without the insidir builds installed and the specific driver from nvidia, so mozilla tts will have to do, but if there's a way to use anything from this repository without insider builds tell me but i presume its not possible, at least so far mozilla tts is the only alternative i found, and yeah i am prepared for long training times since i have no other choice.

**Comment by cesm1980** [comment]
Oh i almost forgot, is everyone here also having to use insider builds to be able to use gpu acceleration in this? there isnt any problems because of insider builds usually being unstable and not being recommended as using as being the main OS? Since i dont want to use dual boot for this...

**Comment by nvpstr** [comment]
This repository is focused on NVIDIA GPU-optimized solutions. You can probably find others that support CPU training. However training modern speech models is costly, and according to our experience using CPU for that purpose won't make it cheaper or shorter.

Have you tried using DL-framework docker containers from NGC? All the sources in this repository work with those.
IMO you could start training your model without "configuration troubles" and without the joining insider program.

**Comment by cesm1980** [comment]
Yeah i mostly used the instructions in https://docs.nvidia.com/cuda/wsl-user-guide/index.html, but somehow the drivers from the nvidia developer program i was able to get, didnt got installed inside the WSL like it's said in there they should, because the repository here keeps giving errors, but just give me some more time, maybe in a few days i can try this again and then i will post here the messages, since meanwhile i am trying to get help from someone else, in case i still need help i will post here the errors and the steps i did to install.

**Comment by cesm1980** [comment]
Ok, i finally tried again moments ago but jeez... this is one of the most messy methods of installing something that i have ever seen... (no wonder since i never used linux before) its almost sure i am doing everything wrong, but hey, that's why i am asking help.

I tried two ways, first i tried following the instructions as said on :

https://docs.nvidia.com/cuda/wsl-user-guide/index.html

And i will tell you later how i did but first this time let me tell you how i tried, based on what you said (getting the DL-framework docker containers from NGC) :

-i got in windows store, download and installed ubuntu 18.04 lts (the version the wsl user guide mentioned, so for now i will still use this one)
-downloaded and clean installed the "NVIDIA Drivers for CUDA on WSL, including DirectML Support" as it said on https://docs.nvidia.com/cuda/wsl-user-guide/index.html#installing-nvidia-drivers, which has the filename :
465.42_gameready_win10-dch_64bit_international.exe

-i am following the links indicated here since it's the Fastpitch model i am interested the most :
https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/SpeechSynthesis/FastPitch#requirements

-i clicked on "NVIDIA Docker", which then gone to it's repository, and in there it says to go to the installation guide here, so it's these steps i am following :
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker

-here it says to use NVIDIA drivers ~= 361.93, but since i have previously tried the nvidia wsl guide ("465.42_gameready_win10-dch_64bit_international.exe") i am using 465.42 since i doubt i have to use that older version!

-i run ubuntu, and have set the unix username and password
-curl https://get.docker.com | sh \
  && sudo systemctl --now enable docker
-sudo usermod -aG docker MYUSERNAME
-distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
   && curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - \
   && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
-curl -s -L https://nvidia.github.io/nvidia-container-runtime/experimental/$distribution/nvidia-container-runtime.list | sudo tee /etc/apt/sources.list.d/nvidia-container-runtime.list
- apt-get update
-sudo apt-get install -y nvidia-docker2
-sudo systemctl restart docker
	- this command gave the error about systemd not being booted as init system, so i used intead :
-sudo service docker start
-sudo docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi
this is where i get the errors :

Unable to find image 'nvidia/cuda:11.0-base' locally
11.0-base: Pulling from nvidia/cuda
54ee1f796a1e: Pull complete
f7bfea53ad12: Pull complete
46d371e02073: Pull complete
b66c17bbf772: Pull complete
3642f1a6dfb3: Pull complete
e5ce55b8b4b9: Pull complete
155bc0332b0a: Pull complete
Digest: sha256:774ca3d612de15213102c2dbbba55df44dc5cf9870ca2be6c6e9c627fa63d67a
Status: Downloaded newer image for nvidia/cuda:11.0-base
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown.

I think this is because the driver i have currently (465.42_gameready_win10-dch_64bit_international) in nvidia-smi indicates cuda 11.3, so this installation guide is outdated, i tried replacing 11.0 to 11.3 in that command but of course it didnt work.

Anyway, nevertheless i tried to go on to the next requirement indicated in Fastpitch list : PyTorch 20.09-py3 NGC container or newer, in the link the command is :
-sudo docker pull nvcr.io/nvidia/pytorch:20.12-py3
	-no errors here
-git clone https://github.com/NVIDIA/DeepLearningExamples.git
-cd DeepLearningExamples/PyTorch/SpeechSynthesis/FastPitch
-sudo bash scripts/docker/build.sh
-bash scripts/docker/interactive.sh
	-again the same error as before :

	docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown.

Overall i think this is the same error i got in the https://docs.nvidia.com/cuda/wsl-user-guide/index.html as well, clearly the problem here is related to the driver, but this is so confusing that i don't know what to do anymore... Can you or someone else advise me on this ??

**Comment by DanRuta** [comment]
Hey @cesm1980.

Just throwing in my two cents, this repo works perfectly fine for me without needing to use either Linux or the docker/NGC container. While it may not be the advised way to run things, if you're having trouble running it, it would be a lot less complicated to just create a virtualenv, and run things native to Windows (it works just fine). Just run pip install on the requirements and for pytorch once you've got the virtualenv set up and activated. You do need CUDA on your Windows machine, but installing it is very easy: https://developer.nvidia.com/cuda-downloads

**Comment by cesm1980** [comment]
Oh it's you, glad to see you're here too after we talked a few weeks ago, yeah i never had so much trouble setting up something before, maybe because i am completly new to linux and this is all new to me and as you seen by my post it's a HUGE hassle, and that's without even installing the windows insider builds which i am trying to avoid at all cost!

Virtualenv? never used that before, i guess i will try it tonight, but nevertheless i think i haven't found a single guide on using these repositories about tts engines on windows only, and you won't imagine the tons of hassle and hours lost in trying to figure out by trial and error on google how to set this up, actually i had to give up and try another repository (mozilla tts) there i was finally able to train a voice from scratch using tacotron2 with CPU only (but obviously it's slow as hell without using cuda) and i had to give up and trying to get cuda working on this repository again but as you see it's quite hard for someone completly new to these things, so i apreciate you trying to help.

Anyway tonight i will try all this and see if it works, so far i only got the mozzilla tts working because it didn't require GPU, but i would strongly prefer the fastpitch model like you did with the skyrim voices since i want to be able to modify the pitch, mainly for interrogation markings, and i am still having hope about the anime voices, but without a european portuguese pre-trained model it's gonna be tough training those from scratch with a gtx 1060 6gb...

**Comment by alancucki** [comment]
Hi @cesm1980,

I'm sorry to hear you're having rough time setting up the environment for your computations. As you've probably noticed, we provide DeepLearningExamples. These are as self-contained as possible, but still require a little bit of technical skills to use.

Unfortunately I cannot help you with setting up the environment on Windows. From the experience I can only say that it's easy to set on plain, non-WSL Ubuntu installation. We provide support mainly for the models, and I'll be happy to help in training once you are all set with the drivers.

@DanRuta Thanks for chipping in! Virtualenv is certainly one way to go about it.

**Comment by cesm1980** [comment]
I have very good news, yesterday thanks to the quickstart help from Danruta i was FINALLY able to properly set everything up without a single part of wsl/ubuntu, which is great because WSL eats a LOT of memory every time huges files are written, so it kept closing itself (and i have 32gb ram memory), along other problems since me never using linux before and this being more complicated than everything i did before. And i didnt even need Virtualenv since even with that i had problems, i might use it later when i get more familiar with this.

Anyway i was able to get this repository working with cuda (DeepLearningExamples/Fastpitch) and EVEN the mozzilla tts repository started recognizing cuda as well! But i really prefer fastpitch because of the adjustments in pitch-

> I'm sorry to hear you're having rough time setting up the environment for your computations. As you've probably noticed, we provide DeepLearningExamples. These are as self-contained as possible, but still require a little bit of technical skills to use.

No kidding, it took me a whole week to finally figure this out with zero experience on the workflow of all this, actually if it wasn't for Danruta i would still be stuck at the driver part, since i had the impression it wasnt possible to use cuda on these things without the special drivers from nvidia from the developer program, and the windows insider builds, but now it's finally done, i mean, not still 100%, now the last remaining part is learning how to set this up for such a small vram as my 1060 super has (6gb) becuase of course the first thing that happened was OOM :) I hope that in this week i get this all completly sorted out.

> We provide support mainly for the models, and I'll be happy to help in training once you are all set with the drivers.

You will?? But it's mostly advice or you can actually also train a dataset i would send? Even tough i probably wont need that kind of help now because the first voice will be using a small dataset, but the next ones arent even in english and perhaps i will need a training from scratch from them in tacotron2, even tough i wont need that so soon yet.

If it's only advise, well maybe it's time then, one of the doubts i have for creating a dataset, in my case the voice i want to train has around 750+- wav files, i was initially thinking sorting the wav files and splitting it into separate datasets for each emotion, for example, one for when the voice is speaking in a happy tone, other for angry tone, etc, but since i have no experience on this and i havent found anyone talking about this on google, i wonder, perhaps it's not possible because the dataset is so small? But even if i had 10000 wavs like ljspeech i wonder if text to speech models like this would actually be able to generate voice in the same kind of tone and emotion, if most samples in the dataset would be all in that same emotion.

IF its not possible and it's best to use everything, then i wonder how exactly can i use fast pitch to convey emotions, because so far the only "common sense" thing i know about this, is that when using a interrogation mark at the end of the sentence, the pitch should be increased at the last word but i have no idea how to do for the rest, like sad tone, happy tone, or even yelling, dont tell me we have to do by trial and error? (which i had because of the huge time waster), but perhaps this is too advanced for the model...

One last thing, after i get done with the correct settings for my 6gb card, were can i make a mini-tuturial for the steps in how to set this up in windows? Or even to whom should i send the text so that it could be incorporated into the set up instructions, because jeez i wouldnt want to anyone having to go to the amount of hoops and loops i have to go through and the hours and hours i wasted almost in blind trial and error and so far there's no tuturials about this anywhere, and the reason it took so long for me to figure this out was because the only guide i was able to find was the official cuda on wsl nvidia guide, which made things VERY complicated for no reason and having absurd requirements about installing windows user builds.

**Comment by ArEnSc** [comment]
@cesm1980 this wasn't designed to be run on windows, anyone who has trained models, knows that ubuntu is the way to go if you want less friction to get this off ground. That being said there should be a warning on the github readme. I also went down this pathway to go to use Ubuntu. Microsoft is still bridging this gap, you will not get the GPU performance you are expecting using WSL2. You should make a pull request about it, for the Readme.

The question you are asking about the training, is an active area of research, and you should consider reading the paper. I don't think you should expect much more from this project other than, getting the model up and running and maybe some questions answered about training.

**Comment by cesm1980** [comment]
> @cesm1980 this wasn't designed to be run on windows, anyone who has trained models, knows that ubuntu is the way to go if you want less friction to get this off ground. That being said there should be a warning on the github readme.

Yeah, unfortunately until 1-2 weeks ago i never used this kind of things before, so i guess its part of the beginner's errors :)

> I also went down this pathway to go to use Ubuntu. Microsoft is still bridging this gap, you will not get the GPU performance you are expecting using WSL2. You should make a pull request about it, for the Readme.

Well, it's all fine now, this morning i finally made the milestone of able to train using my own dataset, a pre-trained tacotron2 model, without errors! Yeah, finally the errors ended, i tought they would never end, i totally agree with your this was CLEARLY not designed for windows BUT it does work if we know the right steps to do, which fortunately i was able to eventually figure out thanks to the huge help of DanRuta as well, which as you seen from what he said, he also pulled this off without using linux and docker container.

> 
The question you are asking about the training, is an active area of research, and you should consider reading the paper. I don't think you should expect much more from this project other than, getting the model up and running and maybe some questions answered about training.

Yeah i got the point, that's what i feared, yet again more trial and error to do.

**Comment by alancucki** [comment]
> I have very good news, yesterday thanks to the quickstart help from Danruta i was FINALLY able to properly set everything up

Congrats :)

> now the last remaining part is learning how to set this up for such a small vram as my 1060 super has (6gb) becuase of course the first thing that happened was OOM :)

Lower batch size and increase graddient accumulation proportionally to maintain global batch size 256:
https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/SpeechSynthesis/FastPitch/scripts/train.sh#L14

> If it's only advise, well maybe it's time then, one of the doubts i have for creating a dataset, in my case the voice i want to train has around 750+- wav files, i was initially thinking sorting the wav files and splitting it into separate datasets for each emotion, for example, one for when the voice is speaking in a happy tone, other for angry tone, etc, but since i have no experience on this and i havent found anyone talking about this on google, i wonder, perhaps it's not possible because the dataset is so small? But even if i had 10000 wavs like ljspeech i wonder if text to speech models like this would actually be able to generate voice in the same kind of tone and emotion, if most samples in the dataset would be all in that same emotion.

The support concerns bugs and features of DeepLearningExamples. With emotion labels, it is likely that you could use them as pseudo-speakers. If you've got more speakers, then it might be better to have a separate `nn.Embedding` for emotions, like you do for speakers. I'm just afraid that 750+ utterances might be too little. With such hardware limitations, you could try fine-tunning the pre-trained model which we provide (assuming your data is English speech), and fine-tunning Tacotron2.

> how exactly can i use fast pitch to convey emotions

Pitch is not the only quality of speech; you won't be able to mimick shouting by just altering pitch. Instead of guessing how pitch patterns should look like, visualize a couple of them (e.g., with [Praat](https://www.fon.hum.uva.nl/praat/)).

> were can i make a mini-tuturial for the steps in how to set this up in windows?

We try to keep README files concise, but also consistent between different DeepLearningExamples, and draw a line at providing pointers to Docker. You could certainly paste your solution in this thread.

**Comment by cesm1980** [comment]
> Lower batch size and increase graddient accumulation proportionally to maintain global batch size 256:
> https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/SpeechSynthesis/FastPitch/scripts/train.sh#L14
> 

Ok yeah i am aware of that formula, but how do i tweak it to get epochs done faster? I ask this since despite the documentation in the readme and since i am still new to this i still couldnt grasp exactly which are the "best" settings for this to make the epochs complete faster, i guess it's what you said exactly, lower batch sizes and highter graddient, that's it? That is, of course, until it reaches the amount of memory in my card (6gb), but i don't know exactly if the formula gives more than 256 is bad or not, for example i tried batch size of 4 and 64 gradient, and indeed it appeared to train epochs faster than batch 10 and gradient 10, but since its not maxing out the vram yet, perhaps i can do better? I will keep trying other values nevertheless then by trial and error, because so far i don't know any other way to get the epochs done faster.

By the way enabling AMP throws a error :
File "train.py", line 450, in main
    raise Exception("loss is NaN")
Exception: loss is NaN
I already asked about this to Danruta but i would like also opinion about more people, specially ones having a card like mine since, since perhaps it's not compatible with my card and therefore i would be wasting time trying to solve this error, and i need everything i can to get the epochs done faster since even with batch 4 and gradient 64 its taking 75-77 seconds for train and 16,5 seconds for validate (but thats with a 1300 sample dataset, the first lines and wavs from ljspeech just for testing, since the 750+- dataset i want isnt ready yet, but it should do it faster because of being twice less the size), but other than adjusting the batch and gradient values, i dont know what else i do to make this faster.

Also usually which number of epochs should i do? Perhaps 1500 is the default value, like i seen in the train.sh file? In other issues they always talk about "steps" but here it's epochs, not sure if it's the same thing :)

> The support concerns bugs and features of DeepLearningExamples. With emotion labels, it is likely that you could use them as pseudo-speakers. If you've got more speakers, then it might be better to have a separate nn.Embedding for emotions, like you do for speakers. I'm just afraid that 750+ utterances might be too little. With such hardware limitations, you could try fine-tunning the pre-trained model which we provide (assuming your data is English speech), and fine-tunning Tacotron2.

Thats interesting! Altough, since it's just 750+- wavs maybe i wont bother with this then, unfortunatly the rest of the voices i am going to create they also have around that number of wavs too so later if i have better conditions i will try this then.

Oh wait the other voices i need to train are european portuguese and not english... thats going to be a problem because so far i only found a portuguese-brazilian trained model, and what i need is european portuguese, in case it doesnt sound good with that one, i will have to train from scratch but with a gpu card like i have (1060 super) not sure how many weeks it will take! 

> Pitch is not the only quality of speech; you won't be able to mimick shouting by just altering pitch. Instead of guessing how pitch patterns should look like, visualize a couple of them (e.g., with Praat).

Oh thats interesting... yeah because i wonder if there's more tips besides the one of the interrogation mark increasing the pitch in the end so i will look into this in Praat later.

> We try to keep README files concise, but also consistent between different DeepLearningExamples, and draw a line at providing pointers to Docker. You could certainly paste your solution in this thread.

Ok, as soon as i am done with this, i will post it at the end.

**Comment by ArEnSc** [comment]
@cesm1980 I think you should try ubuntu, I tried with  WSL2 even with the correct drivers, the card was only operating at 20%. I have a batch size of 32 and grad ac of 1 on a RTX 3080.
Each epoch takes 2.30 seconds. YMWV

**Comment by cesm1980** [comment]
> @cesm1980 I think you should try ubuntu, I tried with WSL2 even with the correct drivers, the card was only operating at 20%. I have a batch size of 32 and grad ac of 1 on a RTX 3080.
> Each epoch takes 2.30 seconds. YMWV

Hum... how you measured 20%? I am using gpuz, and it tells me the gpu load is 98%, nearly all the rest of the meters go to maximum as well (temperature also rises as if it was under intense gaming), not sure if gpuz is reliable for this but if it is, probably i am using the card at it's maxium, note i am not using wsl2 anymore, i am using pure windows command prompt. Also, unfortunatly my card is WAY worse than yours so there's no way you can compare it to mine :D (which doesnt even have tensor cores).

For now this will have to do, besides i wont have huge massive datasets to play with (yours have how many times? 2,30 seconds is truly amazing but perhaps thats not possible to achieve without tensor cores..., anyway nearly all the voices i want wont probably be much more than 750-1000 wavs max so... perhaps this will be enough for my needs.

By the way, by trial and error (as usual) i was able to find the best speeds at batch size 9 and gradient 26, now its 68 seconds for train, and 16,5s for eval, only a 6s improvement on the training but perhaps the card cant do better, since i notice it's getting maxed out in gpuz. It might not make that much of a difference for a few epochs, but when doing hundreds of them... definetly will make some difference. Regarding AMP from what i have been reading online, perhaps its of no use to me since i have no tensor cores so it might be useless for this card.

Another thing, i was unable to use batch sizes higher than 17, but even those between 10 and 16, no matter what combinations i tried, it was always slower than using batch 9 with gradient 26 so...

**Comment by alancucki** [comment]
@cesm1980 To speed up training, you could evaluate every `n` epochs, since evals now take 20% of every epoch.

**Comment by alancucki** [comment]
> where can we change that "n" variable

You'd have to code it. Or just shrink the validation dataset, so it would evaluate faster.

FastPitch is a generative model, and the validation loss serves as a reference for how the model behaves during training, and not how good it sounds. The validation step is of a much lower importance than in discriminative models.

**Comment by cesm1980** [comment]
> You'd have to code it. Or just shrink the validation dataset, so it would evaluate faster.
> 
> FastPitch is a generative model, and the validation loss serves as a reference for how the model behaves during training, and not how good it sounds. The validation step is of a much lower importance than in discriminative models.

What??? I havent ever found any information about this on most documents about models... this is completly new to me... well then i guess i have to keep the validation loss just 1 line, since the script doesnt run without it, thanks this was precious advise, no wonder why most of the documentation i find about AI learning models doesnt apply to fastpitch, i didn't even knew yet about generative and discriminative models, i still have a LOT to read, but at least giving me these terms helps a LOT indeed.
