### ISSUE TITLE
[FastPitch/Pytorch] Multi-speaker setup points of clearification

### ISSUE THREAD

**Issue by ArEnSc** [NVIDIA/DeepLearningExamples#832]
```We've just added support for multiple speakers. This is exactly the conditioning used in the FastPitch paper.
Currently you'd have to prepare you own dataset with filelist following the format:

<mel_path>|<durations_path>|<pitch_path>|<transcript>|<speaker_id>
where speaker_id is an integer from {0,...,n_speakers-1}, and then pass --n-speakers <N> to train.py and inference.py.
```

Would this train on the existing model 1500pt model ? and 
how many hours of training data would you need to get a good conditioned model?. It seems like you guys said around 30 but was that per data set?

**Comment by ArEnSc** [comment]
Hey I looked through the source code and answered the questions thanks !

**Comment by jmasterx** [comment]
I would like to train a multispeaker fast pitch. Is there a more comprehensive guide somewhere I can find that discusses how to train the tacotron2 model for multi speaker, the expected format of the file lists, etc? I'm striggling to find a clear guide to train multispeaker. @ArEnSc

Thanks
