### ISSUE TITLE
batch size question

### ISSUE THREAD

**Issue by jeff-yajun-liu** [NVIDIA/DeepLearningExamples#839]
DeepLearningExamples/tree/master/TensorFlow/Classification/ConvNets/resnet50v1.5

in following command:
mpiexec --allow-run-as-root -np **4** --bind-to socket python -u ./alexnet.py  --batch_size _64_   --num_iter 1000 --precision fp32 --iter_unit batch >>/data/tfrecords/milan-syn-ale-fp32-gpu4   

the batch_size 64, it is per GPU or 'global" batch size?  If it is per GPU, the total batch size should be  4x64=254.  How does the batch size compare with NGC.Ready, which only uses 64 and 128, then times with the number of GPU.

**Comment by hXl3s** [comment]
Hi! With tensorflow convnets, batch_size parameter is interpreted as a local batch size. So with 64 specified and 4 GPU you are training with global batch size 256

**Comment by jeff-yajun-liu** [comment]
Got it, thanks!!
