### ISSUE TITLE
Tensorflow NCF wrong movielens data location

### ISSUE THREAD

**Issue by vinhngx** [NVIDIA/DeepLearningExamples#85]
Data after the preparation step is stored at "/tmp/cache/ml-20m" instead of "/data/cache/ml-20m"
So if one follows the instruction:

datadir=/data/cache/ml-20m
mpirun -np $numgpu \
    --allow-run-as-root \
    python ncf.py --data $datadir

the data will be missing.

**Comment by tgrel** [comment]
This should be fixed in the next release.
