### ISSUE TITLE
How to export the Fastpitch Pytorch Model to ONNX ?

### ISSUE THREAD

**Issue by ductho9799** [NVIDIA/DeepLearningExamples#860]

**Comment by GrzegorzKarchNV** [comment]
Hi @ductho9799 , we don't have ONNX version of FastPitch yet; we'll release new version soon though, hopefully with ONNX support - stay tuned!

**Comment by sciai-ai** [comment]
is this available?

**Comment by prashantskit** [comment]
Any update here?
