### ISSUE TITLE
[DLRM/PyTorch] Preprocessing scripts fail on system with less than 16 GPUs

### ISSUE THREAD

**Issue by jplewis2** [NVIDIA/DeepLearningExamples#872]
Related to **DLRM/PyTorch** 

**Describe the bug**
The default setting of "16" in the `/opt/spark-3.0.0-bin-hadoop3.2/conf/spark-defaults.conf` file causes problems when running on a system with less than 16 GPUs.
`spark.worker.resource.gpu.amount                16`

**To Reproduce**
In a system with less than 16 GPUs, run either proproc script and you will get an error similar to this when it starts the worker:
```
Spark Command: /usr/lib/jvm/java-8-openjdk-amd64/bin/java -cp /opt/spark-3.0.0-bin-hadoop3.2/conf/:/opt/spark-3.0.0-bin-hadoop3.2/jars/* -Xmx1g org.apache.spark.deploy.worker.Worker --webui-port 8081 spark://b9da455fc9c8:7077
========================================
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
21/03/16 13:26:10 INFO Worker: Started daemon with process name: 5591@b9da455fc9c8
21/03/16 13:26:10 INFO SignalUtils: Registered signal handler for TERM
21/03/16 13:26:10 INFO SignalUtils: Registered signal handler for HUP
21/03/16 13:26:10 INFO SignalUtils: Registered signal handler for INT
21/03/16 13:26:10 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
21/03/16 13:26:10 INFO SecurityManager: Changing view acls to: root
21/03/16 13:26:10 INFO SecurityManager: Changing modify acls to: root
21/03/16 13:26:10 INFO SecurityManager: Changing view acls groups to: 
21/03/16 13:26:10 INFO SecurityManager: Changing modify acls groups to: 
21/03/16 13:26:10 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
21/03/16 13:26:11 INFO Utils: Successfully started service 'sparkWorker' on port 35653.
21/03/16 13:26:11 INFO Worker: Starting Spark worker 172.17.0.2:35653 with 224 cores, 1509.3 GiB RAM
21/03/16 13:26:11 INFO Worker: Running Spark version 3.0.0
21/03/16 13:26:11 INFO Worker: Spark home: /opt/spark-3.0.0-bin-hadoop3.2
21/03/16 13:26:11 INFO ResourceDiscoveryScriptPlugin: Discovering resources for gpu with script: /opt/spark-3.0.0-bin-hadoop3.2/conf/get_gpu_resources.sh
21/03/16 13:26:11 ERROR Worker: Failed to setup worker resources: 
java.lang.IllegalArgumentException: requirement failed: Resource: gpu, with addresses: 0 is less than what the user requested: 16)
	at scala.Predef$.require(Predef.scala:281)
	at org.apache.spark.resource.ResourceUtils$.assertResourceAllocationMeetsRequest(ResourceUtils.scala:270)
	at org.apache.spark.resource.ResourceUtils$.$anonfun$assertAllResourceAllocationsMeetRequests$2(ResourceUtils.scala:278)
	at org.apache.spark.resource.ResourceUtils$.$anonfun$assertAllResourceAllocationsMeetRequests$2$adapted(ResourceUtils.scala:278)
	at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:75)
	at org.apache.spark.resource.ResourceUtils$.assertAllResourceAllocationsMeetRequests(ResourceUtils.scala:278)
	at org.apache.spark.resource.ResourceUtils$.getOrDiscoverAllResources(ResourceUtils.scala:308)
	at org.apache.spark.deploy.worker.Worker.setupWorkerResources(Worker.scala:222)
	at org.apache.spark.deploy.worker.Worker.onStart(Worker.scala:207)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:120)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:203)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Expected behavior**
This value should be dynamically changed depending on the preproc script being run. 
* When running `run_spark_cpu.sh` it should be set to 0
* When running `run_spark_gpu.sh` should be set to the number of executors

**Environment**
* Container: pytorch:20.03-py3
* 4-socket Xeon 8180M (4x 28 cores), 1.5TB of memory
* 1x Tesla T4:
* CUDA driver version: 460.32.03

**Comment by mkfilipiuk** [comment]
Hi @jplewis2,
You're totally right - I'll discuss with my team what would be the best way to deal with this issue.
Could you change this value to 0 or 1 and check if you can proceed with Spark CPU preprocessing (Spark GPU implementation needs to be strongly coupled with a specific hardware so there is very faint chance that it'd work with one T4 out of the box)? I'd like not to keep you blocked until we push the solution to the repo.
Best,
Michał

**Comment by mkfilipiuk** [comment]
Hi again @jplewis2,
this or next week we should push a code with the new functionality of specifying the number of GPU used by spark during the building of a docker image.
I'll let you know when it's ready.

**Comment by jplewis2** [comment]
Thanks,
I've verified that setting the value to 0 works with the `run_spark_cpu.sh` script.

After some modifications I was even able to get the `run_spark_gpu.sh` script to work with only 1x T4 GPU.

Did some very quick comparisons using a trimmed down dataset (1% normal size). GPU was slightly slower, but used a fraction of the CPU resources, whereas the CPU runs consumed nearly the entire 112 cores in my 4-socket system.

**Comment by mkfilipiuk** [comment]
Great to hear that it's not blocking you.
Unfortunately, I'm not an expert on tuning Spark performance, so I won't be able to help you how to take as much as possible out of your hardware.

I have already a fix for this problem so I'll let you know when it's pushed to the repo.

**Comment by mkfilipiuk** [comment]
Hi @jplewis2,
I'm back with a release and a new Dockerfile for you, where you can specify how many GPUs you have when building the docker image:
`docker build -t nvidia_dlrm_preprocessing -f Dockerfile_preprocessing . --build-arg NUMBER_OF_GPUS=1`

Let me know if you have any more questions. If not, I'll proceed to close the issue.

Best,
Michał Filipiuk

**Comment by jplewis2** [comment]
This looks great. Thanks! You can close the issue.

**Comment by mkfilipiuk** [comment]
Great! Closing.
