### ISSUE TITLE
cpu run for SpeechRecognition/Jasper

### ISSUE THREAD

**Issue by sans-sense** [NVIDIA/DeepLearningExamples#878]
Related to **Model/Framework(s)** 
Pytorch

**Describe the bug**
Model allows individual audio file inference and works well on cpu. Sadly feature extraction becomes a gpu thing inspite of passing dali_device as cpu, as dali needs json file. Moving audio and audio_lens to cpu solves the issue

**To Reproduce**
python inference.py --ema --model_config <base>/DeepLearningExamples/PyTorch/SpeechRecognition/Jasper/configs/jasper10x5dr_speca.yaml --ckpt <base>/jaspertorch/models/nvidia_jasper_210205.pt --transcribe_wav <base>/DeepLearningExamples/PyTorch/SpeechRecognition/Jasper/notebooks/example1.wav --cpu --dali_device cpu

**Expected behavior**
Should work on cpu without issue

**Environment**
torch 1.7 cuda 11

**Fix**
move audio and audio_lens to cpu in inference.py
<pre>
                # AN : without json file use_dali is false, so everything becomes gpu
                if args.cpu:
                    audio = audio.cpu()
                    audio_lens = audio_lens.cpu()
</pre>
at line 329 of inference.py (DeepLearningExamples/PyTorch/SpeechRecognition/Jasper/inference.py)

**Comment by alancucki** [comment]
Hi @sans-sense , thanks for reporting this! Fixed in https://github.com/NVIDIA/DeepLearningExamples/pull/885 .
