### ISSUE TITLE
BERT and TensorRT

### ISSUE THREAD

**Issue by vince-adamo** [NVIDIA/DeepLearningExamples#88]
I have described a couple of errors I am observing while attempting to optimize a model derived from a BERT NLP model here: https://devtalk.nvidia.com/default/topic/1056241/tensorrt/bert-model-and-tensorrt/

I would like to ask if anyone who is involved with this particular project has attempted to perform a similar optimization and/or may be able to provide any recommendations on how to successfully convert/run BERT models using TensorRT.

Thanks,
Vince Adamo

**Comment by pranavm-nvidia** [comment]
We have a standalone sample for BERT available here: https://github.com/NVIDIA/TensorRT/tree/release/5.1/demo/BERT

**Comment by vince-adamo** [comment]
Thanks for the update! We will check that out...
