### ISSUE TITLE
[resnet50v1.5/tensorflow] standard training process ocuured loss NAN

### ISSUE THREAD

**Issue by Haijunlv** [NVIDIA/DeepLearningExamples#891]
Related to Model/Framework(s)
resnet50v1.5/tensorflow

Describe the bug
standard training process ocuured loss NAN

To Reproduce
we did not change code, just use code  inside the docker image
1) using code in side the nvcr.io/nvidia/tensorflow:20.06-tf1-py3  
start scripts(standard imagenet train scripts)
```
export CUDA_VISIBLE_DEVICES=0,1,2,3
cd /workspace/nvidia-examples/resnet50v1.5
mpiexec --allow-run-as-root --bind-to none --map-by slot -np 4 python3 main.py \
          --mode=train_and_evaluate \
          --iter_unit=epoch \
          --num_iter=90 \
          --batch_size=256 \
          --warmup_steps=100 \
          --use_cosine_lr \
          --label_smoothing=0.1 \
          --lr_init=0.256 \
          --lr_warmup_epochs=8 \
          --momentum=0.875 \
          --weight_decay=3.0517578125e-05 \
          --use_tf_amp \
          --data_dir=/cfs/imagenet/tfrecord/train \
          --results_dir=${work_dirs}  \
          --use_xla
```
log show when 91730 iter loss is Nan 
![image](https://user-images.githubusercontent.com/28926237/112644320-3f117980-8e80-11eb-9588-b632b8e67a6a.png)

log can download from  https://bj.bcebos.com/v1/rudder-workspace/private-data/lvhaijun/ngc_log/20.06-tf1-py3/log.txt?authorization=bce-auth-v1%2F33b1db751f5a416fb82b9ad194444bb2%2F2021-03-26T14%3A17%3A11Z%2F1800%2Fhost%2Fcda93cae8bbc1b646823b1c5f5f352995c167cb50e5c8bebf663ed1ab756159c

2) using code in side the nvcr.io/nvidia/tensorflow:20.12-tf1-py3  
start scripts(standard imagenet train scripts)
```
export CUDA_VISIBLE_DEVICES=0,1,2,3
cd /workspace/nvidia-examples/resnet50v1.5
mpiexec --allow-run-as-root --bind-to none --map-by slot -np 4 python3 main.py \
          --arch=resnet50 \
          --mode=train_and_evaluate \
          --iter_unit=epoch \
          --num_iter=90 \
          --batch_size=256 \
          --warmup_steps=100 \
          --use_cosine \
          --label_smoothing=0.1 \
          --lr_init=0.256 \
          --lr_warmup_epochs=8 \
          --momentum=0.875 \
          --weight_decay=3.0517578125e-05 \
          --use_tf_amp \
          --use_static_loss_scaling \
          --loss_scale=128 \
          --data_dir=/cfs/lvhaijun/imagenet/tfrecord/train \
          --results_dir=${work_dirs}  \
          --weight_init=fan_in \
          --use_xla
```
log also shows loss Nan at 74epoch(92870 iter)
![image](https://user-images.githubusercontent.com/28926237/112644921-e7bfd900-8e80-11eb-9b37-7331b44f70ac.png)
![image](https://user-images.githubusercontent.com/28926237/112645159-28b7ed80-8e81-11eb-8919-8045aeee119a.png)
![image](https://user-images.githubusercontent.com/28926237/112645545-8a785780-8e81-11eb-8f9c-18300f54ad4d.png)

log can download from https://bj.bcebos.com/v1/rudder-workspace/private-data/lvhaijun/ngc_log/20.12-tf1-py3%20%20/log.txt?authorization=bce-auth-v1%2F33b1db751f5a416fb82b9ad194444bb2%2F2021-03-26T14%3A17%3A25Z%2F1800%2Fhost%2F4d0cc411f164ce3b16d50cb90fecfc5edb9124bbad6f956f239cc8d65da8fb32
and tensorboard file can download from https://bj.bcebos.com/v1/rudder-workspace/private-data/lvhaijun/ngc_log/20.12-tf1-py3%20%20/events.out.tfevents.1616685359.bcc-rudder-V100-32G-4--2?authorization=bce-auth-v1%2F33b1db751f5a416fb82b9ad194444bb2%2F2021-03-26T14%3A18%3A35Z%2F1800%2Fhost%2F452ed38b4874180c2912df317097e8d0ec7b5bb3c1be363cd46b0796d7d19157

from loss graph and leaning rate graph, loss diverged after 10k step(8epoch), which is equal to lr_warmup_epochs.
maybe bug is related to  some operation after lr_warmup_epochs? 

Environment
Please provide at least:

Container version： nvcr.io/nvidia/tensorflow:20.06-tf1-py3 or  nvcr.io/nvidia/tensorflow:20.12-tf1-py3  
GPUs in the system:4*Tesla V100-SXM2-32GB
CUDA driver version (e.g. 418.67): 460.32.03, cuda11
CPU：Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz * 16
*CODE: code inside the docker container

**Comment by hXl3s** [comment]
Scheduled some runs for 20.06 to verify that.

**Comment by Haijunlv** [comment]
> Scheduled some runs for 20.06 to verify that.
i found one inconsistence between ngc code and my imagenet tfrecord.
ngc code need imagenet tfrecord label between 1~1000
https://github.com/NVIDIA/DeepLearningExamples/blob/master/TensorFlow/Classification/ConvNets/utils/image_processing.py#L138

my imagenet tfrecord label is between 0~999
this bug is not obvious.
maybe it is more clear to add labels_offset  in argument like tf slim 
https://github.com/tensorflow/models/blob/master/research/slim/train_image_classifier.py#L193

i will reproduce training acc performance later, if have other problem, i will feedback.
