### ISSUE TITLE
[Transformer-XL/Pytorch] logger doesn't show anything in console in ddp mode

### ISSUE THREAD

**Issue by hamid-ramezani** [NVIDIA/DeepLearningExamples#899]
**Describe the bug**
 When I try to train Transformer-XL on WT103 on multiple GPUs, the log is neither shown on the console, nor saved in a file.  However, when I run on one GPU, the logger works perfectly. 

**To Reproduce**
1. Go to directory `DeepLearningExamples/PyTorch/LanguageModeling/Transformer-XL/pytorch`
2. Inside `wt103_base.yaml` set `log_all_ranks` flag to `true` 
3. Launch `bash run_wt103_base.sh train 4`

**Expected behavior**
The training log is not shown in the console. Besides, the log is not saved in `LM-TFM` folder. (only a json file is saved there)

**Environment**
Please provide at least:
* pytorch nightly installed through `pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html`

* GPUs in the system:  4x RTX 3090-24GB:
* CUDA version: 11.2
* CUDA driver: 460.39

**Comment by szmigacz** [comment]
It's because of a bug in pytorch. I submitted PR to pytorch to fix this but I'm still waiting on merge: https://github.com/pytorch/pytorch/pull/52757

In the meantime - I have a workaround which I could push to Transformer-XL model to reenable logging, I'll do that later today.

**Comment by szmigacz** [comment]
@hamid-ramezani I pushed latest version of transformer-xl to https://github.com/NVIDIA/DeepLearningExamples/pull/901, it includes a workaround for issues with logging in latest versions of PyTorch, please check if this fixes the issue in your use case.

**Comment by hamid-ramezani** [comment]
@szmigacz Thank you very much for your time and effort.
