### ISSUE TITLE
pFP16Initializer in train_cifar10.py should be replaced with PseudoFP16Initializer

### ISSUE THREAD

**Issue by dzung-hoang** [NVIDIA/DeepLearningExamples#9]
Running the Caffe2/Classification/cifar10/train_cifar10.py script results in the following error:

```
Traceback (most recent call last):
  File "train_cifar10.py", line 13, in <module>
    from caffe2.python.modeling.initializers import Initializer, pFP16Initializer
ImportError: cannot import name pFP16Initializer
```

This can be fixed by replacing all occurrences of pFP16Initializer with PseudoFP16Initializer.

**Comment by dzung-hoang** [comment]
I ran this using pytorch v1.0rc1.

**Comment by nvpstr** [comment]
Caffe2 will be no longer supported.
