### ISSUE TITLE
Error in downloading data

### ISSUE THREAD

**Issue by HongmingHUANG** [NVIDIA/DeepLearningExamples#90]
When run data_download.sh and it is downloading Wikimedia data, it says there is no such directory. Seems some source file is missing... Is there any other way to get and process the data?

Downloading Wikidump
--2019-06-26 12:10:32--  ftp://ftpmirror.your.org/pub/wikimedia/dumps/enwiki/20190301/enwiki-20190301-pages-articles-multistream.xml.bz2
           => ‘wikidump.xml.bz2’
Resolving ftpmirror.your.org (ftpmirror.your.org)... 204.9.55.82, 2001:4978:1:420::cc09:3752
Connecting to ftpmirror.your.org (ftpmirror.your.org)|204.9.55.82|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/wikimedia/dumps/enwiki/20190301 ...
No such directory ‘pub/wikimedia/dumps/enwiki/20190301’.

**Comment by HongmingHUANG** [comment]
I fixed it by rename the folder name, now this problem is solved but I met another problem... It came up with lots of HTTP error... Does it matters?
Failed to open https://www.smashwords.com/books/download/736702/6/latest/0/0/all-the-way-back.txt
HTTPError: HTTP Error 503: Service Temporarily Unavailable

**Comment by swethmandava** [comment]
Bookscorpus server could be overloaded. The script skips individual books if the server gives a 503 error. A repeated download will retry books if they are not already present locally
