### ISSUE TITLE
can't find the 'export_frozen_graph.py' for QAT in DeepLearningExamples/TensorFlow/Classification/ConvNets/resnet50v1.5/

### ISSUE THREAD

**Issue by shiyongming** [NVIDIA/DeepLearningExamples#903]
I can't find the export_frozen_graph.py for QAT demo in DeepLearningExamples/TensorFlow/Classification/ConvNets/resnet50v1.5/

in this demo, it uses export_frozen_graph.py to Export Frozen graphs (https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/Classification/ConvNets/resnet50v1.5#exporting-frozen-graphs).

But I can't find the export_frozen_graph.py in this repo...

**Comment by hXl3s** [comment]
Hi @shiyongming,

export_frozen_graph.py is in the parent directory: https://github.com/NVIDIA/DeepLearningExamples/blob/master/TensorFlow/Classification/ConvNets/export_frozen_graph.py
