### ISSUE TITLE
[TensorFlow/BERT] Cannot install nor import "run_squad" and "modeling"

### ISSUE THREAD

**Issue by yamagisihide** [NVIDIA/DeepLearningExamples#915]
Related to [DeepLearningExamples/TensorFlow/LanguageModeling/BERT/notebooks/bert_squad_tf_inference_colab.ipynb](https://github.com/NVIDIA/DeepLearningExamples/blob/master/TensorFlow/LanguageModeling/BERT/notebooks/bert_squad_tf_inference_colab.ipynb)

**Describe the bug**
I ran the following commands in the above notebook but got errors "ModuleNotFoundError: No module named 'run_squad (or modeling)'"
     [commands]
     import run_squad
     import modeling

**To Reproduce**
1. Open the following link, click "Open in Colab" to open the notebook in Google Collaboratory 
[DeepLearningExamples/TensorFlow/LanguageModeling/BERT/notebooks/bert_squad_tf_inference_colab.ipynb](https://github.com/NVIDIA/DeepLearningExamples/blob/master/TensorFlow/LanguageModeling/BERT/notebooks/bert_squad_tf_inference_colab.ipynb)

2. Run the block in the notebook under "5. Running QA task inference"that begin with "import run_squad"

3. Run the following commands 
    !pip install --upgrade pip
    !!pip install run_squad
    !!pip install modeling

**Expected behavior**
"run_squad" and "modeling" are installed and imported

**Environment**
Google Collaboratory (might occur in any environment)

**Comment by meatybobby** [comment]
Hi @yamagisihide,
This problem is missing working directory in python path.
Did you run the block under "3. BERT Inference: Question Answering"?
```
import sys

working_dir = os.getcwd();
data_dir = os.path.join(working_dir, 'data/download');
if working_dir not in sys.path:
    sys.path.append(working_dir)
```
