### ISSUE TITLE
AutoaugmentImageNetPolicy in dali 

### ISSUE THREAD

**Issue by pawopawo** [NVIDIA/DeepLearningExamples#919]
How to use [AutoaugmentImageNetPolicy](https://github.com/NVIDIA/DeepLearningExamples/blob/26206dbf8704c91eb57d04baa777bc869bea7e13/PyTorch/Classification/ConvNets/image_classification/autoaugment.py#L6) in dali ？

**Comment by asulecki** [comment]
Right now you can not. DALI does not support picking the augmentations at random.
