### ISSUE TITLE
[BERT/PyTorch] MRPC Download Failure

### ISSUE THREAD

**Issue by roclark** [NVIDIA/DeepLearningExamples#929]
Related to **BERT/PyTorch** 

**Describe the bug**
While running [create_datasets_from_start.sh](https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/LanguageModeling/BERT/data/create_datasets_from_start.sh), the MRPC download fails with the following error:

```
Traceback (most recent call last):
  File "/workspace/bert/data/bertPrep.py", line 363, in <module>
    main(args)
  File "/workspace/bert/data/bertPrep.py", line 60, in main
    downloader.download()
  File "/workspace/bert/data/Downloader.py", line 45, in download
    self.download_glue(self.dataset_name)
  File "/workspace/bert/data/Downloader.py", line 82, in download_glue
    downloader.download(task_name)
  File "/workspace/bert/data/GLUEDownloader.py", line 45, in download
    ['--data_dir', self.save_path, '--tasks', task_name])
  File "/workspace/bert/data/download/glue/download_glue_data.py", line 142, in main
    format_mrpc(args.data_dir, args.path_to_mrpc)
  File "/workspace/bert/data/download/glue/download_glue_data.py", line 65, in format_mrpc
    URLLIB.urlretrieve(MRPC_TRAIN, mrpc_train_file)
NameError: name 'URLLIB' is not defined
```

This comes from an external piece of code found [here](https://gist.github.com/W4ngatang/60c2bdb54d156a41194446737ce03e2e/#file-download_glue_data-py). In that gist, the variable `URLLIB` is used but is never assigned, so the script will throw the error above while trying to run the `create_datasets_from_start.sh` script in this repository. This is an easy fix as line 25 in that gist needs to be updated to

```python
import urllib.requests as URLLIB
```

However, since this is an external script not maintained by this repository, it's harder to work around. Perhaps one solution would be to create a fork of that gist with the expected fix, or use a more reliable source to download the expected data.

**To Reproduce**
1. Configure a new machine (or isolated repo locally).
2. Build the latest BERT container according to the steps in the PyTorch BERT README.
3. Launch the container using `bash scripts/docker/launch.sh`.
4. Run the `create_datasets_from_start.sh` script inside the container. If `set -e` is placed at the top of that script, it will fail immediately after the MPRC section starts.

**Expected behavior**
I would expect the `create_datasets_from_start.sh` script to complete without failures.

**Environment**
Please provide at least:
* Container version: The built `bert` container from the README (doesn't have any tags or specifics).
* GPUs in the system: 2x Quadro RTX 8000 48GB
* CUDA driver version: 460.32.03

**Comment by sharathts** [comment]
@roclark Thank for pointing this out. Can you make an MR for the change please?

**Comment by roclark** [comment]
Sure! I will create a fork of the gist with the fix in my personal account and update the code in the repo here to point to that gist.
