### ISSUE TITLE
Error in Validation of Transformer

### ISSUE THREAD

**Issue by yaoyiran** [NVIDIA/DeepLearningExamples#93]
In train.py, line 391:  predictions = [hypo[1] + ('\n' if hypo[-1]!='\n' else '') for hypo in predictions],  I think it should be predictions = [hypo[1] + ('\n' if hypo[1][-1]!='\n' else '') for hypo in predictions] because hypo[-1] is a whole sentence which will never be "\n" at all.

**Comment by jbaczek** [comment]
This part of the code is well checked. It appends EOL to the sentence if it's not already there.

**Comment by yaoyiran** [comment]
I have printed it out and found that hypo is a tuple like (int,"sentence......\n"). Since hypo[-1] and hypo[1] are the same, which is the whole sentence, the code, line 391, will always append "\n" to hypo[1], and the result is every sentence in the final predictions is ended with "\n\n", double "\n".

**Comment by jbaczek** [comment]
Can you make a pull request then? I'll review it soon.

**Comment by yaoyiran** [comment]
Sure, I have made a pull request yesterday. Thx.

https://github.com/NVIDIA/DeepLearningExamples/pull/94
