### ISSUE TITLE
[FastPitch/Pytorch] Fastpitch with less than 80 mel channels

### ISSUE THREAD

**Issue by juliakorovsky** [NVIDIA/DeepLearningExamples#936]
FastPitch was created for predicting mel-spectrograms with 80 mel channels. If I want to get good results with not 80, but, say, 22 channels, should I adjust parameters and if so, which ones?

**Comment by alancucki** [comment]
Hi @juliakorovsky ,

there is a `--n-mel-channels` argument (set [here](https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/SpeechSynthesis/FastPitch/fastpitch/arg_parser.py#L38)). Be sure to pass it first to `extract_mels.py` when preparing the dataset, and then to `train.py`.
