### ISSUE TITLE
bind.sh script error

### ISSUE THREAD

**Issue by moonsooyoung** [NVIDIA/DeepLearningExamples#945]
Related to BERT/PyTorch Example 

**Describe the bug**
bind.sh has no execute permission and has a typo in bind.sh script with an unnecessary space in the line "#! /bin/bash"

**To Reproduce**
git clone https://github.com/NVIDIA/DeepLearningExamples.git
cd DeepLearningExamples/PyTorch/LanguageModeling/BERT
./bind.sh --> permission error
sudo chmod +x ./bind.sh
./bind.sh
bind.sh: 15: set: Illegal option -o pipefail

**Expected behavior**
Should run without any errors.

**Environment**
Ubuntu 18.04

**Comment by sharathts** [comment]
bind.sh should be used with run.sub as shown in https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/LanguageModeling/BERT/run.sub#L33

I don't think permissions is an issue.
Closing bug, feel free to reopen if you have any other questions.
