### ISSUE TITLE
BERT bind.sh error

### ISSUE THREAD

**Issue by moonsooyoung** [NVIDIA/DeepLearningExamples#946]
Related to **Model/Framework(s)** 
BERT/PyTorch

**Describe the bug**
bind.sh script has typos and has no execution permission
It seems "#! /bin/bash" should be corrected to be "#!/bin/bash" and moved to the top line of the script.

**To Reproduce**
git clone https://github.com/NVIDIA/DeepLearningExamples.git
cd DeepLearningExamples/PyTorch/LanguageModeling/BERT
./bind.sh
Fails with permisson error
After running chmod +x ./bind.sh, the permission error doesn't happen but it fails again with the following error message: 
0: ./bind.sh: 15: set: Illegal option -o pipefail
After correcting the typos mentioned above, the error has been resolved.

**Expected behavior**
It runs without an error.

**Environment**
Container version: PyTorch 20.06
GPUs: A100 PCI
Host OS: Ubuntu 18.04
CUDA driver version: 455

**Comment by sharathts** [comment]
@moonsooyoung Isn't this the same as https://github.com/NVIDIA/DeepLearningExamples/issues/945?

**Comment by sharathts** [comment]
That should be fine. Closing since it's not an issue. Feel free to reopen if you have more questions.
