### ISSUE TITLE
[tacotron2/Pytorch] 'Tacotron2' object has no attribute 'text_to_sequence'

### ISSUE THREAD

**Issue by Luosuu** [NVIDIA/DeepLearningExamples#955]
**Describe the bug**
I run the tutorial on https://pytorch.org/hub/nvidia_deeplearningexamples_waveglow/
and I got errors

`AttributeError: 'Tacotron2' object has no attribute 'text_to_sequence`

it is the error from line 20 of this tutorial

```python3
sequence = np.array(tacotron2.text_to_sequence(text, ['english_cleaners']))[None, :]
```

**To Reproduce**
it will occur no matter executing the tutorial on Google colab or on my local machine 

**Expected behavior**
sequence should be generated from the tacotron2 model by inputting the text

**Environment**
Please provide at least:
* Container version (e.g. pytorch:19.05-py3): pytorch 1.8.1+cu102
* GPUs in the system: (e.g. 8x Tesla V100-SXM2-16GB): GTX1080
* CUDA driver version (e.g. 418.67): 11.2

**Comment by seemethere** [comment]
Also observing this as well

**Comment by seemethere** [comment]
Did some digging and it looks like this might've been broken for a while on `master` but was only recently pushed to the `torchhub` branch,

I've tried the notebook again this time with a commit that for sure works in a8328ce1690fe473f3c5ac55811dab6b0f36700d

CC @nv-kkudrynski

**Comment by Luosuu** [comment]
Is it possible to fix it in the near future? or modify the tutorial on pytorch hub.

**Comment by jan-golda** [comment]
From what I know this should be fixed now that https://github.com/pytorch/hub/pull/204 was merged.
I am not able to check that at the moment, will take a look tomorrow.

**Comment by nv-kkudrynski** [comment]
Indeed, our PR to pytorch/hub with updated example notebooks took a few days to be processed.
@seemethere @Luosuu, I just checked and it works now. Sorry for inconveniece.

**Comment by seemethere** [comment]
No worries, thanks for the fix @nv-kkudrynski!

**Comment by Luosuu** [comment]
thanks for the fix @nv-kkudrynski! Also thanks for your help and analysis @seemethere !
