### ISSUE TITLE
[Jasper/Pytorch] export_model issue 

### ISSUE THREAD

**Issue by areoll** [NVIDIA/DeepLearningExamples#965]
### **Describe the bug**
The checkpoint from https://ngc.nvidia.com/catalog/models/nvidia:jasper_pyt_ckpt_amp can export to decoder model. But can't export to feature-extractor-ts-trace, "ts-trace" "onnx" "tensorrt" successful.   

**To Reproduce**
1. Clone the repository.

git clone https://github.com/NVIDIA/DeepLearningExamples
cd DeepLearningExamples/PyTorch/SpeechRecognition/Jasper

2. Build the Jasper PyTorch container.
Running the following scripts will build the container which contains all the required dependencies for data download and processing as well as converting the model.

bash scripts/docker/build.sh

3. Start an interactive session in the Docker container:

bash scripts/docker/launch.sh <DATA_DIR> <CHECKPOINT_DIR> <RESULT_DIR>

4. Downloading the test-clean part of LibriSpeech is required for model conversion. But it is not required for inference on Triton Inference Server, which can use a single .wav audio file. To download and preprocess LibriSpeech, run the following inside the container: 

bash triton/scripts/download_triton_librispeech.sh
bash triton/scripts/preprocess_triton_librispeech.sh

5. (Option 1) Convert pretrained PyTorch model checkpoint into Triton Inference Server compatible model backends.
Inside the container, run:

export CHECKPOINT_PATH=<CHECKPOINT_PATH>
export CONVERT_PRECISIONS=<CONVERT_PRECISIONS>
export CONVERTS=<CONVERTS>
bash triton/scripts/export_model.sh

**Expected behavior**

**1 . Once we run export "decoder" and got successful result as below:**
root@4daff75f04d7:/workspace/jasper# export CONVERTS="decoder"
root@4daff75f04d7:/workspace/jasper# bash triton/scripts/export_model.sh
mkdir -p /workspace/jasper/triton/scripts/../../triton/model_repo/fp16//decoder-ts-script/1
chmod a+w /workspace/jasper/triton/scripts/../../triton/model_repo/fp16//decoder-ts-script/1
python triton/converter.py --model-module jasper_module --convert ts-script --precision fp16 --save-dir /workspace/jasper/triton/scripts/../../triton/model_repo/fp16//decoder-ts-script/1 -- --batch_size 8 --dataset_dir /datasets/LibriSpeech --val_manifest /datasets/LibriSpeech/librispeech-test-clean-wav.json --model_config configs/jasper10x5dr_speedp-offline_speca_nomask.yaml --ckpt=/checkpoints --ema --component decoder
[Jasper module]: using device cuda
[Jasper module]: using mixed precision

**2. but export to "feature-extractor", got issue as below:** 
root@4daff75f04d7:/workspace/jasper# export CONVERTS="feature-extractor"
root@4daff75f04d7:/workspace/jasper# bash triton/scripts/export_model.sh
mkdir -p /workspace/jasper/triton/scripts/../../triton/model_repo/fp16//feature-extractor-ts-trace/1
chmod a+w /workspace/jasper/triton/scripts/../../triton/model_repo/fp16//feature-extractor-ts-trace/1
python triton/converter.py --model-module jasper_module --convert ts-trace --precision fp16 --save-dir /workspace/jasper/triton/scripts/../../triton/model_repo/fp16//feature-extractor-ts-trace/1 -- --batch_size 8 --dataset_dir /datasets/LibriSpeech --val_manifest /datasets/LibriSpeech/librispeech-test-clean-wav.json --model_config configs/jasper10x5dr_speedp-offline_speca_nomask.yaml --ckpt=/checkpoints --ema --component feature-extractor
Traceback (most recent call last):
  File "triton/converter.py", line 246, in <module>
    model = mm.init_model(model_args_list, args.precision, args.device)
  File "/workspace/jasper/triton/jasper_module.py", line 184, in init_model
    comp = init_comp[args.component](args)
  File "/workspace/jasper/triton/jasper_module.py", line 112, in init_feature_extractor
    if args.max_duration is not None:
AttributeError: 'Namespace' object has no attribute 'max_duration'

3. export to "onnx", got issue as below:** 
root@4daff75f04d7:/workspace/jasper# export CONVERTS="onnx"
root@4daff75f04d7:/workspace/jasper# export CONVERTS="ts-trace"
root@4daff75f04d7:/workspace/jasper# bash triton/scripts/export_model.sh
mkdir -p /workspace/jasper/triton/scripts/../../triton/model_repo/fp16//jasper-ts-trace/1
chmod a+w /workspace/jasper/triton/scripts/../../triton/model_repo/fp16//jasper-ts-trace/1
python triton/converter.py --model-module jasper_module --convert ts-trace --precision fp16 --save-dir /workspace/jasper/triton/scripts/../../triton/model_repo/fp16//jasper-ts-trace/1 -- --batch_size 8 --dataset_dir /datasets/LibriSpeech --val_manifest /datasets/LibriSpeech/librispeech-test-clean-wav.json --model_config configs/jasper10x5dr_speedp-offline_speca_nomask.yaml --ckpt=/checkpoints --ema --component model
Traceback (most recent call last):
  File "triton/converter.py", line 246, in <module>
    model = mm.init_model(model_args_list, args.precision, args.device)
  File "/workspace/jasper/triton/jasper_module.py", line 184, in init_model
    comp = init_comp[args.component](args)
  File "/workspace/jasper/triton/jasper_module.py", line 135, in init_acoustic_model
    if args.max_duration is not None:
AttributeError: 'Namespace' object has no attribute 'max_duration'

4. export to "tensorrt", got issue as below:** 
root@4daff75f04d7:/workspace/jasper# export CONVERTS="tensorrt"
root@4daff75f04d7:/workspace/jasper# bash triton/scripts/export_model.sh
mkdir -p /workspace/jasper/triton/scripts/../../triton/model_repo/fp16//jasper-tensorrt/1
chmod a+w /workspace/jasper/triton/scripts/../../triton/model_repo/fp16//jasper-tensorrt/1
python triton/converter.py --model-module jasper_module --convert tensorrt --precision fp16 --save-dir /workspace/jasper/triton/scripts/../../triton/model_repo/fp16//jasper-tensorrt/1 -- --batch_size 8 --dataset_dir /datasets/LibriSpeech --val_manifest /datasets/LibriSpeech/librispeech-test-clean-wav.json --model_config configs/jasper10x5dr_speedp-offline_speca_nomask.yaml --ckpt=/checkpoints --ema --component model
Traceback (most recent call last):
  File "triton/converter.py", line 246, in <module>
    model = mm.init_model(model_args_list, args.precision, args.device)
  File "/workspace/jasper/triton/jasper_module.py", line 184, in init_model
    comp = init_comp[args.component](args)
  File "/workspace/jasper/triton/jasper_module.py", line 135, in init_acoustic_model
    if args.max_duration is not None:
AttributeError: 'Namespace' object has no attribute 'max_duration'

**Environment**
Follow the instruction to create as below:
* Container version :
1. jasper  latest
2. nvcr.io/nvidia/pytorch  20.10-py3
* GPUs in the system: T4 x1 
* CUDA driver version (e.g. 418.67): Driver Version: 465.19.01

**Comment by GrzegorzKarchNV** [comment]
Hi @areoll , try adding these two lines `parse_args` function in `inference.py`:
```bash
parser.add_argument("--max_duration", default=None, type=float, help='maximum duration of sequences. if None uses attribute from model configuration file')
parser.add_argument("--pad_to_max_duration", action='store_true', help='pad to maximum duration of sequences')
```

**Comment by areoll** [comment]
Hi @GrzegorzKarchNV , 

It's working fine now to put the additional arguments. Thank you, and have a nice day!

**Comment by GrzegorzKarchNV** [comment]
great to hear it, thanks!
