### ISSUE TITLE
TensorRT Conversion and Inference in Colab Notebook

### ISSUE THREAD

**Issue by Darshcg** [NVIDIA/DeepLearningExamples#967]
Hi Nvidia Team,

I am trying to execute the Colab Notebook given on the Jasper TRT Inference(from this: https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/SpeechRecognition/Jasper/notebooks/Colab_Jasper_TRT_inference_demo.ipynb), but when I am executing I am facing an issue as **python3: can't open file '../trt/perf.py': [Errno 2] No such file or directory** I have attached the screenshot on the same below:

![image](https://user-images.githubusercontent.com/48723743/125622822-354fdee3-ca64-4cc4-8baf-9dfaf61d227c.png)

Kindly help me to resolve this issue.

Thanks,
Darshan C G

**Comment by GrzegorzKarchNV** [comment]
Hi @Darshcg, we are in the process of updating the Jasper model and at the moment the notebook is not compatible with the rest of the scripts. Please stay tuned for an update - I'll leave the bug open.
