### ISSUE TITLE
[EfficientNet-B0/Tensorflow2] Low training throughput on EfficientNet-B0

### ISSUE THREAD

**Issue by chunhanl** [NVIDIA/DeepLearningExamples#984]
Related to **Model/Framework(s)** 
EfficientNet-B0/Tensorflow2 & Resnet50v1.5/Tensorflow

**Describe the bug**
On NVIDIA DGX-1 (8x V100 16G), Resnet50v1.5/Tensorflow is reported with a train throughput of **9510** img/s while EfficientNet-B0/Tensorflow2 only has **4065** img/s.

The EfficientNet-B0 has less parameters compare to Resnet50v1.5 but is 2x slower in training speed, is there any possible reason behind this? Thank you.

**To Reproduce**
Numbers reported here:
https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow2/Classification/ConvNets/efficientnet
https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/Classification/ConvNets/resnet50v1.5

**Expected behavior**
Similar or maybe higher throughput on EfficientNet-B0/Tensorflow2

**Environment**
As mentioned in the quick start docs.

**Comment by subhankar-ghosh** [comment]
Hey @chunhanl,
That is a really good observation. EfficientNet-B0/Tensorflow2 training throughput of 4065 img/s is with auto-augmentation, which is extremely expensive and CPU bound. So I don't think it is fair to compare Resnet50v1.5/Tensorflow train throughput of 9510 img/s which uses basic image augmentation.

This is a known issue: https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow2/Classification/ConvNets/efficientnet#known-issues

I hope that answers your question.

**Comment by chunhanl** [comment]
> Hey @chunhanl,
> That is a really good observation. EfficientNet-B0/Tensorflow2 training throughput of 4065 img/s is with auto-augmentation, which is extremely expensive and CPU bound. So I don't think it is fair to compare Resnet50v1.5/Tensorflow train throughput of 9510 img/s which uses basic image augmentation.
> 
> This is a known issue: https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow2/Classification/ConvNets/efficientnet#known-issues
> 
> I hope that answers your question.

Cool that explains a lot, thanks for the reply!
