### ISSUE TITLE
[Transformer/PyTorch] AMP opt-level is not supported anymore

### ISSUE THREAD

**Issue by sneaxiy** [NVIDIA/DeepLearningExamples#998]
Related to **Transformer/PyTorch** 

*Examples:* 
* *Transformer/PyTorch* 
* *AMP* 

**Is your feature request related to a problem? Please describe.**

The Transformer/PyTorch model does not support `--amp-level` anymore. I found that the `--amp-level` is removed in [here](https://github.com/NVIDIA/DeepLearningExamples/commit/7e8102d0ecd258c17c61052198d32c35559dbf69). All APEX codes are replaced with the [PyTorch AMP APIs](https://pytorch.org/docs/stable/amp.html). 

I remember that PyTorch AMP APIs only support the `O1` opt-level but not `O2`. APEX does support both `O1` and `O2`. If I want to use `O2`, how should I do with the current codes? Is there any option or do I have to change the Python codes manually to use APEX APIs?

BTW, why `--amp-level` is removed? Is there any performance gain if we use PyTorch AMP APIs? Do PyTorch AMP APIs support both `O1` and `O2` opt-level?

**Describe the solution you'd like**
Support both `O1` and `O2` opt-level in Transformer/PyTorch AMP training.

**Describe alternatives you've considered**
Replace the PyTorch AMP APIs with APEX APIs manually.

**Additional context**

**Comment by jbaczek** [comment]
Running extensive convergence tests we discovered that APEX O2 doesn't improve overall E2E training time compared to O1. Using O2 influenced convergence rate (in terms of steps) which we want to avoid. Native AMP is roughly equivalent to O1 and due to deprication of APEX API we moved to native AMP.
